app.js, db/README.md, db/migrations/20210719171721-add-jira-issues.js, db/postgres/jiraIssue.js
add jira issues model and try it out in app.js
=> adding jira_issues model

app.js, db/mongo/connection.js, db/mongo/index.js, src/collectors/jira/issues.js
- Integrate mongodb client, and dump Jira issues to a mongo db
- Also add Jira issues to postgres db using a formatted object
=> Add db support for Jira issues

package-lock.json, package.json
=> fix(package): add lost nodemon dev dependency.

README.md
With this change we now have both **Collection** and **Enrichment** (new addition) usage documented in readme
- Added enrichment job specific details to the readme file
=> add enrichment specific details to readme

src/plugins/jira-pond/src/collector/changelogs.js, src/plugins/jira-pond/src/collector/fetcher.js, src/plugins/jira-pond/src/collector/issues.js
This makes a primary key before insert so that no duplicates are stored in mongodb
=> no more duplicate rows

src/plugins/jira-pond/src/collector/issues.js
Total amount for `fetchIssues()` in jira collector is showing undefined. Reworked it to return actual number of issues
=> fix total results to show number

README.md
Update readme to add steps for provisioning a grafana dashboard
=> Docs for provisioning a grafana dashboard

db/migrations/20210729191437-gitlab-merge-requests.js, db/postgres/gitlabMergeRequest.js, grafana/dashboards/Home.json, package-lock.json, rabbitmq.conf, src/plugins/gitlab-pond/index.js, src/plugins/gitlab-pond/src/collector/collection-manager.js, src/plugins/gitlab-pond/src/enricher/index.js
To cover GitLab Merge Request related metrics in grafana, starting with number of MRs.
Collection, storage, enrichment, and grafana dashboard update.
Methods for collection and enrichment, migrations, models, grafana config.
=> Gitlab mr collection

docker-compose.yml
=> fix: separate grafana / enrichment databases

db/migrations/20210730185809-reviewer-as-array.js, db/postgres/gitlabMergeRequest.js, grafana/dashboards/Home.json, src/plugins/gitlab-pond/src/enricher/index.js
Fixes #85 
1. Gather the data in the reviewers as an array from gitlab_merge_requests and display that in grafana
=> Gitlab reviewers

config/local.sample.js, db/migrations/20210730102529-create-jira-board-issue.js, db/migrations/20210731152203-issue-created-updated.js, db/postgres/jiraBoardIssue.js, db/postgres/jiraIssue.js, src/plugins/jira-pond/index.js, src/plugins/jira-pond/src/collector/fetcher.js, src/plugins/jira-pond/src/collector/index.js, src/plugins/jira-pond/src/collector/issues.js, src/plugins/jira-pond/src/enricher/index.js, src/plugins/jira-pond/src/enricher/issues.js
1. Move functions to top level for supporting IDE function jumping/peeking
This is helpful for new Contributor to get familiar with our codebase, also important for user's
technical evaluation
2. Move jira fetcher `maxRetry` to configuration
It makes no sense to specify a `maxRetry` every time, gitlab fetcher should be fixed soon
3. Unify logging message format
Make it easier for debugging, helpful for new Contributor understanding the flow
4. Unify module structures between `collecter` and `enricher`
A unified structure can reduce the cost of developer working among multiple plugins, and it's
a important point to consider when user evaluating a OpenSource project.
5. Wrap `debugging` code in a function named `main` to avoid semicolon confusion
=> feat: enrich jira board-issues relationship

config/local.sample.js, db/migrations/20210731160337-add-jira-board-gitlab-project.js, db/postgres/jiraBoardGitlabProject.js, grafana/dashboards/CompoundFigures.json, src/collection/worker.js, src/enrichment/worker.js, src/plugins/compound-figures/README.md, src/plugins/compound-figures/index.js, src/plugins/compound-figures/package.json, src/plugins/index.js
1. Add plugin initialization mechanism so plugin can do some preparation work
2. Kanban-Repo mapping through JiraBoardGitlabProject model
3. Add CompoundFigure enricher plugin to copy `jiraBoardGitlabProject` configuration to database
=> feat: kanban-repo mapping and compound figures

config/constants.json, config/local.sample.js, db/migrations/20210731152203-issue-created-updated.js, db/migrations/20210803070329-issue-resolvedat-epic-status.js, db/migrations/20210803084926-create-jira-board.js, db/postgres/jiraBoard.js, db/postgres/jiraIssue.js, docker-compose.yml, rabbitmq.conf, src/collection/main.js, src/collection/worker.js, src/enrichment/main.js, src/plugins/jira-pond/src/collector/boards.js, src/plugins/jira-pond/src/collector/fetcher.js, src/plugins/jira-pond/src/collector/index.js, src/plugins/jira-pond/src/collector/issues.js, src/plugins/jira-pond/src/enricher/boards.js, src/plugins/jira-pond/src/enricher/index.js, src/plugins/jira-pond/src/enricher/issues.js
feat: jira board collector/enricher
fix: docker requires shared mount for rabbitmq
feat: add issueResolvedAt/epicKey/status for jira enricherment
fix: fetcher should have default timeout
=> feat: jira board collector/enricher

.eslintignore, .eslintrc.json, db/migrations/20210729124354-add-gitlab-projects.js, db/migrations/20210729134703-add-gitlab-commits.js, db/migrations/20210729191437-gitlab-merge-requests.js, db/migrations/20210730140143-add-gitlab-note.js, db/migrations/20210730182134-change-string-to-text-gitlab.js, db/migrations/20210730185809-reviewer-as-array.js, db/migrations/20210731160337-add-jira-board-gitlab-project.js, db/migrations/20210803070329-issue-resolvedat-epic-status.js, db/migrations/20210803084926-create-jira-board.js, scripts/test-docker-compose.js
Hi @joncodo 
I added some eslint rules according to [this comment](https://github.com/merico-dev/lake/pull/120#discussion_r682123252)
Please help reviewing, thanks.
=> chore: linting for `db/migrations` and `scripts`

grafana/dashboards/DeliveryCost.json, grafana/dashboards/DeliveryEfficiency.json, grafana/dashboards/DeliveryQuality.json, grafana/dashboards/Homepage.json
4 dashboards in total. Homepage will be the default landing page for users.
=> feat: add mvp dashboards

docker-compose.yml
=> feat: add pie-chart plugin for Grafana

src/plugins/README.md
Please let me know if / how I can improve this. Thanks.
=> docs(readme): how to make a new  plugin README

grafana/dashboards/DeliveryCost.json, grafana/dashboards/DeliveryEfficiency.json, grafana/dashboards/DeliveryQuality.json
The `datasource` needs to be `Postgres` instead of `PostgreSQL2`.
=> fix: incorrect data-source of new dashboards

grafana/provisioning/datasources/datasource.yml
=> fix: make provision datasource editable

src/plugins/HOW-TO-ADD-METRICS.md
WIP, first draft. Looking for feedback, please! 
(I know it is not fully complete, but I'd like to get some direction about general feel, formatting, and what level of detail to pursue.
My instinct is not to get too detailed with the technicalities because:
a) They may change
b) Contributors should feel free to do it their own way
=> docs(how to add metrics): just a short readme to add metrics

.github/workflows/reviewdog.yml, .husky/pre-commit, package-lock.json, package.json, plugins/core/src/index.ts, plugins/jira/test/index.spec.ts
This PR setup auto eslint for `ts-main` branch. After this PR:  
- eslint will auto fix before commit.
- github PR will check if there are lint errors.
We introduced `lint-staged` for linting staged files before commit.  
/cc @UltimateBeaver @jaxzhou
=> chore: add eslint check before commit and PR

grafana/dashboards/DeliveryCost.json, grafana/dashboards/DeliveryEfficiency.json, grafana/dashboards/DeliveryQuality.json, grafana/dashboards/Homepage.json
1. fix: replace icons to fit Grafana dark mode
2. feat: add charts for MR Review Time
3. style: modify the layout of delivery efficiency/quality/cost dashboards
=> fix(dashboards): adjust dashboard style

config/docker.sample.js, config/local.sample.js
Better setup experience for new users
This PR adds a line-by-line explanation for our config files.
=> docs: add comments to config files

src/plugins/index.js
Aims to fix the same problem described in https://github.com/merico-dev/lake/pull/173.
=> chore: fix confusing error message

apps/queue/src/consumer/service.ts, plugins/README.md, plugins/core/src/collector.ts, plugins/core/src/enricher.ts, plugins/core/src/index.ts, plugins/core/src/plugin.ts, plugins/jira/src/index.ts
https://github.com/merico-dev/lake/issues/150
```mermaid
graph TD;
A[write your plugin]--copy files to plugins-->B[start]
B --run app--> C[unmigrated]
C --"triforce call migrateUp() when added or updated"--> D[ready]
D --"call migrateDown() when removed"--> C
D --"call execute() when start cal data"--> V0[started]
```
```mermaid
graph TD;
A[plugin unregistered]--"call plugin.execute() to add collectors and enrichers"-->B[plugin started]
B --"call each collector/enrichers.name() to register"--> C[collector and enricher register]
C --"when start collector, run `collector.dependencies(pks)`"--> D[got collector dependencies map]
D --"run `collector.isDataPrepared(pks) && collector.collectData(pks)` one by one"--> E[collect success]
E --"when start enricher, run …
```
=> feat(plugin): add interface of plugin/enricher/collector

.gitignore, README.md, config/docker.sample.js, config/local.sample.js, config/plugins.sample.js, src/plugins/gitlab-pond/README.md, src/plugins/gitlab-pond/index.js, src/plugins/jira-pond/README.md, src/plugins/jira-pond/index.js, src/plugins/jira-pond/src/enricher/issues.js
Absolutely no functional changes at all. Just a bunch updates to docs and removing outdated properties and docs.
=> docs and chore fixes to plugin configuration feature

config/docker.sample.js, config/local.sample.js, config/plugins.sample.js
Some minor spelling/grammar things in example config files. As well I think it's nice to highlight what parts of these example config files actually **NEED** replacing (vs config settings that can be left alone).
- Added unicode symbol `➤➤➤` to highlight "Replace" sections
- Fixed some spelling things
=> Sample config file doc updates

src/plugins/gitlab-pond/README.md
We need more information at the gitlab level. This was too confusing for Maxim as it was. 
- New section for summary with images
- Configuration
- Gathering Data with Github
=> docs: better docs, images and configuration

src/plugins/gitlab-pond/README.md
=> Revert "docs: better docs, images and configuration"

src/plugins/README.md
There was very small formatting issues with plugin docs. All the details are looking good. This PR will just fix a few of those minor things
- bullet points instead of inline a) b) etc (more traditional markdown style)
- formatted numbering flow
=> docs: small formatting updates to plugin doc

README.md, docs/DEVELOPER_SETUP.md
These are feedback items from @MaximDub that we would like to add to our readme. The hope is that this makes it easier for new users to run the application.
The largest change is to move the developer setup to another file to not overwhelm new users.
You can see this ticket for more details: https://github.com/merico-dev/lake/issues/200
=> docs: general doc feedback from maxim v1

CONTRIBUTING.md, package-lock.json
Rephrasing, spelling, capitalization, "closing issues" section, "approval of issues" section,
"proposing a change" section
=> docs: improves CONTRIBUTING.md

src/plugins/gitlab-pond/README.md
We need more information at the gitlab level. This was too confusing for Maxim as it was. 
- New section for summary with images
- Configuration
- Gathering Data with Github
=> docs: gitlab docs for config and summary

src/plugins/jira-pond/README.md
follows the pattern of new and improved GitLab readme
=> docs: new and improved Jira pond readme

.env.sample, README.md, devops/docker-compose.yml
ts branch has some differences with js branch.  even the ts branch is on building, we still need to update the readme to make sure it can be setup .
=> docs: modify ts branch setup in readme

grafana/dashboards/DeliveryEfficiency.json
Based on a review of Delivery efficiency dashboard descriptions there is 2 small adjustments needed regarding formatting/spelling
Updated DeliveryEfficiency.json dashboard with 2 small text changes
[https://github.com/merico-dev/lake/issues/221](https://github.com/merico-dev/lake/issues/221)
=> docs: fix two small text updates in delivery efficiency dashboard

config/docker.sample.js, config/local.sample.js, config/plugins.sample.js, scripts/command-line-config.js, src/plugins/jira-pond/src/collector/fetcher.js
When we use the CLI, it is usually for new users of the app that are following the readme instructions. Mainly `npm run configure` and `npm start`. However, the CLI did not write to the config/docker.js file. This PR fixes that.
It uses the same things that the CLI was using to do this except it now has methods to ask for data and separate methods to write to the file
- I ran `npm run configure` and saw all prompts. 
- Verified all of config/plugins,local and docker were set properly
- Ran `npm start` and saw it pull down valid data
=> Cli docker

README.md
This step is important - npm install
=> docs: added a step to npm install in user setup

README.md
This command works, so I've updated the README:
docker-compose -f docker-compose.yml -f docker-compose.prod.yml logs -f lake
=> docs: updated docker-compose logs command

config/local.sample.js, docs/DEVELOPER_SETUP.md
`local.sample.js` needed to be updated to work with the dev setup. As well the dev setup docs needed an update to use the new command line config setup.
- Uncomment `cron` section in local sample file (just like docker sample)
- Update `DEVELOPER_SETUP.md` to have proper flow for command line tool 
- Update `DEVELOPER_SETUP.md` to have better info about how we immediately start the data collection
=> fix: update local sample dev setup and adjust dev setup docs

.env.sample, apps/rest/src/app.module.ts, apps/rest/src/models/base.ts, apps/rest/src/models/index.spec.ts, apps/rest/src/models/index.ts, apps/rest/src/models/source.ts, apps/rest/src/models/sourceTask.ts, apps/rest/src/providers/typeorm.module.ts, apps/rest/test/app.e2e-spec.ts, package-lock.json, package.json
We need to persist source info and task info into database.
This PR added typeorm support for ts-main branch, with synchronizing models feature.
This PR has not handled database migration, we will add db migration in another PR.
> using synchronize feature is not recommended in production environment.
=> feat: add typeorm module for rest api

README.md, docs/DEVELOPER_SETUP.md
This PR adds a general note about our type/status mapping setup in the `plugins.js` config file. As well as an example of a Jira issue "Bug" type status mapping. Its added to both **User Setup** and **Developer Setup**
No
=> docs: added type mapping and jira status mapping to docs

README.md
This PR updates the screenshot in our README.
=> docs: update screenshots

.github/workflows/commit-msg.yml, .github/workflows/test.yml, Makefile, go.mod, test/example/greetings.go, test/example/greetings_test.go
We need a way to run tests with go in order to verify our code!
You can now run `make test` and see the tests pass in github actions
#271 
1. If this PR shows all tests passing, it works!
This is forked off of #270
=> First go test

models/init.go, plugins/gitlab/gitlab.go, plugins/gitlab/init.go, plugins/gitlab/models/gitlabproject.go, plugins/gitlab/tasks/common.go, plugins/gitlab/tasks/gitlabcommitcollector.go, plugins/gitlab/tasks/gitlabprojectcollector.go
=> Gitlab project collection

.env.example, .gitignore, models/base.go, plugins/jira/init.go, plugins/jira/jira.go, plugins/jira/models/jiraboard.go, plugins/jira/models/jiraboardissue.go, plugins/jira/models/jiraissue.go, plugins/jira/tasks/jiraapiclient.go, plugins/jira/tasks/jiraboardcollector.go, plugins/jira/tasks/jiraissuecollector.go
- [ x] I have read through the [Contributing](../CONTRIBUTING.md) Documentation
- [ x] This PR is using a `label` (bug, feature etc.)
JIRA plugin now is able to collect all issues for a board and build up relationship. This is a breaking change.
- [ x] This is a breaking change
Step to verify:
1. delete jira table from your local database
2. compile plugins: `scripts/compile-plugins.sh`
3. make sure `.env` is up to date and load it to your Environment Variable
4. start up app: `go run main.go`
5. trigger a jira plugin task: `curl -XPOST --data '{"plugin": "jira", "options": {"boardId": 8}}' http://localhost:8080/task`
6. check database to see if all  three jira tables populated …
=> feat: jira board/issues collection

go.mod, go.sum, plugins/jenkins/jenkins.go, plugins/jenkins/models/jenkins_build.go, plugins/jenkins/models/jenkins_job.go, plugins/jenkins/tasks/providers.go, plugins/jenkins/tasks/storage.go, plugins/jenkins/tasks/worker.go
This PR added jenkins plugin, collecting jenkins jobs and builds data.
#307
Fill options below in the request body.
```shell
curl --location --request POST '127.0.0.1:8080/task' \
--data-raw '{
"plugin": "jenkins",
"options": { 
"Host": "",
"Username": "",
"Password": ""
}
}
'
```
```shell
[GIN] 2021/09/01 - 09:35:49 | 201 |  131.395972ms |       127.0.0.1 | POST     "/task"
running plugin jenkins, progress: 1.5384616
INFO[0011] [INFO >>> job has no build exists in past half year - /home/narro/code/merico/lake/plugins/jenkins/tasks/worker.go:68auto_deploy 
running plugin jenkins, progress: 3.0769231
running plugin jenkins, progress: 4.6153846
INFO[0011] [INFO >>> job has no build exists in past half year - …
```
=> feat: jenkins plugins

config/config.go, go.mod, go.sum, plugins/jira/tasks/jiraapiclient.go, plugins/jira/tasks/jirachangelogcollector.go, plugins/jira/tasks/jiraissuecollector.go, plugins/plugins.go, utils/worker_scheduler.go, utils/worker_scheduler_test.go
add a worker_scheduler to collect issues parallelizable
https://github.com/merico-dev/lake/issues/316
now collect one by one
```
running plugin jira, progress: 1
INFO[0049] [INFO >>> jira board issues collection - /Users/lin/projects/lake/plugins/jira/tasks/jiraissuecollector.go:92map[boardId:8 loaded:0 total:3805] 
INFO[0053] [INFO >>> jira board issues collection - /Users/lin/projects/lake/plugins/jira/tasks/jiraissuecollector.go:92map[boardId:8 loaded:900 total:3805] 
INFO[0054] [INFO >>> jira board issues collection - /Users/lin/projects/lake/plugins/jira/tasks/jiraissuecollector.go:92map[boardId:8 loaded:100 total:3805] 
INFO[0054] [INFO >>> jira board issues collection - /Users/lin/projects/lake/plugins/jira/tasks/jiraissuecollector.go:92map[boardId:8 loaded:700 total:3805] …
```
=> feat: add worker_scheduler for parallelization

.env.example, logger/log.go, plugins/jira/jira.go, plugins/jira/models/jiraissue.go, plugins/jira/tasks/jirachangelogcollector.go, plugins/jira/tasks/jiraissuecollector.go, plugins/jira/tasks/jiraissueenricher.go
=> feat: issue leadtime/workload enrichment

models/base.go, models/init.go, plugins/gitlab/init.go, plugins/gitlab/models/gitlabMergeRequest.go, plugins/gitlab/models/gitlabMergeRequestNote.go, plugins/gitlab/models/gitlabReviewers.go, plugins/gitlab/models/gitlabcommit.go, plugins/gitlab/tasks/gitlabMergeRequestCollector.go, plugins/gitlab/tasks/gitlabMergeRequestNote.go
This PR creates FK associations between the following models:
- Merge Requests -> Projects
- Merge Request Notes -> Merge Requests
- Commits -> Projects
- Reviewers -> Merge Requests
It also fixes an issue with Notes collection.
Yes - https://github.com/merico-dev/lake/issues/323
=> Model associations

.env.example, plugins/compound/compound.go, plugins/compound/models/jiraboard_gitlabproject.go
=> feat: compound plugin to sync board/repo config to db

plugins/jira/models/jiraissue.go, plugins/jira/tasks/jiraapiclient.go, plugins/jira/tasks/jirachangelogcollector.go, plugins/jira/tasks/jiraissuecollector.go, plugins/jira/tasks/jiraissueenricher.go
=> Revert "using json tag and gorm tag to simply convert results"

.editorconfig, .env.example, plugins/jira/models/jiraissue.go, plugins/jira/tasks/jiraissuecollector.go, plugins/jira/tasks/jiraissueenricher.go
=> feat: rename workload to storypoint

grafana/dashboards/DeliveryCapability.json, grafana/dashboards/DeliveryCost.json, grafana/dashboards/DeliveryEfficiency.json, grafana/dashboards/DeliveryQuality.json, grafana/dashboards/Homepage.json
1. add Requirement Granularity
2. add Build count and Build Success Rate
3. update most Jira queries
4. rename Delivery Efficiency to Delivery Velocity
5. add Dashboard - Delivery Capability
=> feat: dashboards update from @louis 

plugins/jira/models/jiraissue.go, plugins/jira/tasks/jirachangelogcollector.go
Sync only changed changelogs since last sync 
No
All changelogs got synced
Sync only changed changelogs since last sync
=> feat: jira changelog diff sync

scripts/pm.sh
Make cli debugging easier
`scripts/pm.sh debug` to compile plugins and launch  dlv for command line debugging
`scripts/pm.sh jira` to trigger jira plugin execution
`scripts/pm.sh jira_enrich_issues` to trigger jira issue enrichment
No
=> feat: add cli debugging script

Makefile, README.md, docker-compose.yml, plugins/jira/README.md
User setup documentation
User can set up devlake with docker-compose
=> docs: user setup

plugins/jenkins/README.md
This PR added README.md for jenkins plugin
=> docs(jenkins): add readme for jenkins plugin

.env.example, README.md, plugins/jenkins/README.md, scripts/pm.sh
=> docs: fix user guide

grafana/dashboards/DeliveryCapability.json, grafana/dashboards/DeliveryCost.json, grafana/dashboards/DeliveryQuality.json, grafana/dashboards/DeliveryVelocity.json, grafana/dashboards/Homepage.json
1. update all Jira and Gitlab-related charts;
2. add 2 charts about metric requirement lead time;
3. replace the MARI framework on the homepage with English version;
=> feat: dashboards update from @louis

plugins/gitlab/tasks/gitlab_api_client.go
There's a deadlock in collecting Gitlab commits. This is due to that multiple goroutines in `FetchWithPaginationAnts` can send `false` to the channel while the main for loop breaks immediately after receiving the first `false`. The fix is to only allow the last page in each batch to send a single message (whether `true` or `false`) to the main for loop.
=> Fix deadlock by only allowing the last page in each batch to send a single message

Dockerfile, devops/lake-builder/Dockerfile
Fix dockerfile error caused by #363
=> chore: fix lake builder Dockerfile

grafana/dashboards/DeliveryQuality.json, grafana/dashboards/DeliveryVelocity.json
1. Fix chart pr pass count
2. Wording and styling updates
=> feat: dashboard udpate from @louis

.env.example, plugins/jira/README.md
This PR does two things:
1. Update plugins/jira/README.md to reflect our new metrics in phase 2
2. Format .env.example to make it clearer and easier to consume
=> Update jira doc

ARCHITECTURE.md, README.md
=> docs: update readme.md

plugins/HOW-TO-ADD-METRICS.md, plugins/README.md, plugins/gitlab/README.md
This PR updates the current documentation for HOW-TO-ADD-METRICS to be more accurate to our current Golang system.
=> doc: how to add metrics update

config-ui/Dockerfile, config-ui/pages/index.js, config-ui/utils/envValue.js, docker-compose.yml
This PR added Dockerfile for config-ui
Because nextjs will prerender pages when building, and we don't have .env file when building the nextjs app, it causes an error on `npm run build`. So we simply use `npm run dev` to disable the prerender feature. Please update this PR if you have any better ideas.
=> chore: build config-ui

config-ui/pages/index.js
To fix some minor issues of `config-ui`
1. Change document title from `Create Next App` to `Devlake Config-UI`
2. Add `restart devlake to apply configuration` to success saved prompt
3. Fixed 404 api requests when click `Save Config`
=> fix(config-ui): document title / 404 api requests

plugins/jira/README.md
Add document for issue type/status mapping.
@joncodo @kevin-kline  please help polishing
=> docs: add jira type/status mapping doc

Dockerfile
Clean bin dir before compiling in Dockerfile
=> fix: clean bin dir before compiling in Dockerfile

config-ui/pages/api/triggers/config.js, config-ui/pages/api/triggers/pendings.js, config-ui/pages/api/triggers/task.js, config-ui/pages/triggers.js
config-ui progress not working when launched by `docker-compose up`
=> fix: envvar typo

README.md
Make this open in a new tab as requested by @Startrekzky 
Also updated one line in the docs
=> feat: data sources link as anchor tag

grafana/dashboards/DeliveryCapability.json, grafana/dashboards/DeliveryCost.json, grafana/dashboards/DeliveryQuality.json, grafana/dashboards/DeliveryVelocity.json
fix queries for bug age and incident age
=> fix: fix queries for bug age and incident age

config-ui/pages/plugins/gitlab.jsx, config-ui/pages/plugins/jenkins.jsx, config-ui/pages/plugins/jira.jsx
Updates to config UI:
- Added back in jira gitlab form section on `/jira` page (was missing from rebase merge conflict)
- Changed `ORIGIN_` to `YOUR_` in jira placeholder inputs 
Points 1 and 2 from:
[https://github.com/merico-dev/lake/issues/409](https://github.com/merico-dev/lake/issues/409)
New section on jira plugin page in config ui, and new placeholder
=> fix: new form placeholders and add extra jira field

plugins/gitlab/gitlab.go, plugins/gitlab/init.go, plugins/gitlab/models/gitlab_pipeline.go, plugins/gitlab/tasks/gitlab_pipelinie_collector.go
Fixes: https://github.com/merico-dev/lake/issues/405
(Please see the ticket for more details)
@Startrekzky After this is merged, you can make us some graphs for gitlab ci?
Here is the data we collect:
Note: we added this to the current gitlab plugin since it is pulled from the same api.
=> feat: gitlab pipelines

config-ui/pages/plugins/jira.jsx
=> fix: help link/duplicate field/section organise

.gitignore, README.md
Test badge broke, this PR fixed it and added go report badge.
=> fix: badge error in README.md

go.mod, go.sum, plugins/compound/compound.go, plugins/core/hub.go, plugins/core/hub_test.go, plugins/core/plugin.go, plugins/domainlayer/domainlayer.go, plugins/domainlayer/models/base/base.go, plugins/domainlayer/models/ticket/changelog.go, plugins/domainlayer/models/ticket/issue.go, plugins/domainlayer/okgen/originkey_generator.go, plugins/domainlayer/okgen/originkey_generator_test.go, plugins/github/github.go, plugins/gitlab/gitlab.go, plugins/jenkins/jenkins.go, plugins/jira/jira.go, plugins/jiradomain/jiradomain.go, plugins/jiradomain/tasks/boardconverter.go, plugins/jiradomain/tasks/changelogconverter.go, plugins/jiradomain/tasks/issueconverter.go, plugins/plugins.go, scripts/pm.sh, test/plugins/plugins_test.go
Convert Jira Entities to Domain Entites:
- jira_board -> board
- jira_issue -> issue
- jira_changelog -> changelog
=> Jira Domain Plugin

plugins/domainlayer/domainlayer.go, plugins/domainlayer/models/devops/build.go, plugins/domainlayer/models/devops/job.go, plugins/jenkinsdomain/jenkinsdomain.go, plugins/jenkinsdomain/tasks/buildconverter.go, plugins/jenkinsdomain/tasks/jobconverter.go, plugins/jira/tasks/jirachangelogcollector.go, plugins/jira/tasks/jiraissueenricher.go, plugins/jiradomain/tasks/issueconverter.go, scripts/compile-plugins.sh, scripts/pm.sh
Convert Jenkins Entities to Domain Entites:
jenkins_job -> job
jenkins_build -> build
=> Jenkins domain

config-ui/Dockerfile, config-ui/next.config.js, config-ui/pages/plugins/jira/MappingTag.jsx, config-ui/pages/triggers/index.jsx
e9fdd76 fix: `npm run build` fail due to values being undefined
43037e5 fix: incorrect import path
69c3682 fix: config-ui showing 404 for all path
=> Fix config UI

README.md, plugins/gitlab/README.md, plugins/jira/README.md
Updated main readme and plugin readme to fix some text. For details on specifics see [https://github.com/merico-dev/lake/issues/461](https://github.com/merico-dev/lake/issues/461)
[https://github.com/merico-dev/lake/issues/461](https://github.com/merico-dev/lake/issues/461)
Readme has better readability and fixes a few errors
=> fix: update readme for readability and better descriptions

README.md
1. correct the command in step 2 on main readme
2. update wordings and fix typos on main readme
3. add hyper link to plugin readme
=> fix: correct the command in step 2 on main readme

config-ui/next.config.js, config-ui/pages/plugins/jira/MappingTag.jsx, config-ui/pages/plugins/jira/MappingTagStatus.jsx, config-ui/pages/plugins/jira/index.page.jsx
Fixes issues from https://github.com/merico-dev/lake/issues/474
=> Fix config UI again

grafana/dashboards/AverageRequirementLeadTimeByProcess.json, grafana/dashboards/CommitCountByAuthor.json, grafana/dashboards/DemoHomepage.json, grafana/dashboards/HowFastDoWeRespondToCustomerRequirements.json, grafana/dashboards/IncidentCountPer1kLinesOfCodeBySeverityLevel.json, grafana/dashboards/IsthisMonthMoreProductiveThanLast.json, grafana/dashboards/WasOurQualityImprovedOrNot.json
Add 7 dashboards for demo.
#556 
=> feat: add demo dashboards

config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/connections/EditConnection.jsx, config-ui/src/pages/configure/integration/manage.jsx
Small fixes to to UI for certain requests.
=> fix: small fixes to UI

plugins/gitlab/api/gitlab_sources.go, plugins/gitlab/gitlab.go, plugins/jenkins/api/jenkins_sources.go, plugins/jenkins/jenkins.go
Source API for GitLab and Jenkins.
- GET /sources
- GET /sources/:sourceId
- PUT /sources/:sourceId
https://github.com/merico-dev/lake/issues/590
https://github.com/merico-dev/lake/issues/591
=> GitLab  and Jenkins API sources

plugins/jira/api/jira_sources.go, plugins/jira/jira.go
Adds the following jira plugin routes requested by @e2corporation for the frontend:
- GET plugins/jira/sources/:sourceId/epics
- GET plugins/jira/sources/:sourceId/granularities
- GET plugins/jira/sources/:sourceId/boards
https://github.com/merico-dev/lake/issues/594
=> Jira API routes for Config-UI 

plugins/jira/README-zh-CN.md, plugins/jira/README.md
Gives "since" parameter to Jira plugin collection example in README.
Shows proper format.
=> docs: added since param to jira options

config-ui/src/components/Sidebar/SidebarMenu.jsx
Adds Merico links to sidebar.
https://github.com/merico-dev/lake/issues/616
=> feat: merico links in sidebar

config-ui/src/pages/triggers/index.jsx
No longer send GET requests every 3 seconds to API on "Triggers" page.
https://github.com/merico-dev/lake/issues/611
=> fix: no longer send trigger GET requests

config-ui/src/hooks/useConnectionManager.jsx
This is a one off needed fix since the backend sends back uppercase and the frontend handles lowercase.
This should be fixed by making the front end handle uppercase in all instances but this will fix us for release.
=> feat: handle backend uppercase

config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/hooks/useSettingsManager.jsx, plugins/gitlab/api/gitlab_sources.go
This PR contains a partial fix to this problem: https://github.com/merico-dev/lake/issues/644
This PR repairs the data flow between the frontend and backend. However, it reveals a new problem on the backend. There is an issue with Viper reading the current values in the .env file after it's been written to. 
The problem may exist with this function:
```V := config.LoadConfigFile()```
Not yet.
=> Partial fix to GitLab Config-UI 

config-ui/src/pages/configure/settings/jira.jsx
- Do not include `statusMappings` key (deprecated)
This MR resolves outstanding issues on the **JIRA Settings Configuration** page that prevent **Type Mappings** from being correctly stored.
```
"typeMappings": {
"Story": {
"standardType": "Requirement",
},
"Incident": {
"standardType": "Incident",
},
"Bug": {
"standardType": "Bug",
}
}
```
#672 
Type Mappings cannot be saved or re-loaded for a JIRA connection instance.
Type Mappings are now correctly saved and re-parsed for edit/modify mode when a connection instance is loaded.
=> #672 Fix: JIRA Settings - Use New Format for Type Mappings

config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/connections/ConnectionForm.jsx, config-ui/src/styles/connections.scss
- On `saveComplete` Success, refresh the `activeConnection` object
This PR refreshes **Active Connection Object** being modified so that updated parameters such as the source instance's Name are properly reflected in the title and breadcrumbs.
#680 
When a user updates a connection instance details, the new values aren't automatically refreshed which may cause confusion. If page is reloaded new properties are shown.
When a user updates a connection instance, the details are seamlessly refreshed so the updated Instance Name (and other properties) are properly reflected.
=> #680 Config UI: Connections - Refresh $activeConnection Object on SAVE

config-ui/src/pages/configure/connections/ConnectionForm.jsx, config-ui/src/pages/configure/settings/jira.jsx
Fixes naming mismatch on Jira for:
- Story Point Coefficient
- Story Point Field
Also removes unnecessary helper text.
https://github.com/merico-dev/lake/issues/684
=> fix: jira naming, removed helperText

grafana/dashboards/DeliveryVelocity.json
This PR fixes 2 charts on the Delivery Velocity dashboard in Grafana.
https://github.com/merico-dev/lake/issues/689
=> fix: delivery velocity charts

plugins/github-domain/tasks/issue_converter.go, plugins/github/github.go, plugins/github/models/github_issue.go, plugins/github/tasks/github_issues_collector.go, plugins/github/tasks/github_issues_enrichment.go
- lead time, assignee, priority and type on github issues and enriched domain issues.
I think we also need this for gitlab....
@Startrekzky
=> New GitHub enrichment

config-ui/src/pages/configure/settings/jira.jsx, plugins/jira/api/jira_sources.go, plugins/jira/models/jira_source.go
Closes #702
Check issue #702 for detail
=> fix: jira source detail returning malformed typeMappings

api/router.go, plugins/core/plugin.go, plugins/jira/api/jira_issue_status_mapping.go, plugins/jira/api/jira_issue_type_mapping.go, plugins/jira/api/jira_sources.go
Closes #704
Please check issue for detail
=> fix: all plugins apis returning 201

.env.example, config-ui/config.js, config-ui/src/data/defaultTriggerValue.js, config-ui/src/pages/api/triggers/pendings.js, config-ui/src/pages/documentation/index.jsx, config-ui/src/pages/triggers/index.jsx, config-ui/src/utils/config.js, config-ui/webpack.config.js, services/task.go
Closes #711
config-ui dev env done, can be merged for @joncodo to do his work on `trigger` page.
will put up another pr to setup nginx part, @e2corporation @joncodo pls fix #712  so I can work on that tmr.
=> feat: api requests proxied by ngxin / triggers improvement

config-ui/src/components/SaveAlert.jsx, config-ui/src/pages/configure/index.jsx, config-ui/src/pages/configure/settings/jira.jsx
This PR improves styling on the Alert modal shown after Lake's API Configuration is saved.
#643
=> fix: #643 Config UI - Save API Config - Alert Modal

plugins/github/github.go
Important fix to github.
https://github.com/merico-dev/lake/issues/736
=> fix: added github enrichIssues to default tasks

plugins/domainlayer/models/ticket/issue.go, plugins/github-domain/tasks/issue_converter.go
Fixes: https://github.com/merico-dev/lake/issues/723
Add title to domain layer and have github populate it.
=> feat: title on domain layer

plugins/github-domain/tasks/issue_converter.go, plugins/github/models/github_issue.go, plugins/github/tasks/github_issues_enrichment.go
Fixes: https://github.com/merico-dev/lake/issues/724
=> feat: convert closed and open to Resolved and Todo

config-ui/src/pages/configure/settings/jira.jsx
1. Sets Story Point Coefficient default to 1 in Config UI.
2. Re-orders Story Point Coefficient and Story Point Field in Config UI.
https://github.com/merico-dev/lake/issues/738
=> fix: jira fields

README.md
No breaking change. Issue https://github.com/merico-dev/lake/issues/746
Fixing some grammar and spelling errors in the main `README.md`.
For tracking purposes, an issue is created here: https://github.com/merico-dev/lake/issues/746.
https://github.com/merico-dev/lake/issues/746
N/A
N/A
N/A
N/A
=> docs(README.md): Fixing grammar and spelling issues in the main readme.

docker-compose.yml, grafana/Dockerfile
=> feat: pack our dashboards into grafana

README-zh-CN.md, README.md
fix README for dev environment
=> fix: fix README for dev environment

README.md
=> Updated User Setup steps in README

README.md
=> docs: updated user setup steps in README

docker-compose.yml, plugins/github/github.go, plugins/github/tasks/github_api_client.go, plugins/gitlab/tasks/gitlab_api_client.go, plugins/gitlab/tasks/gitlab_merge_request_collector.go, plugins/gitlab/tasks/gitlab_project_collector.go
Update api endpoint on `config-ui` for github/gitlab wont be picked by future execution.
Closes #763
=> fix: update api endpoint on config-ui not working

config-ui/src/components/Sidebar/SidebarMenu.jsx
Fixes #762 
Also: Remove side nav for API Configuration
=> feat: change docs link

config-ui/config.js, config-ui/src/utils/config.js
=> fix: remove useless config file

config-ui/src/pages/triggers/index.jsx
Updates the documentation text on Triggers page.
#767
=> fix: #767 Config UI: update triggers documentation text and style

README.md
Updated User Setup document to latest status
=> docs: update user setup doc

README.md, plugins/github/README.md
This updates the GitHub README with more recent information.
Contributes to: https://github.com/merico-dev/lake/issues/777
=> docs: github update

plugins/jenkins/README.md, plugins/jira/README.md
Proofread on Jenkins and JIRA
Update README.md of plugin based on latest `config-ui` and behavious.
=> docs: update README based on latest config-ui

plugins/github/README-zh-CN.md, plugins/github/README.md, plugins/gitlab/README-zh-CN.md, plugins/gitlab/README.md
Documentation improvement for GitHub and Gitlab
=> fix: documation improvement

plugins/jenkins/README.md
Adds @e2corporation notes to Jenkins plugin README.
Contributes to https://github.com/merico-dev/lake/issues/778
=> docs: jenkins config update

plugins/github/README.md, plugins/gitlab/README.md
Update Provider documentation for GitHub and GitLab as outlined on ticket #778.
Updates Configuration section of plugin README(s) to reflect new changes with lake and the Configuration UI.
=> docs: #778 github and gitlab configuration readme updates

plugins/jenkins/README-zh-CN.md, plugins/jenkins/README.md
- Format English version readme 
- Translate English Version to Chinese version
=> docs: align eng/chs READMEs for Jenkins

README.md
1. add Tin disclaimer in main README
2. update main README info structure to make it clearer
3. update why devlake section
#754
=> feat: add tin disclaimer and update contents

plugins/jira/README-zh-CN.md, plugins/jira/README.md
- Update Chinese README to match up english version
- Small adjustment for English version
=> docs: align eng/chs README for JIRA

README-zh-CN.md, README.md
1. update the Chinese version main README
2. remove duplicated parts in main README
#780
=> feat: update the Chinese version main readme

plugins/github/README-zh-CN.md, plugins/github/README.md, plugins/gitlab/README-zh-CN.md, plugins/gitlab/README.md
improve `README-zh-CN.md` for GitHub and Gitlab
https://github.com/merico-dev/lake/issues/779
=> docs: improve README-zh-CN.md for GitHub and Gitlab

README.md, devops/sync/req.json
1. Fix the cron job section
2. Update the outdated `req.json` file
3. Add instruction to start config-ui in dev setup 
4. Several minor fixes
=> docs: update the main readme

plugins/jira/api/jira_issue_status_mapping.go, plugins/jira/api/jira_issue_type_mapping.go, plugins/jira/api/jira_sources.go
All POST method of JIRA plugin api returning 201 when succeeded
=> fix: POST requests should return StatusCreated when succeeded

plugins/domainlayer/domainlayer.go, plugins/domainlayer/models/ticket/sprint.go, plugins/jiradomain/tasks/sprint_converter.go
Store relations between sprints and issues.
https://github.com/merico-dev/lake/issues/709
=> feat: sprint_issues in domain layer

plugins/domainlayer/models/base/base.go, plugins/domainlayer/models/code/commit.go, plugins/domainlayer/models/code/note.go, plugins/domainlayer/models/code/pr.go, plugins/github/models/github_commit.go, plugins/github/models/github_issue.go, plugins/github/models/github_issue_comment.go, plugins/github/models/github_issue_event.go, plugins/github/models/github_pull_request_comment.go, plugins/gitlab/models/gitlab_commit.go, plugins/gitlab/models/gitlab_merge_request.go, plugins/gitlab/models/gitlab_merge_request_commit.go, plugins/gitlab/models/gitlab_merge_request_note.go, plugins/jira/models/jira_issue.go
Adds some helpful DB comments as requested by #559 
https://github.com/merico-dev/lake/issues/559
=> chore: some helpful model comments

README-zh-CN.md, README.md
1. update 'why dev lake section'
2. update 'what can be accomplished with dev lake' section
3. add a badge for Tin
=> feat: update tin badge and devlake value prop in main README

README-zh-CN.md, README.md
update tin setup link and adjust alignment
=> feat: update tin setup link and adjust alignment

.github/workflows/front-end-lint.yml, config-ui/package.json, config-ui/src/pages/api/getenv/[key].js, config-ui/src/pages/api/triggers/pendings.js, config-ui/src/pages/api/triggers/task.js
Fixes https://github.com/merico-dev/lake/issues/618
Note the new CI step
=> add lint to ci for Frontend

config-ui/src/components/messages/FormValidationErrors.jsx, config-ui/src/hooks/useConnectionValidation.jsx, config-ui/src/pages/configure/connections/AddConnection.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/connections/ConnectionForm.jsx, config-ui/src/pages/configure/integration/manage.jsx
- `hooks/useConnectionValidation.jsx`
- **Name** is required and has a `minLength` of `3` chars
- **Endpoint URL** is required and has a `minLength` of `3` chars and must start with `http` or `https`
- **Token**(s) must be provided and has a `minLength` of `3` chars (JIRA, GitLab, GitHub)
- **Username** is required and has a `minLength` of `3` chars (_Jenkins_)
- **Password** is required and has a `minLength` of `3` chars (_Jenkins_)
- NOTE: Only Multi-source providers like JIRA have "Add" functionality enabled.
This PR adds form validation rules to the Connection Form to prevent empty or faulty values from being sent to the BE API.
Fixes #621
Currently no validations exist on connections and settings forms for a given provider.
Validation rules are now applied to the Connection Form for …
=> feat: #621 config-ui : connection form validations

README-zh-CN.md, README.md
added a simple architecture diagram
=> docs: add architecture diagram

README-zh-CN.md, README.md, plugins/github/README-zh-CN.md, plugins/github/README.md, plugins/gitlab/README-zh-CN.md, plugins/gitlab/README.md, plugins/jenkins/README-zh-CN.md, plugins/jenkins/README.md, plugins/jira/README-zh-CN.md, plugins/jira/README.md
1. add demo link in main readme
2. add language switching in plugin readmes
=> feat: add demo link and language switching

config-ui/src/components/loaders/ContentLoader.jsx, config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/integration/manage.jsx, config-ui/src/pages/configure/settings/jira.jsx
This PR adds a shared content loader to Config-UI. This loader may only be visible briefly or not at all depending on connection speed. Note that our form components have native loaders on the Submit controls and those are already working where necessary.
#629
=> fix: #629 config-ui : add loading indicators

plugins/domainlayer/domainlayer.go, plugins/domainlayer/models/ticket/worklog.go, plugins/jira/jira.go, plugins/jira/models/jira_worklog.go, plugins/jira/tasks/jira_issue_collector.go, plugins/jira/tasks/jira_worklog_collector.go, plugins/jiradomain/jira_domain.go, plugins/jiradomain/tasks/worklog_converter.go
Extract worklogs from issue and store in the database.
https://github.com/merico-dev/lake/issues/710
=> feat: store jira worklog

README-zh-CN.md, README.md
1. adjust position of archi diagram
2. add a section in 'Make contribution'
3. adjust the font size of headings to make README clearer
=> feat: adjust position of archi diagram in main README

README-zh-CN.md, README.md
update architecture diagram in main readme
=> feat: update architecture diagram in readme

README.md
=> feat: remove ph badges

README-zh-CN.md, README.md, devops/sync/README.md, plugins/jenkins/jenkins.go, plugins/jenkins/tasks/worker.go
=> Fix some small issues found during custom support sessions

README-zh-CN.md, README.md, devops/sync/req.json
Fix docs for https://github.com/merico-dev/lake/issues/638
=> fix: fix doc for #658

plugins/core/testConnection.go
Fixes error message.
Closes https://github.com/merico-dev/lake/issues/882
=> fix: removed unnecessary comma from error message on /test

config-ui/src/components/Sidebar/SidebarMenu.jsx
Text fix. DevLake is more inline with our naming.
Closes #902
=> fix: tiny text update dev lake - devLake

plugins/gitlab/README-zh-CN.md, plugins/gitlab/README.md
README update...
GitHub => GitLab
=> docs: tiny readme update

models/domainlayer/README.md
update domainlayer readme to reflect latest design
=> docs: update domainlayer readme to reflect latest design

plugins/gitlab/tasks/commits_converter.go, scripts/compile-plugins.sh
=> Gitlab was not enriching additions or deletions on commits

grafana/dashboards/DemoCommitCountByAuthor.json, grafana/dashboards/DemoIsThisMonthMoreProductiveThanLast.json
Remove tool layer query from demo dashboards so that demo dashboards can display properly.
fix #925
=> fix: remove tool layer query from demo dashboard

config-ui/package-lock.json, config-ui/package.json, config-ui/src/components/Sidebar.jsx, config-ui/src/pages/triggers/index.jsx, config-ui/src/utils/config.js, config-ui/webpack.config.js
This makes a local mode in webpack. Then we can use variables from webpack in the JS.
Fixes https://github.com/merico-dev/lake/issues/907
=> feat: fix local mode for view dashboards button

plugins/jira/models/jira_issue.go, plugins/jira/tasks/jira_issue_collector.go
#575
collect all jira issue fields to db
create a type `JsonColumn` and add it in `JiraIssue` to collect all jira issue fields to db
[Please mention the issues here.](https://github.com/merico-dev/lake/issues/575)
=> feat: collect all jira issue field in db

MIGRATIONS.md, models/test/main_test.go
Just added a brief description of how migrations work for readers to be up to date with current changes.
No.
=> docs: add description of how migrations work

models/domainlayer/ticket/sprint.go, models/init.go, plugins/jira/tasks/jira_changelog_converter.go, plugins/jira/tasks/jira_sprint_converter.go, plugins/jira/tasks/jira_sprint_issue_burndown_converter.go
Add `sprint_issues_burndown` table in domain layer.
#913 #909
=> feat: sprint issue burndowm

models/domainlayer/crossdomain/board_repo.go, models/domainlayer/crossdomain/issue_commit.go, models/domainlayer/ticket/board_issue.go, models/domainlayer/ticket/issue.go, models/init.go, models/test/factory/issue_factory.go, plugins/jira/jira.go, plugins/jira/tasks/jira_issue_commit_converter.go, plugins/jira/tasks/jira_issue_converter.go
added cross domain tables from #915 according to #700
1. added tables : `board_issues` `board_repo` `issue_commits`
2. board issue relation ship was moved to `board_issue` table
3. convert jira issue/commits relationship to domainlayer
Part of #915
=> Cross domain part for #915

config-ui/Dockerfile
=> chore: fix config ui build error

plugins/github/api/github_connection.go
=> fix: test multiple github tokens in parallel

plugins/github/github.go
=> fix: enrichment should happen before conversion

config-ui/Dockerfile, config-ui/nginx.conf, config-ui/webpack.production.config.js
Fixes https://github.com/merico-dev/lake/issues/823
=> fix: nginx, fonts and images loading no css cache

plugins/github/tasks/github_commit_collector.go, scripts/pm.sh, services/task.go, utils/callframes.go, utils/worker_scheduler.go
=> Fix Github commits data lost

config-ui/src/components/messages/FormValidationErrors.jsx, config-ui/src/pages/pipelines/activity.jsx, config-ui/src/pages/pipelines/create.jsx, config-ui/src/pages/pipelines/index.jsx
This PR performs cleanups, hotfixes and other post-development tasks for the latest **Pipelines** feature release with `v0.6.0`.
=> fix: pipelines feature post-development tasks

plugins/ae/ae.go, plugins/compound/compound.go, plugins/feishu/feishu.go, plugins/github/github.go, plugins/gitlab/gitlab.go, plugins/jenkins/jenkins.go, plugins/jira/jira.go
added check statement to ensure all types implement interface Plugin at compile time for all plugins
Added a check statement to ensure all the plugins type implement interface
This will close issue #666
none to ensure
Added "var _ core.Plugin = (*XXX)(nil)" to ensure corresponding plugins implement core.Plugin
=> refactor(plugins): add check statement

plugins/core/plugin_utils.go, plugins/feishu/feishu.go, plugins/github/github.go, plugins/gitlab/gitlab.go, plugins/jenkins/jenkins.go, plugins/jenkins/tasks/worker.go, plugins/jira/jira.go, plugins/jira/tasks/jira_changelog_collector.go, plugins/jira/tasks/jira_issue_collector.go, plugins/jira/tasks/jira_remotelink_collector.go
added a config to limit gira, gitlab, feishu collecting rate
Added rate limit control in gira, gitlab, feishu plugins
Limit rate of scraping metrics from a large project to avoid causing increased load
Closes issue #931 
Will create a new issue to do some work on UI
=> feat(pipeline): limit requests per second

.github/workflows/golangci-lint.yml, .github/workflows/test-e2e.yml, go.mod, go.sum, models/domainlayer/code/commit.go, models/domainlayer/code/ref.go, models/init.go, plugins/gitextractor/README-zh-CN.md, plugins/gitextractor/README.md, plugins/gitextractor/gitextractor.go, plugins/gitextractor/main.go, plugins/gitextractor/models/interface.go, plugins/gitextractor/parser/libgit2.go, plugins/gitextractor/store/csv.go, plugins/gitextractor/store/csv_test.go, plugins/gitextractor/store/database.go, plugins/refdiff/refdiff.go, plugins/refdiff/utils/collect.go, utils/network_helper_test.go
Git repo extractor extracts commits and references from a remote or local git repository. It then saves the data into database or csv files.
https://github.com/merico-dev/lake/issues/1004
=> feat: git repo extractor

plugins/github/models/github_issue.go, plugins/github/tasks/github_issues_collector.go
Fixes #https://github.com/merico-dev/lake/issues/1113
=> feat: link tool layer github issues to commit

plugins/refdiff/README-zh-CN.md, plugins/refdiff/README.md
more accurate document for ref-diff plugin
Cloeses #1118
=> docs: more accurate document

config-ui/Dockerfile, config-ui/nginx.conf, config-ui/nginx.sh, config-ui/src/components/Sidebar/MenuConfiguration.jsx, docker-compose.yml, plugins/core/apiclient.go, plugins/github/github.go, plugins/github/tasks/github_api_client.go, plugins/github/tasks/github_issue_converter.go, plugins/refdiff/README.md
9a093c8 (HEAD -> pingcap, origin/pingcap) fix: missing severity/component field on issues from github
286bb8f fix: github api client swallowing error cause task hangs indefinitely
5c2e549 fix: github keep sending samem progress multiple times
b52d01b fix: apiclient should provide response body when unmarshal failed
a934222 fix: bring back triggers for multistages pipeline
28cc149 feat: config-ui docker image supports basic auth
=> fix multiple problems for PingCap release

plugins/jira/tasks/jira_issue_commit_converter.go, plugins/jira/tasks/jira_remotelink_collector.go
Fix error message "invalid sture type" when collecting jira remotelink
=> fix: invalid struct type error for jira plugin

plugins/github/github.go, plugins/github/tasks/github_issues_collector.go
collecting labels and issues at the same time
=> refactor: optimize label collect

plugins/github/tasks/github_issue_enricher.go
githubIssue.Severity was given TYPE'value by mistaken
=> fix(plugins): fix severity not shown

plugins/refdiff/refdiff.go, services/task.go
added progress in refdiff
closes issue #1156
=> fix(plugins): added progress

Dockerfile, README-zh-CN.md, README.md, config-ui/src/components/pipelines/ProviderSettings.jsx, config-ui/src/components/pipelines/StageTaskCaption.jsx, config-ui/src/components/pipelines/StageTaskName.jsx, config-ui/src/components/pipelines/TaskActivity.jsx, config-ui/src/data/collectionDefaults.js, config-ui/src/hooks/usePipelineValidation.jsx, config-ui/src/pages/pipelines/activity.jsx, config-ui/src/pages/pipelines/create.jsx, config-ui/src/pages/triggers/index.jsx, config-ui/test/testData.js, devops/sync/req.json, docker-compose.yml
github repository renaming for client side / docker-compose support local build
=> github repository renaming for client side / docker-compose support local build

plugins/github/tasks/github_issue_converter.go
Store number of issue in the key field of table.issues
=> fix(plugins): store number in key field

plugins/core/apiclient.go, plugins/github/tasks/github_api_client.go, utils/worker_scheduler.go
=> fix: fix pipeline got stuck

README.md, plugins/gitextractor/README.md
=> Doc update j

models/domainlayer/code/commit.go, models/domainlayer/code/ref.go, plugins/gitextractor/parser/libgit2.go, plugins/gitextractor/store/csv_test.go, plugins/github/tasks/github_commit_converter.go, plugins/gitlab/tasks/gitlab_commit_converter.go
fix a typo in column name `issues.committer_id`
change some columns from `LONGTEXT` to `VARCHAR`
=> fix: fix column name committer_id

plugins/github/tasks/github_repo_converter.go
added suffix to url
added org as prefix to name
closes issue #1168
closes issue #1168
=> refactor(domainlayer): modify table.boards

docker-compose.yml, grafana/provisioning/datasources/datasource.yml, releases/lake-v0.7.0/docker-compose.yml
1. configure mysql connection vai Environment Variable for grafana container for settings consistence
2. added v0.7.0 docker-compose file
=> Release v0.7.0

releases/lake-v0.7.0/docker-compose.yml, releases/lake-v0.7.0/env.example
remove build section from release yml and make sure `docker-compose up` can work
=> fix: remove build section from release yml

README.md
This PR updates main `README.md` based on changes outlined on #1124
=> `docs`: update main README.md

plugins/github/tasks/github_issue_comments_collector.go, plugins/github/tasks/github_issue_converter.go, plugins/github/tasks/github_issue_events_collector.go, plugins/github/tasks/github_note_converter.go, plugins/github/tasks/github_pull_request_comments_collector.go, plugins/github/tasks/github_pull_request_commits_collector.go, plugins/github/tasks/github_pull_request_converter.go, plugins/github/tasks/github_repo_converter.go, plugins/github/tasks/github_user_converter.go
Changed the way to iterate db data in github to avoid store too much data in memory
changed tasks list is the same as files changed, you can check it in commit
=> refactor(plugins): use cursor to iterate dbdata

k8s-deploy.yaml
Signed-off-by: Daniel Hu <tao.hu@merico.dev>
Feat: Adding Kubernetes deploy support
#844
=> Feat: Adding Kubernetes deploy support

README.md
Updated `User Setup` and `Developer Setup` sections accordingly latest changes
=> docs: update main README for v0.7.0

README-zh-CN.md, README.md
- Update Chinese README to make it align with the English version
- Update the `Step 9 - pipeline run` part in [developer setup](https://github.com/merico-dev/lake#developer-setup)
- Adjust the layout of the main README
=> docs: update English and Chinese Readmes to v0.7.0

plugins/core/plugin_utils.go, plugins/core/plugin_utils_test.go, plugins/jira/api/jira_sources.go, plugins/jira/tasks/jira_api_client.go
Add Encode,Decode function for Encrypt and Decrypt.
Encrypt the BasicAuthEncoded befor it in to the database.
Decrypt ths BasicAuthEncoded after it out from the database.
Will close issue #536 
=> feat:Encrypt for JiraAuth

plugins/refdiff/README.md
update code example for ref diff
=> docs: update readme example code

config-ui/package-lock.json, config-ui/package.json, config-ui/src/components/menus/PipelinePresetsMenu.jsx, config-ui/src/components/widgets/PipelineIndicator.jsx, config-ui/src/data/pipeline-config-samples/default.js, config-ui/src/data/pipeline-config-samples/gitextractor.js, config-ui/src/data/pipeline-config-samples/github.js, config-ui/src/data/pipeline-config-samples/gitlab.js, config-ui/src/data/pipeline-config-samples/jenkins.js, config-ui/src/data/pipeline-config-samples/jira.js, config-ui/src/data/pipeline-config-samples/refdiff.js, config-ui/src/hooks/usePipelineManager.jsx, config-ui/src/hooks/usePipelineValidation.jsx, config-ui/src/pages/pipelines/activity.jsx, config-ui/src/pages/pipelines/create.jsx, config-ui/src/pages/pipelines/index.jsx, config-ui/src/styles/common.scss, config-ui/src/styles/pipelines.scss
- Advanced Mode Toggle Switch
- Preserve RAW `JSON` Configuration Separately
- Support loading configuration from Standard (Visual) Mode
- Parse for Valid JSON
- Detect Supported Providers
- Standard (Visual) Mode
- Advanced Mode
This PR adds **Advanced Mode** to the Create Pipeline RUN Workflow which allows users to manually enter a JSON Configuration for running a complex pipeline. User will turn the Advanced mode Toggle switch to the "ON" Position to activate the JSON Editor for defining tasks manually. This is intended to replace the legacy Triggers page.
Users are expected to consult the documentation prior to using Advanced Mode, however sample task configurations are available from the *Advanced Options* Pipeline Menu.
In a future release, the `Triggers` Sidebar Menu entry should …
=> feat: create pipeline - advanced pipeline mode | `1127`

plugins/jira/tasks/jira_sprint_issues_converter.go
Use domain layer user id instead of tool layer in issue_assignee_history
Used onConflict(updateAll : true) when insert table.assignee_history, table.sprints_history, table.status_history
Will not close issue #1069 , but a fix
Store tool layer raw jira_issues.assignee_id in table.issue_assignee_history
Changed to domain layer user id 
=> fix(plugins): change assignee id

.env.example, k8s-deploy.yaml, services/pipeline.go
=> Fix empty pipeline stage causing backend to crash

plugins/github/github.go
When triggering github plugin from config-ui, pull requests weren't collected.
=> fix(github): github not collecting pull requests

plugins/ae/tasks/ae_api_client.go, plugins/core/apiclient.go
=> fix: retry with new nonce

plugins/gitextractor/gitextractor.go, plugins/gitextractor/main.go
=> fix gitextractor arguments validation

plugins/jira/tasks/jira_board_collector.go
jira CollectBoard with http code checking
Added 'StatusCode' check for http responses in Jira's 'CollectBoard'.
=> Fix jira collect board panic

config-ui/nginx.conf, plugins/github/api/github_connection.go, plugins/gitlab/api/gitlab_connections.go, plugins/jira/api/jira_connections.go, plugins/jira/models/jira_source.go, plugins/jira/tasks/jira_api_client.go
=> User setup fixes

models/domainlayer/ticket/issue.go, models/domainlayer/ticket/issue_history.go, models/domainlayer/ticket/sprint.go, plugins/core/plugin_utils_test.go, plugins/jira/models/jiras_print.go, plugins/jira/tasks/jira_issue_collector.go, plugins/jira/tasks/jira_issue_converter.go, plugins/jira/tasks/jira_remotelink_collector.go, plugins/jira/tasks/jira_sprint_converter.go, plugins/jira/tasks/jira_sprint_issues_converter.go, plugins/jira/tasks/jira_worklog_converter.go
Improve data quality relating to EE integration
=> EE integration bug fix

config-ui/src/components/menus/PipelineConfigsMenu.jsx, config-ui/src/components/menus/PipelinePresetsMenu.jsx, config-ui/src/pages/pipelines/create.jsx
- User can click the **Editor "Settings" Gear** to open the menu.
This PR allows easier access to the "Advanced Options" Pipeline menu which lets the user load preset Configurations for available data providers.
#1213
=> `fix`: create pipeline : optimize advanced menu accessibility

ARCHITECTURE.md, README-zh-CN.md, README.md
1. add roadmap
2. add the link to metric page
3. add the link to domain layer schema design
4. simplify the whole page
5. clearer navigation
#1261
=> docs: refine the main readme

README-zh-CN.md, README.md
1. update Chinese main README according to #1277 
2. update the layout of main README
#1261
=> docs: update Chinese main README

config/config.go, config/config_test.go, plugins/github/api/github_sources.go
Feat add GitHub response field
Add github response field for /plugins/github/sources/1
Merge sturct GithubResponse and GithubConfig
Close https://github.com/merico-dev/lake/issues/1269
=> Feat add GitHub response field

config/config.go, config/config_test.go, plugins/github/api/github_sources.go
feat: add validate for force required field
Add validator in SetStruct for checking.
close https://github.com/merico-dev/lake/issues/1294
=> feat: add validate for force required field

main.go, plugins/core/iso8601time.go, plugins/jira/api/jira_connections.go, plugins/jira/jira.go, plugins/jira/models/response_type.go, plugins/jira/tasks/interfaces.go, plugins/jira/tasks/jira_api_client.go, plugins/jira/tasks/jira_changelog_collector.go, plugins/jira/tasks/jira_cloud_api_client.go, plugins/jira/tasks/jira_remotelink_collector.go, plugins/jira/tasks/jira_server_api_client.go, plugins/jira/tasks/v8models/board.go, plugins/jira/tasks/v8models/changelog.go, plugins/jira/tasks/v8models/interfaces.go, plugins/jira/tasks/v8models/issue.go, plugins/jira/tasks/v8models/project.go, plugins/jira/tasks/v8models/remotelink.go, plugins/jira/tasks/v8models/sprint.go, plugins/jira/tasks/v8models/user.go, plugins/jira/tasks/v8models/worklog.go
support Jira server 8.x.x
#886
=> jira server support

models/domainlayer/ticket/sprint.go, plugins/core/apiclient.go, plugins/jira/tasks/jira_api_client.go, plugins/jira/tasks/jira_remotelink_collector.go, plugins/jira/tasks/jira_server_api_client.go, plugins/jira/tasks/jira_sprint_converter.go, plugins/jira/tasks/v8models/issue.go, plugins/jira/tasks/v8models/remotelink.go, plugins/jira/tasks/v8models/user.go
fix missing records in `jira_board_issues`
handle status code 404 caused by a missing issue.
add `origin_board_id` to `sprint` table.
set timeout of Jira client to 20s
=> fix: handle status code 404

plugins/ae/tasks/ae_commits_converter.go, plugins/core/apiclient_test.go, plugins/github/tasks/github_api_issue_comments_collector.go, plugins/github/tasks/github_comments_enricher.go, plugins/github/tasks/github_commit_converter.go, plugins/github/tasks/github_issue_converter.go, plugins/github/tasks/github_issue_enricher.go, plugins/github/tasks/github_issue_labels_convertor.go, plugins/github/tasks/github_note_converter.go, plugins/github/tasks/github_pull_request_commit_convertor.go, plugins/github/tasks/github_pull_request_converter.go, plugins/github/tasks/github_pull_request_enricher.go, plugins/github/tasks/github_pull_request_issue_enricher.go, plugins/github/tasks/github_repo_converter.go, plugins/github/tasks/github_user_converter.go, plugins/gitlab/tasks/gitlab_api_client.go, plugins/gitlab/tasks/gitlab_commit_collector.go, plugins/gitlab/tasks/gitlab_pipeline_collector.go, plugins/gitlab/tasks/gitlab_tag_collector.go, plugins/jira/tasks/jira_api_client.go, plugins/jira/tasks/jira_issue_collector.go, plugins/jira/tasks/jira_server_api_client.go, plugins/refdiff/tasks/refs_commits_diffs_calculator.go, plugins/refdiff/tasks/refs_issues_diffs_calculator.go, plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
Changed *url.Value to url.Value
Changed errors.TaskCancel to ctx.Err()
=> fix(plugins): fix url.Value

plugins/helper/api_collector.go
pagination unaware of the total number of pages
=> feat: pagination unaware of total number of pages

plugins/github/github.go, plugins/github/models/github_issue.go, plugins/github/models/github_pull_request.go, plugins/github/tasks/github_api_comments_collector.go, plugins/github/tasks/github_api_comments_extractor.go, plugins/github/tasks/github_api_events_collector.go, plugins/github/tasks/github_api_events_extractor.go, plugins/github/tasks/github_api_issue_collector.go, plugins/github/tasks/github_api_issues_extractor.go, plugins/github/tasks/github_api_pull_request_collector.go, plugins/github/tasks/github_api_pull_requests_extractor.go, plugins/github/tasks/github_api_repositories_collector.go
adapt github extractor to new design
=> Refactor GitHub extractor

logger/log.go, plugins/ae/ae.go, plugins/ae/models/ae_commit.go, plugins/ae/models/ae_project.go, plugins/ae/tasks/ae_api_client.go, plugins/ae/tasks/ae_commits_collector.go, plugins/ae/tasks/ae_commits_converter.go, plugins/ae/tasks/ae_commits_extractor.go, plugins/ae/tasks/ae_project_collector.go, plugins/ae/tasks/ae_project_extractor.go, plugins/ae/tasks/ae_task_data.go, plugins/core/apiclient.go, plugins/core/plugin.go, plugins/core/task_context.go, plugins/helper/default_task_context.go
1. decouple global variable dependency
2. raw data layer support
3. define a new interface named `ManagedSubTasks`, in order to replace `Plugin.Execute`
Logging sample:
```
time="2022-03-15 18:07:57" level=info msg="ae start plugin"
time="2022-03-15 18:07:57" level=info msg="ae set progress: 0/5"
time="2022-03-15 18:07:57" level=info msg="ae executing subtask collectProject"
time="2022-03-15 18:07:57" level=info msg="ae [collectProject] start api collection"
time="2022-03-15 18:07:57" level=debug msg="ae [api-client] GET http://???:30012/projects/13"
time="2022-03-15 18:07:58" level=info msg="ae [collectProject] end api collection"
time="2022-03-15 18:07:58" level=info msg="ae inc progress 1/5"
time="2022-03-15 18:07:58" level=info msg="ae executing subtask collectCommits" …
```
=> refactor: AE plugin rawlayer/temporal support

plugins/gitlab/gitlab.go, plugins/gitlab/models/gitlab_commit.go, plugins/gitlab/models/gitlab_merge_request.go, plugins/gitlab/models/gitlab_project_commits.go, plugins/gitlab/models/gitlab_reviewer.go, plugins/gitlab/models/gitlab_user.go, plugins/gitlab/tasks/gitlab_api_client.go, plugins/gitlab/tasks/gitlab_api_commit_collector.go, plugins/gitlab/tasks/gitlab_api_commit_extractor.go, plugins/gitlab/tasks/gitlab_api_merge_request_collector.go, plugins/gitlab/tasks/gitlab_api_merge_request_extractor.go, plugins/gitlab/tasks/gitlab_merge_request_reviewer.go, plugins/gitlab/tasks/gitlab_shared.go, plugins/gitlab/tasks/gitlab_task_data.go, plugins/helper/api_collector.go, plugins/helper/api_rawdata.go
refactor commit and merge request collect
CollectApiCommits
ExtractApiCommits
CollectApiMergeRequests
ExtractApiMergeRequests
=> refactor: refactor commit and merge request collect

plugins/github/github.go, plugins/github/models/github_user.go, plugins/github/tasks/github_api_comments_extractor.go, plugins/github/tasks/github_api_commit_collector.go, plugins/github/tasks/github_api_commit_extractor.go, plugins/github/tasks/github_api_commit_stats_collector.go, plugins/github/tasks/github_api_issue_collector.go, plugins/github/tasks/github_api_pull_request_collector.go, plugins/github/tasks/github_api_pull_request_commit_collector.go, plugins/github/tasks/github_api_pull_request_review_collector.go, plugins/github/tasks/github_commit_converter.go, plugins/github/tasks/github_issue_converter.go, plugins/github/tasks/github_issue_labels_convertor.go, plugins/github/tasks/github_pull_request_commit_convertor.go
Refactored github commits, pr_commits, issue, issue_labels converter
=> Refactor GitHub converter 1

plugins/github/github.go, plugins/github/models/github_user.go, plugins/github/tasks/github_api_comments_extractor.go, plugins/github/tasks/github_api_commit_collector.go, plugins/github/tasks/github_api_commit_extractor.go, plugins/github/tasks/github_api_commit_stats_collector.go, plugins/github/tasks/github_api_issue_collector.go, plugins/github/tasks/github_api_pull_request_collector.go, plugins/github/tasks/github_api_pull_request_commit_collector.go, plugins/github/tasks/github_api_pull_request_review_collector.go
Use repo_id to scope 
Tested all subtasks after refactor
=> Refactor GitHub change to repo

plugins/jira/jira.go, plugins/jira/tasks/board_collector.go, plugins/jira/tasks/jira_api_issues_collector.go, plugins/jira/tasks/project_collector.go, plugins/jira/tasks/sprint_collector.go
3 collectors:
`collectApiBoard`
`collectApiProjects`
`collectApiSprints`
=> refactor: jira plugin

.env.example, plugins/feishu/apimodels/meeting_top_user_item_result.go, plugins/feishu/feishu.go, plugins/feishu/models/feishu_meeting_top_user_item.go, plugins/feishu/tasks/feishu_api_client.go, plugins/feishu/tasks/feishu_meeting_top_user_item_collector.go, plugins/feishu/tasks/feishu_meeting_top_user_item_extractor.go, plugins/feishu/tasks/feishu_task_data.go, plugins/helper/api_collector.go, plugins/helper/iterator.go
=> feat: feishu collector&extractor

plugins/jenkins/jenkins.go, plugins/refdiff/refdiff.go, plugins/refdiff/tasks/refdiff_task_data.go, plugins/refdiff/tasks/refs_commits_diffs_calculator.go, plugins/refdiff/tasks/refs_issues_diffs_calculator.go, plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
=> Refactor refdiff

README-zh-CN.md, README.md, plugins/github/README.md
1. highlight Demo link in the main README
2. weaken the `setup with Tin` entry based on Nitin's observation of 3 users got confused when setting up this way.
3. simplify DevLake value proposition by deleting `why devlake` and updating `What can be accomplished with DevLake?`
4. update step 2 in #user setup.
5. fix a bug in Github readme
=> docs: update main readme

plugins/gitlab/gitlab.go, plugins/gitlab/tasks/gitlab_api_commit_converter.go, plugins/gitlab/tasks/gitlab_api_merge_request_converter.go, plugins/gitlab/tasks/gitlab_api_note_converter.go, plugins/gitlab/tasks/gitlab_api_project_converter.go, plugins/gitlab/tasks/gitlab_merge_request_enricher.go
Gitlab refactor
EnrichMergeRequests
ConvertApiProjects
ConvertApiMergeRequests
ConvertApiCommits
ConvertApiNotes
=> Gitlab refactor

runner/runner.go
minor fix
if progress != nil {
progress <- core.RunningProgress{
Type:          core.SetCurrentSubTask,
SubTaskName:   subtaskMeta.Name,
SubTaskNumber: i,
}
}
=> fix(framework): fix progress

README-zh-CN.md, README.md
get rid of header 'Demo Address' to simplify the main readme
=> docs: simplify the main readme

plugins/gitlab/gitlab.go, plugins/gitlab/tasks/gitlab_api_commit_collector.go, plugins/gitlab/tasks/gitlab_api_commit_converter.go, plugins/gitlab/tasks/gitlab_api_commit_extractor.go, plugins/gitlab/tasks/gitlab_api_merge_request_collector.go, plugins/gitlab/tasks/gitlab_api_merge_request_commits_collector.go, plugins/gitlab/tasks/gitlab_api_merge_request_commits_extractor.go, plugins/gitlab/tasks/gitlab_api_merge_request_converter.go, plugins/gitlab/tasks/gitlab_api_merge_request_extractor.go, plugins/gitlab/tasks/gitlab_api_merge_request_notes_collector.go, plugins/gitlab/tasks/gitlab_api_merge_request_notes_extractor.go, plugins/gitlab/tasks/gitlab_api_note_converter.go, plugins/gitlab/tasks/gitlab_api_pipeline_collector.go, plugins/gitlab/tasks/gitlab_api_pipeline_extractor.go, plugins/gitlab/tasks/gitlab_api_project_collector.go, plugins/gitlab/tasks/gitlab_api_project_converter.go, plugins/gitlab/tasks/gitlab_api_project_extractor.go, plugins/gitlab/tasks/gitlab_api_tag_collector.go, plugins/gitlab/tasks/gitlab_api_tag_extractor.go, plugins/gitlab/tasks/gitlab_merge_request_enricher.go, plugins/gitlab/tasks/gitlab_merge_request_reviewer.go, plugins/gitlab/tasks/gitlab_shared.go, plugins/helper/api_collector.go
refactor: gitlab main
Init
SubTaskMetas
PrepareTaskData
RootPkgPath
ApiResources
main
=> refactor: gitlab main

.env.example, Makefile, plugins/helper/worker_scheduler_test.go
=> fix: worker_scheduler_test unit test

README-zh-CN.md
add k8s setup guide to the main README-zh-CN
#844
=> docs: add k8s setup guide to the main README-zh-CN

.env.example, plugins/github/github.go, plugins/github/tasks/github_issue_enricher.go, plugins/github/tasks/github_pull_request_enricher.go, plugins/github/tasks/github_pull_request_issue_enricher.go
moved regex compile into func
Already tested enrich after changing config-ui
=> fix(github): move regex compile to func

api/pipelines/pipelines.go, api/push/push.go, api/router.go, api/shared/api_output.go, api/task/task.go, plugins/core/plugin_utils.go, plugins/github/api/github_connection.go, plugins/gitlab/api/gitlab_connections.go, plugins/jenkins/api/jenkins_connections.go, plugins/jira/api/jira_connections.go, plugins/jira/api/jira_proxy.go, services/pushapi.go
api server adjustment for issue #1380
=> refactor: unify error response format

plugins/helper/api_async_client.go, plugins/helper/api_collector.go
=> fix: #1373

config-ui/src/data/integrations.jsx, config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/hooks/useSettingsManager.jsx, config-ui/src/pages/configure/connections/AddConnection.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/settings/github.jsx, config-ui/src/pages/configure/settings/gitlab.jsx, config-ui/src/pages/configure/settings/jenkins.jsx, config-ui/src/pages/configure/settings/jira.jsx
-  `fix`: resolve field states for github settings save    
-  `fix`: provide empty config settings on jira save
This PR applies needed hotfixes to **Configuration UI** from minor release `v0.9.1` to `main` branch.
=> config ui - apply v0.9.1 hotfixes `->` main branch

plugins/github/github.go, plugins/github/tasks/github_api_client.go, plugins/github/tasks/github_api_repositories_collector.go, plugins/github/tasks/github_api_repositories_extractor.go, plugins/github/tasks/github_commit_converter.go, plugins/github/tasks/github_issue_converter.go, plugins/github/tasks/github_issue_labels_convertor.go, plugins/github/tasks/github_note_converter.go, plugins/github/tasks/github_pull_request_commit_convertor.go, plugins/github/tasks/github_pull_request_converter.go, plugins/github/tasks/github_pull_request_issues_convertor.go, plugins/github/tasks/github_pull_request_labels_convertor.go, plugins/github/tasks/github_repo_converter.go, plugins/github/tasks/github_user_converter.go
make github plugin great again
=> fix: github plugin not working correctly

plugins/jira/tasks/issues_extractor.go, plugins/jira/tasks/sprint_converter.go
=> fix: missing issue_commits

models/domainlayer/crossdomain/issue_repo_commits.go, plugins/jira/jira.go, plugins/jira/models/jira_issue_commit.go, plugins/jira/tasks/issue_repo_commit_converter.go, plugins/jira/tasks/remotelink_extractor.go, runner/db.go
added one more task, convert issue_repo_commits
=> feat(jira): add issue_repo_commits

plugins/gitlab/tasks/gitlab_api_client.go, plugins/helper/api_ratelimit_calc.go, services/task.go
Add progress detail and fix divide zero
Add GetProgressDetail
Add GetProgressDetailToTasks for less lock
Changed "unlimit" to "Use default" for fix divide 0
issue #1424 
issue #1423 
=> Add progress detail

plugins/gitextractor/parser/libgit2.go
gitextractor performance improvement
=> refactor: gitextractor performance improvement

plugins/github/github.go, plugins/github/tasks/github_pull_request_issue_enricher.go
cherrypick #1437 to release-v0.9
=> fix(github): skip pr_issue when issue invalid

plugins/gitextractor/models/interface.go, plugins/gitextractor/parser/libgit2.go, plugins/gitextractor/store/csv.go, plugins/gitextractor/store/database.go
performance improvement 
fix wrong tag commit sha
#1440 #1407 
=> Gitextractor fix

go.mod, plugins/gitextractor/models/interface.go, plugins/gitextractor/parser/libgit2.go, plugins/gitextractor/store/csv.go, plugins/gitextractor/store/database.go, plugins/gitextractor/tasks/git_repo_collector.go
only calculate diff against parent 0
batch insert
fix wrong tag commit sha
=> Gitextractor performance improvement

config-ui/src/components/Sidebar/MenuConfiguration.jsx, config-ui/src/components/validation/InputValidationError.jsx, config-ui/src/data/Providers.js, config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/connections/ConnectionForm.jsx, config-ui/src/pages/configure/integration/manage.jsx, config-ui/src/pages/pipelines/create.jsx, config-ui/src/pages/pipelines/index.jsx, config-ui/src/pages/triggers/index.jsx, config-ui/src/styles/integration.scss
- `fix`: enhance field behavior on connection settings
- `fix`: update menu labels and titles for pipelines
- `fix`: correct typo with legacy feature notice txt
- `fix`: lookup online status for connections table
This PR applies needed hotfixes to **Configuration UI** from minor release `v0.9.2` to `main` branch.
=> config ui - apply `v0.9.2` hotfixes `->` main branch

.github/workflows/golangci-lint.yml, plugins/gitlab/tasks/gitlab_api_client.go
This fix the `nil` pointer problem mentioned in #1449 , but irrelevant to the root cause.
=> fix: gitlab api client nil pointer error

Dockerfile
=> feat: dbt docker env

.env.example, plugins/github/README-zh-CN.md, plugins/github/README.md, plugins/github/tasks/github_pull_request_issue_enricher.go, plugins/refdiff/tasks/refs_issues_diffs_calculator.go
close #1448
Fixed refs_issues_diffs_calculator.go because some projects might merge requests by both squash&merge and merge directly.
Fixed pull_request_issues_enricher’s regex
Closes #1448
=> fix(plugin): fix minor bugs

plugins/github/models/github_commit.go, plugins/github/models/github_issue.go, plugins/github/models/github_issue_comment.go, plugins/github/models/github_issue_event.go, plugins/github/models/github_issue_label.go, plugins/github/models/github_pull_request.go, plugins/github/models/github_pull_request_comment.go, plugins/github/models/github_pull_request_commit.go, plugins/github/models/github_pull_request_label.go, plugins/github/models/github_repo.go, plugins/github/models/github_reviewer.go, plugins/github/models/github_user.go, plugins/github/tasks/github_api_issues_extractor.go, plugins/github/tasks/github_api_pull_request_collector.go, plugins/github/tasks/github_api_pull_requests_extractor.go, plugins/github/tasks/github_issue_converter.go
github_issue
fix github_pull_requests.url
close #1455
add url to table.issues
fix github_pull_requests.url
close #1455
=> fix(github): add url to github_issues

plugins/gitlab/tasks/gitlab_api_client.go
Fix gitlab commits collection bug
=> fix: gitlab step concurrency

plugins/refdiff/tasks/refs_commits_diffs_calculator.go, plugins/refdiff/utils/commit_node_graph.go
added some comments and changed a func name
=> Chore add comments refdiff

plugins/gitlab/gitlab.go, plugins/gitlab/tasks/gitlab_merge_request_commits_converter.go
gitlab merge request commits convert
Add ConvertMergeRequestCommits
=> feat: convert merge request commits

plugins/refdiff/utils/commit_node_graph.go
rename back to lostSha
rename diffSha back to lostSha
=> style: rename back to lostSha

plugins/dbt/README.md, plugins/dbt/dbt.go, plugins/dbt/tasks/dbt_converter.go, plugins/dbt/tasks/dbt_task_data.go
=> feat: dbt add user defined parameters

plugins/dbt/README-zh-CN.md, plugins/dbt/README.md
=> docs: the dbt plugin add README and README-zh-CH

plugins/github/tasks/note_converter.go
fixed Author in note_converter
=> fix(github): modify notes and comments

plugins/github/tasks/note_converter.go
=> fix(github): fix note converter

plugins/github/tasks/api_issue_collector.go
change github_issues to _tool_github_issues
=> fix(github): issue collector

plugins/helper/api_collector.go
close #1502
close channel c before each return
close #1502
=> fix(framework): fix api-collector

Dockerfile
=> fix: dockerfile install dbt error

Dockerfile
=> fix: The docker is unable to run on mac.

plugins/jira/tasks/apiv2models/issue.go
fix the bug reported in #1552, which is caused by passing an incorrect parameter value
#1552 
=> fix: passing an incorrect parameter value

Dockerfile, Makefile, README.md, docker-compose-temporal.yml
=> Temporal Mode docker image / docker compose and documentation

plugins/github/tasks/commit_converter.go
=> fix(github): commit_converter EnabledByDefault set to false

services/init.go
Set cron to UTC location
close #1510 1510
=> fix(blueprint): add utc location

e2e/gitlab_merge_request_commits_merge_requests_test.go, e2e/gitlab_merge_request_commits_test.go, e2e/gitlab_mrs_test.go, plugins/gitlab/tasks/gitlab_shared.go, plugins/gitlab/tasks/merge_request_comment_converter.go, plugins/gitlab/tasks/merge_request_commits_converter.go, plugins/helper/api_async_client.go
We return the result of retry instead of assign it to err
Close #1506 
relate to #1501
=> fix(framework): return the result of retry instead of assign it to err

models/domainlayer/code/pull_request.go, models/domainlayer/crossdomain/pull_request_issue.go, models/migrationscripts/archived/pull_request.go, plugins/github/models/github_pull_request_issue.go, plugins/github/models/migrationscripts/archived/pull_request.go, plugins/github/models/migrationscripts/archived/pull_request_issue.go, plugins/github/tasks/pull_request_converter.go, plugins/github/tasks/pull_request_issue_enricher.go, plugins/github/tasks/pull_request_issues_convertor.go, plugins/gitlab/models/gitlab_user.go, plugins/gitlab/tasks/merge_request_converter.go
fix #1576 
modify pull_requests and pull_request_issues
For gitlab, we don't process authorId for
pull_requests
pull_request_issues
=> Fix domain pull request

Dockerfile
=> fix: dbt can not run on docker

.env.example, plugins/refdiff/README-zh-CN.md, plugins/refdiff/README.md
assign GITHUB_PR_TITLE_PATTERN and GITHUB_PR_BODY_CLOSE_PATTERN a default value
modify README 
close #1592
=> chore(refdiff): modify docs and .env

plugins/feishu/README-zh-CN.md, plugins/feishu/README.md
relate to https://github.com/merico-dev/lake/issues/1579
=> docs: the feishu plugin update readme

.env.example, .github/workflows/build.yml, config-ui/nginx.conf, config-ui/nginx.sh, docker-compose-temporal.yml, docker-compose.yml
Fixes #1586
1. make `docker build` run in parallel
2. config-ui nginx find out nameserver address automatically
3. remove nginx env-var from `.env` file
=> Support k8s deployment

plugins/feishu/README-zh-CN.md, plugins/github/README-zh-CN.md, plugins/github/README.md
relate to https://github.com/merico-dev/lake/issues/1602
=> The  github plugin readme are up to date

config-ui/src/pages/configure/settings/github.jsx, config-ui/src/pages/pipelines/create.jsx
modify some words in the files below:
github.jsx
create.jsx
Close #1604 #1608
=> fix(config-ui): modify label

plugins/refdiff/tasks/refs_commits_diffs_calculator.go, plugins/refdiff/tasks/refs_issues_diffs_calculator.go, plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
fix #1585 
- fix SQL containing deprecated column names
- fix SQL injection vulnerability
#1585 
=> fix: #1585

README.md
fix the wrong link in README.md
#1624 
=> fix: wrong link in README

grafana/dashboards/GithubBasicMetrics.json, grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
Add two Github dashboards: Basic metrics and quality metrics for Github data.
=> feat: add two Github dashboards

config-ui/src/components/pipelines/ProviderSettings.jsx, config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/pages/pipelines/create.jsx
This PR updates GitExtractor plugin form options to render GitHub repositories in a dropdown list.
#1465
=> `fix`: fetch gitextractor github repos from domain layer api

plugins/jira/api/jira_sources.go
=> fix: decrypt basicAuthEncoded before responding

config-ui/package-lock.json, config-ui/package.json, config-ui/src/components/blueprints/AddBlueprintDialog.jsx, config-ui/src/components/blueprints/BlueprintsGrid.jsx, config-ui/src/components/pipelines/ProviderSettings.jsx, config-ui/src/hooks/useBlueprintManager.jsx, config-ui/src/hooks/useBlueprintValidation.jsx, config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/pages/blueprints/index.jsx, config-ui/src/pages/configure/integration/manage.jsx, config-ui/src/pages/pipelines/create.jsx
This PR uses `cron-parser` as the library that manages **Cron Expression Parsing**, configured with `UTC` option mode set to`true` by default. This is intended to resolve inconsistencies with date scheduling in Crontab UTC and localized date formatting when Next Run Dates are calculated.
#1610, #1644, #1646 
[`Pending...`]
=> `fix`: blueprints: refactor cron expression parsing

config-ui/src/components/pipelines/ProviderSettings.jsx, config-ui/src/hooks/usePipelineValidation.jsx
=> fix: remove multiple board_id / project_id from config-ui

config-ui/src/components/pipelines/ProviderSettings.jsx
fix #1661 
`Select Github Repository` -> `Select Repository`
#1661 
=> fix a small text issue in config ui

releases/lake-v0.10.0-beta1/docker-compose.yml, releases/lake-v0.10.0-beta1/env.example
This PR just creates the new release folder with the new `docker-compose.yml` and `env.example` for the new version.
Closes https://github.com/merico-dev/lake/issues/1648
=> Make a new release for v0.10.0-beta1

plugins/helper/api_collector.go
=> fix: jira changelog collection being very slow

plugins/helper/api_collector.go
=> fix: #1668

plugins/helper/api_async_client.go, plugins/helper/api_collector.go, plugins/jira/tasks/worklog_collector.go
=> fix: unable to cancel jira worklog

plugins/helper/api_collector.go, plugins/helper/default_task_context.go
=> fix: add wait group to api_collector Input logic

plugins/jira/jira.go, plugins/jira/tasks/apiv2models/changelog.go, plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/changelog_extractor.go, plugins/jira/tasks/issues_extractor.go
Closes #1690 
extracting entity `users` from issues and changelogs
#1690 
=> fix: missing users for plugin jira

README.md
remove extra line from main readme
=> docs: remove extra line

docs/create-pipeline-advanced-mode.md
This PR adds documentation for Config UI's advanced mode for creating pipelines.
Cloese https://github.com/merico-dev/lake/issues/1574
=> docs: create pipeline advanced mode

plugins/jira/tasks/worklog_collector.go
add incremental update operation to jira worklog collector
close #1677
=> fix(jira): add incremental to worklog

grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
=> fix: dashboard title name

releases/lake-v0.10.1/docker-compose.yml, releases/lake-v0.10.1/env.example
=> chore: release v0.10.1

errors/errors.go, services/blueprint.go, services/pipeline.go, services/task.go
=> fix: /pipelines/:id return 200 for non-existing id

README.md
=> docs: update link of pipeline-advanced-mode

.env.example, .github/workflows/test-e2e.yml, e2e/database.go, k8s-deploy.yaml, runner/db.go
=> feat: devlake support db url format on mysql

plugins/dbt/tasks/convertor.go
relate to #1544 
mysql final return result:
postgres final return result:
=> feat: dbt plugin support postgres

go.mod, plugins/jira/tasks/issue_convertor.go, plugins/jira/tasks/issue_convertor_test.go
The issues.url was an API endpoint, which returns a JSON response. This PR will point the URL to a webpage
close #1751 
=> fix: fix issue URL

plugins/jira/api/connection.go
=> fix: jira test connection api

README.md, config/config.go, k8s-deploy.yaml
=> docs: update k8s deployment

plugins/tapd/models/bug_changelog.go, plugins/tapd/models/iteration.go, plugins/tapd/models/migrationscripts/archived/bug_changelog.go, plugins/tapd/models/migrationscripts/archived/iteration.go, plugins/tapd/models/migrationscripts/archived/story_changelog.go, plugins/tapd/models/migrationscripts/archived/task_changelog.go, plugins/tapd/models/migrationscripts/archived/worklog.go, plugins/tapd/models/migrationscripts/archived/workspace.go, plugins/tapd/models/story_changelog.go, plugins/tapd/models/task_changelog.go, plugins/tapd/models/worklog.go, plugins/tapd/models/workspace.go, plugins/tapd/tasks/bug_changelog_converter.go, plugins/tapd/tasks/story_changelog_converter.go, plugins/tapd/tasks/task_changelog_converter.go
removed all UNSIGNED in gorm tag as pg doesnt support
close #1790
=> fix(tapd): remove UNSIGNED in gorm tag

docker-compose-temporal.yml, docker-compose.yml, grafana/Dockerfile, k8s-deploy.yaml
=> feat: embed piechart into grafana image

models/migrationscripts/register.go, models/migrationscripts/updateSchemas20220505.go, models/pipeline.go, runner/run_pipeline.go
Rename pipeline.step to stage
1. Added a script updateSchema20220505.go to rename column
2. Add the script to register.go
close #1779
=> refactor(framework): rename pipeline.step to stage

plugins/jira/tasks/changelog_convertor.go, plugins/jira/tasks/sprint_issues_convertor.go
=> fix: #1788

plugins/helper/batch_save.go
fix #1799 
handle empty primary key correctly
close #1799 
=> fix: handle empty primary key correctly

README-zh-CN.md, README.md
Signed-off-by: Daniel Hu <tao.hu@merico.dev>
update the cross-language button in readme file
=> chore: update the cross-language button in readme file

plugins/github/api/connection.go
add 1 to `token` index, so that it will show more understandable index in log
closes #1800
=> feat(github): change invalid `token` index

models/domainlayer/ticket/issue.go, models/migrationscripts/register.go, models/migrationscripts/updateSchemas20220507.go, plugins/jira/jira.go, plugins/jira/models/issue.go, plugins/jira/models/migrationscripts/updateSchemas20220507.go, plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/issue_convertor.go
=> feat: add icon_url for table issues

README-zh-CN.md, README.md
=> doc: update demo link

models/domainlayer/code/note.go, models/migrationscripts/register.go, models/migrationscripts/updateSchemas20220510.go, plugins/gitlab/gitlab.go, plugins/gitlab/models/migrationscripts/updateSchemas20220510.go, plugins/gitlab/models/mr_note.go, plugins/gitlab/tasks/mr_enricher.go, plugins/gitlab/tasks/mr_note_extractor.go, plugins/gitlab/tasks/note_convertor.go
change field `system` to `is_system` to avoid key word of mysql
change `0` to `false` to support pg
closes #1835
=> fix(gitlab): sql not supported by pg

plugins/helper/iterator.go
=> fix(feishu): DateInterator Para Error

grafana/dashboards/Jira.json
update the jira dashboard
#1856
=> fix: update jira dashboard

plugins/helper/batch_save.go, plugins/helper/batch_save_test.go, plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/issue_convertor.go, plugins/jira/tasks/issue_extractor.go, plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
fix 
#1854  Jira issue's epic link and story points are not correctly transformed
#1841 Postgres Support: back quotes caused error
#1855 Jira issue's original_status is empty
close #1854 
close #1841 
close #1855
=> fix: #1854 #1841 #1855

CONTRIBUTING-zh-CN.md, README-zh-CN.md, README.md, plugins/README-zh-CN.md, plugins/README.md
Update some syntax errors and add some important contents for build process into documents.
#1848 
(I'm new here, so I don't have an idea about how to track my Issue-PR process to ensure this completion...
=> PR: docs about #1848

.github/workflows/golangci-lint.yml
increase the logging detail in golangci-lint action
=> fix(lint): increase the logging detail in golangci-lint action

.asf.yaml
Signed-off-by: KeHaoKH <hao.ke@merico.dev>
asf.yaml to conform to apache specifications
=> chore: asf.yaml to conform to apache specifications

.github/pull_request_template.md
=> feat: update mr template

.github/workflows/test-e2e.yml
modify test-e2e.yml to make sure to run `apk add --no-cache tar` before checkout the code
closes https://github.com/apache/incubator-devlake/issues/1941
=> chore(github workflow): add cache to improve github action

plugins/jira/tasks/sprint_issues_convertor.go
=> fix: wrong calculated is_removed value in sprint_issues table

plugins/jira/jira.go, plugins/jira/models/migrationscripts/update_schemas20220518.go, plugins/jira/tasks/changelog_collector.go, plugins/jira/tasks/sprint_issues_convertor.go, plugins/jira/tasks/worklog_collector.go, plugins/jira/tasks/worklog_extractor.go
fix #1904 [jira] incremental data updating not works
Simplify the filter condition for finding issues which ought to collect changelogs and worklogs .
⚠️ for a big project, the first collection may take a long time.
close #1904
=> fix: improve jira changelog and worklog collecting

runner/directrun.go
=> chore: add comment for DirectRun function

README.md
Update Slack Link
Closes #1953 
=> Docs: Update Slack Link

README.md
It fixes issue-1962
No need, check the typo diff below
=> typo in README.md (must be Kubernetes)

CONTRIBUTING.md
It fixes issue-1964
No need, can be seen from the text diff below
=> overly long lines in CONTRIBUTING.md have been fixed

plugins/helper/data_convertor_test.go, plugins/jira/api/connection.go
Add TestApiConvertorExecute
Add TestApiConvertorExecute_Cancel for unit test
close #1947 
=> Unit test for data_convertor 

config-ui/src/hooks/useSettingsManager.jsx
```diff
- endPoing
+ endpoint
```
Closes Ticket ID #1930
=> Update useSettingsManager.jsx - (spelling fix)

.github/pull_request_template.md
=> [bug] update contributing link

go.sum, plugins/helper/config_util.go, plugins/helper/config_util_test.go
=> feat: support more viper data type

Makefile, plugins/helper/api_async_client.go, plugins/helper/api_async_client_test.go, plugins/helper/api_collector.go, plugins/helper/api_collector_test.go, plugins/helper/worker_scheduler.go
Unit test for Total Execute of api_collect.
rebase from #1985 and fix handleResponseWithPages block
close #1984 
close #1985 
close #2001 
=> Unit test for Total Execute of api_collect.

plugins/tapd/models/bug_custom_field.go, plugins/tapd/models/migrationscripts/archived/bug_custom_field.go, plugins/tapd/models/migrationscripts/archived/story_custom_field.go, plugins/tapd/models/migrationscripts/archived/task_custom_field.go, plugins/tapd/models/migrationscripts/archived/workspace.go, plugins/tapd/models/migrationscripts/init_schema.go, plugins/tapd/models/story_custom_field.go, plugins/tapd/models/task_custom_field.go, plugins/tapd/models/workspace.go, plugins/tapd/tapd.go, plugins/tapd/tasks/company_collector.go, plugins/tapd/tasks/company_extractor.go, plugins/tapd/tasks/story_custom_fields_collector.go, plugins/tapd/tasks/story_custom_fields_extractor.go
modify tapd workspace entity
add subtasks to collect all workspaces of a company
add subtasks to collect story custom fields
relate to #2007 
=> feat(tapd): add new entities

plugins/refdiff/README.md
=> Add Missing `cd libgit2`

runner/directrun.go
We changed the way to use golang builtin method:
```go
sigc := make(chan os.Signal, 1)
signal.Notify(sigc, syscall.SIGTSTP)
go func() {
<-sigc
cancel()
}()
```
press Ctr+z to stop the process
closes #1973
=> fix(runner): swallow the error form exec.Command.Run

plugins/jenkins/tasks/job_collector.go
add tree value  like build collector in Query to define how many jobs we want every time
closes #2036
=> fix(jenkins): job collector pager

plugins/github/tasks/pr_commit_collector.go, plugins/github/tasks/pr_review_collector.go, plugins/gitlab/tasks/shared.go, plugins/jenkins/tasks/build_collector.go, plugins/tapd/tasks/bug_commit_collector.go, plugins/tapd/tasks/story_commit_collector.go, plugins/tapd/tasks/task_commit_collector.go
fix #1992 : data is missing for pingcap collectApiPullRequestCommits subtask
fix #2043: Refactor: ApiCollector.Input should only retrieve necessary columns
=> fix: unexpected EOF and busy buffer

plugins/jira/tasks/apiv2models/changelog.go
fix #2059 : jira apiv2model json value is error
=> fix: jira apiv2models json value

deployment/helm/.helmignore, deployment/helm/Chart.yaml, deployment/helm/README.md, deployment/helm/templates/NOTES.txt, deployment/helm/templates/_helpers.tpl, deployment/helm/templates/configmaps.yaml, deployment/helm/templates/deployments.yaml, deployment/helm/templates/services.yaml, deployment/helm/templates/statefulsets.yaml, deployment/helm/values.yaml
issue: #1991
Signed-off-by: Ji Bin <matrixji@live.com>
Partly #1991 
=> feat: support helm deployment

.github/pull_request_template.md
=> Added PR template link

logger/init.go, logger/log.go, logger/logger.go, plugins/gitextractor/main.go, plugins/gitextractor/store/database.go, plugins/gitextractor/tasks/git_repo_collector.go, plugins/helper/api_async_client_test.go, plugins/helper/api_client.go, plugins/helper/api_collector_test.go, plugins/helper/api_extractor.go, plugins/helper/api_extractor_test.go, plugins/helper/batch_save.go, plugins/helper/batch_save_divider.go, plugins/helper/batch_save_divider_test.go, plugins/helper/batch_save_test.go, plugins/helper/data_convertor.go, plugins/helper/data_convertor_test.go, plugins/helper/default_task_context.go, plugins/helper/default_task_logger.go, runner/db.go
1. add some log for extract and collect and delete some redundant log
2. ignore case of log_level
3. move all logger related code from plugins.helper to logger (because of circular reference between plugin.helper and logger.Global)
#2038 
```
[2022-05-30 22:57:25]  INFO  [feishu] start plugin
[2022-05-30 22:57:25]  INFO  [feishu] scheduler for api https://open.feishu.cn/open-apis/vc/v1 worker: 25, request: 18000, duration: 1h0m0s
[2022-05-30 22:57:25]  INFO  [feishu] total step: 1
[2022-05-30 22:57:25]  INFO  [feishu] executing subtask extractMeetingTopUserItem
[2022-05-30 22:57:25]  INFO  [feishu] [extractMeetingTopUserItem] get data from _raw_feishu_meeting_top_user_item where params={"apiResName":"top_user_report"} and got 7282
[2022-05-30 22:57:25]  INFO  [feishu] …
```
=>  Issues/2038

config/config.go, config/config_test.go
- WriteConfig write to $ENV_PATH while ENV_PATH is configured
- Create the env file is not exist, instead of raise error
fixes: #2081
Signed-off-by: Ji Bin <matrixji@live.com>
Closes #2081 
N/A
N/A
=> fix: Configuration handling while ENV_PATH is used

.env.example
close [#2107](https://github.com/apache/incubator-devlake/issues/2107)
Manually verified the change by testing locally.
=> [improve][env]Delete the github auth default character *

api/api.go, config/config.go, config/config_test.go
optimize configuration initialization function  and add endpoint debug log
close [#2055](https://github.com/apache/incubator-devlake/issues/2055)
Manually verified the change by testing locally.
=> [fix#2055][config] optimize configuration initialization function  and add endpoint debug log

Dockerfile, config-ui/Dockerfile, grafana/Dockerfile
Add the ASF header and incubator disclaimer to Dockerfiles
#2123
=> fix: add ASF header to Dockerfiles

generator/template/plugin/plugin_main.go-template, plugins/icla/plugin_main.go
Fix arguments of `DirectRun`. It's imported from rebasing by main not enough
close #2127
=> fix for arguement number

plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/issue_extractor.go
Using jira's `timespent` as issues.spent_minutes
fixes #2136
=> fix: issues.spent_minutes

plugins/tapd/tasks/bug_collector.go, plugins/tapd/tasks/company_extractor.go, plugins/tapd/tasks/story_collector.go, plugins/tapd/tasks/task_collector.go
cherry pick #2142 to release-v0.11
=> fix(tapd): cherry pick #2142 to release-v0.11

plugins/tapd/tasks/bug_collector.go, plugins/tapd/tasks/company_extractor.go, plugins/tapd/tasks/story_collector.go, plugins/tapd/tasks/task_collector.go
change `query.Set("fields", "label")` to `query.Set("fields", "labels")` for bug/story/task collectors
change `ExtractCompanyMeta.EnabledByDefault` to `ExtractCompanyMeta.Required`
closes #2141
=> fix(tapd): change api query

plugins/jira/models/migrationscripts/updateSchemas20220601.go
`plugins/jira/models/migrationscripts/updateSchemas20220601.go` should encrypt the password field
Fixes #2159
=> fix: jira basic auth migration should encrypt password

plugins/helper/api_async_client.go
add api async client debug log
Manually verified the change by testing locally.
=> [Improvement][ApiAsyncClient] add api async client debug log

.github/workflows/deploy-test.yml
Run helm install test while helm deployment changes
Closes: #2132 
N/A
N/A
=> refactor(ci): Add pipeline for helm deployment

.github/workflows/build.yml, releases/lake-v0.11.0/docker-compose.yml, releases/lake-v0.11.0/env.example
add two files
- releases/lake-v0.11.0/docker-compose.yml
- releases/lake-v0.11.0/env.example
fix `build.yml`, push docker images accordingly
close #2162 
=> fix: docker release

impl/dalgorm/dalgorm.go, plugins/core/dal/dal.go, plugins/jira/tasks/changelog_collector.go, plugins/jira/tasks/worklog_collector.go, plugins/refdiff/tasks/ref_commit_diff_calculator.go, plugins/refdiff/tasks/ref_issue_diff_calculator.go, plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
Change gorm.db to dal on refdiff.
Change dal interface to Clause
Add Raw
Add Pluck
Add CreateIfNotExist
Add Model to From
#2149 
=> refactor: refdiff db to dal

plugins/tapd/models/migrationscripts/archived/story_bug.go, plugins/tapd/models/migrationscripts/update_schemas20220531.go, plugins/tapd/models/migrationscripts/update_schemas20220613.go, plugins/tapd/models/story_bug.go, plugins/tapd/tapd.go, plugins/tapd/tasks/bug_changelog_collector.go, plugins/tapd/tasks/bug_collector.go, plugins/tapd/tasks/shared.go, plugins/tapd/tasks/story_bug_collector.go, plugins/tapd/tasks/story_bug_extractor.go, plugins/tapd/tasks/story_changelog_collector.go, plugins/tapd/tasks/story_collector.go, plugins/tapd/tasks/task_collector.go, plugins/tapd/tasks/worklog_collector.go
Added two subtasks:
tasks.CollectStoryBugMeta,
tasks.ExtractStoryBugsMeta,
closes #2175 
=> feat(tapd): add story_bug relation

deployment/helm/Chart.yaml
Provide more detailed description information for helm chart.yaml
=> [Improvemnet][helm] Provide more detailed description information for helm chart.yaml 

releases/lake-v0.11.0/docker-compose.yml
fix #2178 
remove the build section in `releases/lake-v0.11.0/docker-compose.yml`
close #2178
=> refactor: remove build section in `releases/lake-v0.11.0/docker-compose.yml`

models/domainlayer/ticket/changelog.go, models/migrationscripts/register.go, models/migrationscripts/updateSchemas2022061402.go, plugins/jira/jira.go, plugins/jira/models/connection.go, plugins/jira/models/migrationscripts/updateSchemas20220614.go, plugins/jira/models/status.go, plugins/jira/tasks/apiv2models/status.go, plugins/jira/tasks/changelog_convertor.go, plugins/jira/tasks/issue_collector.go, plugins/jira/tasks/issue_convertor.go, plugins/jira/tasks/issue_extractor.go, plugins/jira/tasks/remotelink_collector.go, plugins/jira/tasks/shared.go, plugins/jira/tasks/status_collector.go, plugins/jira/tasks/status_extractor.go, plugins/tapd/tasks/bug_changelog_converter.go, plugins/tapd/tasks/story_changelog_converter.go, plugins/tapd/tasks/task_changelog_converter.go
=> feat: collect jira status

impl/dalgorm/dalgorm.go, plugins/gitlab/gitlab.go, plugins/gitlab/models/migrationscripts/init_schema.go, plugins/gitlab/tasks/commit_convertor.go, plugins/gitlab/tasks/issue_collector.go, plugins/gitlab/tasks/issue_convertor.go, plugins/gitlab/tasks/issue_label_convertor.go, plugins/gitlab/tasks/mr_comment_convertor.go, plugins/gitlab/tasks/mr_commit_convertor.go, plugins/gitlab/tasks/mr_convertor.go, plugins/gitlab/tasks/mr_enricher.go, plugins/gitlab/tasks/note_convertor.go, plugins/gitlab/tasks/project_convertor.go, plugins/gitlab/tasks/shared.go
Modify all sub tasks to change db to dal
closes #2164 
=> Ref gitlab db to dal

models/migrationscripts/updateSchemas2022061402.go
fix migration table name error
=> fix: migration table name error

models/migrationscripts/register.go, models/migrationscripts/updateSchemas2022061402.go, plugins/jira/jira.go, plugins/jira/models/connection.go, plugins/jira/models/migrationscripts/updateSchemas20220614.go, plugins/jira/models/status.go, plugins/jira/tasks/apiv2models/status.go, plugins/jira/tasks/changelog_convertor.go, plugins/jira/tasks/issue_collector.go, plugins/jira/tasks/issue_convertor.go, plugins/jira/tasks/issue_extractor.go, plugins/jira/tasks/shared.go, plugins/jira/tasks/status_collector.go, plugins/jira/tasks/status_extractor.go, plugins/tapd/tasks/bug_changelog_converter.go, plugins/tapd/tasks/story_changelog_converter.go, plugins/tapd/tasks/task_changelog_converter.go
Cherry pick #2182 to release-v0.11
No
=> feat: collect jira status (#2182)

plugins/jira/tasks/issue_collector.go
add board_id filter when calculating `since` to collect jira issues
closes #2209 
=> Fix jira collector filter

plugins/jira/jira.go, plugins/jira/models/issue_label.go, plugins/jira/models/migrationscripts/updateSchemas20220616.go, plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/issue_extractor.go
Signed-off-by: moon.li <moon.li@paytm.com>
Add issue labels for jira
closes #2218
=> add jira issue label

plugins/jira/jira.go, plugins/jira/models/issue_label.go, plugins/jira/models/migrationscripts/updateSchemas20220616.go, plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/issue_extractor.go
Cherrypick #2221 #2225 to v0.11.0-hotfix
=> Cherrypick #2221 #2225

plugins/gitlab/impl/impl.go, plugins/gitlab/tasks/api_client.go, plugins/gitlab/tasks/pipeline_collector.go, plugins/helper/api_collector.go
Change modification of concurrency to `api_collector.go`
Modify gitlab `NewApiClient`
=> fix(gitlab): modify concurrency and NewApiCLient

plugins/gitlab/models/migrationscripts/init_schema.go, plugins/jenkins/models/migrationscripts/init_schema.go, plugins/starrocks/tasks.go
Improve the connection logic for gitlab and jenkins.
related to #636,  #1978
=> feat: multi-data connections support for Jenkins and Gitlab

docker-compose.yml, plugins/github/models/migrationscripts/init_schema_20220611.go
fix apple m1 build fail on mysql 
Does this close any open issues?
related to #1775
=> fix:  docker-compose platform

main.go, plugins/ae/ae.go, plugins/ae/api/connection.go, plugins/ae/models/connection.go, plugins/ae/models/migrationscripts/archived/connection.go, plugins/ae/models/migrationscripts/updateSchemas20220615.go, plugins/ae/tasks/api_client.go, plugins/ae/tasks/task_data.go, plugins/core/plugin_utils.go, plugins/helper/connection.go, services/init.go, test/api/task/task_test.go
Add multi-data support for AE
Mv randomstr to core
Add TestConnection for AE
close #1981 
close #2256 
=> feat: multi-data connections support for ae

deployment/helm/templates/ingresses.yaml
Fix helm chart fix for incorrect rendering with Kubernetes <=1.19
Close #2265 
N/A
N/A
=> fix: helm chart fix for incorrect rendering

plugins/jira/jira.go, plugins/jira/models/issue.go, plugins/jira/models/migrationscripts/updateSchemas20220620.go, plugins/jira/models/remotelink.go, plugins/jira/models/worklog.go, plugins/jira/tasks/apiv2models/changelog.go, plugins/jira/tasks/apiv2models/issue.go, plugins/jira/tasks/apiv2models/worklog.go, plugins/jira/tasks/changelog_convertor.go, plugins/jira/tasks/changelog_extractor.go, plugins/jira/tasks/issue_extractor.go, plugins/jira/tasks/remotelink_collector.go, plugins/jira/tasks/remotelink_extractor.go, plugins/jira/tasks/shared.go, plugins/jira/tasks/worklog_collector.go, plugins/jira/tasks/worklog_extractor.go
=> Refactor collector of worklogs and remotelinks

plugins/github/api/connection.go, plugins/github/models/connection.go
1. fix github cannot be test
close #2276
=> fix github cannot be test

plugins/tapd/e2e/snapshot_tables/_tool_tapd_workspaces_ws_test.csv, plugins/tapd/e2e/workspace_test.go, plugins/tapd/models/story.go, plugins/tapd/tasks/company_extractor.go, plugins/tapd/tasks/workspace_extractor.go
=> refactor(tapd): add cadd e2e -- workspace

.github/workflows/build.yml
CI reported failed for non-semver tags which actually succeeded
=> CI reported failed for non-semver tags which actually succeeded

plugins/github/api/blueprint.go
=> fix: github transformationRules should be placed under a field

plugins/github/api/blueprint.go
=> feat: github blueprint normal mode support refdiff

plugins/gitlab/api/blueprint.go
=> refactor(gitlab): modify blueprint

.github/workflows/build.yml
Modify GitHub action secret name:
`DOCKERHUB_USERNAME`  -> `DOCKER_REGISTRY_USERNAME` 
`DOCKERHUB_TOKEN`  ->  `DOCKER_REGISTRY_PASSWORD`
=> chore: modify secret name

config-ui/Dockerfile, config-ui/nginx.conf, deployment/helm/templates/deployments.yaml, deployment/helm/templates/services.yaml, docker-compose.yml, k8s-deploy.yaml
changed bind port to 4000 from 80 for no root permission.
changed export port 80,443 to 4000,4443
#2372 
=> Fix permission denied of nginx

plugins/gitlab/tasks/mr_label_convertor.go, plugins/helper/api_collector.go, runner/run_task.go
Change the counting method of steps
fix #2368 
=> fix: steps total nums is wrong

plugins/ae/api/connection.go, plugins/ae/api/init.go, plugins/ae/tasks/commits_collector.go
=> fix: ae miss connection id

LICENSE
Add license for 3 files:
- config-ui/src/images/help.svg 
- config-ui/src/images/integrations/github.svg
- config-ui/src/images/integrations/gitlab.svg
=> doc: add license

plugins/gitlab/tasks/project_convertor.go, plugins/gitlab/tasks/project_extractor.go
project_convertor  add domain board entity for gitlab plugin
fix #2381 
=> fix: gitlab is missing the board entity

config-ui/src/utils/config.js
redirect to grafana at the same host in config-ui
close #2109
=> fix: redirect to grafana at the same host in config-ui

plugins/helper/api_client.go, plugins/jira/tasks/api_client.go, plugins/jira/tasks/sprint_collector.go
ignore the error of jira without sprint.
#2317 
=> fix: jira ignore no sprint

generator/cmd/create_collector.go, generator/cmd/create_migration.go, generator/cmd/create_plugin.go, generator/cmd/e2e_raw_create.go, generator/template/plugin/tasks/api_collector.go-template
1. fix some typo in the generator
2. ask http_path in create_collector
=> fix: fix some typo and ask http_path in create_collector

plugins/jira/tasks/issue_convertor.go
cherry pick #2392 
closes #2386
=> fix(jira): change filter for jira_issues

impl/dalgorm/dalgorm.go, plugins/core/dal/dal.go, plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go, plugins/starrocks/tasks.go
=> refactor(dal): rename Raw to RawCursor / cleanup comments

plugins/jira/api/connection.go, plugins/jira/models/response_type.go
Add userSearch to check weather the username all right at connction test.
close #2400
close #2033 
=> fix: jira test connection test not work with username

README.md
Now with more and more projects using emojis, and other graphical means to make the readme look more attractive, and beautiful, I have added emojis to the headers..
=> docs: emojis for readme

runner/directrun.go
remove ctrl+z to cancel
add c and enter to cancel.
close #2040 
=> direct run use c and enter to cancel

.github/workflows/stale.yml
=> ci: add stale bot

.github/workflows/test.yml, README.md
try to fix ci badge by running ci every night
close #2377
=> feat: try to fix ci brage by run ci every night

plugins/github/tasks/issue_extractor.go
=> [fix-2443][github]: remove duplicate logic in issue_extractor

plugins/github/tasks/comment_extractor.go, plugins/jira/models/migrationscripts/init_schema.go
fix github record not found 
fix jira connection failed
close #2462 
close #2464 
=> fix: github record not found and jira connection failed

plugins/github/tasks/comment_extractor.go, plugins/gitlab/tasks/account_convertor.go, plugins/gitlab/tasks/account_extractor.go
fix: account data error in tool laye error
close #2465 
=> fix: account data error in tool laye error

.asf.yaml
update the description and add some labels on the GitHub topic
=> feat: update the description and add some labels on the GitHub topic

api/blueprints/blueprints.go, api/router.go, models/blueprint.go, plugins/helper/pipeline_plan.go, plugins/helper/pipeline_plan_test.go, services/blueprint.go
Check #2468 for detail
Closes #2468
=> feat: trigger blueprint manually

README.md
Updated two wrong links in main readme.
https://github.com/apache/incubator-devlake/issues/2242
=> fix: updated wrong links in main readme

plugins/starrocks/utils.go
=> fix: wrong data type when load data from postgres 

plugins/helper/data_convertor.go
add annotations in data convertor
close #1924
=> docs: add annotations in data_convertor

models/migrationscripts/220622-blueprint-normal-mode.go, models/migrationscripts/archived/notification.go, models/migrationscripts/archived/task.go, models/migrationscripts/init_pre_schema.go, models/migrationscripts/init_schema.go, models/migrationscripts/register.go, models/migrationscripts/updateSchemas20220505.go, models/migrationscripts/updateSchemas20220601.go, models/migrationscripts/updateSchemas20220616.go
Reserved some table such as tasks.
related to #2439 
=> fix: update devlake frame migration

plugins/github/api/connection.go
closes #2497
For github test connection, as described in #2497 , we add `success` and `message` into the body if it succeeds.
closes #2497
=> feat(github): return relevent status inside body when return login

plugins/github/tasks/pr_review_collector.go, plugins/github/tasks/pr_review_convertor.go, plugins/github/tasks/pr_review_extractor.go
set add `core.DOMAIN_TYPE_CODE_REVIEW` to DomainTypes for GitHub
=> fix: fix pr review DomainTypes

config-ui/src/pages/configure/settings/jira.jsx
use `onSettingsChange` right to change epic, story or commit_sha
close #2515
=> fix: fix that epic clear other configs wrong

config-ui/src/components/blueprints/WorkflowActions.jsx, config-ui/src/components/pipelines/StageTaskCaption.jsx
fix for the linter of frontend
=> ci: fix for the linter of frontend

plugins/jira/tasks/issue_extractor.go, plugins/jira/tasks/task_data.go
Adapting the back-end structure to the front-end data format
POST http://127.0.0.1:8080/blueprints
request:
```json
{
"name": "test blueprint normal",
"mode": "NORMAL",
"settings": {
"version": "1.0.0",
"connections": [
{
"plugin": "jira",
"connectionId": 1,
"scope": [
{
"options": {
"boardId": 8,
"connectionId": 1
},
"transformation": {
"epicKeyField": "customfield_10014",
"storyPointField": "customfield_10024",
"remotelinkCommitShaPattern": ".*/commit/(.*)",
"typeMappings": {
"Bug": {
"standardType": "Bug"
},
"Task": {
"standardType": "Requirement"
},
"任务": {
"standardType": "Requirement"
},
"Incident": {
"standardType": "Incident"
}
}
},
"entities": [
"CODE",
"TICKET",
"CICD",
"CROSS",
"CODEREVIEW"
]
}
]
}
]
},
"isManual": true
}
```
response:
```json
{
"name": "test blueprint normal", …
```
=> fix: fix the schema of transformationRules

README.md
update links to the 'docker compose setup' page.
No.
=> docs: update links to docker compose setup page

plugins/helper/api_collector.go, plugins/helper/api_extractor.go
Add IncProgress to results range for ApiExtractor
Add IncProgress to ApiCollector when items was zero.
#2543
=> fix: add inc for lost

grafana/dashboards/GithubBasicMetrics.json
fix grafana GithubBasicMetrics issue_key
=> fix: grafana GithubBasicMetrics issue_key

generator/cmd/create_migration.go, generator/cmd/init_migration.go, generator/template/migrationscripts/add_init_tables.go-template, generator/template/migrationscripts/migration.go-template, generator/template/migrationscripts/migration_with_config.go-template, generator/template/migrationscripts/register.go-template, generator/util/template.go
1. generator init_migration adapt new migration rules.
2. generator create_migration adapt new migration rules.
fix: #2540 
=> fix: generator adapt new migration

plugins/starrocks/tasks.go
=> fix: loadData columns type

plugins/gitextractor/gitextractor.go, plugins/gitextractor/main.go, plugins/gitextractor/parser/repo.go, plugins/gitextractor/parser/repo_creator.go, plugins/gitextractor/tasks/git_repo_collector.go
fix #2513 ([Bug][gitextractor] gitextractor can't finish my task in standalone mode)
close #2513
=> fix: running gitextractor as a standalone process

plugins/gitlab/tasks/issue_extractor.go
Check if it setting the type or issue type before value checking.
close #2555 
=> fix: fix if gitlab api response with no type or issuetype

plugins/gitlab/e2e/snapshot_tables/accounts.csv, plugins/gitlab/tasks/account_convertor.go
fix: accounts miss full_name from gitlab plugin
fix #2568 
=> fix: accounts miss full_name from gitlab plugin

plugins/feishu/api/connection.go, plugins/feishu/impl/impl.go
fix feishu api lost
close #2573 
=> fix: feishu api

README.md
1. move 'how to use DevLake' to the later part of the document
2. update the 'how to contribute' part to make it more actionable
3. fix dead links 
Closes #2564 
=> docs: update the structure and contribution part of the main README

grafana/dashboards/EngineeringOverview.json, grafana/dashboards/EngineeringThroughputAndCycleTime.json, grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json, grafana/dashboards/GitHub.json, grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json, grafana/dashboards/Gitlab.json, grafana/dashboards/Jenkins.json, grafana/dashboards/Jira.json, grafana/dashboards/WeeklyBugRetro.json, grafana/dashboards/WeeklyCommunityRetro.json
1. add a description for all dashboards so that when dashboard shows 'no data', users will understand that it's because the required data is not collected or the required transformation is not configured.
2. bug-fixes for several dashboards.
No
=> feat: add description for all dashboards

docker-compose-temporal.yml, docker-compose.yml, k8s-deploy.yaml
This PR updates the image names listed below in three files:
1. config-ui -> devlake-config-ui
2. lake -> devlake
3. grafana -> devlake-dashboard
Files:
1. k8s-deploy.yaml
2. docker-compose.yaml
3. docker-compose-temporal.yaml
=> chore: update image names

scripts/pm/framework/proceed-db-migration.sh, scripts/pm/github/user.sh, scripts/pm/jira/plugin/connection-create.sh
added api request script to help debugging/development
1. github user API request
2. create jira connection
3. fix script for /proceed-db-migration
No
=> chore: api request script for github/jira

.env.example, releases/lake-v0.12.0/docker-compose.yml, releases/lake-v0.12.0/env.example
add docker-compose.yml file for the release v0.12.0
=> feat: add docker-compose.yml file for v0.12.0

plugins/helper/api_async_client.go, scripts/pm/framework/pipeline-create.sh, scripts/pm/framework/pipeline-get-detail.sh, scripts/pm/framework/pipeline-get-tasks.sh, scripts/pm/framework/proceed-db-migration.sh, scripts/pm/github/trigger-pipline.sh, scripts/pm/github/user.sh, scripts/pm/jira/board-issues.sh, scripts/pm/jira/plugin/connection-create.sh
=> fix: api_async_client retry logic would cause rate-limit-exceeding

models/domainlayer/crossdomain/project_mapping.go, models/migrationscripts/20220725_add_project_mapping_table.go, models/migrationscripts/archived/project_mapping.go, plugins/org/api/project_mapping.go, plugins/org/api/store.go, plugins/org/api/team.go, plugins/org/api/types.go, plugins/org/api/user.go, plugins/org/api/user_account_mapping.go, plugins/org/impl/impl.go
implement  #2503 ([Feature][org plugin] Add project mapping feature to org plugin)
⚠️NOTE 
I use  `table` instead of `table_name`  as the 2nd column name for technical reasons.
close #2503 
=> feat: project_mapping for org plugin

plugins/helper/list.go, plugins/helper/queue.go, plugins/helper/queue_test.go, plugins/jenkins/models/job.go, plugins/jenkins/models/job_test.go
=> [issue-2632] Casting error in FolderInput node struct

.github/workflows/deploy-test.yml, deployment/helm/README.md, deployment/helm/templates/_helpers.tpl, deployment/helm/templates/configmaps.yaml, deployment/helm/templates/deployments.yaml, deployment/helm/templates/ingresses.yaml, deployment/helm/templates/services.yaml, deployment/helm/values.yaml
Align with https://github.com/apache/incubator-devlake/pull/2610
N/A
N/A
=> refactor: align helm chart with docker-compose

config-ui/package-lock.json, config-ui/package.json, config-ui/src/components/blueprints/BlueprintsGrid.jsx, config-ui/src/components/blueprints/DataEntitiesSelector.jsx, config-ui/src/components/blueprints/create-workflow/DataScopes.jsx, config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx, config-ui/src/components/pipelines/StageTaskName.jsx, config-ui/src/data/NullBlueprint.js, config-ui/src/data/Task.js, config-ui/src/data/TestBlueprintDetail.js, config-ui/src/hooks/useBlueprintValidation.jsx, config-ui/src/hooks/usePipelineManager.jsx, config-ui/src/pages/blueprints/blueprint-detail.jsx, config-ui/src/pages/blueprints/create-blueprint.jsx, config-ui/src/pages/blueprints/index.jsx, config-ui/src/pages/configure/settings/github.jsx
- Add `Repository`, `Project ID`, & `Board ID` Context to Stage Task Name
This PR applies additional hotfixes and enhancements to the Blueprints `v0.12.0` Release.
#2621
`[<PENDING>]`
=> `fix` config-ui: blueprints service pack 2.0

models/domainlayer/devops/cicd_pipeline.go, models/domainlayer/devops/cicd_task.go, models/migrationscripts/20220803_add_cicd.go, models/migrationscripts/register.go
add:
cicd_pipeline.go and migration scripts
cicd_task.go and migration scripts
closes #2666
=> feat(domain layer): add cicd entities

models/domainlayer/devops/cicd_pipeline.go, plugins/jenkins/impl/impl.go, plugins/jenkins/models/build.go, plugins/jenkins/models/build_repo.go, plugins/jenkins/models/migrationscripts/20220729_modify_all_entities.go, plugins/jenkins/models/pipeline.go, plugins/jenkins/models/task.go, plugins/jenkins/tasks/build_convertor_cicd.go, plugins/jenkins/tasks/build_enricher.go
convert builds to pipelines and tasks
relates to #2637 
=> feat(jenkins): add jenkins pipeline convertor

docker-compose.yml, plugins/jenkins/impl/impl.go, plugins/jenkins/models/migrationscripts/20220714_add_init_tables.go, plugins/jenkins/tasks/build_cicd_convertor.go, plugins/jenkins/tasks/build_enricher.go, plugins/jenkins/tasks/stage_collector.go, plugins/jenkins/tasks/stage_convertor.go
jenkins stages convertor
Relates to #2637 
=> Feat stages convertor

models/migrationscripts/20220622_rename_tasks_to_plan.go
add devlake_blueprints settings
releated to #2684
=> fix: devlake_blueprints settings does exist

plugins/jenkins/api/connection.go
add swagger for jenkins
closes #2699
=> feat(jenkins): add swagger

plugins/github/api/connection.go
add github connection swagger
close #2697 
=> feat: add github connection swaggger

config-ui/src/pages/blueprints/index.jsx
Changes are highlighted like **`this`**
- Before: A blueprint is **`the`** plan that covers all the work, such as selecting and transforming the data you wish to collect, to get your raw data ready for query and metric **`computaion`** in the dashboards. Try adding your first blueprint!
- fix: A blueprint is **`a`** plan that covers all the work, such as selecting and transforming the data you wish to collect, to get your raw data ready for query and metric **`computation`** in the dashboards. Try adding your first blueprint!
=> fix: index.jsx typo

api/blueprints/blueprints.go, api/domainlayer/repos.go, api/ping/ping.go, api/pipelines/pipelines.go, api/push/push.go, api/task/task.go, api/version/version.go, plugins/ae/api/connection.go, plugins/github/api/connection.go, plugins/gitlab/api/connection.go, plugins/helper/connection.go, plugins/jenkins/api/connection.go, plugins/jira/api/connection.go, plugins/org/api/project_mapping.go, plugins/tapd/api/connection.go
change rateLimit -> rateLimitPerHour
add response body to for successful response in swagger
add framework prefix for all apis belong to framework in swagger
closes #2709
=> fix(plugins): add response body to status=200 in swagger

plugins/feishu/api/connection.go
Add swagger support for feishu plugin api.
close #2707
=> docs: swagger for feishu

plugins/ae/api/connection.go, plugins/gitee/api/connection.go, plugins/github/api/connection.go
The gitee plugin add swagger.
close #2714 
=> docs: swagger for gitee

plugins/gitee/tasks/task_data.go, plugins/helper/connection.go
Remove useless fields and fix typo (related to #2706)
=> Remove useless fields and fix typo (related to #2706)

plugins/starrocks/tasks.go
=> fix: add quote in starrocks create table sql to prevent keyword conflict

NOTICE
add `(incubating)` to the first line in `NOTICE`
closes #2715
=> docs(project): add `(incubating)`

plugins/github/api/blueprint.go, plugins/gitlab/api/blueprint.go
=> fix: github/gitlab should pass down proxy setting to gitext

plugins/dbt/api/connection.go, plugins/feishu/api/connection.go, plugins/gitextractor/api/connection.go, plugins/refdiff/api/connection.go, plugins/starrocks/api/connection.go
add pipeline plan swagger for :
dbt
feishu
starrocks
gitextractor
refdiff
relates to #2734 #2735
=> feat(plugins): add swagger for special plugins

config-ui/package-lock.json, config-ui/package.json, config-ui/src/components/blueprints/BlueprintsGrid.jsx, config-ui/src/components/blueprints/DataEntitiesSelector.jsx, config-ui/src/components/blueprints/create-workflow/DataScopes.jsx, config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx, config-ui/src/components/pipelines/StageTaskName.jsx, config-ui/src/data/NullBlueprint.js, config-ui/src/data/Task.js, config-ui/src/data/TestBlueprintDetail.js, config-ui/src/hooks/useBlueprintValidation.jsx, config-ui/src/hooks/usePipelineManager.jsx, config-ui/src/pages/blueprints/blueprint-detail.jsx, config-ui/src/pages/blueprints/create-blueprint.jsx, config-ui/src/pages/blueprints/index.jsx, config-ui/src/pages/configure/settings/github.jsx, plugins/starrocks/tasks.go
=> fix: config-ui blueprints service pack 2.0 (#2630)

plugins/starrocks/utils.go
=> fix: starrocks plugin double precision convert

plugins/feishu/tasks/api_client.go, plugins/gitee/tasks/api_client.go, plugins/github/tasks/api_client.go, plugins/gitlab/tasks/api_client.go, plugins/helper/api_async_client.go, plugins/helper/api_client.go, plugins/helper/api_collector.go, plugins/helper/api_collector_test.go, plugins/icla/tasks/api_client.go, plugins/jenkins/tasks/client.go, plugins/jira/tasks/api_client.go
fix afterResponse callback will overwrite by helper
close #2489
=> fix: add getAfterResponse to overwrite by helper

plugins/jira/api/connection.go
fix #2747 [Bug][Jira] An error occurred while adding a connection for Jira plugin
close #2747 
=> fix: fix Jira adding connection bug

grafana/dashboards/CommunityExperience.json, grafana/dashboards/DemoAverageRequirementLeadTimeByAssignee.json, grafana/dashboards/DemoCommitCountByAuthor.json, grafana/dashboards/DemoDetailedBugInfo.json, grafana/dashboards/DemoHowFastDoWeRespondToCustomerRequirements.json, grafana/dashboards/DemoIsThisMonthMoreProductiveThanLast.json, grafana/dashboards/DemoWasOurQualityImprovedOrNot.json, grafana/dashboards/EngineeringOverview.json, grafana/dashboards/EngineeringThroughputAndCycleTime.json, grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json, grafana/dashboards/GitHub.json, grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json, grafana/dashboards/Gitlab.json, grafana/dashboards/Jenkins.json, grafana/dashboards/Jira.json, grafana/dashboards/WeeklyBugRetro.json, grafana/dashboards/WeeklyCommunityRetro.json
Add the link to Grafana guide in all dashboards to help users create their own dashboards.
Closes #2250
=> feat: add the link to Grafana guide in dashboards

.asf.yaml
=> docs: fix the wrong comma

api/plugininfo/plugininifo.go, api/router.go, models/domainlayer/domaininfo/domaininfo.go, plugins/core/hub.go
Add api /plugininfo for get the infomation about domainlayer's tables and plugininfos.
Add GetDomainTablesInfo for get the domain tables info.
=> info api and domain layer info

config-ui/src/data/pipeline-config-samples/starrocks.js, plugins/starrocks/starrocks.go, plugins/starrocks/task_data.go, plugins/starrocks/tasks.go
=> feat: add be_host and fix hash columns

plugins/refdiff/tasks/ref_issue_diff_calculator.go
column pull_request_issues.issue_number update to column pull_request_issues.issue_key
close #2776 
=> fix: issue_number does not exist

plugins/starrocks/tasks.go
=> fix: starrocks import data error

config-ui/src/App.js, config-ui/src/components/ErrorBoundary.jsx, config-ui/src/components/blueprints/DataScopesGrid.jsx, config-ui/src/components/blueprints/create-workflow/AdvancedJSON.jsx, config-ui/src/data/pipeline-config-samples/dbt.js, config-ui/src/data/pipeline-config-samples/default.js, config-ui/src/data/pipeline-config-samples/feishu.js, config-ui/src/data/pipeline-config-samples/gitextractor.js, config-ui/src/data/pipeline-config-samples/github.js, config-ui/src/data/pipeline-config-samples/gitlab.js, config-ui/src/data/pipeline-config-samples/jenkins.js, config-ui/src/data/pipeline-config-samples/jira.js, config-ui/src/data/pipeline-config-samples/refdiff.js, config-ui/src/data/pipeline-config-samples/starrocks.js, config-ui/src/pages/blueprints/blueprint-settings.jsx
=> fix: use camel-case props for adv json samples

plugins/tapd/models/story_bug.go
=> fix(tapd): modify story bug because of new api

plugins/github/tasks/pr_issue_enricher.go
fix some issues can not bind pull_request in pr_issue_enricher
update regex
close #2806 
=> fix: some issues can not bind pull_request in pr_issue_enricher

plugins/gitee/tasks/api_client.go, plugins/gitee/tasks/pr_commit_collector.go
=> fix: to fix issue2786

.github/workflows/build.yml, scripts/pm/github/create-blueprint.sh, scripts/pm/jira/board.sh, scripts/pm/jira/boards.sh
The `latest` tag of 3 images was never updated for formal release i.e. v0.12.0.
Closes #2810
=> Fix latest tag never get updated

plugins/gitee/tasks/pr_commit_collector.go
=> fix: add GetTotalPages in gitee/pr_commit_collector to fix issue2785

.env.example, api/pipelines/pipelines.go, config/config.go, docker-compose.yml, services/pipeline.go
=> [feat-2742]: Handle logging config

api/api.go
Update error message for db-migration-confirmation
Closes #2816
=> chore: refine the db-migration-required msg for production

k8s-deploy.yaml
just change the "mericodev" to "apache" in k8s-deploy.yaml
closes #2811
=> fix: change image tag mericodev to apache

config-ui/src/pages/blueprints/blueprint-detail.jsx
closes https://github.com/apache/incubator-devlake/issues/2830
=> fix: wording for log downloading button

plugins/azure/models/migrationscripts/20220825_add_init_tables.go
fix the lost table AzureRepo.
close #2840 
=> fix: table lost fix

deployment/helm/templates/configmaps.yaml, deployment/helm/values.yaml, deployment/k8s/k8s-deploy.yaml, deployment/temporal/docker-compose-temporal.yml
=> [Doc-2827]: Refactor deployment files to include default loggingDir

services/pipeline.go, utils/io.go
=> [fix-2829]: Compress tar-archived logs with gzip

.github/ISSUE_TEMPLATE/bug-report.yml, releases/lake-v0.13.0/docker-compose.yml, releases/lake-v0.13.0/env.example
Prepare for the release v0.13.0, creating deployment files and updating the bug report template
=> chore: prepare for v0.13.0

.github/workflows/test-e2e.yml, .github/workflows/test.yml, Makefile
fix the following error for our github actions
=> fix: ci swag reporting SIGSEGV

releases/lake-v0.13.0/docker-compose.yml
change MySQL version from 8.0.26 to 8
=> fix: switch mysql version to 8

plugins/bitbucket/tasks/issue_comment_collector.go, plugins/bitbucket/tasks/issue_comment_convertor.go, plugins/bitbucket/tasks/issue_comment_extractor.go, plugins/bitbucket/tasks/pr_collector.go, plugins/bitbucket/tasks/pr_comment_collector.go, plugins/bitbucket/tasks/pr_comment_convertor.go, plugins/bitbucket/tasks/pr_comment_extractor.go, plugins/bitbucket/tasks/pr_convertor.go, plugins/bitbucket/tasks/pr_extractor.go, plugins/bitbucket/tasks/repo_collector.go, plugins/bitbucket/tasks/repo_convertor.go, plugins/bitbucket/tasks/repo_extractor.go
just change some DomainTypes in some SubTaskMeta of plugin bitbucket
closes #2836
=> fix: change some DomainTypes in some SubTaskMeta of plugin bitbucket

plugins/dora/api/data.go, plugins/dora/api/init.go, plugins/dora/dora.go, plugins/dora/impl/impl.go, plugins/dora/models/migrationscripts/20220829_add_init_tables.go, plugins/dora/models/migrationscripts/register.go, plugins/dora/tasks/change_lead_time_convertor.go, plugins/dora/tasks/task_data.go
The simplest plugin implementation for Dora.
close #2865
=> feat: add dora plugin by the simplest way

plugins/dora/dora.go
fix dora import name
close #2872
=> fix: fix dora

plugins/jira/api/swagger.go, plugins/jira/tasks/issue_extractor.go, plugins/jira/tasks/task_data.go, runner/run_task.go, services/blueprint.go
Add support define StandardStatus.
=> feat: jira support define standard status

.github/pull_request_template.md
fix: update wording and typo for pr template
Closes xx
=> fix: update wording and typo for pr template

config-ui/src/pages/configure/integration/manage.jsx
replace `connectionLimit` with exist state.
After the fix, it works right (if we would limit these plugins).
close #2894
=> refactor: replace connectionLimit with exist state

config-ui/src/pages/blueprints/blueprint-detail.jsx
add page for history runs at blueprint state
related #2780
close #2843
=> feat: add page for history runs at blueprint state

Dockerfile, plugins/dbt/tasks/convertor.go
dbt add : 'dbt deps' command line, and add dbt execute history log
Closes #2904 
=> feat: dbt add download packages functions and logging functions

config-ui/src/data/pipeline-config-samples/starrocks.js, plugins/starrocks/api/connection.go, plugins/starrocks/starrocks.go, plugins/starrocks/task_data.go, plugins/starrocks/tasks.go, plugins/starrocks/utils.go
=> feat: starrocks plugin support custom dsn

plugins/jira/tasks/issue_type_collector.go
=> fix(jira): cherrypick #2896 to v0.12

plugins/jira/tasks/issue_type_collector.go
=> fix(jira): cherry pick #2896 to 0.13

config-ui/src/hooks/useConnectionManager.jsx
fix a rebase bug by deleting 2 lines of duplicated code.
Closes #2915
=> fix: fix a rebase bug

plugins/jira/models/migrationscripts/20220716_add_init_tables.go
AutoMigrate --> CreateTable
Closes #2935 
=> fix: cached plan must not change result type in postgres

config-ui/src/hooks/useJIRA.jsx, plugins/jira/api/connection.go, plugins/jira/tasks/issue_extractor.go
Cherrypick #2913 #2921 #2931 to v0.12
=> Cherrypick #2913 #2921 #2931 to v0.12

config-ui/src/hooks/useJIRA.jsx, plugins/jira/api/connection.go, plugins/jira/tasks/issue_extractor.go
Cherrypick #2913 #2921 #2931 to 0.13
=> Cherrypick 2913 2921 2931 to 0.13

plugins/helper/api_async_client.go, plugins/helper/api_client.go
Closes  https://github.com/apache/incubator-devlake/issues/2938
=> fix: the timeout of ApiClient is incorrectly overridden #2938

models/domainlayer/devops/cicd_pipeline.go, models/migrationscripts/20220905_modfiy_pipeline.go, plugins/jenkins/tasks/build_cicd_convertor.go
add jenkins pipeline relationship: cicd_pipeline_relationships
We can know which pipeline triggered another one
relate to #2957
=> feat(domain): add jenkins pipeline relation

.github/pull_request_template.md
=> fix: fix issue-2511

plugins/jira/tasks/account_collector.go, plugins/jira/tasks/account_extractor.go
* fix bug #2550
* support jira server collect users
* support jira server collect users
* support jira server collect users
* fix:support jira server collect users
* fix(jira): support jira server collect users
* fix: support jira server collect users
Relate to #2550 
=> cherrypick #2587 to 0.12

Makefile
Add build-images cmds in Makefile to build images quickly for debug devlake on k8s
```
make TAG=0.12.0-debug build-images
```
Closes xx
=> Add build-images cmd in Makefile

models/domainlayer/devops/cicd_pipeline.go, models/migrationscripts/register.go, plugins/github/impl/impl.go, plugins/github/tasks/cicd_pipeline_convertor.go, plugins/gitlab/tasks/pipeline_convertor.go
github add cicd_pipeline_repos by cicd_pipeline_convertor
related to #2951 
=> feat: github add cicd_pipeline_repos

generator/cmd/create_collector.go, generator/cmd/create_extractor.go, plugins/zentao/api/blueprint.go, plugins/zentao/api/connection.go, plugins/zentao/api/init.go, plugins/zentao/impl/impl.go, plugins/zentao/models/archived/connection.go, plugins/zentao/models/connection.go, plugins/zentao/models/migrationscripts/20220906_add_init_tables.go, plugins/zentao/models/migrationscripts/register.go, plugins/zentao/tasks/api_client.go, plugins/zentao/tasks/project_collector.go, plugins/zentao/tasks/task_data.go, plugins/zentao/zentao.go
Relate to #2961
Create new plugin zentao
modify code generator
create project_collector
Relate to #2961
=> feat(zentao): create new plugin

config-ui/src/components/pipelines/StageTaskName.jsx
1. fix error column updateAt;
2. display updateAt as '-' when it's empty, instead of now.
Closes #2976
=> fix: fix bug on update time

models/blueprint.go, models/migrationscripts/20220903_modify_blueprint.go, models/migrationscripts/20220904_modify_pipeline.go, models/migrationscripts/register.go, models/pipeline.go, runner/run_pipeline.go, services/blueprint.go, services/blueprint_helper.go, services/pipeline.go, services/pipeline_helper.go, services/pipeline_runner.go
=> fix:Encrypting blueprint.settings blueprint.plan and pipeline.plan in the database #2868

.github/workflows/commit-msg.yml
Modify commit msg to support : `(feat|fix|build|chore|docs|style|refactor|perf|test|ci)(\(\w+(-\w+)?\))?:(\s*).*`
Closes 2996
=> Modify commit msg lint

generator/cmd/create_collector.go, generator/cmd/create_extractor.go
modify:
create_collector.go
create_extractor.go
Closes #3000 
=> fix(code generator): modify template

models/domainlayer/devops/cicd_pipeline.go, models/migrationscripts/20220905_modfiy_cicd_pipeline.go, plugins/gitlab/models/migrationscripts/20220729_modify_gilab_ci.go, plugins/gitlab/models/migrationscripts/20220907_add_pipeline_projects_tables.go, plugins/gitlab/models/migrationscripts/register.go
add pipeline_projects_tables and fix common import
related to #2998 
=> fix: add pipeline_projects_tables and fix common import

config-ui/src/data/pipeline-config-samples/starrocks.js, plugins/starrocks/api/connection.go, plugins/starrocks/starrocks.go, plugins/starrocks/task_data.go, plugins/starrocks/tasks.go, plugins/starrocks/utils.go
=> feat: Cherry pick starrocks source dsn support

models/domainlayer/devops/cicd_task.go, models/migrationscripts/20220908_modfiy_cicd_tasks.go, plugins/jenkins/impl/impl.go, plugins/jenkins/tasks/build_cicd_convertor.go, plugins/jenkins/tasks/build_stages_enricher.go
1. put all single build without stages to cicd_tasks
2. add field `environment` to cicd_task
relate to #2957
=> fix(jenkins): modify cicd for dora

api/api.go, api/blueprints/blueprints.go, api/pipelines/pipelines.go, api/push/push.go, api/task/task.go, plugins/github/tasks/comment_collector.go, plugins/github/tasks/pr_review_comment_extractor.go, services/blueprint.go, services/init.go
=> style(all): resolve some small issues

plugins/bitbucket/bitbucket.go, plugins/bitbucket/tasks/task_data.go
delte some taskoptions like IssueType , prType etc.
=> fix: delete some useless code

.github/workflows/golangci-lint.yml, .github/workflows/test-e2e.yml, .github/workflows/test.yml, Dockerfile, devops/lake-builder/Dockerfile
Closes #2908 
Blocks #2940/#2984
Blocks #2907/#2941
=> [issue-2908]: Bump lake-builder version to 0.0.8

plugins/zentao/api/blueprint.go, plugins/zentao/api/connection.go, plugins/zentao/api/init.go, plugins/zentao/impl/impl.go, plugins/zentao/models/access_token.go, plugins/zentao/models/archived/connection.go, plugins/zentao/models/connection.go, plugins/zentao/models/migrationscripts/20220906_add_init_tables.go, plugins/zentao/models/migrationscripts/register.go, plugins/zentao/tasks/api_client.go, plugins/zentao/tasks/project_collector.go, plugins/zentao/tasks/task_data.go, plugins/zentao/zentao.go
new plugin zentao
Relate to #2961 
=> Feat zentao fix

plugins/zentao/models/archived/connection.go, plugins/zentao/models/migrationscripts/20220906_add_init_tables.go
=> Fix zentao conn

plugins/zentao/tasks/api_client.go, plugins/zentao/tasks/project_collector.go, plugins/zentao/tasks/shared.go
=> update project collector

plugins/gitea/tasks/commit_collector.go, plugins/gitea/tasks/issue_comment_collector.go, plugins/gitea/tasks/repo_collector.go, plugins/gitea/tasks/shared.go, plugins/github/tasks/comment_extractor.go, plugins/github/tasks/shared.go, plugins/helper/utils.go, plugins/helper/utils_test.go
minor modification for gitea
relate to #2992
=> fix(gitea): modify some minor issues

models/migrationscripts/20220913_modfiy_board_repos.go, models/migrationscripts/register.go, plugins/gitee/tasks/repo_convertor.go, plugins/github/e2e/repo_test.go, plugins/github/e2e/snapshot_tables/board_repos.csv, plugins/github/tasks/repo_convertor.go, plugins/gitlab/e2e/project_test.go, plugins/gitlab/e2e/snapshot_tables/board_repos.csv, plugins/gitlab/e2e/snapshot_tables/boards.csv, plugins/gitlab/tasks/project_convertor.go
add board_repos record for github/gitlab/gitee
closes #3056
=> fix(framework): add board_repo record for git* issues

plugins/dora/tasks/cicd_task_env_enricher.go
fix: enrich tasks env for dora
related to #2876 
=> fix: enrich tasks env for dora

plugins/helper/api_client.go, plugins/tapd/api/connection.go
fixed by setting timeout longer
Closes #3065 [Bug][tapd] error occurred while adding connection for plugin tapd 
=> fix: tapd test connection error

plugins/bitbucket/models/connection.go, plugins/bitbucket/models/migrationscripts/20220803_add_init_tables.go, plugins/bitbucket/models/migrationscripts/archived/connection.go, plugins/gitee/tasks/pr_review_collector.go
closes #3007 
remove dependency on bitbucket ENV in `.env` file
delete useless filed `RemotelinkCommitShaPattern` in `BitbucketConnection` struct
=> fix: remove dependency on bitbucket ENV from `.env` file

services/blueprint.go, services/blueprint_helper.go, services/pipeline_helper.go, services/task.go
update error handling to adapt new error handler
closes #3088
=> fix(framework): fix error handling

models/domainlayer/devops/cicd_task.go, plugins/github/github.go, plugins/github/models/connection.go, plugins/github/tasks/cicd_job_convertor.go, plugins/github/tasks/task_data.go
add deployTagPattern for github
related to #3101 
=> feat: add deployTagPattern for github

plugins/bitbucket/impl/impl.go, plugins/bitbucket/models/migrationscripts/20220914_add_pipeline_tables.go, plugins/bitbucket/models/migrationscripts/archived/pipeline.go, plugins/bitbucket/models/pipeline.go, plugins/bitbucket/tasks/api_common.go, plugins/bitbucket/tasks/pipeline_collector.go, plugins/bitbucket/tasks/pipeline_convertor.go, plugins/bitbucket/tasks/pipeline_extractor.go
add Bitbucket Pipeline Collector&Extractor&Convertor
Closes #3058 
=> add Bitbucket Pipeline Collector&Extractor&Convertor

plugins/zentao/impl/impl.go, plugins/zentao/models/archived/project.go, plugins/zentao/models/migrationscripts/20220906_add_init_tables.go, plugins/zentao/tasks/project_extractor.go
=> feat:add zentao project extractor

grafana/dashboards/GitExtractor.json
Add a dashboard displaying the metrics by gitextractor plugin
related to #1771 
=> feat: add gitextractor dashboard

services/pipeline.go, services/task.go
Add mu.Lock() and defer mu.Unlock() before visit.
Closes #2989 
=> fix: fix the running task lost lock and visit map

plugins/gitlab/gitlab.go, plugins/gitlab/models/connection.go, plugins/gitlab/tasks/job_convertor.go, plugins/gitlab/tasks/task_data.go
feat: add deployTagPattern for gitlab
related to #3101
=> feat: add deployTagPattern for gitlab

plugins/gitlab/tasks/pipeline_project_convertor.go, plugins/webhook/api/cicd_pipeline.go, plugins/webhook/api/cicd_pipeline_test.go, plugins/webhook/api/issue.go, plugins/webhook/impl/impl.go
This PR is based on #3051 .
finish pipeline and issue webhook
Closes #3023
curl http://127.0.0.1:8080/plugins/webhook/1/cicd_tasks -X 'POST' -d '{"pipeline_name":"A123","name":"unit-test","result":"IN_PROGRESS","status":"IN_PROGRESS","type":"TEST","environment":"PRODUCTION","created_date":"2020-01-01T12:00:00+00:00","finished_date":"2020-01-01T12:59:59+00:00","repo_id":"devlake","branch":"main","commit_sha":"015e3d3b480e417aede5a1293bd61de9b0fd051d"}'
```{"success":true,"message":"success"}```
curl http://127.0.0.1:8080/plugins/webhook/1/cicd_tasks -X 'POST' -d '{"pipeline_name":"A123","name":"unit-test","result":"IN_PROGRESS","status":"IN_PROGRESS","type":"CI","created_date":"2020-01-01T12:00:00+00:00","finished_date":"2020-01-01T12:59:59+00:00","repo_id":"devlake","branch":"main","commit …
=> feat: finish pipeline and issue webhook

plugins/bitbucket/tasks/issue_comment_extractor.go, plugins/bitbucket/tasks/issue_extractor.go, plugins/bitbucket/tasks/pr_comment_extractor.go, plugins/bitbucket/tasks/pr_extractor.go, plugins/bitbucket/tasks/repo_extractor.go
=> fix: add json tag for apiresponse

plugins/starrocks/tasks.go, plugins/starrocks/utils.go
=> feat: starrocks plugin support pg array

plugins/github/api/connection.go
=> fix(github): Fix for Github TestConnection error handling

Makefile, plugins/github/api/blueprint.go, plugins/github/api/blueprint_test.go, services/blueprint.go
if request of blueprints for github contains `dora` in `transformation`, we add dora support for it 
The below is the blueprint we GET by /blueprints
```json
{
"name": "test blueprint normal",
"mode": "NORMAL",
"plan": [
[
{
"plugin": "github",
"subtasks": [
"CollectApiPrReviewCommentsMeta",
"extractApiPrReviewComments",
"convertRepo"
],
"options": {
"connectionId": 1,
"owner": "merico-dev",
"repo": "lake",
"transformationRules": {
"prType": "hey,man,wasup"
}
}
},
{
"plugin": "gitextractor",
"subtasks": null,
"options": {
"proxy": "",
"repoId": "github:GithubRepo:1:491450511",
"url": "https://git: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@github.com/merico-dev/lake.git"
}
}
],
[
{
"plugin": "refdiff",
"subtasks": null,
"options": {
"tagsLimit": 10,
"tagsOrder": "reverse semver", …
```
=> feat(github): add dora enrich

config-ui/.prettierignore, config-ui/.prettierrc.js
Add headers to files with missing headers.
=> fix(config-ui): some files do not have a header

runner/run_task.go
1. mimic a panic in subtask:
2. trigger pipeline:
3. pipeline detail should be show failed:
Closes #3140
=> fix: pipeline failed to handle panicking

plugins/webhook/api/connection.go
1. add hook-URL in connections API.
2. add another 2 hook-URL
=> Issues/3023 add hook-URL in connections API

runner/run_task.go
pipeline failed to handle panicking
cherry pick from f4eefc54b129bff9a41b125bcf7d2fa8bd24ea25 ( #3142 )
no
=> Kw 3140 pipeline panic v0.12

plugins/github/api/blueprint_test.go, plugins/gitlab/api/blueprint.go, plugins/gitlab/api/blueprint_test.go
add dora to gitlab blueprint
relate to https://github.com/apache/incubator-devlake/issues/3127
=> feat(gitlab): add dora support and unit test

plugins/jenkins/api/blueprint.go
if transfomationRules contain "dora", add dora enrich to jenkins pipeline
=> feat(jenkins): add dora enrich

config-ui/.prettierrc.js, config-ui/src/components/blueprints/BlueprintDataScopesDialog.jsx, config-ui/src/components/blueprints/DataScopesGrid.jsx, config-ui/src/components/blueprints/GitlabProjectsSelector.jsx, config-ui/src/components/blueprints/ProviderTransformationSettings.jsx, config-ui/src/components/blueprints/create-workflow/DataScopes.jsx, config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx, config-ui/src/components/blueprints/transformations/CICD/Deployment.jsx, config-ui/src/data/DataScopes.js, config-ui/src/hooks/useBlueprintValidation.jsx, config-ui/src/hooks/useConnectionManager.jsx, config-ui/src/hooks/useDataScopesManager.jsx, config-ui/src/hooks/useNetworkOfflineMode.jsx, config-ui/src/models/Connection.js, config-ui/src/pages/blueprints/blueprint-settings.jsx, config-ui/src/pages/blueprints/create-blueprint.jsx, config-ui/src/pages/blueprints/index.jsx, config-ui/src/pages/configure/connections/AddConnection.jsx, config-ui/src/pages/configure/connections/ConfigureConnection.jsx, config-ui/src/pages/configure/integration/manage.jsx, config-ui/src/pages/configure/settings/github.jsx, config-ui/src/pages/configure/settings/gitlab.jsx, config-ui/src/pages/configure/settings/jenkins.jsx, config-ui/src/pages/configure/settings/jira.jsx, config-ui/src/pages/offline/index.jsx, config-ui/src/styles/offline.scss
This PR adds **Deployment Tag** Transformation properties for Blueprints in order to support DORA Metrics. The new transformation properties are mapped to one main Environment, **Production** (`productionPattern`), in a future release **Staging** (`stagingPattern`) and **Testing** (`testingPattern`) environments maybe added. The deployment tag option is **NOT enabled** by default for all applicable providers and will have empty tag values by default. Additionally, this feature is coupled to the **DevOps** **Data Entity Type** (Entity Code === `CICD`). The `CICD` Entity type must be added to the connection scope in order to utilize deployment tag feature.
If the user chooses to _enable_ deployment tag, they should complete the RegEx Tag value for the **Production Environment**.
**Sample …
=> feat: add deployment tag transformation setting

migration/migrator.go, models/migrationscripts/20220913_commitfile_add_length.go, plugins/jenkins/models/migrationscripts/20220916_modify_jenkins_build.go
Add Re Executability to addCommitFilePathLength.
Fix a type error on modifyJenkinsBuild.
Add error message on migrator execute.
Closes #3108 
Closes #3126 
Closes #3131 
=> fix: fix migrator bug

plugins/dora/tasks/cicd_task_env_enricher.go, plugins/dora/tasks/task_data.go
add param datasource for dora enrichTasksEnv
Closes #2876 
=> fix: add param datasource for dora enrichTasksEnv

plugins/github/api/blueprint.go, plugins/github/api/blueprint_test.go, plugins/gitlab/api/blueprint.go, plugins/gitlab/api/blueprint_test.go, plugins/jenkins/api/blueprint.go
change dora enrich trigger method for github/gitlab/jenkins
=> fix(plugins): change dora enrich trigger method

plugins/github/api/blueprint.go, plugins/gitlab/api/blueprint.go, plugins/jenkins/api/blueprint.go
add one more judge for plans to avoid `out of index` error
Closes xx
=> fix(plugins): avoid out of index for plans

plugins/github/api/blueprint.go, plugins/gitlab/api/blueprint.go, plugins/jenkins/api/blueprint.go
=> fix(plugins): add plan

plugins/dora/dora.go, plugins/dora/tasks/cicd_task_env_enricher.go, plugins/dora/tasks/task_data.go, plugins/github/models/connection.go, plugins/github/tasks/cicd_job_convertor.go, plugins/github/tasks/task_data.go, plugins/gitlab/models/connection.go, plugins/gitlab/tasks/job_convertor.go, plugins/gitlab/tasks/task_data.go, plugins/jenkins/models/connection.go, plugins/jenkins/tasks/stage_convertor.go, plugins/jenkins/tasks/task_data.go
=> fix: update strategy environtment

config-ui/src/components/blueprints/transformations/CICD/Deployment.jsx, config-ui/src/hooks/useDataScopesManager.jsx
1. Added environment mapping field.
2. Adjust the default value of the dora deployment field.
none.
none.
=> fix(config-ui): adjust some content about dora

config-ui/src/hooks/useDatabaseMigrations.jsx
This PR fixes the **DB Migration Alert** handler so that the migration request is properly wrapped in an async handler.
Closes #3109
=> fix: config-ui - database migration handler update

plugins/dora/tasks/cicd_task_env_enricher.go
fix: type filed is nil in cicd_task table by github plugin.
Closes #3172 
=> fix: type filed is nil in cicd_task table by github plugin

plugins/helper/iso8601time.go, plugins/zentao/impl/impl.go, plugins/zentao/models/archived/execution.go, plugins/zentao/models/archived/project.go, plugins/zentao/models/execution.go, plugins/zentao/models/migrationscripts/20220906_add_init_tables.go, plugins/zentao/models/project.go, plugins/zentao/tasks/execution_collector.go, plugins/zentao/tasks/execution_convertor.go, plugins/zentao/tasks/execution_extractor.go, plugins/zentao/tasks/project_extractor.go
=> Feat zentao execution

plugins/github/tasks/cicd_job_collector.go
add scope for job collector
closes #3182
=> fix(github): add scope for job collector

plugins/github/tasks/cicd_job_collector.go, plugins/github/tasks/shared.go
fix: github job collector occurs 404
Closes #3177 
=> fix: github job collector occurs 404

plugins/dora/tasks/cicd_task_env_enricher.go
fix: type filed is nil in cicd_task table by jenkins-dora union plugin
related to #3172 
=> fix: type filed is nil in cicd_task table by jenkins-dora union plugin

plugins/webhook/api/connection.go
fix webhook cannot open when no connection
Closes #3170
=> fix: fix response when no webhook connection

plugins/dora/dora.go, plugins/dora/e2e/env_enricher_test.go, plugins/dora/e2e/raw_tables/lake_cicd_tasks_for_prefix.csv, plugins/dora/e2e/snapshot_tables/lake_cicd_tasks_prefix.csv, plugins/dora/tasks/cicd_task_env_enricher.go, plugins/dora/tasks/task_data.go, plugins/jenkins/api/blueprint.go
1. change type of `dataSource` from `[]string` to `string`
2. change `dataSource` to `prefix`
3. add e2e 
4. modify jenkins dora enrich
Relate #3155
=> fix(jenkins): modify dora param `dataSource` to `prefix`

plugins/webhook/api/cicd_pipeline.go, plugins/webhook/api/connection.go, plugins/webhook/api/issue.go, plugins/webhook/impl/impl.go
changed issueId to be issueKey
finshed cicd_task in PostPipelineFinish
create domainBoard only if non-existent
Closes #3196 
Closes #3204 
Closes #3210 
=> fix: fix webhook

plugins/webhook/api/cicd_pipeline.go
changed scan to fetch
related #3217 
=> fix: fix scan to fetch

config-ui/src/hooks/usePipelineValidation.jsx
turn off data provider validation in advanced mode.
Closes #3055
None.
=> fix(config-ui): turn off data provider validation in advanced mode

config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx, config-ui/src/components/blueprints/transformations/CICD/Deployment.jsx
**deploymentPattern** and **productionPattern** are not passed when DORA is not required.
Closes #3189 
**DORA is required**
**DORA is not required**
=> fix(config-ui): adjust the parameters so the devlake can not execute DORA tasks

plugins/helper/api_async_client.go, plugins/helper/api_collector.go
add http post support in api_collector
Closes #3221
=> feat(framework): add post api support

.asf.yaml
=> fix: updated project description in .asf.yaml

plugins/dora/models/migrationscripts/20220928_add_dora_benchmark.go, plugins/dora/models/migrationscripts/register.go
add table.dora_benchmarks 
This will be added to db when dora plugin is installed.
This will happen during dora migrations
Closes #3233 3233
=> feat(dora): add dora benchmarks

config-ui/src/pages/configure/settings/github.jsx, config-ui/src/pages/configure/settings/jira.jsx
=> fix: github transformation - add dora label to github incident group

grafana/dashboards/DORA.json
=> feat: add dora dashboard

config-ui/src/components/Sidebar/MenuConfiguration.jsx, config-ui/src/pages/configure/integration/index.jsx, config-ui/src/pages/configure/settings/jira.jsx, config-ui/src/pages/offline/index.jsx
- Sidebar Menu, Page Heading, Breadcrumbs
Closes #3228
=> fix: config-ui: apply text updates to data integrations section

models/domainlayer/ticket/issue.go, models/migrationscripts/20220929_modify_lead_time_minutes.go, models/migrationscripts/register.go, plugins/bitbucket/tasks/issue_convertor.go, plugins/gitee/tasks/issue_convertor.go, plugins/github/tasks/issue_convertor.go, plugins/gitlab/tasks/issue_convertor.go, plugins/jira/tasks/issue_convertor.go, plugins/tapd/tasks/bug_converter.go, plugins/tapd/tasks/story_converter.go, plugins/tapd/tasks/task_converter.go, plugins/webhook/api/issue.go
fix #3224 [Bug][DORA] bigint unsigned value is out of range mysql 
Alter the table `issues` setting the type of `lead_time_minutes` to `BIGINT`
Closes #3224 
=> fix: modify lead_time_minutes to bigint
