apache/incubator-devlake

- config/local.sample.js
- src/collection/collectors/jira/changelogs.js
- src/collection/collectors/jira/fetcher.js
- src/collection/collectors/jira/index.js
- src/collection/collectors/jira/issues.js
- src/enrichment/enrichers/jira.js
`Lead Time` is the one metric we really wanted to get done as a POC, so I've added it here. This is not the most fail-proof solution, and I've only given it one pass, but I think it's close.
I made a couple decisions here:
- When we collect changelogs, instead of storing the exact response from jira, which includes request meta data, I'm only inserting the actual changes into the changelog collection.
- Because there is no issue id attached to changelogs, I added it in the collection phase.
The calculation for lead time is as follows:
```
last_timestamp = issue created timestamp 
lead_time = 0
for every status change:
if the old status was not closed:
lead_time += the diff in seconds between the change_timestmap and the last_timestamp
last_timestamp = change_date
```
Finally, if the …
> Add jira changelog collector and enrich issues with lead time

- package-lock.json
- package.json
Found that we don't have sequelize-cli in package.json when I ran the migration. Making this PR this add it as a dep.
> Add sequelize-cli to dev dependencies

- src/collection/collectors/jira/changelogs.js
- src/enrichment/enrichers/jira.js
@paulgoertzen-merico I followed the workflow for computing lead time in the README but found pg didn't have any issues. With some `console.log`, I found the return value of `issueCollector.findIssues` is empty. I was able to fix the issue by using project id as the query parameter instead of the project name.
After this change, both changelog collector started to fetch changelogs and JIRA enricher started writing to `jira_issues` table.
> Use project id instead of project name to fetch issues from mongo

- config/plugins.json
- package-lock.json
- package.json
- src/plugins/index.js
This PR implements the plugin registry pattern as described by Hezheng in the Dev Lake MVP doc (https://docs.google.com/document/d/19JqqF_-qVBBzbgbWB5ncaNjtETDMfBrLL7zsaLTtfr0)
The plugin registry doesn't do anything yet, it's not being used. But you can see how we configure it, and how it loads the plugins.
I created https://github.com/merico-dev/jira-pond as the other half to this PR. It implements the plugin interface. Please review it. It also does nothing really, it's just the interface.
You may find the plugin config file weird. I took a few different approaches, but this is the one that seemed best to me. It allows for importing multiple collectors or enrichers from the same package (using the `name` property).
> Integrates the new plugin registry pattern

- README.md
- docker-compose.yml
- Adds grafana dashboard to docker
- Updates readme to have grafana credentials (connect to dashboard via `localhost:3002`)
> add grafana dashboard to docker

- src/plugins/jira-pond/src/collector/changelogs.js
- src/plugins/jira-pond/src/collector/issues.js
- src/plugins/jira-pond/src/enricher/index.js
The latest main branch is broken due to previous unverified PRs. This PR fixes the major issues so that we get non-zero lead time in the pg again.
Besides the necessary fixes, this PR also incorporates @oddscenes and @joncodo's work described below
1. handling pagination when fetching Jira issues
2. fetching Jira changelogs in parallel with `Promise.all`
3. fixing duplicating issues in mongodb and postgres
> Fix lead time

- config/local.sample.js
- package.json
- src/plugins/jira-pond/src/collector/fetcher.js
Hi, guys, I'm having trouble accessing atlassian.net directly, so, I thought maybe an optional proxy setting would be helpful for both development and production scenario.
Note: proxy option of axios won't work properly
> feat: add proxy support for jira fetcher

- docker-compose.yml
- scripts/wait-for
Grafana is failing in our docker-compose build, because it depends on postgres to be up and running first
This change will run a command ensuring postgres is up first before starting grafana
> fix: make grafana wait for postgres on docker startup

- package.json
use `npm run docker` to startup docker, and force rebuilding/no cache
> Run docker from npm

- README.md
- db/migrations/20210719164314-add-jira-users.js
- db/migrations/20210719171721-add-jira-issues.js
- db/migrations/20210729124354-add-gitlab-projects.js
- db/migrations/20210729134703-add-gitlab-commits.js
- db/migrations/20210729165758-add-projectId-to-gitlab-commit.js
- db/postgres/gitlabCommit.js
- db/postgres/gitlabProject.js
- db/postgres/jiraIssue.js
- db/postgres/jiraUser.js
- grafana/dashboards/Home.json
- src/plugins/gitlab-pond/src/collector/collection-manager.js
- src/plugins/gitlab-pond/src/enricher/index.js
- src/plugins/jira-pond/src/enricher/index.js
We want to show metrics based on user commits to a repo that have been enhanced with data
Here are the metrics this collects
1. Number of contributors
2. Number of commits
3. Removed lines of code
4. Added lines of code
5. Accumulated lines (defined as the sum of added lines of code and removed lines of code during a time window)
- To change this, I had to load up grafana on port 3002 and then I had to make queries for the dashboard and run them.
- I also had to add gitlab_commits.project_id
- set page size of gitlab commits to 100 and not the default 20
> Gitlab - adding in commit level metrics to grafana dashboard

- docker-compose.yml
- src/plugins/gitlab-pond/index.js
When we run `npm run docker`, if Postgres is not all the way initialized, Grafana will shutdown. Since Postgres on initial startup takes a moment to set everything up, we need a mechanism to make Grafana wait for Postgres.
Simply setting `depends_on` doesn't work since docker-compose does not wait until a container is “ready” - only until it’s running. Here's the [doc](https://docs.docker.com/compose/startup-order/).
This PR is not a perfect fix, but it should work. By setting `restart: always` in `docker-compose.yml`, Grafana will retry many times until Postgres is fully up. This has been tested on my laptop.
> Make Grafana wait for Postgres by setting restart to always

- docker-compose.yml
We actually don't need to specify the database + datasource for Grafana. This is what's causing all the internal Grafana DB stuff to populate the `lake` postgres db.
**Updated:**
- Removed Grafana database env variables
**Fixes:** 
- Stops cluttering the working db with Grafana internal db things that we don't really need
**Note**
- It's possible in the future if we want this Grafana internal db stuff back, we can just make another db in `docker-compose.yml`. Then populate it. As of now though, I don't see any use for it.
> fix: removed grafana internal db things from working db

- db/migrations/20210730182134-change-string-to-text-gitlab.js
- db/postgres/gitlabCommit.js
- db/postgres/gitlabMergeRequest.js
- src/plugins/gitlab-pond/src/collector/commits.js
- src/plugins/gitlab-pond/src/collector/fetcher.js
- src/plugins/gitlab-pond/src/collector/merge-requests.js
- src/plugins/gitlab-pond/src/enricher/index.js
- src/plugins/jira-pond/index.js
- src/plugins/jira-pond/src/collector/issues.js
1. There was an issue with the fetchPaginated where we were using `?all=true`. I removed that since
it was not giving the correct number of issues in the default branch in gitlab. If you use all=true,
it seems to get about double the commits. I have a theory that this is caused by teams that use
rebase in gitlab. Gitlab seems to save the commits that were rebased with a diffdrent parent so the
ids of the commmits are different. see #95 
2. I also changed the type of the gitlab postgres models to TEXT instead of STRING since some descriptions and title of our data were too long. There is a migration for this and you have to run `npx secquelize db:migrate`
3. I also changed the names of the mongo collections back to `gitlab_commits` and `gitlab_merge_requests` as approved by @UltimateBeaver …
> fix(gitlab collection): fix pagination, table types, mongo names

- src/plugins/jira-pond/src/enricher/index.js
`issueType` was removed from the jira_issues in refactoring, its now added it back in as a field
> fix: added back in issue type to enriched jira issues db

- docker-compose.yml
When I run `npm run docker`, rabbitmq doesn't start up due to a permission denied error: 
```
rabbitmq_1    | 2021-07-31 17:47:47.113606+00:00 [noti] <0.44.0> Application rabbit exited with reason: {{cannot_log_to_file,"/var/log/rabbitmq/rabbit@fcdd6141911a_upgrade.log",eacces},{rabbit,start,[normal,[]]}}
```
This PR fixes the issue by changing the location of rabbitmq volume to the current folder.
> fix: rabbitmq can't log to /tmp on macOS permission denied

- README.md
- config/plugins.js
- package.json
- src/collection/worker.js
- src/enrichment/worker.js
- src/plugins/compound-figures/index.js
- src/plugins/gitlab-pond/index.js
- src/plugins/gitlab-pond/src/collector/index.js
- src/plugins/gitlab-pond/src/enricher/index.js
- src/plugins/gitlab-pond/src/enricher/projects.js
- src/plugins/index.js
- src/plugins/jira-pond/index.js
- src/plugins/jira-pond/src/collector/fetcher.js
- src/plugins/jira-pond/src/collector/index.js
- src/plugins/jira-pond/src/collector/issues.js
- src/plugins/jira-pond/src/enricher/index.js
- src/plugins/jira-pond/src/enricher/issues.js
1. Support plugin configuration injection
Plugin can declare a default configuration on its main module, which could be overridden by 
`config/plugins.js`. We should move their configurations from `local.js` to `plugins.js` file
2. Collectors now execute in parallel, so do enrichers
Our collectors have no dependency to each other at this point, all plugins we specified in 
request body will be executed in parallel
3. Ensure correct data types of parameters(boardId/projectId) on root functions `collect/enrich`
Once and for all
4. `axios` timeout mitigation for `jira-pond`
5. Mitigation for scenario that jira data collecting procedure got interrupted(Ctrl-C) with sorting
jira issues from API by `updated` field
> feat: plugins initialization before all workers

- grafana/dashboards/Home.json
1. All three lead time charts support time filter
2. Fix lead time median trend no data issue
3. Adjust bucket configuration for lead time distribution and improve pie chart labels
> fix: fix lead time charts in grafana dashboard

- package.json
Concurrently seems to not allow you to run something like `DEBUG=true npm run all` so we need `npm
run all` and `npm run all-debug`. The reason to have DEBUG is so we can comment out console logs
with `process.env.DEBUG && console.log()` so we don't remove console logs needed by others.
> chore(npm): we need a way to run without DEBUG when desired

- README.md
- src/plugins/gitlab-pond/src/collector/commits.js
- src/plugins/gitlab-pond/src/collector/index.js
- src/plugins/gitlab-pond/src/enricher/commits.js
- src/plugins/jira-pond/src/enricher/boards.js
Users sometimes do not work off of the main branch on gitlab. The main branch could be 'main' but all the current work is on the 'development' branch. 
You can now send a post request to localhost:3001 with this body:
```
{
"gitlab": {
"projectId": 19688130,
"branch": "jon-test"
}
}
```
Where "branch" is optional. It defaults to the default branch of gitlab.
Here is the terminal output calling this api
Here is the record in mongo locally
Here is the branch I tested in gitlab
Here is the record in psql
> feat: allow users to configure which branch to fetch for gitlab repos

- CONFIGURATION.md
- README.md
- Grafana data source connection info should go in configuration readme with other config
- Duplicate info is also removed from main `readme.md` 
As I'm working on some other readme stuff, I'm considering Grafana and other collection/enrichment tasks as "core" functionality (hence the title). Jira/gitlab etc are "plugin" functionality. I think this split will be useful for scaling the docs
> Move grafana config readme

- README.md
We need to setup a doc structure for easier dev setup, and better scaleability (especially with plugins and features). Need to be able to navigate all documentation sections, with more straight forward structure/language/examples.
Also using markdown files in the codebase vs a Github wiki allows us to keep documentation PRs within this repo. This makes it easier for anyone to contribute.
This PR is focused only on `README.md` (not `CONFIGURATION.md`, `CONTRIBUTING.md` etc). It's the first step in a better documentation system using markdown files within our codebase. Plugin usage especially is setup for scaling as we add more.
High level new structure:
- Logo and title
- Badges
- Project description
- Table of contents (including external doc links)
- Requirements
- Installation 
- Setup …
> docs(readme.me): refactor entire flow and structure of readme setup

- grafana/provisioning/datasources/datasource.yml
We changed Postgres password but didn't update it for Grafana. Without this fix, Grafana can't connect to pg.
> fix: update postgres passwd for grafana

- config/database.json
- package.json
We are trying to reduce the number of steps that a new user needs to do when they attempt to run the application for the first time.  Fixes: https://github.com/merico-dev/lake/issues/145
All we need to do here is to run the migrations when the `npm run compose-prod` command is run.
In order to do this, the Dockerfile has `ENV NODE_ENV=docker`. This means that sequelize will look for a file called database.json and then look for a key called `docker`. This is why I had to add it with the `"host": "postgresdb",` so sequelize could connect to the correct port within docker compose.
You can see the docker logs that show this working here:
And this is a result of modifying the `npm run lake-prod` command.
Which is run from the Dockerfile as `CMD ["npm", "run", "lake-prod"]`
> feat: allow the migrations to be run while running the app in prod mode

- README.md
- docs/CONFIGURATION.md
- docs/GRAFANA.md
- src/plugins/HOW-TO-ADD-METRICS.md
- src/plugins/README.md
An update to the readme docs regarding formatting, linking and adding a new table of contents footer. All changes are made for better navigation and inclusion of all the doc files
1. modified self-closing anchor tags in readmes
- This was breaking some markdown preview functionalities
2. Added a table of contents to other doc files in the repo
- Included at the footer of all markdown files (except plugin specific ones - ex. jira, gitlab)
3. Added syntax highlighting to plugin docs
4. Added `GRAFANA.md` readme file to the table of contents (on main readme and footers) - it was missing previously
> docs: add missing docs, links table and formatting

- src/plugins/gitlab-pond/src/collector/commits.js
Change from withStats to with_stats is necessary to get additions / deletions / total from gitlab commits API.
> fix(gitlab collection for commits): fixed query parameter

- .github/codecov.yml
- .github/workflows/coverage.yml
- .github/workflows/test.yml
- README.md
- apps/queue/test/app.e2e-spec.ts
- package.json
This PR aimed to adding unit test CI check and report coverage for PR.  
We planed to use [codecov](https://app.codecov.io/) to display coverage info in README.md and PR comments. For that purpose, we need install [codecov app](https://github.com/marketplace/codecov) for lake repository, and add the upload token as a secret key called `CODECOV_TOKEN`. @UltimateBeaver
> chore: add ci config for unit test

- README.md
- docs/GRAFANA.md
- src/plugins/HOW-TO-ADD-METRICS.md
- src/plugins/README.md
The plugins section was far down in the main readme and hard to navigate to. as well the plugins section itself needs better definition, and a more descriptive name.
- Change references to "Plugins" to "Data Source Plugins"
- When we add more plugins that do other things (not data source plugins), we will need to use "Plugins" as a main category, and `data source`/`enhancement`/`utility` etc as sub-categories for plugins. But for now, just saying Data Source is easier.
- Moved "Data Source Plugins" under "Requirements" in main readme. Up above user setup near the top.
- Added a short paragraph explanation under **Data Source Plugins** title
> docs: add data source definition details to plugin references

- CONTRIBUTING.md
We need to document these things in the repo and not only in internal communication. This improves our docs substantially :)
> docs: collaboration notes

- README.md
We want to add an image of the dashboard to the main readme file for users to see on github
- Added PNG screenshot to `README.md`
---
Re-created PR of https://github.com/merico-dev/lake/pull/202 - without any unrelated files in this PR
> docs: add dashboard image to readme file

- src/plugins/jira-pond/src/enricher/issues.js
mapping was no longer needed, validation should be removed, or error would be throwed if setting missed in configuration file.
> fix: remove mapping validation

- .github/workflows/commit-msg.yml
- .github/workflows/coverage.yml
- .github/workflows/reviewdog.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
Previous CI configuration combined unit test and e2e test.
- it's not a great practice since these two kind tests are not related. 
- Another reason is that we need setup third-party services for e2e test but not for unit test.
- separate unit test and e2e test into different github actions
- setup mysql for e2e test
- update github actions scope/name
> chore(ci): update github actions

- .github/codecov.yml
- .github/workflows/coverage.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
This PR update pipeline settings, more info in #254 
previous behavior is described in #254, current behaviors as following:
- coverage rate is at least 65% (75% after 9.15)
- covearge rate for added lines is at least 65% (75% after 9.15)
- unit test (node version 12.x, 14.x, 16.x)
- e2e test (node version 12.x)
- commit message lint
- eslint (prettier)
#254
The target coverage rate is planed to 2 stages, now for 65% (current 68%), and 75% after 9.15.
> chore: update pipeline configuration

- .env.example
- .gitignore
- README.md
- devops/docker-compose.yml
- Better notes in README.md and update the db name.
- update of the .env.sample
- update DB name in the docker/compose file
This is needed to run the api locally
> chore: update the readme and change the db name in docker-compose

- models/base.go
- plugins/gitlab/gitlab.go
- plugins/gitlab/init.go
- plugins/gitlab/models/gitlabMergeRequest.go
- plugins/gitlab/models/gitlabMergeRequestNote.go
- plugins/gitlab/models/gitlabReviewers.go
- plugins/gitlab/models/gitlabcommit.go
- plugins/gitlab/models/gitlabproject.go
- plugins/gitlab/tasks/gitlabMergeRequestCollector.go
- plugins/gitlab/tasks/gitlabMergeRequestNote.go
- plugins/gitlab/tasks/gitlabMergeRequestReviewer.go
This PR adds collection to the GitLab Plugin:
- Merge Request
- Merge Request Notes
- Merge Request Reviewers
Yes. It closes this issue: https://github.com/merico-dev/lake/issues/309
GitLab Plugin did not collect all fields needed for metrics from GitLab API.
We are now getting the data we need from GitLab API.
Notes in the DB:
> Gitlab collection - Merge Requests, Reviewers and Notes

- Dockerfile
- README.md
- devops/docker-compose.yml
Add user setup section in README.md and setup docker quick start.
Notice: 
- This PR depend on #330 
- Finish all `TODOs` before merge
TODOs:
```shell
docker build -t ${docker hub account}/lake:${version} .
docker login
docker push ${docker hub account}/lake:${version}
```
> docs: add user setup in readme

- .env.example
- README.md
- api/task/task.go
- test/api/task/task_test.go
- utils/json.go
Users need to be able to query many tasks at once with the api
IE:
```
curl --location --request POST 'localhost:8080/task' \
--data-raw '[
{
"Plugin": "gitlab",
"Options": {
"projectId": 20103385
}
},
{
"Plugin": "jira",
"Options": {
"boardId": 8
}
}
]'
```
NOTE: This means you will have to send down an array of json objects. Otherwise, you get this error:
> feat: allow post to task with many tasks

- plugins/gitlab/README.md
- plugins/gitlab/models/gitlab_merge_request.go
- plugins/gitlab/models/gitlab_merge_request_note.go
- plugins/gitlab/tasks/gitlab_merge_request_collector.go
- plugins/gitlab/tasks/gitlab_merge_request_note.go
To calculate some metrics, we need to have the first comment time on our merge requests.
No.
> feat: adds FirstCommentTime to GL MRs

- plugins/jira/tasks/jiraapiclient.go
- plugins/jira/tasks/jirachangelogcollector.go
- plugins/jira/tasks/jiraissuecollector.go
Now request change logs is one issue by one issue. We need request more parallel.
New Code allow change logs are requested parallel across issue. Now request about 200page/min change logs (It means 400request/min or 2w/min at most or ≈2000/min)
> feat: read jira change log faster(parallelization across issue)

- Makefile
- README.md
- docker-compose.yml
So user can run `docker-compose` command easier, for example: run
`docker-compose ps` to see if all containers were up and ready
> feat: move docker-compose to root folder

- plugins/jira/tasks/jiraboardcollector.go
- plugins/jira/tasks/jiraissuecollector.go
jira board updation would fail due to `created_at` being `0000-00`
This fix makes jira board information update works
> fix: jira board complains `created_at` being 0

- plugins/jira/tasks/jiraapiclient.go
- plugins/jira/tasks/jirachangelogcollector.go
- scripts/pm.sh
Parallelize changelogs collection on issue level
Previous changelogs collection parallelization on changelog level which can collect mulitple pages for one issue at a time, changelogs from different issue still ran on sequential manner.
This PR added a issue scheduler to address the bottleneck
No
> feat: parallelize changelogs collection on issue level 

- plugins/core/apiclient.go
- plugins/gitlab/tasks/gitlab_api_client.go
- scripts/api.sh
- scripts/pm.sh
To handle some pagination api doesn't return `x-Token` header
Some gitlab api like commits doesn't provide `x-total` header, causing plugin collect only the first page for gitlab_commits .
This PR handles this situation in step concurrency manner.
1. For each STEP, send out 1...10 request for each page
2. If page 10 has 'x-next-page' header, go for next STEP
3. If page 1..10 has no 'x-next-page' header, break the loop
> feat: add step concurrency for gitlab apiclient

- plugins/gitlab/models/gitlab_commit.go
- plugins/gitlab/models/gitlab_merge_request.go
- plugins/gitlab/models/gitlab_merge_request_note.go
- plugins/gitlab/models/gitlab_reviewer.go
Remove FK since we are only collecting data and we do not want to store based on data integrity.
From @hezyin 👍 
```
I think there's a misconception, foreign key is not a performance tool. It's meant to ensure the data integrity. It actually degrades performance slightly during insert / update / delete due to the time spent on checking the foreign key constraint. What helps with performance is index. They're two different things. 
I guess what confuses you is that people often create indexes on those foreign key columns, which mixes these two things up a little bit.
```
Removed all the gorm foreign keys but left the primary keys.
- dropped all DB tables
- removed fk on models
- restarted with `make dev`
- Sent post request to gitlab plugin
- All data was still stored and no FK existed
- …
> feat: remove fk from gitlab plugin

- Dockerfile
- devops/lake-builder/Dockerfile
- devops/lake-builder/README.md
This PR enhenced docker build process. Before merge this PR, we should finish below things:
Now we can use ` docker build --build-arg GOPROXY=https://goproxy.io,direct -t lake .` to build lake behind a proxy.
- support goproxy
- use go1.17
- create lake-builder
> chore: update dockerfile

- plugins/gitlab/models/gitlab_commit.go
- plugins/gitlab/models/gitlab_merge_request.go
- plugins/gitlab/models/gitlab_merge_request_note.go
- plugins/gitlab/models/gitlab_reviewer.go
We have removed foreign keys, but we need to add an index on those fields.
We also can clean them up by removing the additional GORM syntax (ie. MergeRequest int) for MergeRequestId foreign key.
> fix: added index to model fields, rm extra fields

- README.md
- devops/sync/docker-compose.yml
Add lake-cli usage (cron sync job) to user setup
> docs: add lake-cli usage to user setup

- scripts/export-env.sh
This failed before in .env
```
DB_URL=foobar # nnnnnn
```
Since the script only removes lines that start with '#'. I changed it to remove end of line comments too.
`export $(grep -v '^#' .env | sed 's/#.*$//g' | xargs)`
> fix: export env remove all comments

- .env.example
To fix the `MySQL connection failed: unknown timezone Asia/Shanghai` error, this PR temporarily removes the timezone info from the connection string.
> fix: remove timezone from db connection string to avoid connection failure

- .env.example
When I deleted timezone from the connection string in `.env.example`, I accidentally deleted the `parseTime=True`, which is needed to auto parse `Date` to `time.Time`.
> fix: add parsetime back to connection string

- Makefile
- README.md
- config-ui/components/Sidebar.js
- config-ui/package.json
- config-ui/pages/api/triggers/task.js
- config-ui/pages/index.js
- config-ui/pages/triggers.js
- config-ui/styles/Home.module.css
- config-ui/styles/Sidebar.module.css
Main update to this PR is a new `/trigger` page to the config ui. This allows us to trigger data collection.
Other updates:
- Updated `README.md` for user focused setup (now that we have containerized config ui)
- `Makefile` now has `make configure` and `make configure-dev`. dev will just run yarn/node. `make configure` will run through docker compose (and most recent docker hub image)
Only way to trigger data collection is through the CLI. We want to offer users (especially non-devs) a way to do it easily through the browser)
Offer an option to trigger data collection through the configuration UI. Also change the docs for better user onboarding. 
- We will need to update docker hub image (config-ui) to see the latest changes for user setup (running `make configure`)
- Testing of this PR …
> feat: trigger ui and doc adjustments

- .editorconfig
- README.md
- api/router.go
- api/task/task.go
- config-ui/pages/api/triggers/config.js
- config-ui/pages/api/triggers/pendings.js
- config-ui/pages/api/triggers/task.js
- config-ui/pages/index.js
- config-ui/pages/triggers.js
- docker-compose.yml
- models/task.go
- plugins/gitlab/README.md
- plugins/gitlab/gitlab.go
- plugins/jenkins/README.md
- plugins/jira/README.md
- scripts/pm.sh
- services/task.go
- test/api/task/task_test.go
Add logic to show tasks progress on config-ui trigger page
> Show tasks progress on config-ui

- docker-compose.yml
Mysql and devlake would fail to start, and causing 500 error on config-ui，this fix should not affect other platform
> fix: apple m1 would fail

- plugins/jira/README.md
Fixes: https://github.com/merico-dev/lake/issues/395
The status mappings are the most confusing to the reader I think. This should help wth that.
UPDATE:
- Added main section called `Configuration` with notes on the `.env` file
- re-ordered sections based on team feedback to match config UI
- Added some more detailed examples
- Added @hezyin 's screenshot for statuses
- General english grammar updates
Questions:
1. @klesh @narrowizard @jaxzhou is this a valid example: `JIRA_ISSUE_TYPE_MAPPING=Requirement:Story;Incident:CustomerComplaint;Bug:QABug;`
2. @hezyin since I rebased, I see that some information was added to the wiki here: https://github.com/merico-dev/lake/wiki/How-to-find-Jira-the-custom-field-ID-in-Jira. Can you tell me which parts of our information belong in the wiki and …
> docs: polish of Jira readme

- config-ui/components/SaveAlert.jsx
- config-ui/pages/index.jsx
- config-ui/pages/plugins/gitlab.jsx
- config-ui/pages/plugins/jenkins.jsx
- config-ui/pages/plugins/jira.jsx
Replace native `alert()` messages on form submit for all form pages (configuration/plugins) with a nicer, in browser dialog UI component
no
native alert on form submit isnt the best user experience, and we can't control much
New dialog lets us (in the first steps at least) show to user better how to restart server
> feat: replace native alert with in browser dialog

- .editorconfig
- docker-compose.yml
- grafana/grafana.config
- grafana/provisioning/datasources/datasource.yml
- plugins/gitlab/README.md
1. `editable: true` is critical for user to change the mysql password for security.
2. `grafana.confg` file is unnecessary and make configuration harder.
3. add missing anchor for gitlab api token
> Fix data source `mysql` uneditable

- config-ui/pages/index.jsx
- config-ui/pages/plugins/gitlab.jsx
- config-ui/pages/plugins/jenkins.jsx
- config-ui/pages/plugins/jira.jsx
- config-ui/styles/Home.module.css
- config-ui/styles/libraries/blueprint.css
- Add new label setup to all inputs (`<Label>` component now vs a prop). Even on components without a required "`*`", for consistency
- Add required star to new layout setup, of required fields
- Added helper icon functionality. Only one help link right now. Plenty of places we can add more, and build out better docs for specific parts. But its setup now to build on (click `?` link and open docs in new tab). Adding help docs to other fields should be another PR, as we lack docs for a lot of them too.
- Moved env var captions to the right (out of the way) to clear the clutter visually (ex. DB_URL) etc
Closes point 3 on [https://github.com/merico-dev/lake/issues/409](https://github.com/merico-dev/lake/issues/409)
no visual indication of what fields are required, and no way to help the user …
> feat: add new required forms setup and help icons

- .env.example
- cmd/lake-cli/api/client.go
- plugins/compound/compound.go
- plugins/github/github.go
- plugins/github/init.go
- plugins/github/models/github_commit.go
- plugins/github/models/github_pull_request.go
- plugins/github/models/github_repository.go
- plugins/github/tasks/github_api_client.go
- plugins/github/tasks/github_commits_collector.go
- plugins/github/tasks/github_pull_requests_collector.go
- plugins/github/tasks/github_repository_collector.go
- plugins/github/utils/utils.go
- plugins/github/utils/utils_test.go
This PR introduces a new plugin - The GitHub Plugin. 
No. It achieves part of issue #407 
No GitHub plugin.
Collects and saves the following data from GitHub:
- Single Repository
- Commits (for the repository)
- Pull Requests (for the repository)
It uses pagination without the ants package. Ants can be incorporated in future work.
> GitHub plugin

- grafana/dashboards/Gitlab.json
- grafana/dashboards/Jenkins.json
- grafana/dashboards/Jira.json
We need a way for users to experience Grafana if they do not analyze all data sources. For instance, if they just analyze Jira, we can only show a few working charts since a lot of charts rely on multiple data sources to be completed.
I have added three new dashboards:
- Jira
- Gitlab
- Jenkins
Each one is a collection of working charts if you only enable one data source.
To do this, I converted all existing charts to library components so if the original gets updated, they all get updated. You can also now add charts to a dashboard from a library of charts which made this task faster.
1. It seems like I can't upload my Library Panels so others can use them? When @kevin-kline pulled this down, he could not see any panels
https://github.com/merico-dev/lake/issues/408
> feat: domain specific dashboards but not loaded properly

- plugins/domainlayer/README.md
- plugins/domainlayer/domainlayer.go
- plugins/domainlayer/models/base/base.go
- plugins/domainlayer/models/code/commit.go
- plugins/domainlayer/models/code/note.go
- plugins/domainlayer/models/code/pr.go
- plugins/domainlayer/models/code/repo.go
- plugins/domainlayer/models/devops/pipeline.go
- plugins/domainlayer/models/ticket/board.go
- plugins/domainlayer/models/ticket/issue.go
Domain Entity Plugin
All entities are divided into 3 categories:
- `code`: code hosting platforms like github/gitlab
- `devops`: CI/CD platforms like Jenkins/Gitlab pipeline
- `ticket`: project management system like jira/TAPD
This plugin will create all Domain Layer Entities on initialization, and that's all.
Conversion plugins will be implemented separately.
Closes #414
@joncodo @kevin-kline  you may merge it if you thought the overall design is ok and continue your work on this plugin.
> feat: domain layer plugin

- plugins/domainlayer/models/base/base.go
@joncodo @kevin-kline 
I'was working on `jira-domain` plugin, had this `indate` operation problem,  maybe we could set `OriginKey` as PrimaryKey so we could do sth like:
```golang
err = lakeModels.Db.Clauses(clause.OnConflict{
UpdateAll: true,
}).Create(jiraIssue).Error
```
any thought?
> feat: set OriginKey as primary to support indate

- plugins/jenkinsdomain/README.md
- plugins/jiradomain/README.md
Add missing README.md for jiradomain and jenkinsdomain plugins.
> fix: add missing README for jiradomain/jenkinsdomain

- config-ui/.eslintrc.json
- config-ui/components/Sidebar.jsx
- config-ui/jest.config.js
- config-ui/jest.setup.js
- config-ui/package.json
- config-ui/pages/plugins/jira/index.test.js
- config-ui/utils/findStrBetween.js
Add jest and testing-library setup to config-ui
No
No testing setup for components/functions
Now can use this setup to test stuff. Will be useful especially for some of the form parsing functions, which we can do in other PRs
> feat: add jest and testing-library support to config-ui

- config-ui/Dockerfile
- config-ui/package.json
- config-ui/server/package.json
- config-ui/server/server.js
- docker-compose.yml
- Stops using dev mode in config ui (in docker). This will make it a lot faster
- Updated docker image to only use statically built files + a small express server
- Lowered file size of docker image build for config ui
uncompressed ([down from 797MB](https://github.com/merico-dev/lake/issues/458#issue-1009472484))
```
REPOSITORY            TAG       IMAGE ID       CREATED             SIZE
mericodev/config-ui   2         680fea42616c   About an hour ago   122MB
```
compressed is ~250mb to ~50mb
https://github.com/merico-dev/lake/issues/458
https://github.com/merico-dev/lake/issues/456
config-ui was slow because running in dev mode. Also docker image was very large.
config-ui is fast because running in prod mode. Also docker image is much smaller.
Old size compressed
New size compressed
I …
> Next optimize docker prod

- plugins/github/github.go
- plugins/github/tasks/github_api_client.go
- plugins/github/tasks/github_commits_children_collector.go
- plugins/github/tasks/github_commits_collector.go
- plugins/github/tasks/github_issues_collector.go
- plugins/github/tasks/github_pull_request_children_collector.go
- plugins/github/tasks/github_pull_request_comments_collector.go
- plugins/github/tasks/github_pull_request_commits_collector.go
- plugins/github/tasks/github_pull_request_reviewer_collector.go
- plugins/github/utils/utils.go
This work allows us to do a few things differently when it comes to github. The main problem is that their api only allows us 5000 requests/minute.
Because of this, we need to be really careful how many requests we make and how quickly we make them.
- DONE - @Jon Performance - Remove the get total requests and use sequential for next page header
- DONE - @Jon Performance - **Refactor the one network scheduler
- DONE - @Jon Performance set the rate ants rate to (number of tokens*1 = 3600 REQUESTS PER HOUR 
- Remove the non ants requests
> feat: github performance

- config-ui/src/data/NullConnection.js
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useSettingsManager.jsx
- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/pages/configure/connections/EditConnection.jsx
- config-ui/src/pages/configure/integration/manage.jsx
- config-ui/src/pages/configure/mock-data/epics.jsx
- config-ui/src/pages/configure/mock-data/granularities.jsx
- config-ui/src/pages/configure/settings/jira.jsx
- config-ui/src/pages/triggers/index.jsx
> **WIP** DO NOT MERGE
- **JIRA** Supports Multiple Connections
- Jenkins and Gitlab Limited to 1 Connection Only
- Add Connection Functionality LOCKED when limit reached
- Add routine for fetching All Connections
- Add Logic for Connection Limiting
This PR is to continue the **Configuration UI Refactor** with regard to Multi-data connection sources UX. As JIRA is the only provider at this time that supports multi-connection sources, a connection limit feature has been added so that Gitlab and Jenkins will have restricted modes limiting them to only 1 instance.
> Config UI Refactor - Connection Limiting & Integration Bugfixes

- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/pages/configure/connections/GenerateTokenForm.jsx
- config-ui/src/pages/configure/settings/gitlab.jsx
- config-ui/src/styles/common.scss
- config-ui/src/styles/connections.scss
This PR allows the user to **Generate a Basic Auth Token** on-the-fly by providing `Username` (or E-mail) and `Password` while creating or editing the Connection settings for that instance. A Base64 string token is then generated from the two params using **Buffer**.
> #415 Config UI: Add Basic Auth Token Generator

- config-ui/src/App.js
- config-ui/src/components/Sidebar/MenuConfiguration.jsx
- config-ui/src/pages/configure/connections/AddConnection.jsx
This PR changes the default landing page on config UI to "Data Integrations" instead of "Dashboard". The reason is that currently "Dashboard" is no different from "API Configuration" in the list, and is also misleading since it is not really a Dashboard. Furthermore, "Data Integrations" is more relevant to the user for now.
https://github.com/merico-dev/lake/issues/614
> fix: remove dashboard from sidenav

- api/env/env.go
Since we're no longer using GITHUB_AUTH_TOKENS in the .env file (we are now using only GITHUB_AUTH for multi-tokens) we do not need this field to read and write from config.
No.
> fix: removed GITHUB_AUTH_TOKENS which is no longer needed

- api/router.go
- api/task/task.go
- config-ui/src/App.js
- config-ui/src/components/Sidebar/MenuConfiguration.jsx
- config-ui/src/data/defaultTriggerValue.js
- config-ui/src/pages/tasks/index.jsx
- config-ui/src/pages/triggers/index.jsx
- plugins/jira/README.md
- services/task.go
Fixes the UI triggers page to query a new backend route that returns pending tasks. 
https://github.com/merico-dev/lake/issues/612
https://github.com/merico-dev/lake/issues/620
API call to dead route: /api/triggers/pending returns nothing.
API call to /task/pending returns tasks that are in progress.
There was some back and forth discussion on how to achieve our goal for this iteration. In the end, we decided to re-activate the old way the Triggers Page worked.
This PR also contains a preliminary table I created for the "Tasks" page when I thought I was developing a different solution. This code may be useful in the future, so I'm leaving it in the PR. Eventually we probably will want a list of all tasks.
> Kk 620 UI task list

- plugins/domainlayer/models/ticket/issue.go
- plugins/jiradomain/tasks/issue_converter.go
This closes #518 , convert collected jira new fields to domain layer.
Keep in mind you may have to drop and recreate your database due to data schema changed.
Step to verify:
1. Drop `jira_issues` and `issues` table if they have `id` column, because `gorm` doesn't delete column at all.
2. Create a jira data source if none existed: export env-var from `.env` file and run `scripts/pm.sh jira_source_post_full` to create  one.
3. Trigger jira plugin `scripts/pm.sh jira <source_id> <board_id>`
4. Trigger jiradomain plugin `scripts/pm.sh jiradomain <source_id>`
5. All new fields should have values except for `parent_origin_key` because collect issues by board would not fetch any subtask, so every issue we have in our database would not have a `parent`
Closes #518
> feat: convert new fields of jira issue to domainlayer

- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/styles/connections.scss
- Locked for ADD mode
- Locked for MODIFY/Edit Mode
This PR makes Connection Name read-only for single-limit instances such as Jenkins and Gitlab.
#647
Users can set connection name for a Gitlab or Jenkins instance but this isn't a customizable field as yet it should not be modified.
Connection Name is now read-only for Gitlab and Jenkins instances.
> #647 FIX: Set Connection Name as READ-ONLY for Single-Limit Instances

- config-ui/src/components/Sidebar/SidebarMenu.jsx
- plugins/gitlab/api/gitlab_sources.go
On the GitLab settings page, the "Map JIRA Boards to GitLab" field was not reading data from the backend. This PR fixes that issue so it reads and writes to and from the backend.
> fix: jira board gitlab project ui data flow

- grafana/dashboards/GithubDomainLayerOnly.json
- plugins/core/apiclient.go
- plugins/domainlayer/models/code/commit.go
- plugins/github-domain/tasks/commit_converter.go
- plugins/github/README.md
- plugins/github/github.go
- plugins/github/tasks/github_api_client.go
- plugins/github/tasks/github_commits_children_collector.go
- plugins/github/tasks/github_commits_collector.go
- plugins/github/tasks/github_issue_children_collector.go
- plugins/github/tasks/github_issue_comments_collector.go
- plugins/github/tasks/github_issue_events_collector.go
- plugins/github/tasks/github_issue_labels_collector.go
- plugins/github/tasks/github_issues_collector.go
- plugins/github/tasks/github_pull_request_children_collector.go
- plugins/github/tasks/github_pull_request_comments_collector.go
- plugins/github/tasks/github_pull_request_commits_collector.go
- plugins/github/tasks/github_pull_request_reviewer_collector.go
- plugins/github/tasks/github_repository_collector.go
- plugins/github/tasks/github_single_commit_collector.go
- plugins/github/tasks/github_single_pull_request_collector.go
- plugins/github/utils/utils.go
- plugins/gitlab/tasks/gitlab_api_client.go
- plugins/jira/tasks/jira_api_client.go
https://merico.feishu.cn/docs/doccn6ZyxRzUgKMFXzWTwzcWH7f#
https://github.com/merico-dev/lake/issues/432
https://github.com/merico-dev/lake/issues/501
https://github.com/merico-dev/lake/issues/470
https://github.com/merico-dev/lake/issues/437
NOTE: continuation of PR: #585 
So this allows us to pull all of the pieces together for github and the domain layer.
I made a new dashboard that shows this data:
This is for our lake repo.
In each of the queries, we are using domain layer models and not the github models.
> Github Domain layer only

- config-ui/src/pages/configure/settings/jira.jsx
This PR reverts selectors on the JIRA settings page to TEXT Inputs for `ITER3` or until after BE implements data endpoints to drive the selectors.
#640, #606
> #640 FIX: Regress JIRA Settings - Convert Selectors to TEXT Input Fields (for now)

- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- `Endpoint`
- `BasicAuthEncoded`
This PR resolves the incorrectly named request parameters when a JIRA connection is saved.
> #654: Fix JIRA Add Connection Request Payload

- config-ui/src/pages/configure/connections/ConnectionForm.jsx
In Config-UI, GitLab configuration had some incorrect placeholder text. In addition, it displayed the token generator button for Jira. The latter has been removed, and the placeholder text fixed by creating a conditional statement between plugins (if Jira, then example A text).
#651
> Config-UI: GitLab placeholder text fix and remove token gen button 

- config-ui/src/pages/configure/integration/manage.jsx
- Clicking this cell will NOT Route to MODIFY Page
- User can highlight ID # to copy and paste on triggers page
This PR updates the Connection Management Table for JIRA Provider so that the Connection's Source ID / `sourceID` is visible to the user. In order to trigger collection this ID will be needed for the JSON Options payload. This is only a workaround solution until the Triggers Page is re-designed, and the Collect table row action(s) are restored on the management table.
#677 
User has no way of determining connection Source ID other than URL Bar inspection or by snooping the JSON API Response from Lake.
User can clearly see **Connection Source ID**, along with a tooltip that instructs them this ID should be used on the Triggers page.
> #677 Config UI: JIRA Connections Management - Show Connection Source ID

- config-ui/src/pages/configure/settings/jira.jsx
These fields now read/write to backend from Jira Settings in Config-UI:
- Epic Key
- Requirement Granularity
- Board Id
No.
These fields don't read/write.
Now they do.
> fix: config-ui jira settings read/write to db

- .env.example
- plugins/jira/README-zh-CN.md
- plugins/jira/README.md
This PR does 3 things:
1. Remove jira configurations from `.env.example` to avoid user confusion
2. Replace .env with config UI for jira English readme
3. Replace .env with config UI for jira Chinese readme
However, the readmes still need more polishment. I only had time to do some basic cleaning.
> Update .env.example and Jira plugin readme

- grafana/provisioning/datasources/datasource.yml
After I collected data under dev mode, I noticed that Grafana dashboard can't connect to mySQL database. I had to edit the datasource setting in grafana to make it work. Seems like it's due to us removing hostname in `docker-compose.yml` file.
fixes https://github.com/merico-dev/lake/issues/685
> fix: change mysqldb to mysql to allow grafana to connect to mysql

- Makefile
When I tried to set up config-ui with `make configure-dev`, I noticed the command hasn't been updated for the new config-ui setup. This PR simply updates that command.
> fix: update command configure-dev in Makefile

- plugins/jira/jira.go
- plugins/jira/tasks/jira_api_client.go
- plugins/jira/tasks/jira_sprint_collector.go
- plugins/jira/tasks/jira_user_collector.go
Closes #665 
We assumed all APIs accept 100 as maximal value for `maxResults` parameter, which is not true.
API like `agile sprints` is configurable, and it was 50 on our instance.
So use a fixed value like 100 to increase our `startAt` parameter is unreliable, and causing some sprints were missed out during collection.
This PR fix this issue by updating the `maxResults` value dynamically base on the `length` we actually received, and use this value  to increase `startAt` parameter.
Closes #665
> fix: jira sprint collection incompleteness

- api/router.go
- plugins/jira/README.md
- plugins/jira/api/jira_proxy.go
- plugins/jira/jira.go
Forward HTTP requests to Jira server
Forward HTTP requests to Jira server
https://github.com/merico-dev/lake/issues/499
Requests with path`/plugins/jira/sources/:sourceId/proxy/*path` would route to `api.Proxy` handler
for example:
Request to http://your_devlake_host/plugins/jira/sources/1/proxy/rest/agile/1.0/board/8/sprint
would forward to
https://your_jira_host/rest/agile/1.0/board/8/sprint
> feat: jira api forwarding

- config-ui/src/data/Providers.js
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/pages/plugins/gitlab/index.jsx
- config-ui/src/pages/plugins/jenkins/index.jsx
- config-ui/src/pages/plugins/jira/ClearButton.jsx
- config-ui/src/pages/plugins/jira/MappingTag.jsx
- config-ui/src/pages/plugins/jira/MappingTagStatus.jsx
- config-ui/src/pages/plugins/jira/index.jsx
- plugins/github/api/github_sources.go
- plugins/github/github.go
- plugins/gitlab/gitlab.go
Fixes: 
TODO - 2.5. Github api routes in plugin layer for sources @Kevin @jon
This allows github to be fully hooked up in config ui.
Routes added:
```
func (plugin Github) ApiResources() map[string]map[string]core.ApiResourceHandler {
return map[string]map[string]core.ApiResourceHandler{
"sources": {
"GET":  api.ListSources,
"POST": api.PutSource,
},
"sources/:sourceId": {
"GET": api.GetSource,
"PUT": api.PutSource,
},
}
}
```
> feat: all api routes hooked up and tested

- .env.example
- README.md
- config-ui/Dockerfile
- config-ui/nginx.conf
- config-ui/src/components/Sidebar.jsx
- config-ui/src/utils/config.js
- docker-compose.yml
Closes #708 
This PR make nginx proxies `/api` to $DEVLAKE_ENDPOINT and redirects `/grafana` to $GRAFANA_ENDPOINT which then can support Cloud deployment like TeamCode
> feat: nginx api forwarding / grafana redirection

- plugins/domainlayer/models/ticket/issue.go
- plugins/github-domain/tasks/issue_converter.go
- plugins/github/models/github_issue.go
- plugins/github/tasks/github_issues_collector.go
- plugins/jira/models/jira_issue.go
- plugins/jira/tasks/jira_issue_enricher.go
- plugins/jiradomain/tasks/issue_converter.go
This PR names the Domain Layer Issue Lead Time to LeadTImeMinutes. It also renames the Jira Issue LeadTime to LeadTimeMinutes (as is accurate). Thirdly, it changes the GitHub conversion from seconds to minutes to conform to this standard.
https://github.com/merico-dev/lake/issues/733
> fix: standardize issue lead time to minutes

- grafana/dashboards/HowFastDoWeRespondToCustomerRequirements.json
- grafana/dashboards/IsThisMonthMoreProductiveThanLast.json
- grafana/dashboards/WasOurQualityImprovedOrNot.json
Updates grafana charts for Jira...mainly fixes "How fast do we respond to customer requirements?" to pull lead_time_minutes instead of lead_time (which is deprecated)
> fix: update grafana charts

- Makefile
- config-ui/src/pages/configure/settings/github.jsx
- config/config.go
- docker-compose.yml
- plugins/github/api/github_sources.go
- plugins/plugins.go
- test/plugins/plugins_test.go
This is a must in mainland china
Also fix the .env file not found error from TeamCode deployment
1. `devalke` service ditch `env_file` altogether, since it's the highest priority in `viper`, thus, even thoug settings  got saved into `.env` file, when reopen `config-ui`, all settings on page went back to old values, unless we restart devlake
2. removed unused settings of `config-ui` service to avoid confusion
3. simplify configuration loading logic
> feat: config-ui supports set GITHUB_PROXY

- config-ui/config.js
Update grafana link to `Demo Homepage` dashboard
before:
after:
> fix: update grafana link to demo-homepage

- config-ui/webpack.config.js
Update the `devServer` Configuration for Webpack and change the `localhost` reference to compressed format `[::1]`
#771
When pulling `main` branch OSX users are unable to fetch data from `/api` because the devServer proxy fails to work as configured resulting in network 404s.
Using the compressed format for localhost this should be more compatible with more environments including OSX so developers don't have to apply a patch to the configuration in order to reach `DEVLAKE_ENDPOINT`
> fix: #771 use compressed format ipv6 loopback address

- README.md
This PR attempts to address some of my concerns with the setup flow in the README. The primary concern is in the Dev Setup, there is no reference to the Config-UI, and no guidance on how to configure plugins. This PR adds the config UI setup steps to the Dev Setup, and gives stronger reference to the links that take the user to the Plugin Configuration docs which have a lot of information they need to get the setup right.
No.
> docs: update README for setup

- README.md
1. add shortcuts to 'set up Dev Lake' in the main readme
2. make the Dev Lake intro section consistent with the intro used elsewhere
3.  replace the 'dev lake user flow' screenshot
> feat: add shortcuts to setup in main readme

- config-ui/src/components/actions/DeleteAction.jsx
- config-ui/src/components/actions/DeleteConfirmationMessage.jsx
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/integration/index.jsx
- config-ui/src/pages/configure/integration/manage.jsx
- config-ui/src/styles/connections.scss
- config-ui/src/utils/request.js
This PR adds support for deleting connections for providers that are flagged as "Multi-source", primarily **JIRA** at this moment. Single-source providers such as GitHub and Jenkins are unaffected by this change.
#619
Users can add multiple connections for **JIRA** but are unable to remove them.
Users are able to **DELETE** a connection added to a multi-source provider such as **JIRA**.
> fix: #619 Config-UI - Setup Delete Connection UX Workflow

- plugins/core/iso8601time.go
- plugins/core/iso8601time_test.go
- plugins/domainlayer/models/ticket/issue.go
- plugins/github/models/github_issue.go
- plugins/github/tasks/github_issues_collector.go
- plugins/jira/models/jira_issue.go
- plugins/jira/tasks/jira_issue_collector.go
- plugins/jira/tasks/jira_issue_enricher.go
- plugins/jira/tasks/jira_project_collector.go
- plugins/jira/tasks/jira_sprint_collector.go
- plugins/jira/tasks/jira_user_collector.go
A long overdue refactor.
1. type assertion are error prone and hard to debug, replaced with
`mapstructure.Decode` which is easy to understand and maintain.
2. replace `sql.NullTime` with `*time.Time` for maintainability.
3. unify struct naming to help distinguish Api structs and Db structs
Closes #563
> Refactor: remove type assertion from jira issue collector

- plugins/core/apiclient.go
- plugins/core/apiclient_test.go
- plugins/github/tasks/github_api_client.go
- plugins/github/tasks/github_commits_collector.go
- plugins/github/tasks/github_issue_comments_collector.go
- plugins/github/tasks/github_issue_events_collector.go
- plugins/github/tasks/github_issue_labels_collector.go
- plugins/github/tasks/github_issues_collector.go
- plugins/github/tasks/github_pull_request_comments_collector.go
- plugins/github/tasks/github_pull_request_commits_collector.go
- plugins/github/tasks/github_pull_request_reviewer_collector.go
- plugins/github/tasks/github_single_pull_request_collector.go
- plugins/gitlab/gitlab.go
- plugins/gitlab/tasks/gitlab_api_client.go
- plugins/gitlab/tasks/gitlab_commit_collector.go
- plugins/gitlab/tasks/gitlab_merge_request_collector.go
- plugins/gitlab/tasks/gitlab_merge_request_commits.go
- plugins/gitlab/tasks/gitlab_merge_request_note.go
- plugins/gitlab/tasks/gitlab_pipeline_collector.go
This PR replaces our old method of putting together query strings with a more robust way that is less error prone. Now we are using the net/url package to resolve any inconsistencies for example with '/' at the end of the string or no '/'. This PR also includes:
- Unit testing for URI formatting
- GitHub plugin refactor to pass query params separate from relative path string
- GitLab plugin refactor for the same as GitHub
https://github.com/merico-dev/lake/issues/804
> Handle url query strings with net/url package

- plugins/core/apiclient_test.go
- plugins/jira/jira.go
- plugins/jira/tasks/jira_board_collector.go
- plugins/jira/tasks/jira_changelog_collector.go
- plugins/jira/tasks/jira_issue_collector.go
- plugins/jira/tasks/jira_project_collector.go
- plugins/jira/tasks/jira_sprint_collector.go
- plugins/jira/tasks/jira_user_collector.go
Due to recent changes with how our api client builds request URLs, we need to be conscious of supplying these distinct categories to the "Get" or "Do" method:
- baseUrl
- relativeUrl
- queryParams
Using Golang's net/url package, we can handle these three very well and very consistently. However, implementing this in #829 made our Jira collectors fail due to this problem: we stored part of the **relative path** in the DB as part of the **base url** as such: ```merico.atlassian.net/rest```
We cannot put "/rest" in the DB and still be compatible with the way the api client builds URLs. We need to store ONLY the base URL as ```merico.atlassian.net``` in the DB in the future, and add "/rest" instead to the **relative path** that the plugin supplies to the Fetch methods.
**Bottom Line** - If …
> fix: jira - add /rest to relative paths ***IMPORTANT FIX - PLEASE READ***

- config-ui/src/data/Providers.js
- plugins/core/apiclient.go
- plugins/core/apiclient_test.go
- plugins/jira/tasks/jira_board_collector.go
- plugins/jira/tasks/jira_changelog_collector.go
- plugins/jira/tasks/jira_issue_collector.go
- plugins/jira/tasks/jira_project_collector.go
- plugins/jira/tasks/jira_sprint_collector.go
- plugins/jira/tasks/jira_user_collector.go
This PR adds a method which allows ApiClient to handle base URLs with or without '/' at the end. It also adds unit tests to prove functionality. This means it is now OK to store endpoint URLs in the DB with or without relative paths attached (for example: ```mysite.com/rest``` or ```mysite.com``` are acceptable.
**Bottom Line** this reverts some changes to Jira plugin where ```rest/``` was added to relative paths. It is now fine to go back to the way we had it by storing ```/rest``` in the DB as the Jira endpoint. In fact, we will need ```/rest``` in the DB for Jira to work.
related to #834 
related to #829 
completes #804 
If endpoint (from .env or DB) does not end with '/' then whatever is written after the last '/' will be removed from the endpoint. 
If endpoint does not end with '/' …
> fix: handle / or no / on baseUrl

- config-ui/package-lock.json
- config-ui/package.json
- config-ui/src/data/availablePlugins.js
- config-ui/src/data/collectionDefaults.js
- config-ui/src/pages/triggers/index.jsx
- config-ui/src/utils/sourcesUtil.js
- config-ui/src/utils/triggersUtil.js
- config-ui/test/json.js
- config-ui/test/testData.js
This PR creates Utils that allow us to get example request body JSON ready to display to the user or send to the /task API based on an array of plugin names. For example, send "jira" and receive:
```
[[{
Plugin: "jira",
Options: {...}
}, {
Plugin: "jiradomain",
Options: {...}
}]]
```
This is a pretty flexible solution for customizing JSON for the user. It also implents:
- unit tests
- Util function for getting sources from the backend to tell us which plugins have existing connections
- Triggers Page updates sample JSON based on plugins with existing connections
closes #774 
Single hard-coded value for sample JSON on Triggers Page.
Dynamic updates for sample JSON on Triggers Page based on which plugins have active source data from the backend.
> feat: dynamic JSON for triggers page

- scripts/compile-plugins.sh
Fixes: https://github.com/merico-dev/lake/issues/487
On my computer, it takes me a long time to compile all plugins. I need a faster way to develop. Most times I only work in one plugin at a time and the re-comilation takes up too much of my day.
Everything will work as before here. All you have to do is run `make dev`
However, if you are only working in one plugin, you can now update this line in `scripts/compile-plugins.sh`
`PLUGIN_TO_COMPILE=all` for all plugins as before
`PLUGIN_TO_COMPILE=github` for only github
> feat: only compile the plugins you want

- scripts/compile-plugins.sh
This changes how you run the make dev command. 
If you want to use this, you need to run `PLUGIN=github make dev`
to compile all plugins `make dev`
> feat: change usage format

- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/pages/configure/integration/manage.jsx
- plugins/core/apiclient.go
- plugins/core/apiclient_test.go
- plugins/core/testConnection.go
- plugins/github/api/github_connection.go
- plugins/github/github.go
- plugins/github/tasks/github_api_client.go
- plugins/gitlab/api/gitlab_connections.go
- plugins/gitlab/gitlab.go
- plugins/gitlab/tasks/gitlab_api_client.go
- plugins/jenkins/api/jenkins_connections.go
- plugins/jenkins/jenkins.go
- plugins/jenkins/tasks/storage.go
- plugins/jira/api/jira_connections.go
- plugins/jira/api/jira_sources.go
- plugins/jira/jira.go
- utils/token.go
Fixes https://github.com/merico-dev/lake/issues/667
So the first question here is: "Do we make it mandatory to include a /test route?"
1. Yes since every plugin needs it
2. No, just allow it to be added or not. Since the front end can still call this route and if a 404 comes back, the UI just disables the test connection button and gives a message to the user that says "Not implemented, please contact the plugin maintainer"
Can we enforce the plugin maintainer to make this route?
No. Since they can just write a route that always returns true to bypass this rule.
So I have decided that the only thing we need to do for this ticket is to simply add 
```
func (plugin Github) ApiResources() map[string]map[string]core.ApiResourceHandler {
return map[string]map[string]core.ApiResourceHandler{ …
```
> feat: test connection

- grafana/dashboards/Gitlab.json
One chart in GitLab's grafana dashboard was broken. This PR fixes it by removing the line:
merged_at != ''
Because merged_at is a datetime type, not string.
> fix: gitlab dashboard 80th percentile metric

- grafana/dashboards/Jira.json
Jira dashboard was broken because of some incorrect names in SQL queries. This replacement JSON fixes them.
lead_time => lead_time_minutes
id => issue_id
Closes https://github.com/merico-dev/lake/issues/887
Screenshots:
> fix: jira dashboard

- Makefile
`make configure-dev` needs to run `npm install` first before `npm start`.
> fix: add npm install to make configure-dev

- plugins/github/models/github_issue_label_issue.go
- plugins/github/models/github_pull_request_commit_pull_request.go
- plugins/gitlab/models/gitlab_merge_request_commit_merge_request.go
The issue raised in #916 is due to the fact that GORM updates records on conflict, but because the models in question were not declared as composite primary keys, there was no conflict, hence it defaulted to Create new records, causing duplicates. Changing ```gorm:"index"``` to ```gorm:"primaryKey"``` on the necessary columns causes the conflict, thus no longer creates duplicates. I've tested this out and believe that it solves the issue.
Closes #916 
Duplicate records are stored on 3 tables because of their model definition.
No more duplicate records are stored on these tables.
After consecutive collections:
This shows there are no duplicate records with the same two "id" fields:
This shows the example row in the issue #916 has only one row:
Thanks to @likyh for raising the issue.
> fix: duplicate data fix gitlab / github

- config-ui/Dockerfile
- config-ui/nginx.conf
- config-ui/src/hooks/useNetworkOfflineMode.jsx
- docker-compose.yml
`wait` will block nginx, so user wont be able to open `config-ui`,
thus, user may never see the `/offline` page at all. this fixes the
problem by removing the `wait` and make nginx be able to start even
`devlake` is not ready.
I have already push the latest build to dockhub. so you can verify it by:
1. chage `config-ui` image tag to latest and remove `depends_on` devlake part for `docker-compose.yml`,
2. stop all by `docker-compose down` and launch `config-ui` only by `docker-compose up -d config-ui`
3. open `config-ui` on browser, config-ui should pop up, and click into plugin, wait a few seconds `offline` page should be pop up
4. better to show `offline` page even if user didn't do anything, we can do this on next iter if @e2corporation think this is a good idea.
> fix: remove `wait` so offline page can show its charm

- scripts/compile-plugins.sh
Fixes https://github.com/merico-dev/lake/issues/883
This simply allows users to run `make dev` and clear out old binaries. 
This solves the problem where a user built binaries on a plugin before such as `jiradomain` and now that plugin no longer exists.
This is safe to always run
> feat: remove old binaries when running make dev

- plugins/gitlab/models/gitlab_merge_request_commit.go
- plugins/gitlab/tasks/gitlab_merge_request_commits.go
Just removes unneeded columns from DB model, since we don't get Additions/Deletions from GitLab API on Merge Request _Commits_
Closes https://github.com/merico-dev/lake/issues/866
> chore: rm extra columns on mrCommits

- plugins/core/apiclient.go
- plugins/jira/tasks/jira_api_client.go
To provide more specific message for jira api request authentication failure
jira plugin now report specific msg for unauthorized error instead of msg like #868
Related to #868 , Closes #878
authentication failure would exhibition message like #868 
Show authentication fail message for http status 404 from jira api server
> fix: more specific error msg for unauthorized

- .github/workflows/test-e2e.yml
- api/push/README.md
- config-ui/src/pages/triggers/index.jsx
- models/domainlayer/README.md
- models/domainlayer/devops/build.go
- models/domainlayer/didgen/domain_id_generator.go
- models/domainlayer/didgen/domain_id_generator_test.go
- models/domainlayer/domainlayer.go
- models/domainlayer/ticket/changelog.go
- models/domainlayer/ticket/issue.go
- models/domainlayer/ticket/sprint.go
- models/domainlayer/ticket/worklog.go
- plugins/github/tasks/github_commit_converter.go
- plugins/github/tasks/github_issue_converter.go
- plugins/github/tasks/github_note_converter.go
- plugins/github/tasks/github_pull_request_converter.go
- plugins/github/tasks/github_repo_converter.go
- plugins/gitlab/tasks/gitlab_commits_converter.go
- plugins/gitlab/tasks/gitlab_note_converter.go
- plugins/gitlab/tasks/gitlab_pr_converter.go
- plugins/gitlab/tasks/gitlab_repo_converter.go
- plugins/jenkins/tasks/buildconverter.go
- plugins/jenkins/tasks/jobconverter.go
- plugins/jira/tasks/jira_board_converter.go
- plugins/jira/tasks/jira_changelog_converter.go
- plugins/jira/tasks/jira_issue_collector.go
- plugins/jira/tasks/jira_issue_converter.go
- plugins/jira/tasks/jira_sprint_converter.go
- plugins/jira/tasks/jira_user_converter.go
- plugins/jira/tasks/jira_worklog_converter.go
Renamed `OriginKey` to `Id`
Fixed "Trigger Collection" button stop working from Triggers page 
Renamed tasks filenames with plugin prefix for all plugins
Keep in mind this primary key changing will break existing user database.
We have two solutions for this change:
1. ask existing users to drop all domain layer tables like we always did.
2. implement DB Migration feature, and make sure db got migrated autmatically.
Closes #945
> Rename `originkey` to `id`

- MIGRATIONS.md
- Makefile
- db/migration/000001_init_schema.down.sql
- db/migration/000001_init_schema.up.sql
- db/migration/000002_init_tables.down.sql
- db/migration/000002_init_tables.up.sql
Related Ticket: https://github.com/merico-dev/lake/issues/806
Ready for review @kevin-kline @hezyin @klesh @mindlesscloud 
So this uses a new tool locally called `golang-migrate`. 
It seems to work well. You can see many more details in the readme of this pull request.
There is a new table in the DB created by golang-migrate
This table maintains the version you are on. To use this, you need to install it locally with brew or other tools. It is not able to be part of `go get`
You can install here: https://github.com/golang-migrate/migrate/blob/5bf05dc3236ef077e5927c9ca9ca02857a87c582/cmd/migrate/README.md
This pull request also contains some sample migrations
> feat: migrations with golang-migrate

- .env.example
- README.md
- docker-compose.yml
Implements #971 
The actual implementation differs slightly from what was proposed. In order to keep the user setup as easy as possible, the `COMPOSE_PROFILES` env variable has been added to `.env` and is set to `user`. This makes it that no change to the user setup is necessary. The readme instructs developers to switch the profile by changing this variable to `dev`.
> feat: adds compose profiles

- plugins/ae/ae.go
- plugins/ae/tasks/ae_api_client.go
- plugins/ae/tasks/ae_commit_collector.go
- plugins/ae/tasks/ae_commit_converter.go
- plugins/ae/tasks/ae_project_collector.go
- plugins/core/apiclient.go
- plugins/core/errors.go
- utils/worker_scheduler.go
Make ae plugin supports canceling, both collector and converter.
The idea is simple:
1. make `api client` supports cancel, so before/after each request, task can be canceled right away as long as `ctx.Context` got passed into `api client` by `SetContext` method correctly.
2. add `cancel checking` in the begining of each loop, so conversion task can be canceled.
> feat: ae supports canceling

- plugins/jira/jira.go
- plugins/jira/models/jira_issue.go
- plugins/jira/models/jira_issue_commit.go
- plugins/jira/models/jira_remotelink.go
- plugins/jira/models/jira_source.go
- plugins/jira/tasks/jira_changelog_collector.go
- plugins/jira/tasks/jira_issue_enricher.go
- plugins/jira/tasks/jira_remotelink_collector.go
- plugins/jira/tasks/jira_remotelink_enricher.go
1. jira issue remotelinks collection
2. create jira issue / git commit sha relationship based on remotelink url pattern
Lately, we received some usabiltiy issues:
1. User have to recollect all data if they set a wrong value for customfield, #575 
2. Conversion takes so long if table was too big
By developing this feature, I also try to solve these issues:
1. Collection stage store only primary key and `RawJson`, and extract needed field on Enrichment stage. So, for customfield, users don't have to recollection if they set it wrong. This is similar to previous js POC implementation.
2. Adopt `Pre Allocated Array` and `Batch Insert` for Conversion tasks which introduced by @mindlesscloud , this technique reduced conversion time dramatically.
I would like everybody @mindlesscloud  @hezyin …
> Jira issue commits relationship

- go.mod
- go.sum
There should be two `require` directives only: one for direct dependencies, and another one for indirect dependencies. To maintain consistency, it is best to tidy them nicely.
N/A
The current `go.mod` file has 4 `require` directives. At Go 1.17 or higher, it is only necessary to have two `require` directives to enable the [module graph pruning](https://go.dev/ref/mod#graph-pruning).
`go.mod` file only has two `require` directives, with direct and indirect dependencies separated.
N/A
N/A
> style: tidy `go.mod` correctly

- .github/workflows/build.yml
- config-ui/Dockerfile
- docker-compose.yml
Auto build and push docker image to docker hub when push a tag to this repository.
#433 
Should add `DOCKER_REGISTRY_USERNAME` and `DOCKER_REGISTRY_PASSWORD` to secrets.
> chore: auto release to docker hub

- config-ui/package-lock.json
- config-ui/package.json
- config-ui/src/App.js
- config-ui/src/components/pipelines/CodeInspector.jsx
- config-ui/src/components/pipelines/ProviderSettings.jsx
- config-ui/src/components/pipelines/StagePanel.jsx
- config-ui/src/components/pipelines/TaskActivity.jsx
- config-ui/src/data/NullPipelineTask.js
- config-ui/src/hooks/usePipelineManager.jsx
- config-ui/src/pages/pipelines/activity.jsx
- config-ui/src/pages/pipelines/create.jsx
- config-ui/src/pages/triggers/index.jsx
- config-ui/src/styles/pipelines.scss
- config-ui/src/utils/time.js
- Polling _Disabled_ for `Completed` and `Failed` tasks.
- Pipeline Name
- Run Date
- Duration
- Progress
- Show Task Name
- Show Task Duration
- Show Task Progress
This PR adds support for monitoring **Pipeline Activity**. After creating a new **Pipeline Run**, users will be guided to the activity screen to monitor the collection process. This page will provide users with all the relevant stage and task activity along with control actions to **CANCEL** `Running` and **RESTART** `Failed` and `Completed` pipelines.
As our Create Pipeline UX flow only supports **ONE** (1) Stage lane at this time, not all features to support multiple stages will be applied at this time. Basic Stage rendering logic has been added, however, and if a Pipeline were to be issued using the Triggers page or via …
> `feat` #965 pipelines: show pipeline activity & details

- config-ui/src/pages/pipelines/activity.jsx
- config-ui/src/pages/pipelines/index.jsx
This Hotfix PR resolves an inaccurate Pagination display counts due when the filtered result set contains 0 records, along with required improvements to pagination slicing with respect to start and end offsets. Max-page detection has also been corrected.
#1044
> `Hotfix` manage pipelines : fix pagination displayed count & range

- config-ui/src/pages/configure/settings/jira.jsx
- config-ui/src/pages/configure/settings/jira/MappingTag.jsx
- config-ui/src/styles/app.scss
- config-ui/src/styles/content.scss
- config-ui/src/styles/theme.scss
Changes label colors to:
Success = Green
Warning = Orange
Danger = Red
Closes https://github.com/merico-dev/lake/issues/797
Without refactoring, this is the quickest way to achieve the result. The coupling is due to the reliance on blueprintJS concept of "labelIntent". Otherwise I would've just added new colours.
I realize this will change these defaults in other areas. That's up to the team to decide if it's OK design wise.
@joncodo @e2corporation @Startrekzky
> fix: label color change

- config-ui/src/components/pipelines/ProviderSettings.jsx
- config-ui/src/hooks/usePipelineValidation.jsx
- config-ui/src/pages/configure/settings/jira/MappingTag.jsx
- config-ui/src/pages/pipelines/create.jsx
- config-ui/src/pages/pipelines/index.jsx
- config-ui/src/styles/common.scss
This PR adds multi-tag selector support on the Create Pipeline form that allows users to enter one or more GitLab Projects and JIRA Boards. All Tasks will belong to the default stage, Stage One.
#987
Users can only enter ONE (1) Gitlab Project ID or JIRA Board ID when Creating a Pipeline.
Users can now enter many Project IDs and Board IDs for Gitlab and JIRA.
> feat: create pipelines - use multi-tag selector for gitlab projects and jira boards | `987`

- config-ui/src/pages/configure/settings/jira/MappingTag.jsx
This PR performs a small usability enhancement to the JIRA Settings Issue Type Selectors, allowing entries to be added `onBlur` in case the user forgets to press `ENTER` key.
#1078
> `feat` jira settings : add jira issue tag selector entries on blur | `1078`

- plugins/jira/tasks/jira_issue_collector.go
use "lakeModels.Db.Clauses(...).Create(...)" to fix concurrency problems
issue #1067
close issue #1067 
method 'lakeModels.Db.FirstOrCreate(...)' caused concurrency problems
lakeModels.Db.Clauses(...).Create(...) fixed the problems above
> fix(db): changed method to insert jira-sprint-issue

- config-ui/src/hooks/useConnectionManager.jsx
- plugins/core/testConnection.go
- plugins/github/api/github_connection.go
- plugins/github/github.go
- plugins/gitlab/api/gitlab_connections.go
- plugins/gitlab/gitlab.go
- plugins/jenkins/api/jenkins_connections.go
- plugins/jenkins/jenkins.go
- plugins/jira/api/jira_connections.go
- plugins/jira/jira.go
Changed previous GET method which used to do test connection into POST method for all plugins in order to hide auth info in log
This will close issue #1066 
Used GET method to do test connections, this exposed auth info in log 
Changed to POST method for all plugins, then no auth info will be showed in log
@e2corporation I changed request method of testConnection() in useConnectionManager.jsx, I used a connectionPayload to store infos, and passed it into POST method, could you spare a moment to review the code, thanks.
> Refactor hide authinfo in log

- .env.example
- models/domainlayer/code/pull_request.go
- plugins/github/github.go
- plugins/github/models/github_issue_label.go
- plugins/github/models/github_pull_request.go
- plugins/github/tasks/github_issue_labels_collector.go
- plugins/github/tasks/github_issues_enrichment.go
- plugins/github/tasks/github_pull_request_converter.go
- plugins/github/tasks/github_pull_request_enricher.go
- plugins/github/tasks/github_pull_request_labels_collector.go
Users can config regular expression for PR_TYPE and PR_COMPONENT
And the github plugin will enrich pull requests with labels which meet the expression configured
type and component have been enriched:
will close issue #951
> feat(plugins-github): enrich pull request with labels

- plugins/jira/jira.go
- plugins/jira/tasks/jira_issue_commit_converter.go
- plugins/jira/tasks/jira_remotelink_collector.go
- plugins/jira/tasks/jira_remotelink_enricher.go
To fix problem: remotelinks/issue_commits still exist in devlake database even if they got removed on jira platform
> fix: clean up previous collected/converted data for jira

- plugins/refdiff/refdiff.go
> fix: ref names of refs_commits_diffs are missing prefix

- models/init.go
fix the "too many connections" error by setting up a connection pool
> fix: fix too many connections

- models/domainlayer/code/refs_commits_diff.go
- plugins/refdiff/refdiff.go
to `new/old_ref_commit_sha` to help user understandard their meaning
better, according to @Startrekzky
> refactor: rename `new/old_commit_sha`

- models/domainlayer/ticket/issue.go
remove column `owner_id` from table `issues`
> refactor: remove issues.owner_id

- plugins/github/tasks/github_repo_converter.go
added org as prefix to github repo name when converted to domain layer `repo`
> fix: added org as prefix to github repo name

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/refactor.md
1. update issue templates so that labels can be automatically tagged after creation
2. add a template for the `refactor`-type of issues, the `proposal`-type of issues will only refer to feature-request in the future. 
No
> docs: update issue templates

- plugins/gitlab/tasks/gitlab_note_converter.go
By mistaken, previously passed a value to the didgen.NewDomainIdGenerator func
Now prepend "&" on gitlabModels.GitlabMergeRequestNote{} in gitlab_note_converter.go
Closes issue #1182 
> fix(plugins): pass pointer instead value

- plugins/refdiff/README.md
This doc update fixes the instructions for how to install for the refdiff plugin. It also adds notes on fixing an error I encountered in this process.
> docs: fixed instructions for updated installation

- config-ui/src/components/ClearButton.jsx
- config-ui/src/hooks/useJIRA.jsx
- config-ui/src/pages/configure/mock-data/jira/fields.js
- config-ui/src/pages/configure/mock-data/jira/issueTypes.js
- config-ui/src/pages/configure/settings/jira.jsx
- config-ui/src/styles/libraries/blueprint.scss
- Requirement Tags
- Bug Tags
- Incident Tags
This PR adds usability improvements to JIRA settings by converting the multi-tag input widgets to Multiselect widgets for **JIRA's Issue Type Mappings**. This will allow the user to select tags from a predefined list using the JIRA API Proxy, rather than manual entry. The list options for Issue Type Mappings will be provided by the available list of `Issue Types`, whereas the options for Epic Key and Story Points will be provided by `Custom Fields`. 
It is expected that the JIRA Source Connection is properly working with a valid Authentication Token and a successful Connection Test.
**Additional Notes and Constraints**
- **Epic** and **Story Point** fields may not have the same value.
- For _New_ or _Invalid_ JIRA Connection Sources (ie bad …
> `feat`: setup multi-selectors for jira issue types w/ api proxy | `1064`

- errors/sub_task_error.go
- models/task.go
- plugins/github/github.go
- plugins/gitlab/gitlab.go
- plugins/gitlab/tasks/gitlab_pipeline_collector.go
- plugins/jenkins/jenkins.go
- plugins/jira/jira.go
- services/task.go
To improve pipeline debugging experience, this change will indicate which sub task failed
1. added an extra field(failed_sub_task) in table.tasks
2. let all plugin.execute return SubTaskError if sub task failed
3. in services/task.RunTask, check if error is SubTaskError
###Todo
let other plugins.execute to return SubTaskError
closes #1050
> refactor(domain layer,plugins): indicate which sub task failed

- go.mod
- go.sum
- plugins/gitextractor/README-zh-CN.md
- plugins/gitextractor/README.md
- plugins/gitextractor/gitextractor.go
- plugins/gitextractor/main.go
- plugins/gitextractor/models/interface.go
- plugins/gitextractor/parser/clone.go
- plugins/gitextractor/parser/libgit2.go
git extractor support private repository
By providing `user` and `password`, we can clone a private repository using HTTP(S).
By providing `privateKey` and `passphrase`(if any), we can clone a private repository using SSH.
#1187
> feat: git extractor support private repo

- plugins/refdiff/refdiff.go
Fix problem mention via PR #1189
> fix: refdiff rook_pkg_path typo

- plugins/gitextractor/README.md
> docs: fix typo for `gitextractor` plugin

- plugins/refdiff/refdiff.go
When calculating progress, use index + 1 to calculate as below: 
progress <- float32((i + 1) / lenCommitPairs);
set the initial progress to 0.00;
otherwise, 1% will appear first, then 0%
> fix(refdiff): fix progress

- .env.example
- plugins/core/plugin_utils.go
- plugins/jira/api/jira_sources.go
- plugins/jira/models/jira_source.go
- plugins/jira/tasks/jira_api_client.go
use hooks to handle encryption and decryption
Add BeforeSave and AfterSave hooks to handle the process of Jira sensitive information being stored in the database
Add AfterFind to handle the process of Jira sensitive information read from the database
When the decryption of sensitive information in Jira fails, it no longer returns an error, but prints the log and blanks the sensitive information
> fix: use hooks to handle encryption and decryption

- Makefile
- README-zh-CN.md
- README.md
- plugins/gitextractor/README.md
- plugins/refdiff/README.md
1. libgit2 installation should be placed before go pkg installation
2. fix command that to bring up mysql/grafana
3. remove useless/confusing make Target
4. add link for `libgit2` installation to gitextractor
> docs: update developer setup procedure

- plugins/jenkins/models/jenkins_build.go
- plugins/jenkins/tasks/jenkins_build_collector.go
Changed jenkins_builds definition
closes #1217 
Gorm set primaryKey to autoincrement by default, we have to set it to sql type manually
> fix(jenkins): fix table definition

- plugins/github/api/github_connection.go
To fix #1216
report invalid token for invalid token
report timeout for invalid endpoint
Closes #1216
reporting 'invalid token' for both invalid endpoint/token
added more specific message to help user understand the situation in depth
> fix: github reporting 'invalid token' for invalid endpoint url

- plugins/refdiff/refdiff.go
Closes #1234
Fix refdiff progress
#1234 
Right now the progress always shows zero until 
The progress shows correctly now
> fix(refdiff): correct progress

- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/settings/gitlab.jsx
- plugins/gitlab/README.md
- **Disable** GitLab ID Project Mappings Field (`DEPRECATED` feature)
This PR deprecates a field for `GitLab` Connection Instances. Gitlab Project ID Mappings is no longer a supported feature. A "No Additional Settings" message will be displayed, and the Save Settings action will be **disabled** (as we do with `Jenkins` Provider)
#1245
> fix: gitlab provider - disable project id mappings field

- plugins/gitlab/gitlab.go
- plugins/gitlab/models/gitlab_tag.go
- plugins/gitlab/tasks/gitlab_tag_collector.go
add gitlab tag collecter for private enricher.
https://github.com/merico-dev/lake/issues/894
collect gitlab tag from gitlab api and save in table `gitlab_tags`
> feat: collect gitlab tags

- plugins/github/tasks/github_api_client.go
- plugins/gitlab/tasks/gitlab_api_client.go
- plugins/jira/tasks/jira_api_client.go
when pass the pointer to apiclient.GetAsync, met some concurrent problems
We should new an object and pass this object's pointer to the goroutine func in every iteration
Concurrent problems
generated an new object and pass the pointer to go func for every iteration
> fix(plugins): fix concurrent problems

- api/api.go
- config/config.go
- config/config_test.go
- e2e/database.go
- logger/log.go
- models/init.go
- plugins/ae/api/ae_sources.go
- plugins/ae/tasks/ae_api_client.go
- plugins/compound/compound.go
- plugins/core/plugin_utils.go
- plugins/feishu/feishu.go
- plugins/github/api/github_sources.go
- plugins/github/github.go
- plugins/github/tasks/github_issue_enricher.go
- plugins/github/tasks/github_pull_request_enricher.go
- plugins/gitlab/api/gitlab_sources.go
- plugins/gitlab/tasks/gitlab_api_client.go
- plugins/jenkins/api/jenkins_sources.go
- plugins/jenkins/jenkins.go
- plugins/plugins.go
- services/pipeline.go
fix: multithread read empty config
refactored configuration file processing
Fix multithreading unsafe issue of flushing global variables in LoadConfigFile().
Fix the problem that the use of local variables in init() of config.go may cause invalid operation.
Delete the ConfigJson data structure
Remove LoadConfigFile() function
Add the GetConfig() function to privatize the Config global variable
Some Chinese annotations were killed because of klesh
All the unified calling functions for Config requirements in the adjustment code are GetConfig()
close https://github.com/merico-dev/lake/issues/1243
Any other information that is …
> fix: multithread read empty config

- plugins/jenkins/tasks/jenkins_build_convertor.go
- plugins/jenkins/tasks/jenkins_job_convertor.go
Changed jenkins job delete scope
only delete builds and jobs which belong to jenkins
closes #1229
Delete all builds and jobs whether is belong to jenkins
> fix(jenkins): change delete scope

- .env.example
- plugins/github/api/github_connection.go
changed the way to decode request for github test connection 
get test connection request params like jira 
close #1278
> fix(github): fix test connection

- config-ui/src/pages/configure/settings/jira.jsx
This PR enables the  `resetOnSelect` for the BlueprintJS **MultiSelect** widgets for the **JIRA** Issue Type Mapping fields. Which will clear the user's typed entry keywords after an option is selected from the Dropdown Menu.
#1250 
When searching for a tag the entered keywords (query) is not cleared after Selecting an option.
The component will be Reset after a Selection is made so the search keywords (query) is cleared.
> fix: jira settings > enable reset query on multiselect fields

- config-ui/src/pages/pipelines/create.jsx
This PR downgrades the **Enhanced** `CodeEditor` to a **Basic** `TextArea` Editor in order to restore functionality for Advanced Pipeline Editing for Config-UI in both development-mode and with **Docker** production-mode. After much troubleshooting there appears to be a problem with the package `@uiw/react-textarea-code-editor` and the application in Built/Minified mode. This will require more troubleshooting in `v0.10.0` and the CodeEditor will be upgraded in a future release with a replacement package or fix.
#1251
The Pipeline Advanced Editor is malfunctioning in Production UI mode.
The Pipeline Advanced Editor is working in both development and production mode.
> fix: create pipeline > restore basic textarea editor in advanced mode

- plugins/jira/models/jira_source.go
Change proxy field into lowercase, related to #1288
> fix: jira proxy should be lowercase

- config-ui/src/components/Sidebar.jsx
- config-ui/src/data/NullConnection.js
- config-ui/src/data/Providers.js
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useConnectionValidation.jsx
- config-ui/src/hooks/useSettingsManager.jsx
- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/pages/configure/settings/github.jsx
- config-ui/src/pages/configure/settings/jira.jsx
- config-ui/src/styles/sidebar.scss
- GITHUB_PR_TYPE
- GITHUB_PR_COMPONENT
- GITHUB_ISSUE_SEVERITY
- GITHUB_ISSUE_COMPONENT
- GITHUB_ISSUE_PRIORITY
- GITHUB_ISSUE_REQUIREMENT
- GITHUB_ISSUE_TYPE_BUG
- GITHUB_ISSUE_TYPE_INCIDENT
- `RemoteLinkCommitSha`
This PR re-configures the **Proxy** field as a _Connection_ level parameter for all applicable providers (**GitHub**, **JIRA**, **GitLab**). It also enhances the **GitHub** Provider Settings with 8 new fields related to PR and Issue Enrichment using `Labels`. It also adds the `RemoteLinkCommitSha` field for **JIRA** Provider.
NOTE: This PR will impact and resolve multiple issue tickets related to Data Provider settings & Proxy (outlined below)
#1223, #1247, #1248, #1249, #1252, #1264
> feat: reconfigure proxy and extend github settings

- config-ui/src/pages/configure/settings/jira.jsx
Change url for issuetype and field from api/3 to api/2
closes #1308
Use api/3, but jira server cannot support 
Use api/2/issuetype 
> fix(frontend): modify jira url for issuetyp and field

- plugins/jenkins/tasks/jenkins_build_convertor.go
Change jenkins durationSec unit from microsecond to second
DurationSec: uint64(jenkinsBuild.Duration),
DurationSec: uint64(jenkinsBuild.Duration / 1000),
> fix(jenkins): change DurationSec unit to second

- config-ui/src/components/pipelines/ProviderSettings.jsx
- config-ui/src/components/pipelines/TaskActivity.jsx
- config-ui/src/data/Providers.js
- config-ui/src/data/integrations.jsx
- config-ui/src/hooks/usePipelineValidation.jsx
- config-ui/src/pages/pipelines/create.jsx
- config-ui/src/styles/integration.scss
- config-ui/src/styles/pipelines.scss
- Validate `url`
- Validate `repoId`
This PR adds **GitExtractor** as a **Pipeline** **Provider** in Visual/UI Mode when creating a new Pipeline Run. It requires 2 parameters, `URL` and `RepoId`. Previously `gitextractor` was only detected in Advanced Mode, now it will be available in both Visual and Advanced modes.
#1194
> `feat`: create pipeline ui - add gitextractor plugin support

- errors/errors.go
- plugins/core/apiclient.go
- plugins/helper/api_extractor.go
- utils/worker_scheduler.go
added task canceling support for api_extractor
> feat: api_extractor support task canceling

- plugins/helper/api_collector.go
api collector was not working at because scheduler.WaitUntilFinish never get called.
> fix: wait_async was not executed

- plugins/core/apiclient.go
- plugins/jira/api/jira_proxy.go
- plugins/jira/tasks/jira_api_changelog_collector.go
- plugins/jira/tasks/jira_api_client.go
- plugins/jira/tasks/jira_api_issues_collector.go
- plugins/jira/tasks/jira_server_api_client.go
Fix secondary rate limit
1. dial down your plugin api client timeout to a low value to simulate a massive failure situation
2. run plugin, and retry should be working
3. reset timeout
4. run plugin, and retry should be gone
api client retry on failure automatically, and, directly without scheduler, this is problematic when network connectivity is bad, which causes too many api request sent in a short peroid of time.
this fix moves retry logic under schedulers control to avoid such a problem.
Closes #1322
> fix: github secondary rate limit when too many retries

- models/init.go
- plugins/helper/api_collector.go
missing `url.Values` refactor for api_collector
> fix: missing `url.Values` refactor for api_collector

- config-ui/src/components/menus/RefDiffTasksMenu.jsx
- config-ui/src/components/pipelines/ProviderSettings.jsx
- config-ui/src/components/pipelines/pipeline-settings/refdiff.jsx
- config-ui/src/data/integrations.jsx
- config-ui/src/hooks/usePipelineValidation.jsx
- config-ui/src/pages/pipelines/activity.jsx
- config-ui/src/pages/pipelines/create.jsx
- config-ui/src/styles/common.scss
- config-ui/src/styles/libraries/blueprint.scss
- config-ui/src/styles/pipelines.scss
- Validate `repoId` (Non-Empty)
- Validate `Tasks` (At least 1 selected)
- Validate `Pairs` (At least 1 pair defined)
This PR adds **RefDiff** as a **Pipeline** **Provider** in Visual/UI Mode when creating a new Pipeline Run. It requires 3 parameters, `RepoId` , `Pairs` and `Tasks`. Previously `refdiff` was only detected in Advanced Mode, now it will be available in both Visual and Advanced modes.
Users are able to select from a Preset list of **Tasks** for the RefDiff Plugin:
- `calculateCommitsDiff`
- `calculateIssuesDiff`
Currently there is no max limit placed on the Ref TagPairs that can be added, we could restrict this value in the future.
#1195, #1314
> `feat`: create pipeline ui - add refdiff plugin support

- plugins/gitextractor/README-zh-CN.md
- plugins/gitextractor/README.md
- plugins/gitextractor/gitextractor.go
- plugins/gitextractor/main.go
- plugins/gitextractor/parser/clone.go
- plugins/gitextractor/parser/libgit2.go
- plugins/gitextractor/tasks/git_repo_collector.go
- plugins/helper/default_task_context.go
This is a minor refactor PR to get the git extractor conformed to the new `SubTaskEntryPoint` interface. It also removes usage of progress channel and global logger to prepare for the migration to Temporal.
After the refactor, I truncated the related tables and re-run the plugin for verification. The number of rows for each table is summarized below (data collected against DevLake git repo):
| Table     | COUNT |
| ----------- | ----------- |
| refs      | 20       |
| commits   | 2757       |
| repo_commits | 2757 | 
| commit_files | 17810 | 
| commit_parents | 3460 |
> Refactor git extractor

- runner/directrun.go
`DomainIdGenerator` needed plugin to be registered into `core` , this step is missing from `directrun.go` logic, causing `Converter` not able to work.
This shoud fix the problem, but I dont have existing `Converter` to test, please rebase and test it out.
> fix: didgen not working when being called by plugin.main

- config-ui/src/data/integrations.jsx
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useSettingsManager.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/settings/github.jsx
- config-ui/src/pages/configure/settings/gitlab.jsx
- config-ui/src/pages/configure/settings/jenkins.jsx
- config-ui/src/pages/configure/settings/jira.jsx
- Track _Empty_ field Changes with `onKeyUp` handlers
- Update `disabled` attribute for `isSavingConnection` event
This **Hotfix PR** for the `v0.9.x` **DevLake** release branch resolves problems related to the **GitHub** Data Provider with regard to saving Connection and Configuration Settings. When saving the connection additional configuration settings will be bundled with the payload so the BE API has all relevant fields for processing. The issue of **emptying** or _blanking_ a field has also been fixed, depending on the nature of how _backspace_ or _delete_ is used the `onChange` event will not fire as intended, causing an unwanted side-effect of the old value being preserved during save even though the user-controlled value was erased.
ℹ️ …
> `fix` v0.9.0 github settings - field saving issues

- config-ui/src/pages/configure/connections/AddConnection.jsx
This Hotfix PR provides a supporting fix to the `v0.9.1` release branch that resolves a `JSON` error warning when a user attempts to **Save** a new **JIRA** Connection source. 
#1396
> `fix` v0.9.1 cannot save jira connection

- plugins/github/tasks/github_api_client.go
- plugins/gitlab/tasks/gitlab_api_client.go
- plugins/helper/api_async_client.go
- plugins/helper/api_ratelimit_calc.go
Due to `MaxRetry` was not set, the `DynamicRateLimit` was never actaully worked, so it always fallbacked to `GlobalRateLimitPerHour` setting
> fix: dynamic rate limit not actually working

- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/pages/configure/integration/manage.jsx
- Extend `testConnection` with manual Payload Support
- Add `testAllConnections` function to maintain tested connections list 
This PR fixes the "**Online**" status column indicator for a Data Connection record on all Data Provider Tables. Previously the indicator would assume online based on a 200 Response from the API sources endpoint, which is not very meaningful. Now a connection **Test** is performed with the saved parameters for a data source after all the connections are fetched.
The default state would be "**Offline**" (`status=0`) for a connection, once a test is completed it will be updated to "**Online**" (`status=1`) or sometimes "**Failed**" (`status=2`) based on the TestResponse results.
ℹ️ **NOTE**: This hotfix will also be …
> `fix` `v0.9.2` : lookup online status for connections table

- config-ui/src/pages/triggers/index.jsx
This PR corrects a small typo with the "Legacy Feature Notice" text on the Triggers page.
#1408
> `fix` `v0.9.2` triggers page typo with "legacy feature notice"

- plugins/github/tasks/github_pull_request_commit_convertor.go
fix wrong usage of prId in github_pull_request_commit_converter 
Closes #1426
first run
second run
> fix(github): fix minor bug

- config-ui/src/components/Sidebar/MenuConfiguration.jsx
- config-ui/src/pages/pipelines/create.jsx
- config-ui/src/pages/pipelines/index.jsx
This PR applies UX copy updates to the **Pipelines** service(s).
ℹ️ **NOTE**: This hotfix will also be cherry-picked and applied to the `main` branch under a separate Pull Request to maintain consistency.
#1387
> `fix` `v0.9.2` config ui - update menu labels and titles for pipelines

- config-ui/src/components/validation/InputValidationError.jsx
- config-ui/src/data/Providers.js
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/styles/integration.scss
This PR applies copy and behavior updates to the Configure Connection Form UX. **Field Error** messages are being relayed in a more efficient manner with closer placement to the field that needs attention. These changes impact all applicable Data Providers with connection settings.
#1386
> `fix` `v0.9.2` data integrations - configure connection form ux updates

- .env.example
- models/init.go
- plugins/github/README-zh-CN.md
- plugins/github/README.md
- plugins/github/github.go
- plugins/github/tasks/github_pull_request_issue_enricher.go
- plugins/refdiff/tasks/refs_issues_diffs_calculator.go
close #1448
Added 	sqlDB.SetConnMaxLifetime(time.Hour * 24)  in init.go
Fixed refs_issues_diffs_calculator.go because some projects might merge requests by both squash&merge and merge directly.
Fixed pull_request_issues_enricher’s regex
Closes #1448
> fix(plugin): fix minor bugs

- plugins/github/tasks/api_repositories_extractor.go
Sometimes we input a wrong repo, but get panic wrong date format, I think we'd better remind users that the repo is wrong
> fix(github): add repo not found remind

- models/domainlayer/code/pull_request.go
- models/domainlayer/code/refs_commits_diff.go
- models/domainlayer/crossdomain/refs_issues_diff.go
- models/domainlayer/ticket/issue.go
- models/migrationscripts/archived/issue.go
- models/migrationscripts/archived/pull_request.go
- models/migrationscripts/archived/ref.go
- plugins/github/tasks/issue_converter.go
- plugins/jira/tasks/issue_converter.go
- plugins/refdiff/tasks/refs_commits_diffs_calculator.go
`issues.key` -> `issues.number`
new field `pull_requests.number`
rename `new_ref_name` and `old_ref_name` to `new_ref_id` and `old_ref_id`
#1525 
> refactor: rename some fields

- README.md
Use Slack instead of Discord as Slack is more popular.
- Existing documentation is updated
Replace the Discord badge with a Slack one in README.
> docs(README): replace Discord with Slack

- plugins/gitlab/tasks/gitlab_api_pipeline_collector.go
- plugins/gitlab/tasks/gitlab_api_pipeline_extractor.go
1. delete GetTotalPages in pipeline collector.
As there is no "X-Total-Pages" in response.header, but we set GetTotalPages for collector, so the request will be sent only once
close #1575
> fix(gitlab): fix pipeline

- plugins/helper/api_collector.go
- plugins/helper/api_ratelimit_calc.go
When we set the ratelimit to max, it might exceed a little sometimes, so we only use 95% of max.
Closes #1596 
> Fix gitlab invalid json text

- config-ui/src/hooks/useConnectionValidation.jsx
- config-ui/src/pages/configure/integration/manage.jsx
show 'To be configured' in the Endpoint column if there's no endpoint configured
show 'Disconnected' in the Status column  if the status is not connected
change 'warning' style in the form page 
close  #1609 
> Fix config UI warning

- config-ui/src/hooks/useBlueprintManager.jsx
- config-ui/src/pages/blueprints/index.jsx
- config-ui/src/pages/pipelines/create.jsx
This PR updates the Create Pipeline Automation switch to open the blueprint dialog automatically when the switch is toggled to the ON position. Additionally, the default value for a new blueprint's name has been changed to "MY BLUEPRINT"
#1626, #1616
> `fix`: open blueprint dialog on automation toggle

- config-ui/src/pages/pipelines/create.jsx
This PR closes the Blueprint Dialog automatically after saving a blueprint.
#1621
> `fix`: create pipeline: auto-close blueprint dialog on save

- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useSettingsManager.jsx
This PR resolves an issue with the **Save Settings** routine for a Connection source where stale connection data is used as settings are saved/modified during the same session as when connection level settings are modified. This creates the undesirable situation of the user overriding previously saved connection data when the decoupled save settings action is used. The Active Connection object is now refreshed after modification so the connection payload is in-sync, preventing any data inconsistency.
#1613
> `fix`: config-ui: connections - update active connection state after modify

- config-ui/src/components/Sidebar/MenuConfiguration.jsx
This PR hides/deactivates the Triggers feature on the Sidebar Menu for Config-UI.
#1590
> `fix`: config-ui: hide triggers legacy feature on sidebar menu

- services/blueprint.go
> fix: all pipelines triggered by different blueprints have same name

- plugins/helper/api_client.go
- plugins/helper/api_collector.go
Jenkins fix.
add total for counting the go routine thread if it is finished.
close https://github.com/merico-dev/lake/issues/1490
close https://github.com/merico-dev/lake/issues/1620
close https://github.com/merico-dev/lake/issues/1629
> Jenkins fix

- config-ui/src/components/blueprints/AddBlueprintDialog.jsx
- config-ui/src/hooks/useBlueprintManager.jsx
- config-ui/src/pages/blueprints/index.jsx
- config-ui/src/pages/pipelines/activity.jsx
- config-ui/src/pages/pipelines/create.jsx
- config-ui/src/pages/pipelines/index.jsx
- Generate presets dynamically from Blueprint Manager
- Fix HOURLY mode to run all 7 Days instead of only M-F
- Fix Incorrect Description Values
This PR applies additional fixes and enhancements to the Blueprints v0.10.0 release with regard to Cron Preset Options.
#1610
> `fix`: blueprints: update cron preset frequency options + fixes

- plugins/helper/api_collector.go
> fix: jira stuck at collectChangelog when if Input is empty

- plugins/jira/jira.go
If since is zero, we don't assign it to taskData
Otherwise, we cannot assign a right value when creating cursor
relate to #1649
> fix(jira): fix wrong assign to since

- config-ui/src/components/pipelines/ProviderSettings.jsx
- config-ui/src/pages/pipelines/activity.jsx
change Project IDs to Project ID on create pipeline page of config-ui 
Currently we will not change jira board setting
close #1657
> fix(config-ui): fix typo

- plugins/helper/api_async_client.go
- plugins/helper/worker_scheduler.go
- plugins/helper/worker_scheduler_test.go
close #1693
Add a subpool for scheduler to hold retry requests
And to avoid rate limit, for main pool submit, we will sleep for a second if there are still some running goroutines in the subpool. 
close #1693 
> fix(api_collector): fix dead lock

- plugins/jira/tasks/issues_extractor.go
Closes #1698 
The two columns `issue_created_date` and `resolution_date` in `_tool_jira_sprint_issues` did not be populated during the extracting stage.
#1698 
> fix: missing columns in `sprint_issues`

- plugins/helper/data_converter.go
The reason of #1701 was `InputRow` being reuse between different record, so , when plugin try to use the address of `inputRow.createdAt`, they end up using same value.
We discussed following solution:
1. changing the type of `issue.CreatedDate` from pointer to direct value #1702 
2. changing the type of `pluginIssue.CreatedAt` from direct value to pointer
3. changing the design of `Converter` to let plugin author aware that `inputRow` is shared between `Convert` methods, so they can create another pointer.
4. not sharing `inputRow`
We opt for solution 4 , because the work is minimum, and future proof (plugin authors do not need to care these detail), at expense of a little bit more memory usage which is limited and acceptable.
Describe what this PR does, and aims to solve in a few …
> fix: incorrect domain layer issue `created_date`

- config-ui/src/components/validation/InputValidationError.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
[**V0.10.0** RELEASE TARGET] Ⓜ️ `main`
This PR adds "**Validate On-Focus**" support to the primary **Connection Form Inputs** for JIRA and other Data Providers as well. In the case of JIRA, a multi-source provider, when Adding a New connection this will allow the input fields to appear with less "Severity" by default, only when focus is given to the primary Input element will the error states be fully activated.
#1606
> `feat` `v0.10.0` connection inputs: add validate-on-focus support

- config-ui/src/hooks/useJIRA.jsx
[**V0.10.0** RELEASE TARGET] Ⓜ️ `main`
This PR removes duplicate **JIRA Issue Types** fetched from the `REST` `API` in cases where types of the same name such as "**Bug**" are unnecessarily duplicated within the response. This doesn't happen on all JIRA Instances, however in cases where the `Issuetype:name` property (ie `value` key) is repeated it will be removed from the list selection.
#1641
> `fix` `v0.10.0` jira provider - remove duplicate jira issue types from list

- grafana/dashboards/WeeklyBugRetro.json
This PR adds a default dashboard to show the team their new bug reports as well as closed bugs from the last week. The dashboard has one variable `repo_id` to support filtering data by repos. See below for DevLake's own data:
Note: users need to set up their bug label configuration in order for this dashboard to work.
Closes #1720
> feat: add dashboard for weekly bug retro use case

- plugins/github/tasks/issue_extractor.go
- plugins/github/tasks/pr_extractor.go
- plugins/github/tasks/task_data.go
Add a field config to GithubOptions
The config contains all about issue&pr enrichment options
In issue&pr extractor, we assign variable with value in config, and if it's empty, we assign it with value from .env
closes #1727
> feat(github): allow github override issue&pr enrichment options

- Makefile
- api/router.go
- api/version/version.go
- main.go
- version/version.go
- worker/main.go
Backend part of issues #1747
1. Version is generated based on tag/commit sha of current commit
2. devlake server/worker would print `Version` on start up
3. devlake server provides `/version` to return version information
> feat: add version information based on git tag/sha

- config-ui/src/components/Sidebar.jsx
This PR adds a **Version Tag** to Config-UI's Sidebar so that users are aware of the current release version and commit hash being served.
#1747
> feat: config ui - add devlake api version tag to sidebar

- config-ui/src/components/Sidebar.jsx
- config-ui/src/hooks/useConnectionManager.jsx
This PR will perform a Connection test when a Connection Source is modified, but only for token based providers such as GitHub and JIRA. If a multi-token string is detected in the payload, a connection test will be performed afterwards to notify the user if there is a problem with one of the tokens.
#1662
> feat: connections - test connection on save for multi-token providers

- plugins/jira/tasks/sprint_issues_convertor.go
Fix #1812 (missing prefix in `issue_assignee_history.assignee`)
Close #1812
> fix: issue_assignee_history.assignee missing prefix

- plugins/jira/jira.go
change subtask name `ConvertUsers` to `convertUsers`
closes #1804 
> fix(jira): change subtask name `ConvertUsers` to `convertUsers`

- config-ui/src/data/Providers.js
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/styles/common.scss
- config-ui/src/styles/integration.scss
This PR Updates the Token form field for a GitHub Data Source Connection. A multi-line TextArea will be used for GitHub provider specifically so multiple tokens can be easier managed.
#1385
> fix: use multi-line textarea on github token field

- docker-compose.yml
- plugins/github/github.go
- plugins/github/models/migrationscripts/updateSchemas20220509.go
change table._tool_github_pull_request `author_id` type from varchar to bigint
tested github plugin, it's ok for postgres now
Also added postgres to docker-compose
closes #1806
> fix(github): change `author_id` to bigint

- logger/log.go
- plugins/gitlab/gitlab.go
- plugins/helper/default_logger.go
- plugins/helper/default_task_logger.go
Add a logger pool to DefaultLogger, whenever we need a nested logger, we use file name to check if the pool has that logger, if so, we just return it to create a  new default logger, otherwise, we create a new logger
closes #1716
> feat(framework): print log to both file and console

- go.mod
- go.sum
- plugins/helper/api_async_client_test.go
- plugins/helper/api_collector.go
- plugins/helper/api_collector_test.go
Unit test for api_collect
TestSaveRawData
TestSaveRawData_Fail
TestHandleResponse
TestHandleResponse_Fail
TestFetchAsync
TestFetchAsync_Fail
TestHandleResponseWithPages
TestHandleResponseWithPages_Fail
TestStepFetch
TestStepFetch_Fail
TestExecWithOutPageSize
TestExecWithGetTotalPages
TestExecWithOutGetTotalPages
TestExecute
fix some bugs.
close #1656
close #1766
close #1802
close #1803
> Unit test for api_collect

- plugins/helper/api_async_client.go
- plugins/helper/api_async_client_test.go
- plugins/helper/api_collector_test.go
Add retry when got the http status code more than 400 even without any error.
also modified corresponding unit test
In issue #1833 , it failed because it didn't retry when http status code is 503. 
The http request retry only when it has error, to fix, we make sure the http request will retry when the status code  is equal or larger than http.StatusBadRequest(400)
closes #1833
> fix: system panic when http response code is 503

- config-ui/src/hooks/useConnectionManager.jsx
jenkins got `Disconnected` because it tried to fetch Username/Password,
Right now, we changed all fields to camelCase, so we need to assign `c.username/password`
closes #1847
> fix(config-ui): change Username/Password to camelCase

- plugins/README.md
Update doc `how to create a new plugin`
part of #1821 
> docs(plugins): how to create plugin

- plugins/github/models/connection.go
In `github.models.Config`, `IssueTypeIncident` has wrong tag.
Modify `IssueTypeIncident` tag to unify all the fields in both frontend and backend
closes #1887
> fix(github): modify issueTypeIncident

- plugins/jira/jira.go
- plugins/jira/tasks/apiv2models/changelog.go
- plugins/jira/tasks/apiv2models/issue.go
- plugins/jira/tasks/apiv2models/user_test.go
- plugins/jira/tasks/changelog_extractor.go
- plugins/jira/tasks/user_collector.go
fix #1895 [jira] assignee data of issue_assignee_history table beyond users scope
collect user information from the assignee changelog which was ignored
close #1895
> fix: extract jira user from assignee changelog

- .github/workflows/build.yml
- .github/workflows/commit-msg.yml
- .github/workflows/front-end-lint.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- Dockerfile
Adding [cache](https://github.com/marketplace/actions/cache) allows caching dependencies and build outputs to improve workflow execution time.
Also modified the workflow not to run test if only modified docs
closes #1941
before:
lint: 2m
e2e: 2m
unit: 4m
after
lint: 1m
e2e: 1m
unit: 2m
> feat(github workflow): improve github action

- plugins/jira/tasks/changelog_collector.go
- plugins/jira/tasks/issue_extractor.go
Accelerate jira changelog collecting.
- set `GetTotalPages` as `GetTotalPagesFromResponse` for Jira issue changelog collector
- set `changelog_updated` as issue collecting time
> refactor: accelerate jira changelog collecting

- runner/directrun.go
swallow the error from exec.Command.Run()
closes #1973
> fix(runner): swallow the error form exec.Command.Run

- plugins/jira/api/connection.go
- plugins/jira/api/init.go
This PR fixes #2032 by the following approach:
for Jira connections endpoint, when `.env` got deleted and decryption failed, no more 400 bad requests, but with empty `basic auth`, so developer/user can still list out all Jira connections, and update their `basic auth` which will then be encrypted with the newly generated key. 
Fixes #2032
> fix: jira connections api should not depend on encKey

- plugins/feishu/feishu.go
- plugins/feishu/models/meeting_top_user_item.go
- plugins/feishu/models/migrationscripts/updateSchemas20220526.go
- plugins/feishu/tasks/meeting_top_user_item_extractor.go
- plugins/helper/batch_save.go
- plugins/helper/batch_save_test.go
- runner/directrun.go
copy migrate from `services/init.go` to `directrun.go` for migration in cli;
delete `id` in  feishu model and add new primaryKey
I want to keep this PR small, but I got a error when fix feishu model because of time cannot use as primary key.
So Fix it in commit 2. 
StartTime is a struct so `isPrimaryKey` not run and StartTime cannot detect as primary key.
I fix it like this: check isPrimaryKey before check struct; add need_recursion to avoid unuseful recursion
close #2029
close #2014
close #2031
> add migration for directrun; update feishu model

- Makefile
- plugins/jira/models/migrationscripts/updateSchemas20220601.go
- fix `make fmt` under macos
- add gofmt `-s` options for aligning golang-ci's
Signed-off-by: Ji Bin <matrixji@live.com>
Not. Related: #2099 
N/A
N/A
> fix: minor fix for golangci-lint

- plugins/ae/ae.go
- plugins/dbt/dbt.go
- plugins/feishu/feishu.go
- plugins/github/github.go
- plugins/gitlab/gitlab.go
- plugins/jenkins/jenkins.go
- plugins/jira/jira.go
- plugins/refdiff/refdiff.go
- plugins/tapd/tapd.go
- runner/directrun.go
fix some golangci-lint like follow.
ineffectual assignment to err (ineffassign)
SA4009: argument subtasks is overwritten before first use (staticcheck)
SA4009(related information): assignment to subtasks (staticcheck)
> fix: fix lint check failed

- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- Dockerfile
- devops/lake-builder/Dockerfile
Previously, we don't have tar in our base image lake-builder, so we have to run `add no cache tar` during github action workflow.
In this pr, we removed all `add no cache tar` in *.yml and add it to base image dockerfile
closes #2102
> fix(ci): remove add tar in github action and modify lake-builder image

- Dockerfile
- devops/alpine-dbt-mysql/Dockerfile
- devops/alpine-dbt-mysql/README.md
- devops/lake-builder/Dockerfile
preinstall python and dbt-mysql in mericodev/alpine-dbt-mysql image.
to prevent install it every time we release lake
fix #1692
Before merge this PR, we should push image `mericodev/alpine-dbt-mysql` to docker hub.
> chore: create alpine-dbt-mysql

- plugins/gitlab/impl/impl.go
- plugins/gitlab/tasks/pipeline_collector.go
- plugins/gitlab/tasks/pipeline_extractor.go
delete CollectChildrenPipeline and ExtractChildrenPipeline as the relevant api of gitlab have rate limit problem
And these two tasks only added `coverage` field to table._tool_gitlab_piplines. So we decide to delete them.
Closes #2118 
> Cherry pick pr 2119

- plugins/refdiff/README.md
- plugins/refdiff/refdiff.go
- plugins/refdiff/tasks/ref_commit_diff_calculator.go
- plugins/refdiff/tasks/ref_issue_diff_calculator.go
- plugins/refdiff/tasks/refdiff_task_data.go
Add TagsPattern to set Pattern for refdiff
Add TagsLimit to limit the count of TagsPattern matching.
Add TagsOrder to set the order rule for  list of TagsPattern  matching.
Add surpport of DirctRun for new param. 
Optimize partial logs
The TagsPattern support CalculateIssuesDiff and CalculateCommitsDiff.
close #1983 
> Add TagsPattern for use Pattern in refdiff

- plugins/helper/api_collector.go
I think it is missing the InputJson. so `Input:  reqData.InputJSON` is NULL
fix: #2153 
fix: #2140
> fix: api_collector is missing the value of the input parameter

- plugins/jenkins/tasks/build_extractor.go
- plugins/jenkins/tasks/job_collector.go
closes #2158
In api_collector, when we copy reqData, we forgot to copy inputJson. 
In Jenkins jobs collector, we should set the concurrency to 1. If the concurrency is larger than 1, it might go to fetch data which jenkins does not have, then it will report 500.
closes #2158
> fix(jenkins): copy inputjson

- .github/workflows/build.yml
fix #2173 
Only the official releases are tagged as `latest`
close #2173
> feat: only tag  to official releases

- helpers/unithelper/dummy_logger.go
- plugins/helper/api_async_client.go
- plugins/helper/worker_scheduler.go
- runner/loader.go
The `gatherError` didn't work as expected, it failed to collect the error
This work scheduler is too abstract, in order to low down the complexity, I decided to remove the `callframes` information for now, feel free to discuss if you think it is neccessary.
Fixes #2167 
This screenshot shows that errors now can be collected, and task stop after a while
> Fix work_scheduler wouldn't halt on error

- .env.example
- config-ui/src/data/Providers.js
- config-ui/src/data/integrations.jsx
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useSettingsManager.jsx
- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/pages/configure/integration/manage.jsx
- plugins/github/api/connection.go
- plugins/github/api/init.go
- plugins/github/github.go
- plugins/github/models/connection.go
- plugins/github/models/migrationscripts/updateSchemas20220608.go
- plugins/github/tasks/api_client.go
- plugins/github/tasks/issue_extractor.go
- plugins/github/tasks/pr_extractor.go
- plugins/helper/connection.go
- plugins/icla/plugin_main.go
Save GitHub connection in DB and support creating multi-connection.
It's the first PR for #1980. Only can collect data by the connection named `GitHub` or fail.
#1980
1. Github Connections now support POST/DELETE API like Jira Plugin.
2. Github Connections now replace all column `auth` with `token`.
3. Now support save multi connections.
4. delete the below columns in all GitHub Plugin Api.
```
PrType
PrComponent
IssueSeverity
IssuePriority
IssueComponent
IssueTypeBug
IssueTypeIncident
IssueTypeRequirement
```
> save github connection in db and support create multi connection

- plugins/gitextractor/parser/libgit2.go
fix #2186 [Bug] [gitextractor] gitextractor does not collect remote branches.
The method `func (v *Reference) IsBranch() bool` would return `true` only if the branch is a local one. To fix it, we brought in another method `func (v *Reference) IsRemote() bool`, as the name indicated, it tells us whether the branch is remote
close #2186 
> fix: gitextractor does not collect remote branch

- .github/ISSUE_TEMPLATE/bug-report.yml
Recently recreated "bug report" doesn't come with `type/bug` label
This PR aim to fix the problem
> fix bug report template label setting

- plugins/jira/tasks/issue_extractor.go
minor fix for pr #2221 : delete duplicate `return`
closes #2218
> fix(jira): minor bug

- config-ui/Dockerfile
config-ui nginx was running as root, which is not a best practice, as an attacker can potentially become root in a given kubernetes node using some security breach. This commit switches to use an unprivileged nginx container, which runs as nginx user. In addition, it fixes the tag of the image to inherit from, as using latest is also not a good practice, as it can lead to introduce breaking changes if the parent image moves the latest tag to a new image with said breaking changes.
No
We have it running with those changes in our Kubernetes cluster with no issues. Notice the custom securityContext configuration that we set states to not run the containers as root:
N/A
> Run config-ui nginx container as non-root

- api/blueprints/blueprints.go
- models/blueprint.go
- models/migrationscripts/updateSchemas20220616.go
- services/blueprint.go
- services/init.go
Implement `mode` support for `blueprint`
1. added `mode` field to `blueprint`
2. `tasks` field is not required if `mode` == `NORMAL` because it would be generated by `settings` in the near future
3. added `isManual` to indicate if it is triggered by scheduler, `cronConfig` is required IFF `isManual == false`, but it gets validated if provided
4. `NORMAL` is not implemented yet
Closes #1987
> feat: add `mode` to blueprint entity

- plugins/helper/api_async_client.go
- plugins/helper/api_client.go
- plugins/helper/api_collector.go
- plugins/helper/api_collector_test.go
- plugins/helper/common/callbacks.go
- plugins/helper/common/hooks.go
- plugins/jira/jira.go
- plugins/jira/tasks/api_client.go
- plugins/jira/tasks/changelog_collector.go
- plugins/jira/tasks/remotelink_collector.go
- plugins/jira/tasks/worklog_collector.go
fix #2226 
Adding an function type attribute `AfterResponse` to `helper.ApiCollectorArgs`. This function would check all the HTTP responses, if the status code is 404, it returns a predefined error `helper.ErrIgnoreAndContinue`. The rest part of the `collector` will ignore this error and skip to the next HTTP request.
close #2226
> fix: ignore http status code 404

- plugins/tapd/impl/impl.go
- plugins/tapd/tasks/bug_changelog_collector.go
- plugins/tapd/tasks/bug_collector.go
- plugins/tapd/tasks/bug_commit_collector.go
- plugins/tapd/tasks/iteration_collector.go
- plugins/tapd/tasks/story_changelog_collector.go
- plugins/tapd/tasks/story_collector.go
- plugins/tapd/tasks/story_commit_collector.go
- plugins/tapd/tasks/task_changelog_collector.go
- plugins/tapd/tasks/task_collector.go
- plugins/tapd/tasks/task_commit_collector.go
- plugins/tapd/tasks/worklog_collector.go
ignore err if it's `record not found` when fetch latestUpdate from db in `Collector`
relate to #2282 
> fix(tapd): ignore err if it's record not found

- Makefile
- scripts/compile-plugins.sh
1. run `make debug` to fire up api server with `delve` for breakpoint debugging
2. fix `scripts/compile-plugins.sh` error swallowing, it keeps going even if the compilation failed
> Debug with delve / compile-script swallowing compilation error

- impl/dalgorm/dalgorm.go
- models/blueprint.go
- models/migrationscripts/220622-blueprint-normal-mode.go
- models/migrationscripts/register.go
- models/pipeline.go
- models/task.go
- plugins/core/dal/dal.go
- plugins/core/plugin_blueprint.go
- plugins/core/plugin_task.go
- services/blueprint.go
- services/blueprint_test.go
- services/pipeline.go
- test/api/task/task_test.go
1. `blueprint.tasks` and `pipeline.tasks` were renamed to `plan`
2. `dal.First` would return `dal.ErrRecordNotFound` instead of `gorm.ErrRecordNotFound`
3. migration script is written in a novel convention for better readability, feel free to argue
4. define `Blueprint` protocol `1.0.0` including `interface` and `struct` they should adopt, so the framework and plugin can generate Pipeline.Plan based on it
5. define `DOMAIN_TYPES` (aka, `entities` from config-ui), the naming is open for discussion.
6. blueprint would call plugin to generate Plans, and then merge them into one unified Plan
**This is framework implementation, which would require plugin support to produce a meaningful result.**
Part of #1982
> feat: blueprint normal mode framework-side

- .github/workflows/deploy-test.yml
- deployment/helm/README.md
- deployment/helm/templates/deployments.yaml
- deployment/helm/templates/statefulsets.yaml
- deployment/helm/values.yaml
Add mount entry for localtime while deploy with helm chart.
Closes #2278 
```
[root@nuc incubator-devlake]# kubectl exec devlake0-lake-0 -- date
Tue Jun 21 18:18:36 CST 2022
[root@nuc incubator-devlake]#
```
With this patch, the container uses the same time zone as the node.
N/A
> fix: add mount localtime while deploy with helm

- .github/workflows/commit-msg.yml
commit message linter has broken for a while, it is time to bring it back.
> ci: fix commit message linter

- plugins/gitlab/tasks/api_client.go
- plugins/gitlab/tasks/pipeline_collector.go
Add ignoreHTTPStatus403 to ignore the http code 403
For collect pipeline with CI/CD disable.
close #2065
> fix: ignore collect pipeline 403 for CI/CD disable

- plugins/helper/api_async_client.go
- plugins/helper/api_collector.go
- plugins/helper/api_collector_test.go
Add Release() for RateLimitedApiClient and ApiAsyncClient.
Add defer Release() call at Execute of api_collector.
close #1772 
> fix: add release to apiclient

- plugins/gitee/api/init.go
- plugins/github/api/connection.go
- plugins/github/api/init.go
- plugins/github/models/connection.go
Modify github test connection,
before: config-ui send a request which contains a list of tokens, and backend will check one by one and return the index if one of tokens failed
now: config-ui will only send one token per time.
```json
POST /plugins/github/test
REQUEST BODY:
{
"endpoint": "https://api.github.com/",
"token": "github api access token"
}
RESPONSE BODY:
- Success:
{
"login": "xxx"
}
- Failure:
{
"success": false,
"message": "invalid token"
}
```
relate to #2423
> feat(github): modify test conn

- plugins/gitlab/api/blueprint.go
- plugins/gitlab/tasks/commit_collector.go
- plugins/gitlab/tasks/commit_convertor.go
- plugins/gitlab/tasks/commit_extractor.go
1. fix typo in the plugin name
2. collect/extract/convert commits should be disabled by default.
> fix: gitlab blueprint generator

- api/api.go
- config-ui/src/components/blueprints/BlueprintsGrid.jsx
- config-ui/src/hooks/useBlueprintManager.jsx
- config-ui/src/utils/request.js
- services/blueprint.go
- [fix: notify user for 428 error (db migration confirmation)](https://github.com/apache/incubator-devlake/pull/2521/commits/1ad8b98877b934a3aa633a90bb41ce5005c9d8ea)
- [fix: unable to save Manual blueprint](https://github.com/apache/incubator-devlake/pull/2521/commits/1054d4d78fbef5d884b16e49dfa3f1ff953cc17b)
- [fix: liniting](https://github.com/apache/incubator-devlake/pull/2521/commits/b0523a07f6e59af63998e0f6ac986d87108c51b2)
- [fix: blueprints page failed if there were Manual items](https://github.com/apache/incubator-devlake/pull/2521/commits/90fb37c55ab32bb854506b25b175b38c48d26911)
> Kw 220718 config-ui fixes

- config-ui/src/pages/blueprints/blueprint-detail.jsx
1. fix start_at/end_at display bug
now start_at/end_at can display correctly when one of them or both of them are null
> fix: fix start_at/end_at display bug

- .github/workflows/build-builder.yml
- .github/workflows/build.yml
- .github/workflows/commit-msg.yml
- .github/workflows/deploy-test.yml
- .github/workflows/front-end-lint.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- config-ui/src/styles/app.scss
- config-ui/src/styles/blueprints.scss
- config-ui/src/styles/breadcrumbs.scss
- config-ui/src/styles/common.scss
- config-ui/src/styles/configure.scss
- config-ui/src/styles/connections.scss
- config-ui/src/styles/content.scss
- config-ui/src/styles/fonts.scss
- config-ui/src/styles/globals.scss
- config-ui/src/styles/integration.scss
- config-ui/src/styles/nav.scss
- config-ui/src/styles/offline.scss
- config-ui/src/styles/pipelines.scss
- config-ui/src/styles/sidebar-menu.scss
- config-ui/src/styles/sidebar.scss
- config-ui/src/styles/theme.scss
- k8s-deploy.yaml
- plugins/github/e2e/milestone_test.go
fix #2501 ([Doc][all] Add ASF license header to scss/yaml/yml... things in that nature)
Added ASF header for the following files:
- .github/workflows/build-builder.yml
- .github/workflows/build.yml
- .github/workflows/commit-msg.yml
- .github/workflows/deploy-test.yml
- .github/workflows/front-end-lint.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- config-ui/src/styles/app.scss
- config-ui/src/styles/blueprints.scss
- config-ui/src/styles/breadcrumbs.scss
- config-ui/src/styles/common.scss
- config-ui/src/styles/configure.scss
- config-ui/src/styles/connections.scss
- config-ui/src/styles/content.scss
- config-ui/src/styles/fonts.scss
- config-ui/src/styles/globals.scss
- config-ui/src/styles/integration.scss
- …
> fix: add asf header to some files

- config-ui/nginx.conf
Signed-off-by: KeHaoKH <hao.ke@merico.dev>
when clicking the dashboard button on the config-ui page, a username/password error. 
See the screenshot below.
https://github.com/apache/incubator-devlake/issues/2531
> fix: when clicking the dashboard button on the config-ui page, a username/password error

- grafana/dashboards/GithubBasicMetrics.json
1. remove panel "1.3 - Mean New Issue Count and Standard Deviation".
2. update "2.4 Mean Issue Lead Time in Days [Issues Created in Each Month]" to "Issues Closed in Each Month". If not, `issue lead time` will always get lower when time goes by.
3. update wordings.
No
> fix: update GitHub basic metrics dashboard

- config-ui/src/data/Providers.js
gitlab, github, jenkins endpoint url is at end of '/'.
close #2591 
> fix: plugins endpoint url miss /

- config-ui/src/pages/blueprints/blueprint-detail.jsx
This PR applies a hotfix to turn on Auto-refresh (Activity Polling) for a **CREATED** Pipeline (`TASK_CREATED`). Previously when pipelines were created, the task was always set to `TASK_RUNNING` as the pipeline started immediately, which was a pre-requisite for having turning on polling in the first place. The backend recently made a change to now place the task in a `TASK_CREATED` status to provide a "throttling" feature, which caused this bug.
`TASK_CREATED` and `TASK_RUNNING` are now both supported in the check that turns on polling. 
#2593
> `hotfix` `v0.12.0` blueprint detail - enable auto-refresh for created status

- config-ui/src/pages/blueprints/blueprint-detail.jsx
This PR applies a supplemental hotfix to the last PR #2595 that further updates status on the **Current Run's** Activity, as well as resolves the **Started At** and **Duration** display values to take into consideration the pipeline's Pending or "Created State".
#2593
> `hotfix` `v0.12.0` blueprint detail: update current run object status on refresh

- docker-compose.yml
- grafana/Dockerfile
- k8s-deploy.yaml
The `grafana` service is reverse-proxied by `config-ui` since v0.12
related to #2609
> fix: grafana is reverse-proxied since v0.12

- k8s-deploy.yaml
Required directory creation in k8s-workers through k8s-deploy.yaml
> feat: add DirectoryOrCreate in k8s-deploy.yaml

- models/migrationscripts/20220801_add_NoPKModel_to_CommitParent.go
- models/migrationscripts/register.go
- plugins/gitextractor/parser/repo.go
fix #2650 ([Bug][GitExtractor] Some commits are missing during collectGitCommits)
When the first `commit` came in,
several lines of buggy code hid an error.
```go
if err != r.storeParentCommits(commitSha, commit) {
return err
}
```
Which caused an interruption in the execution process. So the first `commit` can not be saved to the database.
It won't happen again from the second `commit`, due to the nature of `BatchSaveDivider.ForType`
close #2650 
> fix: add NoPKModel to commit_parents

- models/blueprint.go
- plugins/helper/iso8601time.go
- plugins/helper/mapstructure.go
- plugins/helper/mapstructure_test.go
- scripts/pm/framework/blueprint-create.sh
- scripts/pm/framework/blueprint-update.sh
- services/blueprint.go
`PATCH /blueprints/:id` was using `mapstructure.Decode` for `blueprint` partial update, which was unable to handle `datatypes.JSON` or `json.RawMessage`.
This fix enhanced the `helper.DecodeMapStruct` to handle the situation, and replaced mapstructure.Decode with it.
Closes #2658
> fix: patch /blueprints/:id wouldn't handle byte[]

- models/migrationscripts/20220711_add_subtasks_table.go
- models/migrationscripts/register.go
- models/task.go
- plugins/core/plugin_task.go
- runner/directrun.go
- runner/run_task.go
> [feat-2433]: record execution time for plugin subtasks

- utils/structfield_test.go
Add TestWalkFields
Fix WalkFileds lost to filter the struct.
close #2652 
> fix: fix walk fields not filter struct

- Makefile
Allowing access `/swagger` for api document under User Model (launched by docker container)
Closes #2646
> fix: pack swagger doc into docker images

- plugins/jira/tasks/issue_changelog_collector.go
- plugins/jira/tasks/worklog_collector.go
fix #2653 ([Bug][jira] The worklog Diff Sync didn't work as expected )
It is reasonable that collecting Jira worklogs takes a long time.
But from the second time, it should not take too long.
Before collecting, we first select issues which should be collecting worklogs.
It turns out, that issues without any worklogs were selected due to an unprecise SQL query.
close #2653 
> fix the worklog collecting taking too long

- grafana/dashboards/CommunityExperience.json
Add a new dashboard that computes 8 key metrics for dev experience in the community. Here's the metric list:
Issue Metrics:
1. Time to Initial Issue Response
2. Issue Resolution Time
3. Issue Response Rate within SLA (user can customize their SLA in the dashboard)
4. Number of Good First Issues (user can customize the issue label that represents good first issues in their repo)
PR Metrics:
1. Time to Initial PR Review
2. PR Resolution Time
3. PR Resolution Rate within SLA (user can customize their SLA in the dashboard)
4. PR Closed W/O Merging Rate
Future work includes differentiating between community issues/PRs vs core team issues/PRs.
Example Screehshot:
> feat: add community experience dashboard

- models/migrationscripts/20220622_rename_tasks_to_plan.go
Repeated migration: _devlake_blueprints
https://github.com/merico-dev/lake/blob/fix%232684/models/migrationscripts/20220616_update_blueprint_mode.go
https://github.com/merico-dev/lake/blob/fix%232684/models/migrationscripts/20220622_rename_tasks_to_plan.go
fix #2684 
> fix: cached plan must not change result type

- plugins/github/impl/impl.go
- plugins/github/tasks/cicd_job_convertor.go
- plugins/github/tasks/cicd_pipeline_convertor.go
- plugins/github/tasks/cicd_run_enricher.go
github cicd add convertor: pipelines and tasks
related to #2584 
> feat: github cicd convertor

- plugins/gitlab/api/connection.go
Swagger support for gitlab plugin.
close #2698 
> docs: swagger support for github plugin

- plugins/tapd/api/connection.go
add tapd swagger
closes #2701 
> docs(tapd): add swagger

- Dockerfile
- devops/lake-builder/Dockerfile
- fix missing version for docker-image
- fix missing `swag` command for lake-builder
Closes #2708 
Since the version is determined by the `tag` that my local `HEAD` is pointing to, the version `builder-v0.0.7` is  expected. It should be `v0.13.0` for next release
> API `/version` returning `@` in docker mode

- models/blueprint.go
- services/blueprint.go
- services/blueprint_test.go
Add before_action and after_action for the blueprint
close #2502
```bash
curl -X POST -H 'host:4000/api/blueprints -d '{"name":"MY BLUEPRINT","cronConfig":"0 0 * * *","plan":[[]],"settings":{"version":"1.0.0","before_plan":[[{"plugin":"before","options":{"connectionId":1},"subtasks":["collectApiJobs"]}]],"after_plan":[[{"plugin":"after1.1","options":{"connectionId":1},"subtasks":["extractApiJobs"]},{"plugin":"after1.2","options":{"connectionId":1},"subtasks":["extractApiJobs"]}],[{"plugin":"after2.2","options":{"connectionId":1},"subtasks":["extractApiJobs"]}]],"connections":[{"plugin":"jira","connectionId":1,"scope":[{"transformation":{"epicKeyField":"","typeMappings":{},"storyPointField":"","remotelinkCommitShaPattern":"","bugTags":[],"incidentTags":[],"requirementTags":[]},"options":{"b …
```
> feat: add before_action and after_action for blueprint

- plugins/gitlab/api/proxy.go
- plugins/gitlab/impl/impl.go
add a proxy for gitlab, which can allow config-ui to use:
`http://localhost:4000/api/plugins/gitlab/connections/3/proxy/rest/projects?visibility=private` to request all gitlab projects which granted to the specified user with the given token
relate to #2376
> feat(gitlab): add projects api

- api/blueprints/blueprints.go
- api/pipelines/pipelines.go
- api/router.go
- api/shared/api_output.go
- services/blueprint.go
- services/pipeline.go
Add a new api /blueprints/{id}/pipelines, to return pipelines triggered by blueprints.
results:
```
{
"count":3,
"pipelines":[
{
"id":2,
"createdAt":"2022-08-10T11:54:17.378Z",
"updatedAt":"2022-08-10T11:58:30.361Z",
"name":"MY BLUEPRINT 1660132457363",
"blueprintId":2,
"plan":[
[
{
"plugin":"github",
"options":{
"repo":"incubator-devlake-website",
"owner":"apache",
"connectionId":1,
"transformationRules":{
"prType":"",
"refdiff":null,
"prComponent":"",
"issueTypeBug":"",
"issuePriority":"",
"issueSeverity":"",
"issueComponent":"",
"issueTypeIncident":"",
"issueTypeRequirement":""
}
},
"subtasks":[
"collectApiIssues",
"extractApiIssues",
"collectApiPullRequests",
"extractApiPullRequests",
"collectApiComments",
"extractApiComments",
"collectApiEvents",
"extractApiEvents", …
```
> feat: api to get pipeline list of blueprints by blueprint_id

- plugins/jira/tasks/account_collector.go
- plugins/jira/tasks/account_extractor.go
- plugins/jira/tasks/apiv2models/user.go
> fix bug #2550

- plugins/gitee/api/connection.go
- plugins/github/api/connection.go
- plugins/gitlab/api/connection.go
github,gitlab,gitee blueprint and pipelines swagger
relate to #2734 #2735
> feat: github,gitlab,gitee blueprint and pipelines swagger

- plugins/github/api/connection.go
- plugins/gitlab/api/connection.go
- plugins/jenkins/api/connection.go
- plugins/jira/api/connection.go
- plugins/tapd/api/connection.go
Added error handling missing code in gitlab/api/connections.go (GET /plugins/gitlab/connections/:connectionId)
Added error handling missing code in gitlab/jenkins/connections.go (GET /plugins/jenkins/connections/:connectionId)
Added error handling missing code in gitlab/jira/connections.go (GET /plugins/jira/connections/:connectionId)
Added error handling missing code in gitlab/tapd/connections.go (GET /plugins/tapd/connections/:connectionId)
[Refactor][gitlab,jira,jenkins,tapd] Missing error handling #2561
> perf: added error handling missing code 

- plugins/tapd/models/story_changelog.go
- plugins/tapd/models/task_changelog.go
- plugins/tapd/tasks/story_changelog_extractor.go
- plugins/tapd/tasks/task_changelog_extractor.go
Seems like tapd has modified their api, so we got error when extracting story changelog
right now, I added one more logic to adopt the change.
Detail:
if somebody add comment on story/task, it will generate a changelog. And this changelog may have different struct comparing with before.
close #2757
> fix(tapd): modify changelog

- config-ui/src/hooks/useDataScopesManager.jsx
- config-ui/src/pages/configure/settings/github.jsx
This PR adds a new Transformation field for the **GitHub** Provider called "**PR Body** Close Pattern". It maps to the API Request payload key `prBodyClosePattern`. This field is grouped with the Code Review Entity and available during Blueprint Creation and Settings management.
Closes #2672
> feat: add github pr-body transform field

- config-ui/src/components/blueprints/ConnectionDialog.jsx
- config-ui/src/data/NullConnection.js
- config-ui/src/data/Providers.js
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useConnectionValidation.jsx
- config-ui/src/pages/blueprints/create-blueprint.jsx
- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
This PR adds the **Rate Limit** (per hour) numeric setting for the **Connections** definition for All Data Providers (Plugins). The default value is `0`. NOTE: It's property is `NOT` included when _Testing_ a connection.
#931
> feat: add connection rate limit setting

- config-ui/src/hooks/useConnectionManager.jsx
This PR uses the updated API property key `rateLimitPerHour` instead of `rateLimit` that was previously used for the connection's response body.
> refactor: active connections - use rateLimitPerHour property

- config-ui/src/pages/blueprints/create-blueprint.jsx
This PR adds a needed restriction to the **Create Blueprint Workflow** so that **JIRA Proxy** API resources are **only** fetched if JIRA is an _enabled_ Provider (ie. the user selects a JIRA connection for the current blueprint). In a scenario where JIRA is not detected, such as a blueprint with GitHub only -- API request calls for JIRA resources will not be made.
#2789
> fix: fetch proxy only if jira is an enabled provider

- config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
This PR applies an adjustment to the Create Blueprint Workflow so that the first Active Project or Board is not automatically selected for editing. This is needed so that users can see the list of projects/boards to "edit" first. A Tooltip Indicator has also been added to the "Go Back" action so users are aware that they must complete editing before proceeding _Next_.
#2784
> fix: do not pre-select active entity in create-mode

- plugins/gitlab/tasks/mr_note_extractor.go
extract `approval` from notes to comments
also set this kind of comments' type to `REVIEW`
closes #2814
> fix(gitlab): add approval to pr_comments

- models/domainlayer/code/pull_request_comment.go
- plugins/github/tasks/pr_comment_convertor.go
- plugins/gitlab/tasks/mr_comment_convertor.go
- plugins/gitlab/tasks/mr_note_extractor.go
classify gitlab mr comments to three types: DIFF, NORMAL, REVIEW to adapt cycle time calculation
also define these three types in `pull_request_comment.go`
closes #2818
> feat(gitlab): convert comments to adapt cycle time calculation

- config-ui/src/pages/blueprints/blueprint-detail.jsx
This PR resolves an issue with the Pipeline Logfile Download process where Pipeline ID defaulted to `0` due to missing pipeline object as argument. It also relays the API message if present in a `404` scenario.
#2765
> fix: add missing pipeline var with logfile download

- README.md
I've added the following fixes for the Readme file,
- Fixed the links in the readme provided for installation via Docker,Kubernetes & Temporal in the [Getting Started](https://github.com/apache/incubator-devlake#-getting-started) section
- Added link for [`Installing via Helm`](https://devlake.apache.org/docs/GettingStarted/HelmSetup)
- Fixed links for installing via Docker and Kubernetes in the [Set up DevLake](https://github.com/apache/incubator-devlake#1-set-up-devlake) section
> fix: Correcting the links to installation docs

- config-ui/src/components/blueprints/BlueprintsGrid.jsx
- config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/usePaginator.jsx
- config-ui/src/pages/blueprints/index.jsx
This PR creates a new **Paginator Hook** that will allow Page Components to use `client-side` pagination on larger data sets. Pagination has been enabled on the **Blueprints Grid**. Later on, the Paginator will be further enhanced to support `server-side` pagination to better accommodate listing of many pipelines (historical runs) and other api resources.
#2837
> feat: create paginator hook and paginate blueprints grid

- config-ui/src/hooks/useBlueprintManager.jsx
> fix: handle blueprint activation api errors

- config-ui/src/hooks/useConnectionManager.jsx
1. move setAllConnections to the right statement (it will cause bug sometimes because `c` is null)
2. replace 2 setters with `useMemo`
related #2881
> fix: move setAllConnections to the right statement

- models/domainlayer/ticket/board.go
- models/migrationscripts/20220830_add_type_field_in_board.go
- models/migrationscripts/register.go
- plugins/dora/models/migrationscripts/20220829_add_init_tables.go
- plugins/jira/e2e/board_test.go
- plugins/jira/e2e/snapshot_tables/boards.csv
- plugins/jira/impl/impl.go
- plugins/jira/tasks/board_convertor.go
Add field type to domain layer boards table
Convert jira_board.type to board.type
Other plugins can't find the corresponding fields so  their board.type not be filled.
closes #2801 
_tool_jira_boards table
boards table
> fix: add `type` field in `boards` table

- config-ui/src/hooks/useJIRA.jsx
use `id` instead of `key` when we are creating ListData for `fieldsResponse` in `config-ui/src/hooks/useJIRA.jsx`
I checked, in jira cloud, value of `id` is same to value of `key` in /fields response
closes #2930
cloud:
server:
> fix(config-ui): use `id` instead of `key` as jira server `fields` has no `key`

- config-ui/src/App.js
- config-ui/src/components/MigrationAlertDialog.jsx
- config-ui/src/components/Toast.jsx
- config-ui/src/components/loaders/ContentLoader.jsx
- config-ui/src/config/migration.js
- config-ui/src/hooks/useDatabaseMigrations.jsx
- config-ui/src/pages/blueprints/create-blueprint.jsx
- config-ui/src/utils/request.js
This PR adds a formal Database Migration Alert Dialog to Configuration UI. If the API has detected a migration, all its resource responses will return a `428` Status response, in which case a special `localStorage` key will be set to indicate that a migration warning is in effect. The Alert is mounted at the Application level so that it renders no matter what Page Service is being accessed. At this point the user can choose to **Proceed** with the migration operation or **Cancel** and take no action (Abort).
If the user chooses to **Proceed to Database Migration**, a `[GET]` request will be pushed to the Migration API Endpoint, if successful, the user will be given the option to continue or they can manually reload the browser. The local storage warning will be _removed_, and no …
> feat: setup database migration alert dialog on ui

- config-ui/src/hooks/useConnectionManager.jsx
This PR resolves a bug with Jenkins Connection where the Proxy URL field was not properly dispatched with the Connection Save Handler, resulting in an empty proxy field. Ideally, this should have been caught during prior QA Testing.
Closes #2897
`[PATCH]`
`[GET]`
> fix: add missing jenkins proxy field on save

- docker-compose.yml
remove platform and move mysql version to latest
Closes https://github.com/apache/incubator-devlake/issues/2945
> fix(m1): mysql image cannot be pulled

- Makefile
fix #3004 ([Bug][docker] the docker image name should keep consistent )
rename the `grafana` image name `devlake-grafana` in `Makefile` to `devlake-dashboard`  to keep consistent with the one in `.github/workflows/build.yml`
Closes #3004 
> fix: fix the docker image name in Makefile

- plugins/gitlab/models/job.go
- plugins/gitlab/models/migrationscripts/20220906_fix_duration_to_float8.go
- plugins/gitlab/models/migrationscripts/register.go
change duration from text to float8.
After this fix, job e2e test can pass in pg.
(It can not pass before this fix.)
Closes #2977
> feat: change duration from text to float8

- config-ui/src/components/blueprints/BlueprintDataScopesDialog.jsx
- config-ui/src/components/blueprints/DataScopesGrid.jsx
- config-ui/src/components/blueprints/GitlabProjectsSelector.jsx
- config-ui/src/components/blueprints/StandardStackedList.jsx
- config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
- config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
- config-ui/src/config/gitlabApiProxy.js
- config-ui/src/hooks/useBlueprintValidation.jsx
- config-ui/src/hooks/useDataScopesManager.jsx
- config-ui/src/hooks/useGitlab.jsx
- config-ui/src/hooks/useJIRA.jsx
- config-ui/src/pages/blueprints/blueprint-settings.jsx
- config-ui/src/pages/blueprints/create-blueprint.jsx
- config-ui/src/pages/configure/settings/github.jsx
Add more user-friend project selector for project choosing when add blueprint for gitlab.
Closes #2861
Gitlab has so many public projects. So add a checkbox to control if display these projects which user is a member of.
> feat: add projects selector fetching by api for gitlab when adding blueprint

- deployment/helm/README.md
- deployment/helm/templates/configmaps.yaml
- deployment/helm/values.yaml
Add configs: ui.admin.enabled/user/password to enable BasicAuth of config ui in helm charts
Closes xx
> feat:  Support BasicAuth configs in devlake helm charts

- api/api.go
- api/blueprints/blueprints.go
- api/pipelines/pipelines.go
- api/push/push.go
- api/shared/api_output.go
- api/task/task.go
fix #3024 ([Bug][framework] compile error)
The error was caused by a cycle of dependency. It's fixed by moving the constant `BadRequestBody` defined in the package `api` to the package `api/shared`
Closes #3024
> fix: cycle import of api and api/blueprints

- plugins/helper/api_client.go
fix #2960 [Bug][gitihub] collect account failed by not found user
In the case of `err == ErrIgnoreAndContinue`, the `err` should not be wrapped, because on the caller side, the expression `err == ErrIgnoreAndContinue`  would evaluate as false.
```go
if apiClient.afterResponse != nil {
err = apiClient.afterResponse(res)
if err != nil && err != ErrIgnoreAndContinue {
res.Body.Close()
return nil, errors.Default.Wrap(err, fmt.Sprintf("error running afterRequest for %s", req.URL.String()), errors.UserMessage("error after making API call"))
}
}
```
Closes #2960 
> fix: task failure caused by 404

- .github/workflows/asf-header-check.yml
- .licenserc.yaml
- errors/errors_test.go
- generator/template/migrationscripts/archived/connection.go-template
> fix: let workflow `check-Apache-license-header` work

- plugins/github/tasks/comment_collector.go
With latestUpdatedIssueComt.GithubId and latestUpdatedPrComt.GithubId was zero it will return 0.
Closes #3054 
Closes #3073 
> fix: fix calculateSince out empty but not nil

- config/config_test.go
The `TestReadConfig` is highly coupled with an external setting, which is out of the scope of the test case.
This makes it an ineffectual test case.
> fix: remove invalid test case TestReadConfig

- config-ui/.eslintrc
- config-ui/.prettierrc.js
- config-ui/package-lock.json
- config-ui/package.json
No.
Not any.
Ensure the consistency of multi-person collaborative code style.
> feat(config-ui): added prettier to help format code

- plugins/github/api/blueprint.go
- plugins/github/api/blueprint_test.go
- plugins/gitlab/api/blueprint.go
- plugins/gitlab/api/blueprint_test.go
- plugins/jenkins/api/blueprint.go
add a param named `datasourse` and set it to `jenkins` in jenkins blueprint when make pipeline
> feat(jenkins): add param datasource as jenkins to dora options

- config-ui/webpack.config.js
This PR turns **OFF** the **ESLint** _autofix_ setting for **Webpack** which was appropriate during early stages of development. With recent changes to the Global ESLint  & adopting Prettier configuration, however, this creates an undesirable situation for developers with older versions of `main` when trying to rebase or update, Webpack's ESLint's auto-fix will try to enforce the new standards while the server is starting or re-compile if it is running already running, which will automatically try to write changes to local files which will cause workflow conflicts.
```js
...
...
new ESLintPlugin({
// Do NOT auto-fix w/ eslint on webpack startup!
fix: false,
context: path.resolve(__dirname, './'),
exclude: ['dist', 'packages', 'cypress', 'config', 'node_modules']
}),
...
...
```
Closes …
> refactor: webpack & eslint - disable autofix on startup compile

- plugins/jira/tasks/account_collector.go
fix #3184 
Using `key` instead of `username` as a query keyword while collecting Jira accounts.
Closes #3184 
> fix: search jira account by key instead of username

- config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
adjust the transform rule button text "Go Back" to "Finish", and remove the tooltip for the button.
Closes #3187 
> fix(config-ui): adjust the transform rule button text 'Go Back' to 'Finish', and remove the tooltip for button

- plugins/jenkins/tasks/build_cicd_convertor.go
fix: deployTagPattern is missing in jenkins build converter
Closes #3220 
> fix: deployTagPattern is missing in jenkins build converter

- api/api.go
fix #3225 
Equipped with this fix, the API `/proceed-db-migration` would return 200, if no pending migration script.
Closes #3225 
> fix: return 200 if no pending migration script

- config-ui/src/pages/blueprints/blueprint-detail.jsx
This PR applies an update to the **Run Now** action for a **Blueprint** so that it's button state is Disabled when the current pipeline run is either `TASK_CREATED` or `TASK_RUNNING` state. This will prevent the user from running duplicate pipelines while the backend is still waiting to execute the last requested job.
Closes #3237
> fix: config-ui: disable run now if pipeline created or running

- plugins/gitextractor/gitextractor.go
- plugins/gitextractor/parser/clone.go
- plugins/gitextractor/parser/repo.go
- plugins/gitextractor/parser/repo_creator.go
- plugins/gitextractor/tasks/git_repo_collector.go
fix #3235 [Bug][gitextractor] gitextractor does not support socks5 proxy
Closes #3235 
> fix: gitextractor supports socks5 proxy

- plugins/github/tasks/account_convertor.go
- plugins/github/tasks/cicd_job_collector.go
- plugins/github/tasks/cicd_pipeline_convertor.go
- plugins/github/tasks/milestone_collector.go
- plugins/github/tasks/milestone_converter.go
- plugins/github/tasks/pr_issue_enricher.go
- plugins/gitlab/e2e/pipelines_test.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/tasks/account_convertor.go
- plugins/gitlab/tasks/job_convertor.go
- plugins/gitlab/tasks/pipeline_commit_convertor.go
- plugins/gitlab/tasks/project_convertor.go
Add scope for the following subtasks:
Github
-- ConvertAccounts
-- ConvertMilestones
-- CollectApiMilestones
-- EnrichPullRequestIssues
Gitlab 
-- ConvertAccounts
-- ConvertJobs
-- ConvertPipelineProjects
-- ConvertApiProjects
relate to #3182 
> fix(plugins): add scope for subtasks

- plugins/jira/tasks/apiv2models/sprint.go
fix #3250 [Bug][Jira] sprint start date is wrong when using jira server
Overwrite startDate with the value of activatedDate if it is available
Closes #3250 
> fix: overwrite startDate with the value of activatedDate

- config-ui/src/pages/configure/settings/github.jsx
since **autoFoucs** is set for the **TextArea**, the cursor will be tracked to the **TextArea** when the page is initially entered.
Closes #3243
Nothing.
> fix(config-ui): extra settings cause the incorrect cursor

- config-ui/src/components/blueprints/transformations/CICD/Deployment.jsx
Unify the method of radio text output in the deployment component, and adjust the text description.
Closes #3245
Nothing.
> fix(config-ui): adjust the text description in transformation

- config-ui/src/pages/blueprints/blueprint-detail.jsx
duration only cal how long beganAt to now when status is running or created
Closes #3263
> fix: duration only cal how long beganAt to now when status is running or created

- config-ui/src/hooks/useConnectionManager.jsx
tell error correctly when duplicate name
related #2892
> fix: tell error correctly when duplicate name

- runner/run_pipeline.go
- services/init.go
- services/pipeline.go
- services/pipeline_helper.go
for the following `pipeline`, and `tasks`, we should be seeing `finish_tasks` to be `0` or `2`, however, we got `1`, which means the `RunPipelineInQueue` function loaded an incomplete list of tasks!
```
{
"id": 1,
"createdAt": "2022-09-29T22:36:05.997327+08:00",
"updatedAt": "2022-09-29T22:45:15.69865+08:00",
"name": "MY BLUEPRINT 1664462165990",
"blueprintId": 1,
"plan": [
[
{
"plugin": "github",
"subtasks": [
],
"options": {
}
},
{
"plugin": "gitextractor",
"subtasks": null,
"options": {
}
}
],
[
{
"plugin": "dora",
"subtasks": null,
"options": {
}
}
],
[
{
"plugin": "dora",
"subtasks": null,
"options": {
}
}
]
],
"totalTasks": 4,
"finishedTasks": 1,
"beganAt": "2022-09-29T22:36:06.108868+08:00",
"finishedAt": "2022-09-29T22:45:15.698184+08:00",
"status": "TASK_COMPLETED",
"message": …
```
> fix: pipeline showed succeeded when tasks actually failed

- config-ui/src/components/blueprints/BoardsSelector.jsx
- config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
- config-ui/src/hooks/useJIRA.jsx
- config-ui/src/pages/blueprints/blueprint-detail.jsx
- config-ui/src/pages/configure/settings/jira.jsx
This PR applies required updates to **JIRA Boards** Logic so that when "saved" board tags are retrieved, to only _spread_ the saved tags array if one exists, since re-configuring board selections will create a scenario where saved tags may be non-existent for retrieval. Additionally during Blueprint Modification Workflow and JIRA Board re-selection, the newly selected board must be wrapped with `JiraBoard` Data Model so the variant type is properly detected.
Closes #3274
> fix: add array checks to all chosen tags for jira boards

- api/router.go
- api/shared/api_output.go
- plugins/helper/connection.go
fix #2892 [Bug][backend-framework] duplicate name when adding connection should have the right message
Closes #2892 
> fix: more friendly error message for duplicated connection name

- config-ui/src/pages/connections/incoming-webhook/index.jsx
webhook id is the interface return value.
Closes #3284
Nothing.
> fix(config-ui): webhook id is the interface return value

- config-ui/src/hooks/useDataScopesManager.jsx
Using the api to create a blueprint without setting the transformation-related content will cause the failure to obtain this configuration and cause the page to report an error.
Closes #3313
Nothing.
> fix(config-ui): incorrect value to get when transformation does not exist

- plugins/tapd/api/proxy.go
- plugins/tapd/impl/impl.go
Requests with path`/plugins/tapd/connections/:connectionId/proxy/*path` would route to `api.Proxy` handler
for example:
Request to http://your_devlake_host/plugins/tapd/connections/1/proxy/rest/story_categories?workspace=1
would forward to
https://api.tapd.cn/story_categories?workspace=1
closes #3194
> feat(tapd): add proxy to forward api to tapd

- plugins/dora/tasks/change_lead_time_calculator.go
- plugins/github/github.go
With this fix, most PRs would have deploy time except those yet to be deployed
**HOWEVER, IT DOESN'T SOLVE ALL PROBLEMS**
Previously, we presume that `deployment.environment` could be deduced by the `cicd_task.name`, which is fundamentally wrong judge by our own repo's data.
The following screenshot shows our github action jobs for `testing/production`, the name for both environments are identical, we can not tell the difference by looking at the `job.name` solely.
Closes #3376
> fix: most PRs don't have deploy time after dora.calculateChangeLeadTime subtask

- config-ui/src/pages/connections/incoming-webhook/add-modal.jsx
- config-ui/src/pages/connections/incoming-webhook/index.jsx
- config-ui/src/pages/connections/incoming-webhook/styled.js
- config-ui/src/pages/connections/incoming-webhook/view-or-edit-modal.jsx
display curl in the webhook page
The text copied is:
```
curl http://localhost:4000/api/plugins/webhook/1/deployments -X 'POST' -d "{
\"repo_url\":\"$CIRCLE_REPOSITORY_URL\",
\"commit_sha\":\"$CIRCLE_SHA1\",
\"start_time\":\"$start_time\"
}"
```
> fix: display curl in the webhook page

- plugins/bitbucket/models/migrationscripts/20221014_add_RepoId_CommitSha_field_pipeline_tables.go
- plugins/bitbucket/models/migrationscripts/20221014_add_repoId_commitsha_field_pipeline_tables.go
- plugins/bitbucket/models/migrationscripts/register.go
- plugins/bitbucket/models/pipeline.go
- plugins/bitbucket/tasks/pipeline_convertor.go
- plugins/bitbucket/tasks/pipeline_extractor.go
add cicd commits for bitbucket
Closes #3439 
`cicd_pipeline_commits` table
According to the latest CiCDPipelineCommit definition, there is no repo field anymore，so the field `repo` is null
> feat: add cicd commits for bitbucket

- plugins/jira/tasks/issue_extractor.go
fix #3441 [Bug][jira] Different behavior of issue type mapping in v0.12 and v0.14
In the version v0.12, the value of `issueType.Name` is assigned to `issue.Type`, only if `UntranslatedName` is not empty.
```go
if issueType.UntranslatedName == "" {
typeIdMapping[issueType.Id] = issueType.Name
} else {
typeIdMapping[issueType.Id] = issueType.UntranslatedName
}
```
However, in the version v0.14, the value of `issueType.Name` is assigned to `issue.Type`, no matter the value of `UntranslatedName`
Closes #3441 
> fix: use issueType.Name as issue.Type

- grafana/dashboards/GitExtractor.json
This PR update gitextractor dashboard and update more metrics by repo_snapshot table.
The metrics discussed and displayed in #3216 
The final effect is as follows：
Closed #1771
> feat: update gitextractor dashboard

- .github/workflows/yaml-lint.yml
- deployment/helm/templates/deployments.yaml
- deployment/helm/templates/services.yaml
- deployment/helm/templates/statefulsets.yaml
Add yaml lint for helm chart
Initial add yamllint for helm chart, this is could help to avoid some low-level mistakes, such as typo, incorrect indent. May add more yaml to lint, such k8s yaml, docker-compose's yaml, etc.
Related Issue: #3388
Partially fix #3388
If have any lint issue on YAML from the helm chart, it will be blocked at Pipeline, and Got the below comments on PR:
N/A
> refactor(ci): add yaml lint for helm chart

- config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
- config-ui/src/data/Variants.js
- config-ui/src/models/GithubProject.js
- config-ui/src/models/GitlabProject.js
- config-ui/src/models/JenkinsJob.js
- config-ui/src/models/JiraBoard.js
> refactor: add providerId to entity type data models

- .github/workflows/deploy-test.yml
- deployment/helm/values.yaml
Using the latest image for helm deployment on the main branch.
Fix: #3479, maybe lit bit the same as ongoing #3480
Closes #3479
N/A
Currently, Mysql-8 uses oracle based image, it seems not to work well with the KinD pipeline, so keep Debian-based MySQL image in the CI pipeline.
> fix(deployment): Using latest image in helm chart

- plugins/github_graphql/plugin_main.go
fix cherry-pick #3497. `ConvertJobsMeta` is only defined in main(0.15).
> fix cherry-pick #3497. ConvertJobsMeta is only defined in main(0.15).

- .asf.yaml
1.  add `mintsweet` and `keon94` to collaborators
2. protect branch `release-v0.11` to `release-v0.15`
3. add dismiss_stale_reviews and required_status_checks in the branch main
4. disable `rebase`. Now only support squash merge
> feat: add branch protection and some other config

- plugins/bitbucket/api/connection.go
- plugins/bitbucket/models/connection.go
fix #3517 [Bug][bitbucket] The endpoint /plugins/bitbucket/test responses with status code 500
Closes #3517 
> fix: test connection response with 500

- .asf.yaml
delete 0.15 protection in `.asf.yaml`. It need add back when release-v0.15 is created.
> fix: delete 0.15 protection in .asf.yaml

- config/config.go
- plugins/gitee/models/migrationscripts/20220714_add_init_tables.go
if env not set endpoint or enckey
gitee will not create conn any more.
Closes #3549 
> fix: gitee create conn with empty env

- plugins/gitlab/tasks/issue_collector.go
gitlab issue collector query set `updated_after` not `since`
Closes #3570 
> fix: gitlab issue Incremental Sync

- plugins/dbt/tasks/convertor.go
pass the value of `projectPath` from dbt plugin to the argument `--project-dir` of the command `dbt run` instead of `--profiles-dir`
Closes https://github.com/apache/incubator-devlake/issues/3574
> fix: pass the value of projectPath to dbt project-dir argument

- services/blueprint_helper.go
- services/page_helper.go
- services/pipeline_helper.go
- services/task.go
Added maxPageSize to limit the size of data for the following entities that return to frontend:
blueprint
pipeline
task
We add a new func pagehelper.ProcessDbClausesWithPager to process all pager issues
closes #3593 
> fix(framework): add max pageSize

- plugins/bitbucket/api/blueprint.go
When we send a post request to http://localhost:4000/api/blueprint, there are some errors.
This is because the refdiffRules of input parameter is nil, and then the program type assertion fails
Adding a `nil check` before type assertion can solves this issue.
Closes #3595 
> fix: checkout if refdiffRules is nil 

- models/domainlayer/code/repo.go
- models/domainlayer/ticket/board.go
- plugins/core/plugin_blueprint.go
**Epic**: https://github.com/apache/incubator-devlake/issues/3468
**Section**: Implementation No. 3 - Blueprint Plan Generation Version v2.0.0
**Content**:
1. Defining `Scope` interface with methods `ScopeId()/ScopeName()/TableName()`, and update `repos` `boards` `cicd_scopes`(not yet exists, skipped) to implement the interface.
2. `PluginBlueprintV200` takes only `ScopeIds`(`connectionId`/`transformationRuleId` can be inferred) as input, and returns `PipelinePlan` and `[]Scope` to indicate the scopes belonging to the project.
Part of #3468
> feat: defining PluginBlueprintV200 to support project

- plugins/dbt/tasks/convertor.go
When convert to `dbt` command line, skip `--select` if,
1. no input in the option (nil)
2. the slice is empty
Closes https://github.com/apache/incubator-devlake/issues/3637
> fix: skip --select argument if input is empty

- config-ui/src/store/integrations-context.jsx
> refactor: update integration context initial props

- services/task.go
cancel pager for tasks for two reasons:
1. most of time, we need to see all tasks within one pipeline
2. most of time, a set of tasks within one pipeline is not too large
relates to https://github.com/apache/incubator-devlake/issues/3593
> fix(framework): cancel pager for tasks

- config-ui/src/models/GithubProject.js
- config-ui/src/models/JenkinsJob.js
This PR applies an optional chaining check to handle `null` or `undefined` entity **names** when keys are generated by **Transformations Manager**, and the base trait function `getConfiguredEntityId()` is accessed by what are expected to be Entity Objects that are instances of `GitHubProject` and `JenkinsJob`. This fix should have been included with PR for Plugin Registry Phase 1, however it was not detected during code review.
Closes #3628
> fix: add optional chain check for null entity name

- plugins/jira/tasks/issue_extractor.go
when accountId = "" , then 400 error occur. so we need to filter the  accountId = ""
Closes #3614 
> fix: jira subtask collectAccounts ended unexpectedly

- models/domainlayer/devops/cicd_pipeline.go
- models/migrationscripts/20221107_remove_cicd_pipeline_relation.go
- models/migrationscripts/register.go
- plugins/jenkins/e2e/builds_test.go
- plugins/jenkins/e2e/snapshot_tables/cicd_pipeline_relationships.csv
- plugins/jenkins/tasks/build_cicd_convertor.go
I created cicd_pipeline_relationships by mistaken, so this pr is to do the following:
1. remove model: CICDPipelineRelationship
2. create migrationscript to delete table.cicd_pipeline_relationships which created in models/migrationscripts/20220905_modfiy_cicd_pipeline.go
3. delete the code which insert data to table.cicd_pipeline_relationships
Closes #3682
> fix(framework): remove cicdPipelineRelationship

- config-ui/src/models/DataScopeConnection.js
The judgment condition is wrong to let the data scope is not displayed.
Closes #3696
Before:
Fixed:
Nothing.
> fix(config-ui): the judgment condition is wrong to let the data scope is not displayed

- config-ui/src/hooks/useBlueprintValidation.jsx
fix pattern which matches repository name for the support repository name contains a dot
Closes #3620 
after patched:
N/A
> fix: support github repository with dot(.) char

- plugins/core/plugin_blueprint.go
- services/blueprint.go
- services/blueprint_makeplan_v100.go
- services/blueprint_makeplan_v200.go
- services/blueprint_makeplan_v200_test.go
- services/blueprint_test.go
feat: added MetricPluginBlueprintV200 interface
updated Nov 08
1. separate `PluginBlueprintV200` to 2 interfaces `DataSourcePluginBlueprintV200` and `MetricPluginBlueprintV200` because they have quite different input/output parameters
2. PluginBlueprintV200 takes `connections` just like v100 instead of `scopes` for plugins to handle them more easier
3. move `GeneratePlanJsonV100` to a separate file `services/blueprint_makeplan_v100.go`
4. rename `MergePipelinePlans` to `ParallelizePipelinePlans` which is more specific about what it does
5. add `SequencializePipelinePlans` as another operation for merging multiple pipeline plans
6. rename `FormatPipelinePlans` to `WrapPipelinePlans`
7. add `GeneratePlanJsonV200` in `services/blueprint_makeplan_v200.go` to generate v2.0.0 plan based on …
> feat: added MetricPluginBlueprintV200 interface

- helpers/migrationhelper/migrationhelper.go
- models/migrationscripts/20221109_modfiy_commits_diffs.go
- models/migrationscripts/register.go
In order to increase the scalability of commits diffs, now the refs_commits_diffs table needs to modify.
1. rename refs_commits_diffs to commits_diffs.
2. upgrade the  commits_diffs struct.
3. add commits_diffs_status table.
related to #3685 
The new tables show:
copy data result:
pre:
now:
This is just a migration script, the model will be processed in the next pr
> feat: modify refs_commits_diffs table name and struct

- models/migrationscripts/20220903_encrypt_blueprint.go
- models/migrationscripts/20220904_encrypt_pipeline.go
In pr: https://github.com/apache/incubator-devlake/pull/3712, we fixed bugs, but because it's an urgent fix, the way we fixed the bug is quite complicated(another reason is less familiar with PostgreSQL). 
In this pr, we found a new way to simplify the migration script that changed in pr #3712 , and tested through the following steps:
1. deploy devlake  v0.12 by docker-compose
2. created several blueprints and pipelines
3. shutdown v0.12 devlake
4. deploy new code 
5. check blueprints and pipelines through config-ui
Relates to https://github.com/apache/incubator-devlake/issues/3537
> fix(framework): simplify the migration scripts

- models/migrationscripts/20220722_commitfile_component.go
- models/migrationscripts/20220903_encrypt_blueprint.go
- models/migrationscripts/20220904_encrypt_pipeline.go
- plugins/jenkins/models/migrationscripts/20220729_modify_all_entities.go
In pr: https://github.com/apache/incubator-devlake/pull/3727, we fixed bugs for #3713 but just a hotfix for v0.14, this pr is to resolve the problem in main branch ,  in addition, for all fields with `datatypes.JSON`, we changed to `json.RawMessage` as pg would treat these two types with difference.
Lastly, we tested through the following steps:
1. deploy devlake v0.12 by docker-compose
2. created several blueprints and pipelines
3. collect jira, github, jenkins which were impacted in new data
4. shutdown v0.12 devlake
5. export all data
6. deploy 0.14 devlake and shutdown
7. deploy new code
8. check blueprints and pipelines through config-ui
Again, we also tested through the following steps which skipped step 4 above:
1. deploy devlake v0.12 by docker-compose
2. import the data which was …
> fix(framework): fix migration scripts

- config-ui/src/components/pipelines/StageLane.jsx
- config-ui/src/hooks/usePipelineManager.jsx
- config-ui/src/pages/blueprints/blueprint-detail.jsx
- config-ui/src/pages/blueprints/index.jsx
summary write at comments
Closes #3733 
Closes https://github.com/apache/incubator-devlake/issues/3640
Closes https://github.com/apache/incubator-devlake/issues/3522
Closes https://github.com/apache/incubator-devlake/issues/3490
> fix: fix some bugs

- api/blueprints/blueprints.go
- api/router.go
- api/task/task.go
- models/blueprint.go
- models/migrationscripts/20221107_add_skip_on_fail.go
- models/migrationscripts/register.go
- models/task.go
- plugins/core/plugin_blueprint.go
- runner/run_pipeline.go
- runner/run_task.go
- services/blueprint_helper.go
- services/blueprint_makeplan_v100.go
- services/pipeline.go
- services/pipeline_helper.go
- services/pipeline_runner.go
- services/task.go
Give users the option to skip/rerun failed tasks, and rerun them in the future.
To skip failed tasks, set the `onFailSkip=true` on creating the blueprint.
To rerun failed tasks, post `taskId` to the API `/pipelines/{pipelineId}/tasks`, if `taskId = 0` all failed tasks will rerun
To get tasks, `GET /pipelines/{pipelineId}/tasks`, only the most recent tasks will be returned
**We introduced a new pipeline status `TASK_RERUN` which indicates the pipeline is going to rerun**
1. find the pipeline by ID, and return an error if the status is among `TASK_CREATED`, `TASK_RUNNING`, and `TASK_RERUN`
2. find the tasks that need to be rerun
3. delete all tasks with the status `TASK_CREATED`
4. generate new tasks from the tasks that need to be rerun, and set their status as `TASK_CREATED`
5. set the …
> feature: skip & rerun failed tasks

- helpers/migrationhelper/migrationhelper.go
- helpers/migrationhelper/migrationhelper_test.go
- impl/dalgorm/dalgorm.go
- models/migrationscripts/20220913_fix_commitfile_id_toolong.go
- models/migrationscripts/20221109_modfiy_commits_diffs.go
- plugins/core/dal/dal.go
- plugins/dora/tasks/cicd_task_env_enricher.go
- plugins/helper/data_convertor.go
- plugins/helper/iterator.go
- plugins/jira/models/migrationscripts/20220716_add_init_tables.go
- plugins/starrocks/tasks.go
Add dal.Rows interface for the mocking of *sql.Rows..
Add TestTransformTable
Add TestTransformTable_RollBack
Add TestTransformColumns
Add TestTransformColumns_RollBack
Add TestChangeColumnsType
Add TestChangeColumnsType_Rollback
Add TestCopyTableColumns
Add TestCopyTableColumns_RollBack
Fix the error lost on Transform rollback.
Fix the error about migration script fixCommitFileIdTooLong use the wrong table name.
Closes #3332 
Closes #3333 
Closes #3714 
Closes #3724
Closes #3725 
Closes #3735
Closes #3739 
Closes #3741
> Unit test migration helper

- config-ui/src/components/blueprints/ConnectionDialog.jsx
- config-ui/src/components/pipelines/StageTaskName.jsx
- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/hooks/useIntegrations.jsx
- config-ui/src/models/Connection.js
- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/registry/plugins/github.json
- config-ui/src/registry/plugins/github_graphql.json
- plugins/github/api/blueprint.go
- plugins/github/models/connection.go
- plugins/github/models/migrationscripts/20221114_add_enable_graphql_for_connection.go
- plugins/github/models/migrationscripts/register.go
- plugins/github_graphql/tasks/account_collector.go
- plugins/github_graphql/tasks/check_run_collector.go
- plugins/github_graphql/tasks/issue_collector.go
- plugins/github_graphql/tasks/pr_collector.go
- plugins/github_graphql/tasks/repo_collector.go
1. add enableGraphql in config-ui
2. display repo name for github graphql
3. add domain_entity for github graphql
I add a column for github connection `enable_graphql`. `Github.makePipelinePlan` will return github_graphql or github by enable_graphql.
Closes #3528
Related #3529
> feat: add "enable graphql" in config-ui

- plugins/zentao/e2e/snapshot_tables/board_issues_task.csv
- plugins/zentao/tasks/task_convertor.go
Use models.ZentaoExecution as boardIdGen in taskConvertor
Closes xx
> fix(zentao): use zentaoExecution as boardIdGen

- api/blueprints/blueprints.go
- api/pipelines/pipelines.go
- config-ui/src/hooks/usePipelineManager.jsx
- config-ui/src/pages/blueprints/blueprint-detail.jsx
- config-ui/src/pages/blueprints/create-blueprint.jsx
- models/blueprint.go
- models/migrationscripts/20221115_add_labels.go
- models/migrationscripts/20221115_add_parallel_labels.go
- models/migrationscripts/register.go
- models/pipeline.go
- plugins/helper/api_async_client.go
- plugins/helper/worker_scheduler.go
- plugins/helper/worker_scheduler_test.go
- services/blueprint.go
- services/blueprint_helper.go
- services/pipeline.go
- services/pipeline_helper.go
- services/pipeline_runner.go
- utils/slice.go
- utils/slice_test.go
1. add labels for blueprint/pipeline
2. use labels which start with `parallel/*` to control how pipeline run parallel.
3. [config-ui] use api `trigger` to run blueprint
4. delete unused param `retry`
5. fix a bug imported by https://github.com/apache/incubator-devlake/pull/3754: the response body from `/blueprints` changed.
Now the pipelines with the same labels which start with `parallel/*` (just need one) can only run one by one.
all labels in the blueprint will pass to the pipeline when triggered.
Closes #3234
parallel_label in `Get /pipelines` must be a complete label name to filter.
> Issues/3234 add parallelLabels for blueprint/pipeline

- plugins/gitlab/api/blueprint.go
- plugins/gitlab/api/blueprint_v200.go
- plugins/gitlab/impl/impl.go
- utils/callframes.go
This is the implementation of GitLab for data source plugins to support the PluginBlueprintV200 interface.
You can know more detail about the PluginBlueprintV200 interface on issue #3613 
related #3468 
closed #3794
> feat: implement DataSourcePipelinePlanV200 for gitlab

- plugins/github/api/scope.go
- plugins/github/api/transformation_rule.go
- plugins/github/api/utils.go
- plugins/github/e2e/cicd_test.go
- plugins/github/e2e/comment_test.go
- plugins/github/e2e/issue_test.go
- plugins/github/e2e/milestone_test.go
- plugins/github/e2e/pr_enrich_issue_test.go
- plugins/github/e2e/pr_test.go
- plugins/github/e2e/repo_test.go
- plugins/github/impl/impl.go
- plugins/github/models/connection.go
- plugins/github/models/migrationscripts/20221116_add_trasformation_rule_table.go
- plugins/github/models/migrationscripts/20221124_add_trasformation_rule_table.go
- plugins/github/models/migrationscripts/archived/transformation_rules.go
- plugins/github/models/migrationscripts/register.go
- plugins/github/models/repo.go
- plugins/github/models/transformation_rule.go
- plugins/github/tasks/issue_extractor.go
- plugins/github/tasks/repo_extractor.go
- plugins/github/tasks/task_data.go
- plugins/jira/api/scope.go
- plugins/jira/impl/impl.go
- plugins/jira/models/board.go
- plugins/jira/models/migrationscripts/20221116_add_trasformation_rule_table.go
- plugins/jira/models/migrationscripts/archived/transformation_rules.go
- plugins/jira/models/transformation_rules.go
1. add table `_tool_github_transformation_rules`
2. add `transformation_rule_id`  to `_tool_github_repos`
3. remove default transformation rules
4. supply HTTP endpoints for the entities `transformation rules` and `GitHub repos`
No, partially fulfilled issue #3468
> feat: github support scope and transformation rule

- plugins/github/tasks/pr_review_comment_collector.go
- plugins/github/tasks/pr_review_comment_extractor.go
fix #3720 ([Bug][Pipeline] GitHub pipeline failed when only CODE entities were specified)
The reason for the bug was described in the comment on the original issue #3720, from where the quote below was taken 
> The error was caused by the missing records in the table `_tool_github_pull_requests` during extracting PR review comments. Every subtask belongs to some domain type, for `ExtractApiPrReviewComments` it is `CODE`, and for `CollectApiPullRequests` it is `CODEREVIEW`. If we only collect the `CODE` entities, the pull requests will not be collected, this caused the original error. To fix this problem we need to set the domain type of `CollectApiPullRequests` to `CODEREVIEW`, in the same way as `CollectApiPullRequests`
1. set `DomainTypes` of `CollectApiPrReviewCommentsMeta` to …
> fix: set `DomainTypes` for PR review comment

- plugins/gitlab/api/scope.go
- plugins/gitlab/api/transformation_rule.go
- plugins/gitlab/e2e/account_test.go
- plugins/gitlab/e2e/issues_test.go
- plugins/gitlab/e2e/job_test.go
- plugins/gitlab/e2e/mr_commits_test.go
- plugins/gitlab/e2e/mr_notes_test.go
- plugins/gitlab/e2e/mr_test.go
- plugins/gitlab/e2e/pipelines_test.go
- plugins/gitlab/e2e/project_test.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/models/connection.go
- plugins/gitlab/models/migrationscripts/20221125_add_trasformation_rule_table.go
- plugins/gitlab/models/migrationscripts/archived/transformation_rules.go
- plugins/gitlab/models/migrationscripts/register.go
- plugins/gitlab/models/project.go
- plugins/gitlab/models/transformation_rule.go
- plugins/gitlab/tasks/project_extractor.go
- plugins/gitlab/tasks/task_data.go
- plugins/helper/pagenation.go
1. add table `_tool_gitlab_transformation_rules`
2. add `transformation_rule_id`  to `_tool_github_repos`
3. supply HTTP endpoints for the entities `transformation rules` and `GitHub repos`
4. implement `core.PluginSource` for plugin gitlab
5. remove default transformation rules
No, partially fulfilled issue #3468
> feat: add table `_tool_gitlab_transformation_rules` and support `scope`

- plugins/github/tasks/repo_collector.go
- plugins/github/tasks/repo_convertor.go
- plugins/github/tasks/repo_extractor.go
- plugins/github_graphql/tasks/repo_collector.go
- services/blueprint_makeplan_v100.go
According to #3804 , I found that if we only choose `ticket` to collect, devlake will not collect repo info , then we cannot get githubId of repo to collect issues.
So in this pr, I update `DomainTypes` for repo collector&extractor&convertor in both github and graphQL
Closes #3804 
> fix(github): update domain types for subtasks

- plugins/github/api/blueprint_V200_test.go
- plugins/github/models/migrationscripts/archived/transformation_rules.go
- plugins/github/models/transformation_rule.go
- plugins/gitlab/models/migrationscripts/archived/transformation_rules.go
- plugins/gitlab/models/transformation_rule.go
- plugins/jenkins/impl/impl.go
- plugins/jenkins/models/migrationscripts/archived/transformation_rules.go
- plugins/jenkins/models/transformation_rule.go
- plugins/jira/api/transformation_rule.go
- plugins/jira/models/migrationscripts/archived/transformation_rules.go
- plugins/jira/models/transformation_rules.go
- plugins/jira/tasks/task_data.go
The frontend needs a name to display to the user
1. add `name` to `_tool_github_transformation_rules`
2. add `name` to `_tool_gitlab_transformation_rules`
3. add `name` to `_tool_jira_transformation_rules`
4. add `name` to `_tool_jenkins_transformation_rules`
No
> fix: add name to transformation rules

- config-ui/src/store/connections/api.ts
- config-ui/src/store/connections/index.ts
- config-ui/src/store/connections/types.ts
- config-ui/src/store/connections/use-connections.ts
- config-ui/src/store/index.ts
Add global **connections** store.
Connections are used in many places throughout the config UI. And every time it is used, a request will be sent to get this information. This results in meaningless requests and performance loss. Maintaining connections in multiple places also causes inconsistency.
> feat(config-ui): add global connections store

- plugins/github/api/scope.go
- plugins/github/models/repo.go
- plugins/gitlab/api/scope.go
- plugins/gitlab/models/project.go
- plugins/jenkins/api/scope.go
- plugins/jenkins/models/job.go
- plugins/jira/api/scope.go
- plugins/jira/models/board.go
Add `transformationRuleName` to the response of the following API:
GET `/plugins/jira/connections/{connectionId}/scopes/`
GET `/plugins/jira/connections/{connectionId}/scopes/{scopeId}`
GET `/plugins/github/connections/{connectionId}/scopes/`
GET `/plugins/github/connections/{connectionId}/scopes/{scopeId}`
GET `/plugins/gitlab/connections/{connectionId}/scopes/`
GET `/plugins/gitlab/connections/{connectionId}/scopes/{scopeId}`
GET `/plugins/jenkins/connections/{connectionId}/scopes/`
GET `/plugins/jenkins/connections/{connectionId}/scopes/{scopeId}`
No, related to #3468
> refactor: add transformationRuleName to the scope APIs

- api/project/project.go
- api/shared/api_output.go
- models/project.go
- services/project_helper.go
To maintain the consistency of the interface, after communicating with the front end, it is now decided to adjust the case of the relevant parameters of the project interface, adjust the return value when an error occurs in some interfaces, and fix a problem that causes HTTP to lose necessary error details.
projects_post.sh
```bash
#!/bin/sh
curl --location --request POST 'devlake:8080/projects' \
--data-raw '{
"name":"TestProject",
"description":"this is one of test project"
}'
echo "\r\n"
```
projects_patch.sh
``` bash
#!/bin/sh
curl --location --request PATCH 'devlake:8080/projects/TestProject' \
--data-raw '{
"name":"TestProject",
"description":"this is one of test project witch been patch", …
```
> fix: adjust the case of parameters and fix missing error messages

- plugins/webhook/api/blueprint_v200.go
- plugins/webhook/api/cicd_pipeline.go
- plugins/webhook/impl/impl.go
add scope for cicd in webhook. Just create a virtual scope to keep pace with other plugin and blueprint v200.
This is the implementation of Webhook for data source plugins to support the PluginBlueprintV200 interface.
You can know more detail about the PluginBlueprintV200 interface on issue https://github.com/apache/incubator-devlake/pull/3613
Related to https://github.com/apache/incubator-devlake/pull/3613
> feat: add scope for cicd in webhook

- models/migrationscripts/20221201_add_project_pr_metric.go
- services/blueprint.go
This pr modify the process of handling blueprints.
For advanced mode bp, we keep the same process as before
For normal mode bp, we will not set plan for it, and convert bp.settings to pipeline plan for every trigger
In addition, we set all existed normal bp.plan to empty
Every time when we trigger the bp, we can see the following msg
> Feat(framework): regenerate plan by blueprint settings before running blueprint

- models/project.go
- plugins/core/plugin_handle.go
- plugins/helper/connection.go
- services/blueprint_helper.go
- services/project.go
- services/project_helper.go
To allow the front end to modify the project name, now the back end adds support for project renaming.
Other tables associated with the project will also be renamed synchronously when the project is renamed.
Added the PluginHandle interface, through which the plug-in can synchronize the relevant modifications of the framework layer.
project_patch_rename.sh
```
#!/bin/sh
curl --location --request PATCH 'devlake:8080/projects/TestProject' \
--data-raw '{
"name":"NewTestProject",
"description":"this is one of test project witch been patch",
"enable": false,
"metrics": [
{
"pluginName": "dora",
"pluginOption": "{}",
"enable": true
}
]
}'
echo "\r\n"
```
project_get_newone.sh
```
#!/bin/sh
curl --location --request GET …
```
> Project api support rename

- plugins/gitextractor/parser/clone.go
Explain why we chose git2go rather than go-git. The git2go is a golang binding of the C library libgit2.
No
> docs: explain why we chose git2go rather than go-git

- models/task.go
- services/pipeline_helper.go
Redefine pending task status, and apply it to api `get pipelines`.
fix #3893
Create a cancelled pipeline for bp 2.  
Get bp's pipelines with pending filter.  
Create a new pipeline and get bp's pipeline again.  
> fix: pending task status

- config-ui/package-lock.json
- config-ui/package.json
- config-ui/src/App.js
- config-ui/src/components/dialog/index.tsx
- config-ui/src/components/toast2/index.tsx
- config-ui/src/pages/connections/index.ts
- config-ui/src/plugins/index.ts
- config-ui/src/plugins/webook/components/create-dialog/index.tsx
- config-ui/src/plugins/webook/components/create-dialog/styled.ts
- config-ui/src/plugins/webook/components/delete-dialog/index.tsx
- config-ui/src/plugins/webook/components/delete-dialog/styled.ts
- config-ui/src/plugins/webook/components/index.ts
- config-ui/src/plugins/webook/components/view-or-edit-dialog/index.tsx
- config-ui/src/plugins/webook/components/view-or-edit-dialog/styled.ts
- config-ui/src/plugins/webook/connection/api.ts
- config-ui/src/plugins/webook/connection/index.tsx
- config-ui/src/plugins/webook/connection/styled.ts
- config-ui/src/plugins/webook/connection/use-connection.ts
- config-ui/src/plugins/webook/index.ts
1.  simplify the use of component **toast**.
2. support parameter **style** in **dialog**.
3. refactor the webhook page.
#3648 
Nothing.
> refactor(config-ui): the webhook page

- models/domainlayer/code/repo.go
- plugins/bitbucket/tasks/repo_convertor.go
- plugins/gitee/tasks/repo_convertor.go
- plugins/github/api/blueprint.go
- plugins/github/api/blueprint_V200_test.go
- plugins/github/api/blueprint_test.go
- plugins/github/api/blueprint_v200.go
- plugins/github/impl/impl.go
- plugins/github/tasks/repo_convertor.go
- plugins/github/tasks/task_data.go
- plugins/github_graphql/impl/impl.go
- plugins/gitlab/tasks/project_convertor.go
- plugins/jenkins/api/blueprint_v200.go
- plugins/jira/api/blueprint_v200.go
- services/blueprint_makeplan_v200.go
- services/pipeline_helper.go
Change the way to set options in plugin GitHub.
Before, we set all values to tasks.GithubOptions when making plan, right now, we just pass scopeId to options, and set other values when preparing plugin data
we can see that the blueprint can be triggered successfully
bp V100:
> fix(github): modify bp v200

- plugins/github/github.go
- plugins/github/impl/impl.go
- plugins/github/tasks/cicd_run_collector.go
- plugins/github/tasks/comment_collector.go
- plugins/github/tasks/commit_collector.go
- plugins/github/tasks/event_collector.go
- plugins/github/tasks/issue_collector.go
- plugins/github/tasks/issue_extractor.go
- plugins/github/tasks/pr_collector.go
- plugins/github/tasks/pr_commit_collector.go
- plugins/github/tasks/pr_review_collector.go
- plugins/github/tasks/pr_review_comment_collector.go
- plugins/github/tasks/task_data.go
- plugins/github_graphql/impl/impl.go
- plugins/github_graphql/plugin_main.go
- plugins/github_graphql/tasks/issue_collector.go
- plugins/github_graphql/tasks/pr_collector.go
- plugins/github_graphql/tasks/repo_collector.go
- plugins/helper/api_collector_with_state.go
- plugins/helper/graphql_collector.go
- plugins/helper/worker_scheduler.go
- plugins/jenkins/jenkins.go
- plugins/jira/jira.go
1. add options CreatedDateAfter for github & github_graphql
2. fix some bugs when github running.
3. let `cicd_run` only request data created after `CreatedDateAfter`(for restful & graphql). Notice: cicd_run do not support incremental
4. update `comment/commit/event/issue/pr/plugins/pr_review_comment`'s incremental collector(for restful & graphql)
5. let `pr_commit` only request data created after `CreatedDateAfter`(for restful).
6. let `pr_review` only request data created after `CreatedDateAfter`(for restful & graphql).
7. let `issue/pr` and related model only request data created after `CreatedDateAfter`(for graphql). Notice: graphql do not support incremental.
8. delete wrong incremental in event&pr (for restful); !!there is no `since` in these 2 api.
Because Graphql uses cursor to …
> feat: add time filter for github & github graphql; fix some bugs when running

- helpers/unithelper/dummy_baesres.go
- helpers/unithelper/dummy_logger.go
- impl/dalgorm/dalgorm.go
- models/common/base.go
- models/domainlayer/code/repo.go
- models/domainlayer/devops/cicd_scope.go
- models/domainlayer/domainlayer.go
- models/domainlayer/ticket/board.go
- plugins/core/dal/dal.go
- plugins/gitlab/api/blueprint_V200_test.go
- plugins/gitlab/api/blueprint_v200.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/models/project.go
- plugins/gitlab/models/transformation_rule.go
- plugins/gitlab/tasks/job_convertor.go
- plugins/gitlab/tasks/pipeline_commit_convertor.go
- plugins/gitlab/tasks/pipeline_convertor.go
- services/blueprint_makeplan_v200.go
After `GitLab` supports `scope` and `transformation rule`, we need to add relevant content to `MakeDataSourcePipelinePlanV200` of `GitLab`, and we need to add unit tests for it to ensure that the relevant code can work correctly.
bp_post2.0.0.sh
```bash
#!/bin/sh
curl --location --request POST 'devlake:8080/blueprints' \
--data-raw '
{
"name":"test-gitlab-nddtf-v200",
"projectName":"TestProject",
"cronConfig":"0 0 * * *",
"plan":{},
"settings":
{
"version":"2.0.0",
"connections":
[
{
"plugin":"gitlab",
"connectionId":1,
"scopes":[
{
"id": "37",
"name": "思码逸 / Lake",
"entities":["CODE","TICKET","CODEREVIEW","CROSS","CICD"]
}
]
}
]
},
"enable":true,
"mode":"NORMAL",
"isManual":true
}'
echo "\r\n"
```
related #3468 
closes #3900 
closes #3902 …
> feat: gitlab plan v200

- plugins/azure/api/blueprint.go
- plugins/jenkins/api/blueprint_v100.go
- plugins/jenkins/api/blueprint_v200.go
- plugins/jenkins/api/blueprint_v200_test.go
- plugins/jenkins/impl/impl.go
- plugins/jenkins/tasks/task_data.go
- plugins/jira/impl/impl.go
- services/blueprint_makeplan_v200.go
- services/blueprint_makeplan_v200_test.go
Change the way to set options in plugin jenkins.
Before, we set all values to tasks.JenkinsOptions when making plan, right now, we just pass scopeId to options, and set other values when preparing plugin data
Also make a little modification for services/blueprint_makeplan_v200.go: if we enable metricPlugin, even if plugin's option is nill, we still need to create that stage
create bp for jenkins:
output:
```json
{
"name": "TEST_PROJECT_1-BLUEP2RINT",
"projectName": "TEST_PROJECT_1",
"mode": "NORMAL",
"plan": [
[
{
"plugin": "jenkins",
"skipOnFail": false,
"subtasks": [],
"options": {
"connectionId": 1,
"scopeId": "a/b/c"
}
}
],
[
{
"plugin": "jenkins",
"skipOnFail": false,
"subtasks": [],
"options": {
"connectionId": 1,
"scopeId": "a/b/c/d"
}
}
],
[
{
"plugin": "refdiff", …
```
> feat(jenkins): update bp v200

- plugins/dbt/tasks/convertor.go
make sure the cmd.Wait() can be executed.
Closes #3919 
before:
Execute three times in a row, process screenshot：
after:
Execute three times in a row, process screenshot：
> fix: dbt zombie processes

- config-ui/src/pages/blueprint/create/hooks/use-blueprint-value.ts
- config-ui/src/pages/blueprint/create/step-one/index.tsx
- config-ui/src/store/index.ts
- config-ui/src/store/store.tsx
The connections store is not injected into the context, and it will trigger a lot of extra requests.
> fix(config-ui): connection store not injected into the context

- impl/default_basic_res.go
- plugins/core/basic_res.go
- plugins/core/config.go
- plugins/core/logger.go
- plugins/feishu/models/migrationscripts/20220714_add_init_tables.go
- plugins/github/models/migrationscripts/20220715_add_init_tables.go
- runner/basic_res.go
- runner/db.go
- services/init.go
This is a prerequisite of #3709 
1. Remove the unused/deprecated interfaces: `ConfigGetter` `InjectConfigGetter` and `InjectLogger`
2. Add `GetConfigReader` to `BasicRes` for:
- Remove `viper` coupling
- Callers may utilize the typed methods(`GetBool` `GetInt`, etc.) which make our life easier 
- We can create a new `BasicRes` instance from the existing one with ease
3. Replace `viper` with `ConfigReader` in the `services` module
prerequisite of #3709 
I tested the GitHub pipeline, it looks alright.
> refactor: add ConfigReader to BasicRes interface

- plugins/jenkins/api/jobs.go
- plugins/jenkins/api/jobs_test.go
- plugins/jenkins/impl/impl.go
- plugins/jenkins/jenkins.go
To ensure the smooth execution of v100-related businesses, V100-related processing is added to PrepareTaskData.
Including EnrichOptions ConvertJobToJenkinsJob, and GetJob with corresponding unit tests
Closes xx
> feat: add enrich options for jenkins prepare

- plugins/dora/impl/impl.go
- plugins/dora/impl/impl_test.go
- plugins/gitlab/models/project.go
- services/blueprint_makeplan_v200_test.go
Change refdiff subtask name that was created by dora when making plan.
By the way, this pr also changed the json tag of a field(HttpUrlToRepo) of GitlabProject
Closes #3940 
> fix(dora): change refdiff subtask name

- plugins/dbt/tasks/convertor.go
ProcessState contains information about an exited process, available **after** a call to Wait or Run.
Closes #3968 
Network problem, the screenshot cannot be submitted, please make it up later.
> fix: dbt log show failure, but it succeeded

- services/blueprint.go
- services/blueprint_makeplan_v200.go
support creating a blueprint without any project.
Check the blueprint's project name if it was used by another blueprint.
bp_post2.0.0.sh
```bash
#!/bin/sh
curl --location --request POST 'devlake:8080/blueprints' \
--data-raw '
{
"name":"test-gitlab-nddtf-v200",
"projectName":"TestProject",
"cronConfig":"0 0 * * *",
"plan":{},
"settings":
{
"version":"2.0.0",
"connections":
[
{
"plugin":"gitlab",
"connectionId":1,
"scopes":[
{
"id": "37",
"name": "思码逸 / Lake",
"entities":["CODE","TICKET","CODEREVIEW","CROSS","CICD"]
}
]
}
]
},
"enable":true,
"mode":"NORMAL",
"isManual":true
}'
echo "\r\n"
```
bp_patch2.0.0.sh
```bash
#!/bin/sh
curl --location --request PATCH 'devlake:8080/blueprints/25' \
--data-raw ' …
```
> fix: support create bp without project

- models/migrationscripts/20220913_fix_commitfile_id_toolong.go
- plugins/gitextractor/parser/repo.go
- plugins/gitextractor/tasks/git_repo_collector.go
Before change, we swallowed some errors in order to let the process continue. These errors were produced by libgit2, but would not impact the whole process. So in this pr, we just print them in log files.
In addition, we update 20220913_fix_commitfile_id_toolong.go to let commit_files keep additions and deletions. Otherwise, it will panic.
Closes #3864
> fix(gitex): print all errors that swallowed before

- runner/run_task.go
- services/pipeline_runner.go
- services/task.go
Improve the error message. Save more detailed information in the database when an error occurs.
The `_devlake_pipelines.message` and `_devlake_tasks.message` is filled with a detailed error message.
Closes #3974 
_devlake_pipelines.message
_devlake_tasks.message
> refactor: improve the error message for pipeline and task

- plugins/gitlab/impl/impl.go
move the handler of PUT scopes from `connections/:connectionId/scopes/:projectId` to `connections/:connectionId/scopes`
> fix: fix gitlab PUT scopes router

- impl/dalgorm/encdec_serializer.go
- models/migrationscripts/20221221_encrypt_task.go
- models/migrationscripts/register.go
- models/task.go
- plugins/core/plugin_model.go
- plugins/core/plugin_utils.go
- runner/basic_res.go
- runner/directrun.go
- services/task.go
Encrypting / Decrypting `task.options` in the database:
1. added a Dal-level mechanism for encryption/decryption to work transparently
2. updated `task` model to adopt the mechanism
3. added migration script to encrypt existing tasks
Closes #3709
> Encrypt `task.options` in database

- plugins/gitlab/tasks/job_collector.go
- plugins/gitlab/tasks/shared.go
- plugins/helper/api_collector.go
add time filter for gitlab jobs.
GitLab jobs do not support the time filter and time sorting. It can only sort by id desc (not strictly). https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines
So filter by stopping when job's create time before than options.
gitlab's pipeline can sort by time asc, so I haven't add this. Sort asc can avoid new rows qustions.
The result for only collect the rows created after `2022-12-01T00:00:00Z`
> feat: add time filter for gitlab jobs

- services/pipeline.go
Fix pipeline execution stucks
When the `dbPipeline` variable gets put outside the `for` loop, the `dbPipeline.id` gets passed to the next `dequeue` query (line#182), hence no pipeline would ever get dequeued anymore.
Closes #4014
> fix: pipeline stucks after first execution

- services/blueprint.go
The error message for error occurred during `make plan` should be **make plan for blueprint failed**, not ~~invalid plan~~
Closes #3926 
> fix: wrong error message for make-plan-err

- plugins/gitextractor/impl/impl.go
- plugins/gitextractor/parser/repo.go
Existing code would collect `commit_files` information IFF the commit has a **Parent**, which is not good for **Initial Commits**
This PR fixes the problem by including the **Initial Commits**
Closes #4001
Tested on https://github.com/merico-dev/build-frontend
> fix: commit_files of initial commits were not collected

- models/migrationscripts/20221109_rename_project_metrics.go
- models/migrationscripts/register.go
- models/project.go
- services/blueprint.go
- services/project.go
To make the name of the table easier to read.
So rename project_metrics to project_metric_settings.
> refactor: rename project metrics

- config-ui/src/pages/blueprint/components/advanced-editor/example/index.ts
- config-ui/src/pages/blueprint/components/advanced-editor/example/tapd.ts
- config-ui/src/pages/blueprint/components/advanced-editor/example/zentao.ts
- config-ui/src/pages/configure/settings/github.jsx
- config-ui/src/plugins/github/components/code-review/index.tsx
- plugins/github/github.go
1. According to pr #3927 , we combined owner and repo into name, so we also need to update `prBodyClosePattern`
2. add lodingTemplate of tapd
in new pr, we can successfully collect refs_issues_diffs
> fix(github): update prBodyClosePattern to adapt new github options

- plugins/jenkins/api/scope.go
the table  lake._tool_jenkins_jobs has not 'id' column, should be 'transformation_rule_id'
Closes #4038
> fix: jenkins scope api error

- plugins/jenkins/api/scope.go
fix: the jenkins plugin can not scope name in transformation rules.
the model is error.
Closes #4038 
old:
new:
> fix: the jenkins plugin can not scope name in transformation rules

- plugins/jenkins/models/transformation_rule.go
jenkins production_pattern is same to deployment_pattern, ProductionPattern model set error
Closes #4049 
> fix: jenkins production_pattern is same to deployment_pattern

- config-ui/src/App.js
- config-ui/src/pages/connection/form/api.ts
- config-ui/src/pages/connection/form/index.tsx
- config-ui/src/pages/connection/form/styled.ts
- config-ui/src/pages/connection/form/use-form.ts
- config-ui/src/pages/connection/list/api.ts
- config-ui/src/pages/connection/list/connection.tsx
- config-ui/src/pages/connection/list/index.tsx
- config-ui/src/pages/connection/list/styled.ts
- config-ui/src/plugins/types.ts
- config-ui/src/plugins/webook/config.ts
- config-ui/src/store/connections/index.ts
- config-ui/src/store/connections/status.tsx
1. add connection status component.
2. adjust the type for plugin config.
3. refactor the connection list page.
4. refactor the connection detail page.
5. use new connection page to replace old.
> refactor(config-ui): the connections page

- plugins/gitlab/tasks/issue_extractor.go
- plugins/gitlab/tasks/mr_extractor.go
The following snippet is taken from the codebase. It looks like it would result in the `index out of range error`, but the function `FindStringSubmatch` ensures this will not happen. In this PR, we improved the readability by changing the expression inside the `if` statement from `len(groups) > 0` to `len(groups) > 1`
```go
groups := labelTypeRegex.FindStringSubmatch(label)
if len(groups) > 0 {
gitlabMergeRequest.Type = groups[1]
}
```
> refactor: improve slice size check for gitlab

- config-ui/src/pages/blueprint/create/step-one/index.tsx
no reset **scopeMap** when **connection** changed.
Closes #4040
> fix(config-ui): no reset scopeMap when connection changed

- plugins/jenkins/api/blueprint_v200.go
- plugins/jenkins/api/jobs.go
- plugins/jenkins/impl/impl.go
1. jenkins v200 add transformation rule id for prepareTaskData usage.
2. fix getjobs api error
Closes #4057 
> fix: jenkins transformation rules have not in effect and getjobs api error

- config-ui/src/pages/blueprints/blueprint-settings.jsx
fixed the jira connection scope not exist.
When the user uses the advanced mode to create the bp of jira scope, there is no connectionId of jira, so there is no board information, so this error will be caused.
Closes #4077
> fix(config-ui): the jira connection scope not exist

- plugins/jenkins/impl/impl.go
fix: jenkins transformation rules have not in effect by blueprint.
the JenkinsTransformationRule never equel nil.
Closes #4057 
> fix: jenkins transformation rules have not in effect by blueprint

- plugins/gitextractor/impl/impl.go
- plugins/gitextractor/main.go
- plugins/gitextractor/store/database.go
- services/pipeline.go
The phenomenon described in #4024 was caused by the fact that `gitextractor` failed to delete previously collected data, it was due to the fact `_raw_data_*` fields were never populated so they would never be deleted.
This PR fixes the problem
Closes #4024
> gitextractor should delete old data

- api/pipelines/pipelines.go
- api/task/task.go
`/pipeline/{pipelineId}/rerun` should be `/pipelines/{pipelineId}/rerun`
> fix: typo of rerun-pipeline url

- plugins/azure/tasks/api_client.go
- plugins/bitbucket/tasks/api_client.go
- plugins/helper/api_client.go
- plugins/helper/api_collector.go
- plugins/jira/tasks/issue_collector.go
- plugins/tapd/tasks/api_client.go
1. fix jira issue jql;
2. fix afterFunction's effort in other collectors. The old logic afterFunction will affect other collector because it change ApiClient.
3. use recorded last updated.
> fix: fix jira issue jql; fix afterFunction's effort in other collectors

- errors/util_test.go
- plugins/helper/api_collector.go
- plugins/helper/worker_scheduler.go
- runner/run_pipeline.go
- services/task.go
Fix the bug that canceling does not work when `SkipOnFail` is set to true
- make sure every task returns the error `context.Canceled` when it is canceled
- if the error is`context.Canceled`, return it despite the value of `SkipOnFail`
> fix: fix the canceling does not work when SkipOnFail is set to true

- plugins/gitextractor/impl/impl.go
- plugins/gitextractor/parser/repo.go
If error.string() != "the requested type does not match the type in the ODB", just return error, not log it
Relate to #3975 
> Fix(gitex): return err instead of logging

- config-ui/src/pages/blueprint/create/bp-context.tsx
- config-ui/src/pages/blueprint/create/index.tsx
- config-ui/src/pages/project/detail/index.tsx
- config-ui/src/pages/project/detail/panel/blueprint.tsx
- config-ui/src/pages/project/home/index.tsx
fixed page error when project name with **/**.
Closes #4086
> fix(config-ui): page error when project name with /

- plugins/gitlab/e2e/job_test.go
- plugins/gitlab/e2e/snapshot_tables/cicd_tasks.csv
- plugins/gitlab/tasks/job_convertor.go
modify gitlab to adapt the new way to convert TYPE/ENVIRONMENT for cicd_tasks
Relate to pr #3850 
> fix(gitlab): update job convertor

- plugins/github/tasks/comment_collector.go
- plugins/github/tasks/pr_review_comment_collector.go
In collectApiPrReviewCommentsMeta and collectApiComments, we are using `since` instead of `created` to collect data created after the given time. This might mislead developers, so we add some annotations.
Using `since` will return data updated the given time, so the data contains both that updated and created after the given time.
Relate to #4044 
> docs(github): add comment for collector using since

- models/domainlayer/ticket/issue.go
- plugins/bitbucket/models/connection.go
- plugins/bitbucket/tasks/issue_extractor.go
BitBucket does not have priority, component because the BitBucket issue has priority, component as semantically explicit attributes that do not need to be extracted from the issue labels like GitHub does.
BitBucket does not have a type configuration because
a. BitBucket issue also has a type field, so there is no need to extract it from labels like GitHub does.
b. BitBucket types are only "enhancement", "proposal", "task", "bug", and cannot be customized by users. So by default we transform "enhancement", "proposal" and "task" to REQUIREMENT and "bug" to BUG to save users' time.
BitBucket does not have severity because BitBucket does not have related fields, so let's put it aside for a while and do it later.
BitBucket has "status mapping" because unlike GitHub issues which only have 2 …
> feat: add bitbucket issueStatusOther for bitbucket transformationrules

- plugins/dbt/dbt.go
- plugins/dbt/tasks/convertor.go
The dbt threads default value changed to 4, but it can not release when the project run ended,
so we need set dbt default threads=1.
https://docs.getdbt.com/docs/dbt-versions/release-notes/dec-2022/default-thread-value
related to #3921
> fix: dbt zombie process, set dbt default threads=1

- plugins/bitbucket/api/blueprint.go
- plugins/bitbucket/api/blueprint_test.go
Fixes an issue reported by a Slack user regarding using the git-extractor plugin on Bitbucket. The credential logic for the extractor was incorrect, leading to failed repo clones. This PR fixes that. It'll be ported back to v0.14.8 as well.
Closes #4138
> fix: Bitbucket git-extractor repo cloning fix

- docker-compose.yml
- releases/lake-v0.14.0/docker-compose.yml
Set grafana default theme to `light` when deploying grafana by docker-compose
> feat(grafana): change default theme

- .asf.yaml
This PR edits `.asf.yaml` to temporarily unprotect release-v0.14. Once we fix the branch, we'll issue another PR to add the protection back.
> chore: temporarily unprotect release-v0.14 branch

- .asf.yaml
This PR adds the protection for release-v0.14 branch back. We have fixed the branch head.
> chore: add protection for release-v0.14 back

- .dockerignore
- .github/workflows/build.yml
- Dockerfile
- Makefile
- config-ui/Dockerfile
Support multi-arch docker images build when version tag push
Some main changes:
- base image change to Debian, and put all things in one Dockerfile
- keep builder and base target cache in the docker registry as `devlake:builder` and `devlake:base`
- compile libgit2 from the source in the builder stage.
Closes #4016
The multi-arch images tagged with v0.15.0-alpha14 was pushed, and the arm64-based image works fine under M1 MacBook.
And the GitExtract plugin (Which requires libgit2, and was cross-compiled in this PR) should work correctly.
> feat: build multi-arch docker images for amd64 and arm64

- config-ui/src/pages/blueprint/components/advanced-editor/example/tapd.ts
- grafana/dashboards/EngineeringThroughputAndCycleTime.json
- grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
- plugins/tapd/tasks/bug_commit_collector.go
- plugins/tapd/tasks/story_bug_collector.go
- plugins/tapd/tasks/story_commit_collector.go
- plugins/tapd/tasks/task_commit_collector.go
1.  delete pageSize for story/bug/task_commits collection, because tapd story/bug/task_commits collection api don't have any param for pagination, it only needs one time collection, but with PageSize, devlake will collect `concurrency` times.
2. update tapd template for time filter
3. update cycle time with project_pr_metrics
> fix(tapd): fix minor bugs

- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
fix jenkins upgrade.
V100 bp with transformation may like this:
```
{
"name": "TEST_PROJECT_2-BLUEPRINT",
"mode": "NORMAL",
"enable": true,
"cronConfig": "0 0 * * *",
"isManual": false,
"skipOnFail": false,
"labels": [],
"settings": {"connections":[{"connectionId":1,"plugin":"jenkins","scope":[{"entities":["CICD"],"options":{},"transformation":{"deploymentPattern":"","productionPattern":""}}]}],"version":"1.0.0"},
"createdAt": "2022-12-12T08:36:38.079Z",
"updatedAt": "2022-12-13T08:31:51.696Z"
}
```
So add some fix for upgrade
> fix: fix jenkins upgrade

- impl/dalgorm/dalgorm.go
- plugins/github/api/transformation_rule.go
- plugins/github/models/migrationscripts/20221214_add_trasformation_rule_table.go
- plugins/github/models/migrationscripts/archived/transformation_rules.go
- plugins/github/models/transformation_rule.go
- plugins/gitlab/api/transformation_rule.go
- plugins/gitlab/models/migrationscripts/20221125_add_html_url_to_project.go
- plugins/gitlab/models/migrationscripts/archived/transformation_rules.go
- plugins/gitlab/models/transformation_rule.go
- plugins/jenkins/api/transformation_rule.go
- plugins/jenkins/models/migrationscripts/20221205_add_trasformation_rule_table.go
- plugins/jenkins/models/migrationscripts/archived/transformation_rules.go
- plugins/jenkins/models/transformation_rule.go
- plugins/jira/api/transformation_rule.go
- plugins/jira/models/migrationscripts/20221116_add_trasformation_rule_table.go
- plugins/jira/models/migrationscripts/archived/transformation_rule.go
- plugins/jira/models/transformation_rules.go
- plugins/jira/tasks/task_data.go
add a unique index for the column `name` of the following tables:
- `_tool_github_transformation_rules`
- `_tool_gitlab_transformation_rules`
- `_tool_jenkins_transformation_rules`
- `_tool_jira_transformation_rules`
empty or duplicate `name` value will return an error of `400 bad request` for the following API
- POST /plugins/github/transformation_rules
- POST /plugins/gitlab/transformation_rules
- POST /plugins/jenkins/transformation_rules
- POST /plugins/jira/transformation_rules
- PATCH /plugins/github/transformation_rules/{id}
- PATCH /plugins/gitlab/transformation_rules/{id}
- PATCH /plugins/jenkins/transformation_rules/{id}
- PATCH /plugins/jira/transformation_rules/{id}
> fix: add unique index for the name of transformation rule

- plugins/gitlab/tasks/api_client.go
- plugins/gitlab/tasks/pipeline_collector.go
limit the max rate limit = 200 for GitLab. Because the pipeline seems to have can only support about 250 requests per minute. Although Gitlab allow 2000 pre minute, I find that Devlake now can only use about 300 per minute by rateLimit header for GitLab. So I think we can set it to 200 at the most.
Closes #3192
> fix: limit the max rate limit = 200 for gitlab

- config-ui/src/pages/blueprint/components/advanced-editor/example/general.ts
- config-ui/src/pages/blueprint/components/advanced-editor/example/jenkins.ts
fix jenkins example bug. `jobFullName` is the correct name.
> fix: fix jenkins example bug

- plugins/github/models/migrationscripts/archived/transformation_rules.go
- plugins/github/models/transformation_rule.go
- plugins/gitlab/models/migrationscripts/archived/transformation_rules.go
- plugins/gitlab/models/transformation_rule.go
- plugins/jenkins/models/migrationscripts/archived/transformation_rules.go
- plugins/jenkins/models/transformation_rule.go
- plugins/jira/models/migrationscripts/archived/transformation_rule.go
- plugins/jira/models/transformation_rules.go
change the index name for the columns:
- `_tool_gitlab_transformation_rules.idx_name` ->  `_tool_gitlab_transformation_rules.idx_name_gitlab` 
- `_tool_github_transformation_rules.idx_name` ->  `_tool_github_transformation_rules.idx_name_github` 
- `_tool_jenkins_transformation_rules.idx_name` ->  `_tool_jenkins_transformation_rules.idx_name_jenkins` 
- `_tool_jira_transformation_rules.idx_name` ->  `_tool_ira_transformation_rules.idx_name_jira` 
otherwise, it would create the index for only **one** table on the Postgres database
Closes xx
> fix: fix can not create index with name idx_name for pg

- plugins/helper/graphql_async_client.go
- plugins/helper/graphql_collector.go
fix graphql cannot cancel.
cancel when getting ratelimit:
cancel when querying:
cancel when retry:
> fix: fix graphql cannot cancel

- grafana/dashboards/GitHub.json
- grafana/dashboards/Gitlab.json
We have the word Reivew written in 2 dashboards of graphana (GIthub and gitlab). With the change once you load the json again you will have the typo fixed
Closes xx
> style(graphana): Corrected typo on word Review

- README.md
Currently the supported-datasources table is duplicated in both the Readme and the Website docs. This PR will hyperlink the Readme to the website so that we only have a single source. This will ease the maintenance burden.
Closes #3095
> doc: Replace supported data-sources in Readme with a hyperlink to website

- impl/dalgorm/dalgorm.go
- plugins/core/dal/dal.go
Add `dal.RawCursor` back due to sometimes users might need to execute complicated SQL queries.
> feat: add `dal.RawCursor` back for compatibility

- DISCLAIMER
- DISCLAIMER-WIP
- LICENSE
- NOTICE
- requirements.txt
- remove pagerduty from the `requirements.txt`
- update the LICENSE file
- update the NOTICE file and supply the following information:
>  - [github.com/hashicorp/hcl] (https://github.com/hashicorp/hcl), licensed under the Mozilla Public License 2.0 License
> - [github.com/davecgh/go-spew] (https://github.com/davecgh/go-spew), licensed under the ISC License
> - [github.com/russross/blackfriday] (https://github.com/russross/blackfriday), licensed under the Simplified BSD License
> - [github.com/gogo/protobuf] (https://github.com/gogo/protobuf), licensed under the BSD License 2.0
> - [github.com/emirpasic/gods] (https://github.com/emirpasic/gods), licensed under the Simplified BSD License
> - [github.com/go-git/gcfg] (https://github.com/go-git/gcfg), licensed under the BSD License 2.0
> - …
> fix: fix the license issues

- backend/Dockerfile
due to alpine -->  debian, so we need to update `apk` to `apt-get` on tini, add docker init, solve zombie process.
Closes #3919 
> fix: update apk to apt-get on tini

- backend/server/services/pipeline.go
- backend/server/services/pipeline_helper.go
Directly assign labels from newPipeline to dbPipeline in `CreateDbPipeline`
In pr #4227, we didn't do this in `CreateDbPipeline`, we called `fillPipelineDetail` in `CreatePipeline`, this is not efficiency.
Relate to #4227 
> fix(framework): assign labels to dbpipeline in CreateDbPipeline

- .licenserc.yaml
- backend/Dockerfile
- backend/scripts/docker/mysql/init-ds.sql
- docker-compose.datasources.yml
Creates a new docker compose file to support running supported datasources locally. For starters, I am adding Jenkins, Jira and Bitbucket.
Relates to https://github.com/apache/incubator-devlake-website/issues/385
Potentially closes it too depending on feedback.
Tested locally and all three worked.
> feat: Docker-compose for data-sources

- backend/plugins/ae/api/connection.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/connection.go
- backend/plugins/sonarqube/tasks/api_client.go
According pr #4260, we modify sonarqube's connection to conform the new pattern. Then we can use multi-auth very easily in future
Relate to #4260 
> fix(sonarqube): modify connection to conform pr4260

- config-ui/package-lock.json
- config-ui/package.json
- config-ui/src/pages/blueprint/create/step-two/index.tsx
- config-ui/src/pages/blueprint/create/step-two/use-columns.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/plugins/components/data-scope-list/index.tsx
- config-ui/src/plugins/components/data-scope/index.tsx
- config-ui/src/plugins/components/data-scope/use-data-scope.ts
- config-ui/src/plugins/register/github/components/miller-columns/index.tsx
- config-ui/src/plugins/register/github/data-scope.tsx
- config-ui/src/plugins/register/gitlab/components/miller-columns/index.tsx
- config-ui/src/plugins/register/gitlab/components/project-selector/index.tsx
- config-ui/src/plugins/register/gitlab/data-scope.tsx
- config-ui/src/plugins/register/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jenkins/data-scope.tsx
- config-ui/src/plugins/register/jira/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jira/data-scope.tsx
- config-ui/src/utils/operator.ts
The previous modification to #4240 can only be said to be a patch, not a perfect solution, so the content of this part has been refactored.
1. simplify the selection and change of data scope
2. operator supports hidden toast
#4240
> refactor(config-ui): simplify the selection and change of data scope

- backend/plugins/bitbucket/tasks/pr_commit_collector.go
delete gitlab task in bitbucket.
bitbucket cannot run before this change.
> fix: delete gitlab task in bitbucket

- backend/plugins/bitbucket/api/blueprint_test.go
- backend/plugins/bitbucket/api/connection.go
- backend/plugins/bitbucket/models/connection.go
- backend/plugins/bitbucket/tasks/api_client.go
1. simplify bitbucket apiclient creation
2. remove unused struct: EpicResponse / BoardResponse
Part of #4298 
pipline
> refactor: simplify bitbucket apiclient creation

- backend/helpers/pluginhelper/api/connection_auths.go
- backend/plugins/ae/api/connection.go
- backend/plugins/ae/models/connection.go
- backend/plugins/azure/api/connection.go
- backend/plugins/bitbucket/api/connection.go
- backend/plugins/feishu/api/connection.go
- backend/plugins/feishu/models/connection.go
- backend/plugins/feishu/tasks/api_client.go
- backend/plugins/feishu/tasks/meeting_top_user_item_collector.go
1. change `connection_auths.go` to pointer type to avoid memory copy
2. simplify feishui apiclient creation
Part of #4298 
pipeline
> refactor: simplify feishui apiclient creation

- backend/helpers/pluginhelper/api/api_collector.go
add GetNextPageCustomData to support request pages one by one.
Related to #4292
add test code in collector:
```golang
collector, err := helper.NewApiCollector(helper.ApiCollectorArgs{
……
PageSize:           50,
Query: func(reqData *helper.RequestData) (url.Values, errors.Error) {
query := url.Values{}
query.Set("state", "all")
query.Set("pagelen", fmt.Sprintf("%v", reqData.Pager.Size))
if reqData.CustomData != nil {
query.Set("page", reqData.CustomData.(string))
}
return query, nil
},
GetNextPageCustomData: func(reqData *helper.RequestData, prevPageResponse *http.Response) (interface{}, errors.Error) {
resBody, err := io.ReadAll(prevPageResponse.Body)
// decode json from body
if rawMessages.Next == `` {
return ``, helper.ErrFinishCollect
}
u, err := url.Parse(rawMessages.Next) …
```
> feat: add GetNextPageCustomData to support request pages one by one

- backend/plugins/bitbucket/tasks/api_common.go
- backend/plugins/bitbucket/tasks/pr_commit_collector.go
- backend/plugins/bitbucket/tasks/pr_convertor.go
- Fix the pagination params on Bitbucket API and add a feature to get the PR merge datetime (in order to fix the Lead Time feature on DORA for Bitbucket plugin).
Closes #4285
After these modifications, DORA metrics dashboard shows these metrics.
> [Bitbucket] Pagination params and merged date on PRs

- backend/plugins/pagerduty/api/connection.go
- backend/plugins/pagerduty/models/connection.go
- backend/plugins/pagerduty/models/migrationscripts/20230203_add_endpoint_proxy_to_conn.go
- backend/plugins/pagerduty/models/migrationscripts/register.go
1. simplify pagerduty test onnection
2. remove incorrect migrationscript
3. fix pagerduty connection table
Part of #4298 
> refactor: simplify pagerduty test onnection

- backend/core/models/domainlayer/securitytesting/st_issues.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/tasks/hotspots_convertor.go
add hotspot convertor
part of #2305 
> feat(sonarqube): add hotspot convertor

- backend/plugins/sonarqube/api/scope.go
- backend/plugins/sonarqube/api/swagger.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue_code_block.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_project.go
- backend/plugins/sonarqube/models/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_issue_code_block.go
- backend/plugins/sonarqube/models/sonarqube_project.go
feat: add sonarqube scope and fix some models
part of #2305 
1. /plugins/sonarqube/connections/{connectionId}/scopes [PUT]
2. /plugins/sonarqube/connections/{connectionId}/scopes/ [GET]
3. /plugins/sonarqube/connections/{connectionId}/scopes/{projectKey} [GET]
4. /plugins/sonarqube/connections/{connectionId}/scopes/{projectKey} [PATCH]
> feat: add sonarqube scope and fix some models

- backend/helpers/pluginhelper/api/api_async_client.go
- backend/helpers/pluginhelper/api/api_collector.go
- backend/helpers/pluginhelper/api/worker_scheduler.go
- backend/helpers/pluginhelper/api/worker_scheduler_test.go
- backend/plugins/gitlab/tasks/api_client.go
- backend/plugins/gitlab/tasks/pipeline_collector.go
1. Added option `MinTickInterval` to `ApiCollector` to restrict the maximum RateLimit for a specific Collector
2. Set Gitlab pipeline Maximum RateLimit to 200reqs/min
3. Simplify WorkScheduler
Closes #4210
> feat: gitlab pipeline could have a different ratelimit to other subtasks

- backend/plugins/gitlab/api/remote.go
Add name for child
fix project id error
`curl --location --request GET 'devlake:8080/plugins/gitlab/connections/6/remote-scopes?groupId=4064756&pageToken='`
```json
{
"children": [{
"type": "scope",
"parentId": "4064756",
"id": "16773509",
"name": "Persper Licenses",
"data": {
"connectionId": 0,
"gitlabId": 16773509,
"name": "Persper Licenses",
"description": "Persper Foundation Licenses",
"defaultBranch": "master",
"pathWithNamespace": "persper/licenses",
"webUrl": "https://gitlab.com/persper/licenses",
"creatorId": 0,
"visibility": "public",
"openIssuesCount": 0,
"starCount": 0,
"forkedFromProjectId": 0,
"forkedFromProjectWebUrl": "",
"httpUrlToRepo": "https://gitlab.com/persper/licenses.git",
"createdDate": "2020-02-08T09:08:43.397Z",
"updatedDate": "2020-02-09T11:44:14.913Z"
}
}, { …
```
> fix: gitlab remote api fix

- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
Fixed transformation name is duplicated when upgrading bp.
> fix(config-ui): transformation name is duplicated when upgrading bp

- models/collector_state.go
- models/migrationscripts/20230213_add_updated_date_after_to_collector_state.go
- models/migrationscripts/register.go
- plugins/core/plugin_blueprint.go
- plugins/helper/api_collector_with_state.go
- plugins/jira/impl/impl.go
- plugins/jira/tasks/issue_collector.go
- plugins/jira/tasks/task_data.go
In order to address issue #4403 , the following actions were taken:
1. added `TimeAfter` to `collector_state` as well as jira `TaskOptions` and `TaskData`
2. `ApiCollectorStateManager.IsIncremental` was modified to take `TimeAfter` as the First Factor to consider, or fallback to `CreatedDateAfter` if `TimeAfter` omitted. In other words, `TimeAfter` would override the `CreatedDateAfter` option
3. JIRA `issue_collector` was modified to follow the principle accordingly
Closes #4403
The initial collection, should respect the `timeAfter` option
Whenever an older issue got updated, it should be collected.
> feat: jira supports timefilter by updated_at

- backend/plugins/sonarqube/api/remote.go
Fix remote api according to #4411
part of #2305 
```shell
curl --request GET \
--url 'http://127.0.0.1:8080/plugins/sonarqube/connections/1/remote-scopes?pageToken=eyJwYWdlIjoyLCJwZXJfcGFnZSI6MTAsInRhZyI6IiJ9' \
--header 'content-type: multipart/form-data'
```
```shell
curl --request GET \
--url 'http://127.0.0.1:8080/plugins/sonarqube/connections/1/search-remote-scopes?search=AndroidUtilCode' \
--header 'content-type: multipart/form-data'
```
> fix(sonarqube): fix remote api

- backend/plugins/github/tasks/api_client.go
According to issue #4387 , if users are using github enterprise server, the response header does not have `X-RateLimit-Limit`. Under this situation, we can just use globalRatelimit in devlake
Closes #4387
> fix(github): process situation without ratelimit header

- backend/generator/template/plugin/api/connection.go-template
- backend/plugins/azure/api/connection.go
- backend/plugins/bitbucket/api/connection.go
- backend/plugins/feishu/api/connection.go
- backend/plugins/gitee/api/connection.go
- backend/plugins/jenkins/api/connection.go
- backend/plugins/jira/api/connection.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/sonarqube/api/remote.go
- backend/plugins/tapd/api/connection.go
- backend/plugins/zentao/api/connection.go
This pr mainly fixed sonarqube test connection response to keep it similar to gitlab and github.
And also fixed zentao, tapd, jira
After we unified all test connection response, @mintsweet can process all test connection response in the same way
part of #2305 
bitbucket
jira
jenkins
sonarqube
tapd:
zentao
> fix(plugins): unify test connection response

- backend/plugins/sonarqube/api/scope.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_project.go
- backend/plugins/sonarqube/models/sonarqube_project.go
1. In SonarqubeProject, add `json:"connectionId" for ConnectionId
2. change decode method in put scope, because we should process time.  mapstructure.Decode cannot convert string to a time.Time or Iso8601Time
part of #2305
> fix(sonarqube): put scope bug

- backend/plugins/bamboo/api/connection.go
- backend/plugins/bamboo/models/connection.go
We can use RESOURCE_NAME.json to get json data.
One more thing, instead of getting repository to test connection, we'd better get server info to support multiple versions of bamboo in future
Closes xx
> fix(bamboo): simplify test connectino and use json instead of xml

- backend/plugins/github/api/blueprint_v200.go
- backend/plugins/github/github.go
- backend/plugins/github/impl/impl.go
- backend/plugins/github/tasks/cicd_run_collector.go
- backend/plugins/github/tasks/comment_collector.go
- backend/plugins/github/tasks/commit_collector.go
- backend/plugins/github/tasks/issue_collector.go
- backend/plugins/github/tasks/pr_collector.go
- backend/plugins/github/tasks/pr_commit_collector.go
- backend/plugins/github/tasks/pr_review_collector.go
- backend/plugins/github/tasks/pr_review_comment_collector.go
- backend/plugins/github/tasks/task_data.go
- backend/plugins/github_graphql/impl/impl.go
- backend/plugins/github_graphql/plugin_main.go
- backend/plugins/github_graphql/tasks/check_run_collector.go
- backend/plugins/github_graphql/tasks/issue_collector.go
- backend/plugins/github_graphql/tasks/pr_collector.go
Rename `createdDateAfter` to `timeAfter` for github and github_graphql
Part of #4403
> refactor: rename createdDateAfter to timeAfter for github

- backend/plugins/bamboo/models/connection.go
- backend/plugins/bamboo/models/migrationscripts/20230216_add_init_tables.go
- backend/plugins/bamboo/models/migrationscripts/archived/connection.go
As we need to support bamboo 6.8.1, we have to use basic auth
part of #3322 
> fix(bamboo): change connection auth type

- backend/core/runner/loader.go
- backend/python/pydevlake/README.md
- backend/python/pydevlake/pydevlake/__init__.py
- backend/python/pydevlake/pydevlake/context.py
- backend/python/pydevlake/pydevlake/doc.template.json
- backend/python/pydevlake/pydevlake/docgen.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/message.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/subtasks.py
- backend/python/pydevlake/test/remote_test.go
- backend/python/pydevlake/test/stream_test.py
- backend/server/services/remote/models/models.go
- backend/server/services/remote/plugin/default_api.go
- backend/server/services/remote/plugin/init.go
- backend/server/services/remote/plugin/plugin_impl.go
- backend/server/services/remote/plugin/scope_api.go
- backend/server/services/remote/plugin/transformation_rule_api.go
- backend/test/remote/fakeplugin/fakeplugin/main.py
Add support for transaction rule and scope APIs for python plugins.
Closes 4437
> feat(pyplugins): tx rule scope ap is py

- backend/plugins/github/tasks/cicd_run_collector.go
github runs collector supports timeFilter/diffSync
Due to the fact that github runs API doesn't support `since`(filter by updated_at) parameter, 
this PR uses another approach to support timeFilter and diffSync:
1. Collect newly added records by examining the `created_at` field
2. Load unfinished records in the database and collect their details from API if diffSync is in action
Part of #4403
I took the following steps to verify:
1. I set the `timeAfter`, and collect data, and observed the database, it worked as expected
2. I then reran the task with the same parameters as the previous step, and no data changed which is correct
3. I then modified the `timeAfter` parameter to a later date and the database stay the same which is correct
4. lastly, I pushed `timeAfter` to an older date and …
> feat: github runs collector supports timeFilter/diffSync

- backend/plugins/github/tasks/cicd_run_collector.go
fix: check array length before accessing for github run collector
> fix: check array length before accessing for github run collector

- config-ui/src/plugins/register/github/api.ts
- config-ui/src/plugins/register/github/components/miller-columns/use-miller-columns.ts
GitHub does not list private membership organizations.
Closes #4439
> fix(config-ui): github does not list private membership organizations

- backend/plugins/bamboo/tasks/job_build_collector.go
- backend/plugins/bamboo/tasks/job_collector.go
- backend/plugins/bamboo/tasks/plan_build_collector.go
- backend/plugins/bamboo/tasks/plan_collector.go
Before, we use reqData.page * size to express start_index for bamboo entities, according to review for #4460 , we can use reqData.skip instead.
part of #3322 
> fix(bamboo): use skip to replace page * size

- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
- devops/releases/lake-v0.14.0/docker-compose.yml
- devops/releases/lake-v0.15.0/docker-compose.yml
- docker-compose.yml
1. In mysql, the default collation is utf8mb4_general_ci is case insensitive. So when I was working on sonarqube dashboard, I found that we missed some data.
This pr mainly add the following to mysql part in docker-compose.yml:
```yaml
command:
--character-set-server=utf8mb4
--collation-server=utf8mb4_bin
```
utf8mb4_bin is case sensitive
2. In addition, because we need to update Sonarproject.LastAnalysisDate, we need to request apiProject whenever we want to collect data. 
part of #2305 
> fix(sonarqube): fix data loss

- backend/plugins/github/tasks/comment_collector.go
- backend/plugins/github/tasks/commit_collector.go
- backend/plugins/github/tasks/issue_collector.go
- backend/plugins/github/tasks/pr_commit_collector.go
- backend/plugins/github/tasks/pr_review_collector.go
- backend/plugins/github/tasks/pr_review_comment_collector.go
Rename all `CreatedDateAfter` to `TimeAfter` for  github
Part of #4403
> refactor: github to adopt timeAfter param

- backend/plugins/gitlab/api/blueprint_v200.go
- backend/plugins/gitlab/gitlab.go
- backend/plugins/gitlab/impl/impl.go
- backend/plugins/gitlab/tasks/issue_collector.go
- backend/plugins/gitlab/tasks/job_collector.go
- backend/plugins/gitlab/tasks/mr_collector.go
- backend/plugins/gitlab/tasks/mr_commit_collector.go
- backend/plugins/gitlab/tasks/mr_detail_collector.go
- backend/plugins/gitlab/tasks/mr_note_collector.go
- backend/plugins/gitlab/tasks/pipeline_collector.go
- backend/plugins/gitlab/tasks/pipeline_detail_collector.go
- backend/plugins/gitlab/tasks/shared.go
- backend/plugins/gitlab/tasks/task_data.go
1. Replaced `createdDateAfter` with `timeAfter`
2. Fixed collectors diffSync didn't work properly
Part of #4403
> refactor: gitlab adopt timeAfter option

- backend/plugins/bamboo/tasks/job_build_collector.go
- backend/plugins/bamboo/tasks/job_collector.go
- backend/plugins/bamboo/tasks/plan_build_collector.go
- backend/plugins/bamboo/tasks/plan_collector.go
- backend/plugins/bamboo/tasks/task_data.go
change `NewApiCollectorWithState` back to NewApiCollector as we don't need bamboo to support diff sync for right now.
part of #3322 
> refactor(bamboo): change back to NewApiCollector

- backend/plugins/jira/impl/impl.go
Add tasks.ConvertIssueLabelsMeta to SubTaskMetas. Fix the bug of missing records in the table `issue_labels`
Closes #4500
> fix: add tasks.ConvertIssueLabelsMeta to SubTaskMetas

- plugins/jira/impl/impl.go
Cherry-pick #4503 fix: add tasks.ConvertIssueLabelsMeta to SubTaskMetas
Closes #4500
> cherry pick#4503 fix: add tasks.ConvertIssueLabelsMeta to SubTaskMetas (#4503)

- backend/plugins/bitbucket/api/blueprint_v200.go
- backend/plugins/bitbucket/bitbucket.go
- backend/plugins/bitbucket/impl/impl.go
- backend/plugins/bitbucket/tasks/api_common.go
- backend/plugins/bitbucket/tasks/issue_collector.go
- backend/plugins/bitbucket/tasks/issue_comment_collector.go
- backend/plugins/bitbucket/tasks/pipeline_collector.go
- backend/plugins/bitbucket/tasks/pipeline_steps_collector.go
- backend/plugins/bitbucket/tasks/pr_collector.go
- backend/plugins/bitbucket/tasks/pr_comment_collector.go
- backend/plugins/bitbucket/tasks/pr_commit_collector.go
- backend/plugins/bitbucket/tasks/task_data.go
1. renamed `createdDateAfter` to `timeAfter`
2. add special increment collector for deployment collector
Part of #4403
> refactor: bitbucket adopts timeAfter

- backend/plugins/starrocks/impl/impl.go
- backend/plugins/starrocks/tasks/tasks.go
refactor starrocks, improve performance, solve bugs.
Closes #4418 
Closes #4376 
Closes #4377 
export data:
cancel task:
pipeline is blocked for 30+ mins：
> refactor: refactor starrocks, improve performance, solve bugs

- backend/plugins/bitbucket/tasks/api_common.go
format timeAfter to RFC3339 for updated_on in bitbucket.
> fix: format timeAfter to RFC3339 for updated_on

- backend/plugins/webhook/impl/impl.go
revert webhook migrator changes. It's a bug imported when path moving.
Related to https://github.com/apache/incubator-devlake/issues/2078,  https://github.com/apache/incubator-devlake/pull/3884/files#diff-d10872fce1824a1b10e8d38d64f631b56ccbb8b3f987a27d229f9b1b80b79018R60
> fix: revert webhook migrator changes

- backend/plugins/bitbucket/tasks/pipeline_steps_convertor.go
Fix the subtask convertPipelineSteps ended with an error.
The bug was caused by trying to insert a record with an empty `started_date` in the database. In this PR, this type of record was ignored.
Closes #4552
> fix: subtask convertPipelineSteps ended with error

- backend/server/api/api.go
pr #4518 just changed logic of extracting port from .env, but didn't considered old port in .env, so this pr  just cut the prefix `:` if port contains that
Closes #4496 
> fix(framework): adapt old port in dotenv

- backend/core/models/blueprint.go
- backend/plugins/webhook/api/blueprint_v200.go
- backend/server/services/pipeline.go
1. add some log; 
2. wait when the query fails in RunPipelineInQueue. The old logic will run pipeline when `err != nil` and err is not RecordNotFound.
Related to #4486
> fix: add some log; wait when query fail in RunPipelineInQueue

- backend/plugins/bitbucket/api/blueprint_V200_test.go
- backend/plugins/bitbucket/api/blueprint_v200.go
Fix the gitextractor can not clone bitbucket private repos.
It was caused by using `git` rather than the actual username when constructing the clone URL 
Closes #4558
> fix: gitextractor can not clone bitbucket private repos

- backend/plugins/bitbucket/e2e/repo_test.go
Fix #4572 
This bug is caused by using the wrong file name
Closes #4572
> fix: extra csv file generated during e2e test

- backend/plugins/webhook/api/blueprint_v200.go
- backend/plugins/webhook/api/connection.go
- backend/plugins/webhook/api/issue.go
- backend/plugins/webhook/impl/impl.go
board id can not match project_mapping row_id by webhook plugin. 
remove the boardKey, same to Jira.
Closes #4574 
> fix: board id can not match project_mapping row_id by webhook plugin

- backend/plugins/zentao/models/archived/department.go
- backend/plugins/zentao/models/department.go
- backend/plugins/zentao/models/migrationscripts/20221121_add_init_tables.go
- config-ui/src/plugins/register/zentao/config.ts
1. fix zentao cannot run in pg; 
2. add min version tips
Closes #4578 
All data are collected in at least 1 row.
> fix: fix zentao cannot run in pg; add min version tips

- backend/plugins/bitbucket/tasks/pr_extractor.go
check nil for HeadRef and BaseRef. No logic changed
Closes #4306
> fix: check nil for HeadRef and BaseRef

- backend/plugins/zentao/tasks/execution_collector.go
- backend/plugins/zentao/tasks/project_collector.go
- backend/plugins/zentao/tasks/task_collector.go
- backend/plugins/zentao/tasks/task_data.go
We just skip tasks which depend on executionId if executionId is not assigned
Closes #4601 
when execution id is 0, we can see we didn't collect any data
> fix(zentao): skip tasks if relevent id is zero

- backend/plugins/webhook/api/cicd_pipeline.go
fill `Repo` as repoUrl from request; fill `RepoId` as `repos.id` if url equals.
Closes #4599
> fix: add related repo id for webhook deployments

- config-ui/src/plugins/register/gitlab/config.tsx
Fixed doc link for gitlab connection token.
> fix(config-ui): doc link for gitlab connection token

- config-ui/nginx.conf
- config-ui/nginx.sh
In our deployment Grafana and Devlake are using HTTPS. This change allows us to proxy to those endpoints without having to modify the image ourselves.
This should retain the existing behavior and therefore be backwards compatible.
N/A
N/A
N/A
> feat: allow protocol used in proxying to be overridden

- backend/plugins/jira/tasks/task_data.go
- backend/plugins/jira/tasks/task_data_test.go
Fix #4637 
The default value of `_tool_jira_transformation_rules.remotelink_repo_pattern` in the database could not be unmarshaled into a string slice.
Closes #4637
> fix: jira error on unMarshaling RemotelinkRepoPattern

- backend/Makefile
It seems that the target `python-dep` has the wrong path.
> fix(Makefile): wrong python-dep path

- backend/core/runner/db.go
What does this PR do? 
DB connection strings can now have special chars without problems.
Closes #4664
> [fix-4664]: GORM init fix to allow special characters in connection string

- backend/plugins/github_graphql/tasks/pr_collector.go
fix: decrease page size for github graphql pr collector
It may slow than the old pr collector about 20%.
Related to #3708
> fix: decrease page size for github graphql pr collector

- backend/python/pydevlake/pydevlake/domain_layer/code.py
- backend/python/pydevlake/pydevlake/domain_layer/devops.py
I don't think these are right. Without this change it seems as though the value in the DB will always be set to something like:
```
typing.Optional[pydevlake.domain_layer.devops.CICDResult]
```
N/A
N/A
N/A
> Fix type annotations

- config-ui/nginx.conf
> Cherry pick 4670 to v0.16 - fix: nginx timeout is too short causing download log fails with 504

- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
Missed `timeAfter` after change data scope.
> fix(config-ui): missed timeAfter after change data scope

- backend/plugins/tapd/tasks/bug_status_extractor.go
- backend/plugins/tapd/tasks/story_status_extractor.go
Tapd sometimes return `[]` for bugStatus and storyStatus, so we can just return nil if we meet this situation.
part of  #4680 
> fix(tapd): return nil if row data is an empty array

- backend/plugins/starrocks/tasks/tasks.go
add gorm close.
When using GORM to connect to the database, if you do not manually call the db.Close() method to close the connection, the connection will be returned to the GORM connection pool after the program is executed. At this point, the state of the connection will change to "idle", indicating that the connection is idle and available for other requests.
In GORM, if there is no connection available in the connection pool, then GORM will create a new connection. If there is a free connection in the connection pool, GORM will get a connection from the connection pool and assign it to the request.
Under normal circumstances, there should always be some idle connections in the connection pool, so as to meet the needs of concurrent requests. If the number of idle connections in the …
> fix: add db close connection

- config-ui/nginx.conf
Increase nginx proxy timeout to accommodate download log API
Closes #4656
> fix: nginx timeout is too short causing download log fails with 504

- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/pyproject.toml
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/model.py
- backend/server/services/remote/plugin/connection_api.go
- Make connection.name optional when calling test-connection
- Include error messages in response body
- Rename connection's `pat` to `token`
- Allow empty connection's `proxy`
> Improve test connection

- backend/core/dal/dal.go
- backend/core/plugin/plugin_blueprint.go
- backend/plugins/org/api/types.go
- backend/plugins/org/e2e/project_mapping_test.go
- backend/plugins/org/e2e/snapshot_tables/project_mapping.csv
- backend/plugins/org/impl/impl.go
- backend/plugins/org/tasks/project_mapping.go
- backend/plugins/org/tasks/task_data.go
- backend/server/services/blueprint_makeplan_v200.go
- backend/server/services/blueprint_makeplan_v200_test.go
The binding between project and scopes is performed by the subtask `SetProjectMapping`.  We defined a new interface `ProjectMapper` implemented by the plugin org. While creating the blueprint, the framework will find the org plugin and invoke its `MapProject` method. 
Closes #4534
> feat: set project mapping by plugin org

- backend/plugins/jira/models/issue_commit.go
- backend/plugins/jira/models/migrationscripts/20230322_expand_remotelink_url.go
- backend/plugins/jira/models/migrationscripts/register.go
- backend/plugins/jira/models/remotelink.go
Fix #4726 ([Bug][JIRA] long URL exceeding the current limit of URL column for jira integration)
Expand `_tool_jira_remotelinks.url` and `_tool_jira_issue_commits.commit_url` to `LONGTEXT`
Closes #4726
> fix: expand Jira remotelink to LONGTEXT

- config-ui/src/plugins/components/connection-form/fields/app-id.tsx
- config-ui/src/plugins/components/connection-form/fields/index.tsx
- config-ui/src/plugins/components/connection-form/fields/secret-key.tsx
- config-ui/src/plugins/components/connection-form/operate/test.tsx
- config-ui/src/plugins/config.ts
- config-ui/src/plugins/register/teambition/assets/icon.svg
- config-ui/src/plugins/register/teambition/config.tsx
- config-ui/src/plugins/register/teambition/connection-fields/index.ts
- config-ui/src/plugins/register/teambition/connection-fields/styled.ts
- config-ui/src/plugins/register/teambition/connection-fields/tenant-id.tsx
- config-ui/src/plugins/register/teambition/connection-fields/tenant-type.tsx
- config-ui/src/plugins/register/teambition/index.ts
Let config ui support teambition connection. Since there is no teambition logo, I use tapd logo instead temporarily.
Closes #4774
> feat(config-ui): support teambition connection config

- backend/plugins/tapd/tasks/shared.go
- backend/plugins/tapd/tasks/shared_test.go
This PR introduces improvements to the unit tests within the Tapd plugin. Specifically, it:
Adds tests for parseIterationChangelog, GetRawMessageDirectFromResponse, getTapdTypeMappings, getStdTypeMappings, getStatusMapping, getDefaultStdStatusMappingEmptyStatusList, unicodeToZh, convertUnicode, and generateDomainAccountIdForUsers functions.
This change enhances the overall test coverage and reliability of the Tapd plugin.
part of #4765 
> test(tapd): add unit test for shared

- backend/plugins/dora/tasks/change_lead_time_calculator.go
- backend/plugins/dora/tasks/change_lead_time_calculator_test.go
This pull request addresses the issue of code complexity and readability in the CalculateChangeLeadTime function. To improve code quality and maintainability, we have undertaken the following refactoring steps:
1. Extract complex logic into a separate function: We have identified the complex logic related to building deployment pairs and extracted it into a new function called buildDeploymentPairs. This function now handles the deployment pairs construction, making the main function easier to understand.
2. Add comments for better understanding: We have added comments to the newly extracted buildDeploymentPairs function, explaining its purpose and functionality. This will help other developers to better understand the code and contribute effectively.
3. Implement unit tests for the …
> Refactor(dora): Refactor CalculateChangeLeadTime Function for Improved Readability and Maintainability

- devops/releases/lake-v0.16.0/docker-compose.yml
- docker-compose.yml
This PR addresses the issue of rapid MySQL database size growth due to the storage of binlogs. By adding the --skip-log-bin option to the MySQL configuration, we effectively disable the creation and storage of binlogs, thus reducing the rate at which the database size increases.
Closes #4797 
This change was made by adding the --skip-log-bin option to the mysql section in the configuration file:
```yaml
Copy code
mysql:
image: mysql:8
volumes:
- mysql-storage:/var/lib/mysql
restart: always
ports:
- 3306:3306
environment:
MYSQL_ROOT_PASSWORD: admin
MYSQL_DATABASE: lake
MYSQL_USER: merico
MYSQL_PASSWORD: merico
command:
--character-set-server=utf8mb4
--collation-server=utf8mb4_bin
--skip-log-bin
```
This modification should help in managing the growth …
> fix(release): add skip binlog for mysql

- backend/plugins/jira/tasks/epic_extractor.go
- backend/plugins/jira/tasks/issue_extractor.go
The Jira `Epic` issues were not saved in the previous versions. It is fixed by storing them in the table `_tool_jirta_board_issues`, `board_issues`, and `issues`.
Closes #4549
> fix: save the epic type issues as well as the normal issues

- grafana/dashboards/DORA.json
Median Lead Time for Changes from a different blueprint/project
add `pm.project_name in ($project)` condition to sql
Closes #4727 
old:
new:
> fix: Median Lead Time for Changes from a different blueprint/project

- backend/core/plugin/plugin_connection_abstract.go
- backend/helpers/pluginhelper/api/iso8601time_test.go
- backend/helpers/pluginhelper/api/mapstructure.go
- backend/helpers/pluginhelper/api/mapstructure_test.go
- backend/helpers/pluginhelper/api/remote_api_helper.go
- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/transformation_rule_helper.go
- backend/plugins/bamboo/api/remote.go
- backend/plugins/bitbucket/api/remote.go
- backend/plugins/gitlab/api/remote.go
- backend/plugins/jira/api/transformation_rule.go
- backend/plugins/sonarqube/api/remote.go
- backend/plugins/trello/api/scope.go
- backend/plugins/trello/api/transformation_rule.go
- backend/plugins/webhook/api/cicd_pipeline.go
- backend/plugins/webhook/api/issue.go
- backend/plugins/zentao/api/remote.go
- backend/server/services/blueprint.go
- backend/server/services/project.go
1. add prepareFirstToken api. Sometimes we have custom params to query remote scope, like tapd company id.
2. update tr helper decode type. To avoid difficult decode like jira.
Related to #4566
> feat: add prepareFirstToken api; update tr helper decode type

- .github/workflows/build.yml
fix: build and push devlake base failed when push a new tag
add backend path to context.
related to #4763 
> fix: build and push devlake base failed when push a new tag

- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/pydevlake/pydevlake/__init__.py
- backend/python/pydevlake/pydevlake/message.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/testing/__init__.py
- backend/server/services/remote/plugin/remote_scope_api.go
- backend/test/integration/helper/models.go
- backend/test/integration/remote/python_plugin_test.go
- Add support for azure devops API tokens limited to a single organization
- Fix missing data in remote scopes responses
- Remote test warning
> Support token limited to single organization

- backend/core/utils/ipc.go
- backend/go.mod
- backend/python/pydevlake/pydevlake/__init__.py
- backend/python/pydevlake/pydevlake/helpers/debugger.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/subtasks.py
- backend/python/test/fakeplugin/fakeplugin/main.py
- backend/server/services/remote/bridge/bridge.go
* Adds a missing nil check on Go side which was causing crashes whenever Python would stream back a "RemoteProgress". This would get triggered if the number of records fetched on Python side was greater than 100 (or the default value of sync_point_interval in general) which is why we hadn't ran into it before in our light-weight tests. Tests updated to use larger datasets.
* Logic fix for progress counter which would always stay at 0 and possibly skip the last update.
* Some fixes to the Python remote debugger as I encountered issues during testing
Closes #4772 
> [fix-4772]: Python progress update crashes Go DevLake server

- backend/plugins/jenkins/tasks/build_collector.go
fix: jenkins build collectUnfinishedDetails add filter condition.
CollectUnfinishedDetails.BuildInputIterator This function should only return "builds that have not yet finished running"
reletad to #4535 
> fix: jenkins build collectUnfinishedDetails add filter condition

- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/server/services/remote/bridge/cmd.go
- backend/server/services/remote/models/models.go
- backend/server/services/remote/plugin/connection_api.go
- backend/server/services/remote/plugin/default_api.go
- backend/server/services/remote/plugin/scope_api.go
- backend/server/services/remote/plugin/transformation_rule_api.go
- config-ui/src/plugins/components/data-scope-form/index.tsx
- config-ui/src/plugins/components/transformation-form/index.tsx
- config-ui/src/plugins/components/transformation/index.tsx
- config-ui/src/plugins/register/azure/config.tsx
- config-ui/src/plugins/register/azure/connection-fields/base-url.tsx
- config-ui/src/plugins/register/azure/connection-fields/index.ts
- config-ui/src/plugins/register/azure/connection-fields/styled.ts
- config-ui/src/plugins/register/azure/data-scope.tsx
- config-ui/src/plugins/register/azure/styled.ts
- config-ui/src/plugins/register/azure/transformation.tsx
- config-ui/src/plugins/register/azure/types.ts
support plugin azure devops.
Closes #3321
> feat(config-ui): support plugin azure devops

- backend/server/services/remote/models/models.go
- backend/server/services/remote/plugin/scope_api.go
- backend/test/integration/remote/helper.go
Commit 4c07a8113 renamed two JSON tags of server/services/remote/models/models.go:ScopeModel fields. 
This made the python_plugin_test.go tests fail for all builds.
> fix: Fix failing tests

- backend/plugins/jira/tasks/issue_changelog_convertor.go
**Why**
The current validation in convertIds function only guards against leading/trailing white space. This can cause an issue if other characters such as `[` or `]` are included in the ids input by the caller e.g. 123,[90],65
Resulting in errors such as
```
time="2023-03-30 12:46:45" level=error msg=" [pipeline service] [pipeline #1] run tasks failed
caused by: Error running task 70.
Wraps: (2) subtask convertIssueChangelogs ended unexpectedly
Wraps: (3) error calling Converter plugin implementation
Wraps: (4) strconv.ParseUint: parsing "[90]": invalid syntax
Wraps: (5) strconv.ParseUint: parsing "[90]"
Wraps: (6) invalid syntax
Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *hintdetail.withDetail (5) *strconv.NumError (6) …
```
> fix: ensure Changelog IDs are numeric

- .asf.yaml
This PR adds CamilleTeruel as a collaborator so Camille can approve workflow runs.
> misc: add CamilleTeruel as a collaborator

- backend/core/models/migrationscripts/20230405_rename_tap_collector_state.go
- backend/core/models/migrationscripts/register.go
- backend/helpers/pluginhelper/tap/models.go
Rename the table used by singer-tap state tracking logic so it's not confused by the one already used by the normal state table. 
Closes #4249 
> refactor: Rename state table used by Singer framework

- backend/plugins/starrocks/tasks/tasks.go
fix cached plan must not change result type in customize 
Closes #4867 
> fix: cached plan must not change result type in customize

- grafana/dashboards/DORA.json
fix: the unit of Y-axis for change failure rate is incorrect
Closes #4882 
> fix: the unit of Y-axis for change failure rate is incorrect

- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
Project name not encode in blueprint connection page.
> fix(config-ui): project name not encode in blueprint connection page

- backend/plugins/dora/e2e/snapshot_tables/project_pr_metrics.csv
- backend/plugins/dora/tasks/change_lead_time_calculator.go
This pr refactors the code to improve the calculation of metrics related to pull requests (PRs) in the specified project. The previous implementation had several issues related to incorrect time calculations, which have been resolved in this update.
The main changes made in this pr are:
1. The calculation of the cycle time for a PR now takes into account the earliest date between the PR creation date and the deployment task finished date.
2. If a pr has not been deployed, we will not calculate its cycletime
Closes #4853
> fix(dora): ignore to calculate cycletime if pr has not been deployed

- backend/plugins/bamboo/e2e/plan_build_commits_test.go
- backend/plugins/bamboo/e2e/plan_build_test.go
- backend/plugins/bamboo/e2e/snapshot_tables/_tool_bamboo_plan_build_commits.csv
- backend/plugins/bamboo/e2e/snapshot_tables/cicd_pipeline_commits.csv
- backend/plugins/bamboo/tasks/plan_commit_convertor.go
- Fill in the `cicd_pipleline_commits.repo_url` for bamboo plugin
- e2e test for `ConvertPlanVcs`
Part of https://github.com/apache/incubator-devlake/issues/4869
> fix: missing repo_url

- backend/plugins/jira/tasks/issue_collector.go
- backend/plugins/jira/tasks/issue_collector_test.go
A user reported a timezone-related issue with a Jira plugin: https://github.com/apache/incubator-devlake/issues/4902. The most important information is a log that the user provided, which includes a timestamp and some debug information.
```text
time="2023-04-11 13:51:26" level=debug msg=" [pipeline service] [pipeline #2] [task #2] [collectIssues] fetchAsync >>> done for agile/1.0/board/1302/issue map[expand:[changelog] jql:[updated >= '2023/04/11 20:20' AND updated >= '2022/10/11 00:00' AND created is not null ORDER BY created ASC] maxResults:[100] startAt:[0]] <nil>"
```
There are two issues with the log: 
1.  the "updated" field appears twice in the JQL query
2.  the log timestamp is earlier than the "updated" timestamp
```go
if data.TimeAfter != nil {
jql = fmt.Sprintf("updated >= '%v' …
```
> fix: the jql time zone issue

- .github/ISSUE_TEMPLATE/bug-report.yml
Update the bug report template to include v0.16.0
No
> chore: update bug report template to include v0.16.0

- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/tests/streams_test.py
- backend/python/pydevlake/pydevlake/domain_layer/devops.py
Rename the repo field of CiCDPipelineCommit in pydevlake and in azuredevops plugin
to matche recent changes on go-side counterpart struct.
Not on its own but is part of #4869.
@klesh
> Rename CiCDPipelineCommit.repo to repo_url

- backend/plugins/dora/impl/impl.go
- backend/plugins/dora/tasks/change_lead_time_calculator.go
- backend/plugins/dora/tasks/prev_deployment_commit_enricher.go
- backend/plugins/refdiff/e2e/deployment_commit_diff/commits_diffs.csv
- backend/plugins/refdiff/e2e/deployment_commit_diff/finished_commits_diffs.csv
- backend/plugins/refdiff/tasks/deployment_commit_diff_calculator.go
update DORA blueprint v200 code to adopt the new flow
Closes #4869
With this last step, the Jenkins builds can be included in Change Lead Time calculation:
bitbucket repo: https://bitbucket.org/zhenmianws/jks/src/main/
> Refactor Change Lead Time - Step 8: update DORA blueprint v200 code to adopt the new flow

- backend/server/services/remote/plugin/plugin_impl.go
Fix remotePluginImpl.RootPkgPath that caused the domain id generator to generate wrong plugin names in domain ids..
Closes #4970
> fix: Fix wrong package name in domain ids

- backend/helpers/pluginhelper/api/graphql_collector.go
Before going any further, let's take a look at an example.
```go
var f struct {
I int     `json:"i"`
A *string `json:"a"`
}
blob1 := `{"i": 42, "a": "hello"}`
json.Unmarshal([]byte(blob1), &f)
blob2 := `{"i": 42}`
json.Unmarshal([]byte(blob2), &f)
fmt.Println(*f.A)
```
The output of this piece of code would be "hello", because the `blob2` has no "a" key, the field `f.A` would keep the value set at the last time. 
The `ExtractExistRawData` function in the `GraphqlCollector` suffers from the same issue. During each iteration of the loop, the same query object is being populated by a call to `json.Unmarshal`, causing the previous field values to persist. To fix this issue, we propose creating a new query object during each iteration of the loop.
Here's the relevant code:
```go
query, …
```
> fix: resolution_date is earlier than created_date

- config-ui/src/pages/project/home/index.tsx
missed margin between DORA link and wording.
> fix(config-ui): missed margin between DORA link and wording

- backend/plugins/github_graphql/impl/impl.go
This is a fix for #4962, as #4962 only changed github restful. This pr added type/env enrichment in graphQL
Part of https://github.com/apache/incubator-devlake/issues/4869
> fix(github): add regex enricher for deployment in graphql

- config-ui/src/utils/request.ts
When basic auth is enable, the following dialog from Chrome browser would never go away.
It was caused by the code overwriting the `Authorization` header set by the Browse, practically defeating the Basic Authentication Mechanism
Closes #5021
> fix: chrome asks user/pass infinitely when basic auth enabled

- backend/core/runner/run_task.go
- backend/helpers/pluginhelper/api/worker_scheduler.go
fix #5018 [Bug][Framework] Recovered errors from panics are not logged when SkipOnFail flag is set to true
Closes #5018
> fix: log the panic errors

- backend/plugins/dora/tasks/deployment_commits_generator.go
Problem: the record in the following screenshot was produced by the `dora.deployment_commit_generator` which is incorrect because it doesn't meet the criteria
Why: this is caused by the incorrect SQL condition:
The `t.type = p.type` and the `OR` operator are used in conjunction which is incorrect
> fix: deployment_commit_generator produced unwanted records

- backend/plugins/github/tasks/cicd_run_convertor.go
- backend/plugins/github_graphql/tasks/job_collector.go
for the `apache/incubator-devlake` repo with the following `transformation settings`
we are expecting to see [this github action](https://github.com/apache/incubator-devlake/actions/runs/4782906377) to be appear in `cicd_deployment_commits` table.
However, it didn't happen because the essential information for `cicd_deployment_commits` record to be generated was missing.
1. the `type` and `env` fields were not loaded from the database
2. during the investigation, I found out the `github_graphql` doesn't enrich the `type` / `env` as well, it is not the direct cause of the above problem. but it clearly a bug, might fix it as well.
With this fix, the `cicd_deployment_commits` can be produced correctly:
> Github workflow run/job doesn't end up in cicd_deployment_commits table with correct Regex

- backend/plugins/pagerduty/tasks/incidents_collector.go
right now, pagerduty use reqData.Pager.Page as offset when sending reqeusts.
This will cause data loss. This pr use reqData.Pager.Skip as offset.
part of #5031 
> fix(pagerduty): fix offset

- config-ui/src/pages/pipeline/components/task/index.tsx
fixed refdiff task name error.
> fix(config-ui): refdiff task name error

- backend/plugins/tapd/models/migrationscripts/20230323_add_transformation.go
- backend/plugins/tapd/models/migrationscripts/archived/transformation_rule.go
fix missing id in tapd transformationRule migration.
The bug:
After fix, migration can run~
After run:
Although id is not primary key if the table transformation rule exist, I think it's no matter. Because this script haven't publish to users.
> fix: fix missing id in tapd transformationRule migration

- backend/plugins/gitlab/api/remote.go
- backend/plugins/gitlab/models/project.go
Because the request was changed
The fix #4307 on config-ui does not work.
So it needs to be fixed on the backend.
Rename the group id, and add `group:` before the id
related #4296
> fix: fix config ui do not support same group and project id

- config-ui/nginx.conf
When trying to access `/grafana` , nginx would redirect users to `/grafana/` due to 404.
However, for whatever reason, nginx produces a Full Qaulified URL which is undesirable, especially for modern DevOps practice.
This PR fixes the problem by turning `absolute_redirect` off
Closes #5048
> fix: /grafana being redirected to a wrong URL

- backend/plugins/gitlab/api/remote.go
Add `group:` before group id.
Because the config-ui does not support the same group id and project id.
> fix: cherry pick #5037

- backend/plugins/ae/api/connection.go
- backend/plugins/azure/api/connection.go
- backend/plugins/bamboo/models/connection.go
- backend/plugins/bitbucket/api/connection.go
- backend/plugins/feishu/models/connection.go
- backend/plugins/gitee/api/connection.go
- backend/plugins/github/api/connection.go
- backend/plugins/gitlab/api/connection.go
- backend/plugins/gitlab/models/connection.go
- backend/plugins/jenkins/api/connection.go
- backend/plugins/jira/api/connection.go
- backend/plugins/pagerduty/api/connection.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/tapd/api/connection.go
- backend/plugins/teambition/api/connection.go
- backend/plugins/trello/api/connection.go
- backend/plugins/zentao/models/connection.go
Because of the 401 error will reset the config-UI login.
So It changed all 401 to 400.
Closes #5068
> fix: unauthorized return 400 instead of 401

- backend/python/plugins/azuredevops/azuredevops/streams/pull_request_commits.py
- backend/python/pydevlake/pydevlake/model.py
Fix empty transformation rule fields in db caused by a casing mismatch.
@hezyin 
Closes #5072
> Fix empty tx rules patterns

- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
Exclude all timeline entries that are not jobs from the Jobs stream of AzureDevops plugin.
@hezyin 
Closes #5070
> Exclude all non-job timeline entries from collection

- backend/plugins/customize/service/service.go
This pull request adds functionality to insert or update a new record into the `boards` table with the type set to kanban, upon uploading the issues.csv file. 
Closes #5086
> feat: save board as kanban type

- backend/helpers/pluginhelper/api/mapstructure.go
- backend/server/services/remote/plugin/transformation_rule_api.go
- backend/test/e2e/remote/python_plugin_test.go
- backend/test/helper/api.go
Fix the PATCH endpoint of remote plugin transformation rules API.
Refactor and add tests
Closes #5082
> 5082 fix patch tx rule

- backend/plugins/gitlab/tasks/account_collector.go
It seems like the pagination code has always been commented out since day one.
I checked the API reference, nothing strange, and tried to uncomment the related code and ran it locally, all seems fine...
Closes #5126
> fix: no pagination is used in the collectionAccounts of gitlab

- grafana/dashboards/BitBucket.json
- grafana/dashboards/ContributorExperience.json
- grafana/dashboards/GitHub.json
- grafana/dashboards/Gitlab.json
updated pr-status-realated metrics
part of #4745 
> feat: updated pr-status-realated metrics

- backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
- backend/python/plugins/azuredevops/tests/streams_test.py
- backend/python/pydevlake/pydevlake/domain_layer/code.py
feat: azure adapts original_status and status
part of #4745 
> feat: azure adapts original_status and status

- config-ui/nginx.conf
- grafana/Dockerfile
upgrade grafana to v9.5.1
Closes #5017
Collect 1 month data from `apache/incubator-devlake` and the `Github` dashboard seemed alright.
> feat: upgrade grafana to v9.5.1

- backend/plugins/tapd/impl/impl.go
- backend/plugins/tapd/tasks/workspace_converter.go
Fix #5156
The routine of converting the TAPD workspace to the board was moved from the subtask list to MakeDataSourcePipelinePlanV200, which would not be executed in the `ADVANCE` mode. In this PR, we fix it by adding a new subtask `convertWorkspace` to the subtask list, it will be called in any case, whether it is `NORMAL` or `ADVANCE`.
Closes #5156
> fix: missing board for tapd

- backend/python/plugins/azuredevops/azuredevops/models.py
Fix azuredevops migration for jobs table on postgresql.
MySQL and postgresql don't have the same syntax to remove a primary key constraint.
Closes #5187
> fix: Fix Job.migrate on postgresql

- backend/python/plugins/azuredevops/azuredevops/models.py
Change the type of azure devops pull request description from `var(255)` to `text`.
Closes #5151
> fix: Set type of description column to TEXT

- backend/python/plugins/azuredevops/azuredevops/models.py
Fix collection of abandonned PRs that don't have the lastMergeCommit property.
Closes #5108
> fix: Make PR.merge_commit_sha optional

- backend/helpers/pluginhelper/api/api_async_client.go
- backend/plugins/pagerduty/tasks/incidents_collector.go
Closes #5107
Wrote a script to generate a little over 10k incidents on my account. The reported error was reproduced with the original code, and resolved by the fix. Exactly up to 10k latest incidents will now get returned.
> [fix-5107]: PagerDuty data collection limit with service filtering

- .github/ISSUE_TEMPLATE/bug-report.yml
chore: change version to a input instead of select
Closes #5128
> chore: change version to a input instead of select

- backend/plugins/github/tasks/repo_convertor.go
fix: gitHub repos' url columns are empty
related to #5100 
> fix: github repos' url columns are empty

- backend/plugins/pagerduty/impl/impl.go
- backend/plugins/pagerduty/tasks/incidents_converter.go
- backend/plugins/pagerduty/tasks/service_converter.go
PagerDuty now emits board domain models as required for correct DORA metric computation.
Closes #5233 
MTTR was n/a before despite having an incident that was resolved. With this fix it's now calculated in the dashboard.
> [fix-5233]: Pagerduty MTTR computation fix

- backend/plugins/github/models/migrationscripts/20230518_fix_run_name_to_text.go
- backend/plugins/github/models/migrationscripts/register.go
- backend/plugins/github/models/run.go
I do not have rights to add labels.
Github workflows may have longer than 255 characters long names. In order to sync it I changed gorm type from `varchar(255)` to `text` for `GithubRun` type `Name` field. 
Error received while syncing github repository:
```
time="2023-05-09 08:37:03" level=error msg=" [pipeline service] [pipeline #3] [task #25] subtask extractRuns ended unexpectedly
Wraps: (2) error adding result to batch
Wraps: (3) Error 1406: Data too long for column 'name' at row 17
Wraps: (4) Error 1406: Data too long for column 'name' at row 17
Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"
```
> Use text instead of varchar(255) for GitHubRun's name

- backend/plugins/bitbucket/api/remote.go
- backend/plugins/bitbucket/e2e/snapshot_tables/_tool_bitbucket_repos.csv
- backend/plugins/bitbucket/models/repo.go
fix: bitbucket repos' url columns are empty
Closes #5100 
> fix: bitbucket repos' url columns are empty

- backend/core/dal/dal.go
- backend/core/models/blueprint.go
- backend/core/models/dynamic_tabler.go
- backend/helpers/pluginhelper/api/reflection_helper.go
- backend/helpers/pluginhelper/api/scope_db_helper.go
- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/scope_helper_test.go
- backend/helpers/pluginhelper/services/blueprint_helper.go
- backend/impls/dalgorm/dalgorm.go
- backend/impls/dalgorm/db_mapper.go
- backend/plugins/pagerduty/api/init.go
- backend/plugins/pagerduty/api/scope.go
- backend/python/pydevlake/pydevlake/message.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/stream.py
- backend/python/pydevlake/pydevlake/subtasks.py
- backend/python/pydevlake/tests/stream_test.py
- backend/resources/swagger/open_api_spec.json.tmpl
- backend/server/services/remote/models/conversion.go
- backend/server/services/remote/models/models.go
- backend/server/services/remote/plugin/default_api.go
- backend/server/services/remote/plugin/init.go
- backend/server/services/remote/plugin/plugin_extensions.go
- backend/server/services/remote/plugin/plugin_impl.go
- backend/server/services/remote/plugin/scope_api.go
- backend/server/services/remote/plugin/scope_db_helper.go
- backend/test/e2e/remote/python_plugin_test.go
The goal of this PR is to allow remote plugins (i.e. Python) support DeleteScopes. To do a clean job with the code and avoid messy duplications some additional refactoring has been done:
* scope_helper has been refactored into generic_scope_helper to support Python->Go runtime models as well. It is now used by two helpers: scope_helper (Go plugins), remote_scope_helper (Python plugins).
* Scope related database operations are now abstracted in the ScopeDatabaseHelper interface. It has two impls: One for Go and one for Python.
* Python plugins (i.e. AzureDevops as of now) adapted to support DeleteScopes.
Reduced from #4906
Part of #4762 
> [feat-4762] part2: Rework scope_helper for compatiblity with Python

- backend/plugins/sonarqube/api/proxy.go
- backend/plugins/sonarqube/impl/impl.go
1. add proxy api to sonarqube plugin
2. fix search-remote-scope api of sonarqube plugin
3. fix some swagger document definition
Closes #5171 
Closes #5254 
> feat: add proxy api to sonarqube plugin

- backend/plugins/github/models/migrationscripts/20230518_fix_run_name_to_text.go
Fix #5245 ([Bug][GitHub] migration script run into error)
A missing `id` column in the migration script caused the bug
Closes #5245 
> fix: fix the migration script of _tool_github_runs

- backend/plugins/sonarqube/api/proxy.go
fix #5264, which is caused by a syntax error in the Swagger source file
Closes #5264
> fix: the swagger error for sonarqube-proxy-endpoint

- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/helpers/pluginhelper/services/blueprint_helper.go
- backend/server/api/blueprints/blueprints.go
- backend/server/api/router.go
- backend/server/services/blueprint.go
- backend/test/e2e/remote/helper.go
- backend/test/e2e/remote/python_plugin_test.go
- backend/test/helper/api.go
Blueprints may now be deleted. The new endpoint is:
`DELETE http://devlake-endpoint/blueprints/[1]`
where `[1] = blueprintId`.
This returns nothing and only deletes the blueprint from the backend. This does not impact scopes or blueprint data.
Part of #4864 
Manually verified against PagerDuty (using two scopes/services), and Python via an integration test.
> [feat-4864] Support for deleting blueprints

- backend/plugins/jira/tasks/issue_comment_extractor.go
Fix #5223, the name of the subtask `ExtractIssueComments` was wrongly set to `extractIssueChangelogs`, in this PR, the name is set to the correct value.
Closes #5223
> fix: missing `_raw_jira_api_issue_comments` table

- backend/helpers/pluginhelper/api/connection.go
- backend/plugins/github/api/connection.go
make sure the connection endpoint ends with "/"
Closes #4996
**Please review carefully, I'm not sure it is the best way.**
I noticed that currently, after receiving JSON information from the frontend, the decoding, validation, and saving to the database **are done together**, making it difficult to implement custom logic here.
I also observed that all connections call the NewApiClientFromConnection function and pass connection.GetEndpoint() as the base URL. So, instead of modifying the records in the database, I'm trying to automatically add a / when the endpoint is needed on the backend.
> [Feature][Connection]: make sure the connection endpoint ends with "/"

- backend/core/plugin/plugin_blueprint.go
- backend/core/plugin/plugin_blueprint_test.go
- backend/server/services/blueprint.go
- Not run the blueprints which do not contain any plugin other than `org`, `dora` and `refdiff`
- Not run the blueprints if all of the plans are empty
- Allow creating empty blueprints in advanced mode
Closes #5307
> Skip empty blueprint

- backend/python/README.md
- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/pydevlake/pydevlake/api.py
Fix error when collecting jobs of builds that failed because of bad `azure-pipelines.yaml`.
Closes #5083
> Fix exception on 204 when collecting jobs

- backend/plugins/pagerduty/tasks/incidents_collector.go
- backend/plugins/pagerduty/tasks/task_data.go
PagerDuty API params was missing the service ID reference. This is already fixed in main/v0.18, but wasn't back-ported to v0.17.
Closes #5311
> cherrypick(v0.17.0-beta9): #5311

- backend/python/plugins/azuredevops/azuredevops/models.py
Fixes an error while extracting running builds.
Closes #5336
> fix: Build.result must be optional

- backend/plugins/gitlab/models/migrationscripts/20230606_add_issue_assignee.go
- backend/plugins/gitlab/models/migrationscripts/archived/issue_assignee.go
- Fix #5368 
- provide migration script to create the table `_tool_gitlab_issue_assignees`
Closes #5368 
> fix: create table _tool_gitlab_issue_assignees

- backend/plugins/jira/api/init.go
Fixes the call to `/plugins/jira/connections/{connectionId}/scopes/?blueprints=true` erroring out with:
It errors out because the reflection param value name for Boards doesn't exactly match the name on the struct:
https://github.com/apache/incubator-devlake/blob/f3e23cebde39cea18b618c7c72546eeff938099f/backend/plugins/jira/models/board.go#L29
Closes n/a
> fix(Jira): Fix Jira scope reflection field name: BoardID -> BoardId

- backend/plugins/bitbucket/api/blueprint_V200_test.go
- backend/plugins/bitbucket/api/blueprint_v200.go
- backend/plugins/gitextractor/tasks/git_repo_collector.go
- backend/plugins/github/api/blueprint_V200_test.go
- backend/plugins/github/api/blueprint_v200.go
- backend/plugins/gitlab/api/blueprint_V200_test.go
- backend/plugins/gitlab/api/blueprint_v200.go
- config-ui/src/pages/pipeline/components/task/index.tsx
Fix the gitextractor tasks names displayed.
Add the name to the gitextractor on GitHub, GitLab, and Bitbucket on the blueprint.
Closes #5088
> fix: tasks name fixed

- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/pydevlake/pydevlake/subtasks.py
Fix a 404 that arise when trying to collect timelines of a deleted build that got "cleaned".
Once the retention policy of an Azure DevOps build expires, this build can be deleted but is still accessible during at least a month. During that time, we can query its timeline in which case we get a 204.
But after that time querying the build timeline returns a 404.
This PR:
- adds a filter to exclude deleted builds from the builds endpoint.
- deletes all previously collected tool level rows when not incremental.
- handles 404 when collecting a build jobs
Closes #5383
> 5383 build not found

- backend/core/config/config_viper.go
feat: add ENV_FILE var
Closes #5235 
> feat: add ENV_FILE var

- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/helpers/pluginhelper/services/blueprint_helper.go
fix #5400 ([Bug][framework] The scope list API returns wrong number of blueprints)
Closes #5400
> fix: missing blueprints from the scope list API

- backend/python/README.md
- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/pydevlake/pydevlake/__init__.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/message.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/test/fakeplugin/fakeplugin/main.py
- backend/server/services/remote/plugin/connection_api.go
Change test_connection to return a TestConnectionResult that contains a message and a status code
that are used on go-side to build responses to GET 'plugins/<plugin>/test-connection'.
Closes #5080
> 5080 Let test_connection report status from tool API

- backend/plugins/github/api/remote.go
- only return scope if the groupId is not empty
- set scope name as full name 
- set clone URL for github scope
Closes #5430 #5431 
> fix: github remote api

- backend/plugins/github_graphql/impl/impl.go
fix #5445 ,  the subtask `convertIssueAssignee` was not added to the plugin `github_graphql`
Closes #5445 
> fix: missing data in the table issue_assignees

- backend/plugins/sonarqube/tasks/issues_collector.go
Sonarqube issue collector will split result of issues/search by using createdBefore & createdAfter filter params, if the result exceed 100 pages. 
The split end when createdBefore - createdAfter less than 1 second, which is createdBefore == createdAfter, and sonarqube api do not allow createdBefore and createdAfter to be equal. In some case sonar scanner failed to do backdating, all issues have same createdTime, the split will end up createdBefore == createdAfter, and fail with sonarqube api error.
This time range spliting don't need to be so acurate, this PR change the end condition to 10 seconds.
Closes #5442
> fix: sonar issue collector time range split 

- backend/core/config/config_viper.go
- backend/core/config/config_viper_test.go
- backend/test/helper/client.go
fix remove write file config code
Closes #5235 
> fix: remove write file config code

- backend/core/models/blueprint.go
- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/helpers/pluginhelper/api/scope_helper_test.go
- backend/plugins/bamboo/api/init.go
- backend/plugins/bitbucket/api/init.go
- backend/plugins/gitlab/api/init.go
- backend/plugins/jenkins/api/init.go
- backend/plugins/jira/api/init.go
- backend/plugins/sonarqube/api/init.go
- backend/plugins/tapd/api/init.go
- backend/plugins/trello/api/init.go
- backend/plugins/zentao/api/init.go
- backend/server/services/project.go
- backend/server/services/remote/plugin/default_api.go
- backend/server/services/remote/plugin/plugin_impl.go
- backend/test/e2e/manual/azuredevops/azure_test.go
- backend/test/helper/api.go
Addresses a bug reported during v0.18 beta testing: deleting scopes was not deleting their data for at least Jira and GitLab. Turns out RawScopeParamName was not set for most plugins including these two. This PR fixes that, and a few other minor issues.
Additionally, Scope objects were not having _raw_data_params written to them because they don't go through Collectors anymore but rather through the Scope API. As a result, any of their dependent domain tables (boards) were missing this field which would cause deletion to not happen on them.
Closes n/a
Gitlab test
After deleting two scopes:
> fix: Add missing RawScopeParamName field to plugins

- backend/helpers/pluginhelper/api/api_extractor.go
- Fix #5490 
- Collectors are supposed to create the raw layer tables, if the collector never got executed, the tables are missing, and the extractors could not find the tables. In this PR, the extractors would return without any error, if they found the table is missing
Closes #5490 
> fix: missing raw layer tables

- backend/plugins/customize/service/service.go
- backend/plugins/tapd/api/blueprint_v200.go
- backend/plugins/tapd/api/blueprint_v200_test.go
- backend/plugins/tapd/tasks/workspace_converter.go
Fix #5157 ([Bug][Tapd] Tapd board type not set to scrum in domain layer's boards table)
Closes #5157
> fix: Assign proper value to the column `type`  of table `boards`

- .github/workflows/commit-msg.yml
- backend/plugins/gitlab/tasks/api_client.go
- backend/plugins/gitlab/tasks/mr_commit_collector.go
- backend/plugins/gitlab/tasks/mr_detail_collector.go
- backend/plugins/gitlab/tasks/mr_note_collector.go
ignore 404 errors when collecting merge request detail.
Closes #5385 
fabricated a missing MR
Fixed
Without ignoring
> fix: ignore 404 when collecting gitlab mr detail

- backend/core/models/domainlayer/domaininfo/domaininfo.go
Fix #5536 ([Bug][framework] the table issue_assignees was missing in the return of GetDomainTablesInfo)
Closes #5536
> fix: issue_assignees was missing

- backend/python/plugins/azuredevops/azuredevops/main.py
Add prefix to repositories names in azure devops.
External repositories are also prefixed with provider name (e.g. "GitHub", "Bitbucket")
> fix: AzureDevops prefix repositories names with project names

- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/test/e2e/remote/helper.go
fix: scope gets emptied when deletion failed (#5532)
Closes #5532
> fix: Scope data shouldn't be removed on deletion conflict (#5532)

- backend/plugins/gitlab/tasks/pipeline_commit_convertor.go
- backend/plugins/gitlab/tasks/pipeline_convertor.go
- backend/plugins/jira/api/blueprint_v200.go
- backend/plugins/zentao/tasks/project_convertor.go
- Set `boards.url` and `boards.type` on creating a pipeline for Jira
- Set `boards.type` as 'scrum' on converting project for Zentao
> fix: boards.type

- backend/helpers/pluginhelper/subtaskmeta_sorter/dependency_test.go
- backend/plugins/dora/impl/impl_test.go
- backend/plugins/sonarqube/e2e/account_test.go
- backend/plugins/sonarqube/e2e/filemetrics_test.go
- backend/plugins/sonarqube/e2e/hotspot_test.go
- backend/plugins/sonarqube/e2e/issue_test.go
- backend/plugins/sonarqube/e2e/project_test.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/tasks/hotspots_collector.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/task_data.go
There's a check for updateDate to detect new analysis while collection sonarqube data, to prevent loading a half new half old issue list. But sonarqube issue UpdateDate is updated when manually set issue resolution state in sonarqube, so it can't be used as an indicator of new analysis. 
This PR changed project LastAnalysisTime to task start time, if issue got updated during devlake data collection, the collection will fail, otherwise update issue status will not cause data collection failure.
This update time check also added to hotspot collector task.
Fixed some lint issue with `gofmt -w -s`
Closes #5544 
> fix(sonarqube): issue collector failed when issue status updated (#5544)

- backend/plugins/tapd/tasks/bug_status_extractor.go
- backend/plugins/tapd/tasks/shared.go
- backend/plugins/tapd/tasks/shared_test.go
- backend/plugins/tapd/tasks/story_status_extractor.go
Fix #5573 ([Bug][TAPD] ExtractBugStatus Task, an error reported If there is no “Bug Status“ data). This bug is caused by incorrect handling of empty arrays.
Closes #5573
> fix: tapd status extraction error

- config-ui/src/components/table/hooks/use-row-selection.ts
- config-ui/src/plugins/components/data-scope-select/index.tsx
Changing the scopes of a connection would see the following error
**Cause**: the `useRowSelection` does not support changing the type of the `rowKey`
**Fix**: added an optional `getRowKey` for callers to be able to customize the behavior.
> fix: scope selection is not working

- backend/server/services/blueprint_makeplan_v200.go
- backend/server/services/blueprint_makeplan_v200_test.go
Fix #5582. During the execution of the blueprint, the scopes were created/updated twice, once at creating the pipeline and once at converting the boards/repos/cicd_scopes, the column `_raw_data_params` was not populated in the previous one. In this PR, we fix the issue by only creating/updating scopes once.
Closes #5582
> fix: _raw_data_params are missing for some scope

- backend/plugins/gitlab/models/migrationscripts/20230625_add_mr_commitsha.go
As noted [here](https://github.com/apache/incubator-devlake/pull/5577/files#r1244735425) the fix for `gitlab commit sha` introduced an erroneous migration which this PR should fix.
- Should this PR be on `release-17` or `master`?
- Should this be a new migration? (as i guess the previous migration hasn't been tagged yet)
> Fix the migration for the introduction of the squash and diff columns

- backend/core/runner/run_task.go
cherry-pick #5586 back to release-v0.17
Closes #5585
> cherry-pick(v0.17.0-beta13): #5586

- config-ui/src/pages/connection/home/styled.ts
- config-ui/src/plugins/register/jira/transformation-fields/cross-domain.tsx
- config-ui/src/plugins/register/jira/transformation-fields/dev-panel.tsx
1. Fixed cancel the text bold in connection home page.
2. Fixed revert icon direction in jira transformation.
> fix(config-ui): some bugs for style

- .github/workflows/golangci-lint.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- backend/Dockerfile
- backend/go.mod
- backend/go.sum
- devops/docker/lake-builder/Dockerfile
Same source code would fail on golang v0.19, but not v1.20
https://github.com/apache/incubator-devlake/actions/runs/5421209399/jobs/9856360137
> Kw upgrade go1.20.4 for better generic support

- devops/releases/lake-v0.17.0/docker-compose.yml
- docker-compose.yml
reworking the PR per #5554#issuecomment-1605815004 Added SEContext to mount
Closes #5474
a modification to the docker-compose file to set the SELinux context on .env for
the devlake container
Closes #5474 
REDO of my First PR (#5554) on this project. I hope I targetted the right file. Would appreciate insights, feedback and thanks for taking time to review. Thanks @klesh and @hezyin on your ongoing support. I hope I nailed your intentions on this one :)
> fix:SELinux context not set crashes container

- backend/plugins/gitextractor/parser/clone.go
- backend/plugins/github_graphql/impl/impl.go
Fix for github_graphql and gitextractor when running devlake behind a corporate proxy. Currently both connections ignores the proxy configuration option and times out when trying to connect to github.
The proxy option `git.ProxyTypeAuto` in libgit2 seems to only use proxy when http proxy environment variables are set, instead `git.ProxyTypeSpecified`should be used to correctly specify proxy url.
To set proxy config on oauth2 one has to pass a custom `http.Client` object to the library through the context when creating the oauth2 client:
https://cs.opensource.google/go/x/oauth2/+/refs/tags/v0.9.0:oauth2.go;l=334
Closes #5502
> Proxy fixes for github_graphql and gitextractor

- backend/plugins/zentao/models/project.go
Remove the `project/` prefix from the scope ID
Closes #5602
> fix: remove prefix from scope ID

- config-ui/src/plugins/register/zentao/config.tsx
- config-ui/src/plugins/register/zentao/connection-fields/db-url.tsx
- config-ui/src/plugins/register/zentao/connection-fields/index.ts
Support field db url in zentao connection.
Closes #5627
> feat(config-ui): support field db url in connection

- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/pydevlake/pydevlake/pipeline_tasks.py
Frontend expects gitextractor task to have a `name` property in its options.
> Add missing name to gitextractor task
