- services/task.go
> fix: tasks api 504 when pipeline is running

- config-ui/src/App.js
- config-ui/src/config/migration.js
- config-ui/src/hooks/useDatabaseMigrations.jsx
- config-ui/src/utils/request.js
1. fix migration dialog only appear after refresh
2. fix migration cannot success
Closes #3255 
Closes #3109
> fix: fix migration dialog only appear after refresh

- plugins/github/api/blueprint.go
- plugins/github/api/blueprint_test.go
- plugins/gitlab/api/blueprint.go
- plugins/gitlab/api/blueprint_test.go
- plugins/jenkins/api/blueprint.go
- services/blueprint.go
add subtasks to dora stage when creating plan in github/gitlab/jenkins blueprint
Closes #3270 
> fix(plugins): modify default dora subtasks for data source

- README.md
> fix: updated main README

- grafana/dashboards/WeeklyCommunityRetro.json
some panels can not show in weekly-community-retro
missing table alias
Closes #3281 
older:
newer:
> fix: some panels can not show in weekly-community-retro

- plugins/dora/e2e/env_enricher_test.go
- plugins/dora/tasks/task_data.go
> fix: prefix param should move TransformationRules to DoraOptions

- config-ui/src/pages/connections/incoming-webhook/add-modal.jsx
- config-ui/src/pages/connections/incoming-webhook/view-or-edit-modal.jsx
change some wording
Closes #3289
> fix: change some wording

- services/task.go
Add GetTaskById.
relate #3256 
> fix: fix-3256

- config-ui/src/components/blueprints/BlueprintDataScopesDialog.jsx
- config-ui/src/components/blueprints/BoardsSelector.jsx
- config-ui/src/components/blueprints/DataScopesGrid.jsx
- config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
- config-ui/src/hooks/useDataScopesManager.jsx
- config-ui/src/hooks/useJIRA.jsx
- config-ui/src/pages/blueprints/blueprint-settings.jsx
- config-ui/src/pages/blueprints/create-blueprint.jsx
Change the Jira board selection box to be searchable, and avoid the interface only returning 50 boards limit.
Closes #3254
Nothing.
> fix(config-ui): change jira board selection box to be searchable

- plugins/jira/api/connection.go
connection test api/2/status to agile/1.0/board
Closes #3277 
Closes #2400 
> fix: fix 3277

- .asf.yaml
docs: add hackertoberfest and dora topics
> docs: add hackertoberfest and dora topics

- .asf.yaml
fix: update dora label to lowercase
> fix: update dora label to lowercase

- config-ui/src/components/Nav.jsx
- config-ui/src/components/Sidebar.jsx
- config-ui/src/hooks/useWIndowSize.jsx
- config-ui/src/index.js
- config-ui/src/store/UIContext.jsx
- config-ui/src/styles/common.scss
- config-ui/src/styles/nav.scss
- Added `UIContext` for Universal State Management of the Sidebar.
- Added Conditional Rendering to the Sidebar.
- Added new `Navbar Item`, `menu` button, that toggles the sidebar on smaller window sizes.
- UI Context Added for further UI State Management.
- Responsive Sidebar would be implemented in the Config-UI.
- There would be a toggle button for seen in the smaller screen sizes.
Closes #3106 
> feat: Added Responsive Sidebar

- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/integration/manage.jsx
- config-ui/src/pages/connections/incoming-webhook/index.jsx
1. fix some wording
Closes #3299
> fix: some wording

- generator/cmd/create_collector.go
Adding a nil check before throwing an error. 
Closes #3307 
Before 
After
> Extractor Not able to detect the Collector Name

- helpers/migrationhelper/helper.go
- impl/dalgorm/dalgorm.go
- plugins/core/dal/dal.go
Add ReBuildTable
Add ReBuildTableWithOutBak
Closes #3158 
> refactor: migration helper

- api/router.go
- plugins/core/plugin_api.go
- plugins/jira/api/proxy.go
fix #3341 [Bug][jira] issue changelogs convertor read issue statuses from other connection
Closes #3341 
> fix: forward original status code and body

- plugins/tapd/impl/impl.go
- plugins/tapd/tasks/story_status_last_step_collector.go
- plugins/tapd/tasks/story_status_last_step_enricher.go
- plugins/tapd/tasks/task_extractor.go
add subtasks to define if story status is last step
relate to #3208 
> feat(tapd): add story status last step

- plugins/tapd/impl/impl.go
- plugins/tapd/tasks/bug_status_last_step_collector.go
- plugins/tapd/tasks/bug_status_last_step_enricher.go
add subtasks to define bug status last step
relate to #3208 
> Feat add tapd bug status last step

- plugins/tapd/e2e/stories_test.go
- plugins/tapd/impl/impl.go
- plugins/tapd/models/migrationscripts/20221009_add_init_tables.go
- plugins/tapd/models/migrationscripts/archived/workitem_type.go
- plugins/tapd/models/workitem_type.go
- plugins/tapd/tasks/shared.go
- plugins/tapd/tasks/story_extractor.go
- plugins/tapd/tasks/story_status_extractor.go
- plugins/tapd/tasks/task_data.go
- plugins/tapd/tasks/workitem_type_collector.go
- plugins/tapd/tasks/workitem_type_extractor.go
according to jira issue type mapping, we add story type mapping to tapd
closes #3195
> feat(tapd): add type mapping

- README.md
docs: add collection mode for data sources
Closes #3338 #3318
> docs: add collection mode for data sources

- grafana/dashboards/WeeklyBugRetro.json
fix: some live demo can not show
related to #3352
> fix: some live demo can not show

- plugins/tapd/api/swagger.go
- plugins/tapd/tasks/bug_extractor.go
- plugins/tapd/tasks/shared.go
- plugins/tapd/tasks/story_extractor.go
- plugins/tapd/tasks/task_data.go
add tapd status mapping to transformation rules, 
now tapd transformation rules will be shown as below
```json
"transformationRules": {
"statusMappings": {
"doneStatus": [
"string"
],
"inprogressStatus": [
"string"
],
"todoStatus": [
"string"
]
},
"typeMappings": {
"additionalProp1": {
"standardType": "string"
},
"additionalProp2": {
"standardType": "string"
},
"additionalProp3": {
"standardType": "string"
}
}
}
```
closes #3208
> feat(tapd): status mapping

- grafana/dashboards/Jenkins.json
fix: jenkins dashboard can not work
Closes #3352 
> fix: jenkins dashboard can not work

- config-ui/src/components/Sidebar/SidebarMenu.jsx
fix href. Now it will not reload when click.
Closes #2994
> fix: fix sidebar href

- .github/ISSUE_TEMPLATE/bug-report.yml
Update the bug report template to include v0.14.0 and v0.14.1
> fix: update bug report template for v0.14

- plugins/coding/coding.go
- plugins/coding/impl/impl.go
- plugins/coding/models/depot.go
- plugins/coding/models/migrationscripts/archived/depot.go
- plugins/coding/tasks/depot_extractor.go
- plugins/coding/tasks/task_data.go
> feat(coding): add depot extractor

- models/migrationscripts/20220913_add_origin_value_for_pr.go
- models/migrationscripts/20220929_modify_lead_time_minutes.go
issues and pull_requests cached plan must not change result type
related to #2935 
> fix: issues and pull_requests cached plan must not change result type

- config-ui/src/pages/connections/incoming-webhook/add-modal.jsx
- config-ui/src/pages/connections/incoming-webhook/index.jsx
- config-ui/src/pages/connections/incoming-webhook/view-or-edit-modal.jsx
- plugins/webhook/api/cicd_pipeline.go
- plugins/webhook/api/connection.go
- plugins/webhook/impl/impl.go
add a new DORA deployments incoming webhook
Closes #3377
`curl http://localhost:4000/api/plugins/webhook/1/deployments -X 'POST' -d '{"repo_url":"devlake","commit_sha":"015e3d3b480e417aede5a1293bd61de9b0fd051d","start_time":"2020-01-01T12:00:00+00:00","end_time":"2020-01-01T12:59:59+00:00","environment":"PRODUCTION"}'`
```
{"success":true,"message":"success","causes":null}
```
`curl http://localhost:4000/api/plugins/webhook/1/deployments -X 'POST' -d '{"repo_url":"devlake","commit_sha":"115e3d3b480e417aede5a1293bd61de9b0fd051d","start_time":"2020-01-01T12:00:00+00:00"}'`
```
{"success":true,"message":"success","causes":null}
```
`curl http://localhost:4000/api/plugins/webhook/1/deployments -X 'POST' -d '{"repo_url":"devlake","commit_sha":"115e3d3b480e417aede5a1293bd61de9b0fd051d"}'`
``` …
```
> feat: new deploy task webhook

- plugins/dora/tasks/change_lead_time_calculator.go
- plugins/github/github.go
Cherry pick #3399 to main branch
> fix: most PRs don't have deploy time  (cherry pick #3399 to main)

- config-ui/src/pages/connections/incoming-webhook/add-modal.jsx
- config-ui/src/pages/connections/incoming-webhook/index.jsx
- config-ui/src/pages/connections/incoming-webhook/view-or-edit-modal.jsx
- plugins/webhook/api/cicd_pipeline.go
- plugins/webhook/api/connection.go
- plugins/webhook/impl/impl.go
cherry-pick some webhook fix to 0.14
> Hotfix/webhook 0.14

- plugins/starrocks/utils.go
> fix: starrocks plugin sync pg enum data type

- plugins/github/api/blueprint.go
- plugins/github/api/blueprint_test.go
- plugins/helper/api_client.go
modify github blueprint.go and blueprint_test.go to be more elegant
> Fix makepipelineplan

- plugins/tapd/models/workitem_type.go
cherrypick #3419 to 0.14
Closes xx
> fix(tapd): modify json tag for workflow id

- config-ui/src/pages/configure/settings/jira.jsx
transformation not updating correctly when switching boards.
Closes #3295
Nothing.
Nothing.
> fix(config-ui): transformation not updating correctly when switching boards

- config-ui/src/components/blueprints/transformations/CICD/Deployment.jsx
adjust the text description for DORA.
Closes #3412
Nothing.
Nothing.
> fix(config-ui): adjust the text description for DORA

- plugins/github/api/blueprint.go
- plugins/gitlab/api/blueprint.go
- plugins/gitlab/api/blueprint_test.go
modify blueprint and blueprint_test for gitlab
relate to #3127
> fix(gitlab): modify makePipelinePlan

- plugins/jenkins/api/blueprint.go
- plugins/jenkins/api/blueprint_test.go
- plugins/jenkins/tasks/task_data.go
modify blueprint and blueprint_test for jenkins
relate to https://github.com/apache/incubator-devlake/issues/3127
> fix(jenkins): modify jenkins blueprints

- plugins/bitbucket/api/blueprint.go
- plugins/bitbucket/api/blueprint_test.go
- plugins/github/api/blueprint.go
- plugins/github/api/blueprint_test.go
- plugins/gitlab/api/blueprint.go
- plugins/gitlab/api/blueprint_test.go
- plugins/jenkins/api/blueprint_test.go
modify blueprint and blueprint_test
relate to https://github.com/apache/incubator-devlake/issues/3312
> fix(bitbucket): modify blueprint

- config-ui/src/components/blueprints/transformations/CICD/Deployment.jsx
> cherry-pick #3433 to 0.14

- config-ui/src/components/pipelines/StageTaskName.jsx
- config-ui/src/data/Providers.js
displays the name of the DORA task.
Closes #3438
Nothing.
> feat(config-ui): displays the name of the DORA task

- plugins/starrocks/tasks.go
fix: starrocks cached plan must not change result type
Closes #3407 
> fix: starrocks cached plan must not change result type

- scripts/jira-api-benchmark.sh
Some of our users keep running into jira API timeout, this script would help us identify the root cause of the problem.
Related to #3346
> feat: add jira api benchmarking script

- docker-compose.yml
refactor: update docker-compose config ui default password
Closes #3460 
> refactor: update docker-compose config ui default password

- models/migrationscripts/20220406_add_frame_tables.go
- models/migrationscripts/20220505_rename_pipeline_step_to_stage.go
- models/migrationscripts/20220616_add_blueprint_mode.go
- models/migrationscripts/20220913_fix_commitfile_id_toolong.go
- models/migrationscripts/20220929_change_leadtimeminutes_to_int64.go
- models/migrationscripts/register.go
part of #3459
related to #3459
> docs: add comments and rename scripts

- plugins/jira/impl/impl.go
- plugins/jira/models/migrationscripts/20220407_add_source_table.go
- plugins/jira/models/migrationscripts/20220505_rename_source_table.go
- plugins/jira/models/migrationscripts/20220716_add_init_tables.go
- plugins/jira/models/migrationscripts/register.go
Refactor all migration scripts to implement the interface core.MigrationScript.
Related  to #3176 Migration adopts BasicRes
Closes #3469 
records in `_devlake_migration_history`:
created tables:
> refactor: implement the interface core.MigrationScript

- config-ui/src/hooks/useBlueprintValidation.jsx
A repetitive piece of code.
Nothing.
Nothing.
> fix(config-ui): code repeat

- plugins/github/tasks/comment_extractor.go
- plugins/github/tasks/event_extractor.go
- plugins/github/tasks/pr_review_comment_extractor.go
- plugins/github/tasks/pr_review_extractor.go
- plugins/github_graphql/plugin_main.go
- plugins/github_graphql/tasks/pr_collector.go
- plugins/github_graphql/tasks/repo_collector.go
- plugins/helper/graphql_async_client.go
- plugins/helper/graphql_collector.go
- services/pipeline.go
> cherry-pick #3493 to 0.14

- config-ui/src/data/pipeline-config-samples/starrocks.js
- plugins/starrocks/starrocks.go
- plugins/starrocks/task_data.go
- plugins/starrocks/tasks.go
> feat: add order by for starrocks plugin and use transaction repeatable read when load data

- plugins/ae/impl/impl.go
- plugins/ae/models/migrationscripts/20220714_add_init_tables.go
- plugins/ae/models/migrationscripts/register.go
- plugins/azure/impl/impl.go
- plugins/azure/models/migrationscripts/20220825_add_init_tables.go
- plugins/azure/models/migrationscripts/register.go
- plugins/bitbucket/impl/impl.go
- plugins/bitbucket/models/migrationscripts/20220803_add_init_tables.go
- plugins/bitbucket/models/migrationscripts/20220914_add_pipeline_tables.go
- plugins/bitbucket/models/migrationscripts/20221013_add_deployment_tables.go
- plugins/bitbucket/models/migrationscripts/20221014_add_RepoId_CommitSha_field_pipeline_tables.go
- plugins/bitbucket/models/migrationscripts/register.go
As a part of a whole refactoring plan, we deal with the migration scripts of the AE, Azure, and bitbucket  in this pull request
Closes #3507 
created tables:
> refactor: migration scripts of AE, Azure, bitbucket

- plugins/jenkins/impl/impl.go
- plugins/jenkins/models/migrationscripts/20220714_add_init_tables.go
- plugins/jenkins/models/migrationscripts/20220729_modify_all_entities.go
- plugins/jenkins/models/migrationscripts/20220916_modify_jenkins_build.go
- plugins/jenkins/models/migrationscripts/register.go
- plugins/tapd/impl/impl.go
- plugins/tapd/models/migrationscripts/20221013_add_init_tables.go
- plugins/tapd/models/migrationscripts/register.go
Refactor all migration scripts to implement the interface core.MigrationScript.
Related to https://github.com/apache/incubator-devlake/pull/3176 Migration adopts BasicRes
Closes #3483 
> refactor: tapd and jenkins implement the interface core.MigrationScript

- plugins/gitee/api/connection.go
Swagger doc issue on Golang side.
n/a
> fix(backend): Fixed incorrect model reference in Gitee API doc

- plugins/webhook/impl/impl.go
- plugins/webhook/models/migrationscripts/20220908_add_init_tables.go
- plugins/webhook/models/migrationscripts/register.go
Refactor Webhook MigrationScripts.
Closes #3514 
> refactor: webhook migration scripts

- plugins/feishu/impl/impl.go
- plugins/feishu/models/migrationscripts/20220714_add_init_tables.go
- plugins/feishu/models/migrationscripts/register.go
Refactor Feishu MigrationScripts
Closes #3510 
> refactor: feishu migration scripts

- plugins/gitee/impl/impl.go
- plugins/gitee/models/migrationscripts/20220714_add_init_tables.go
- plugins/gitee/models/migrationscripts/register.go
Refactor Gitee MigrationScripts
Closes #3499 
> refactor: refactor gitee migration scripts

- config-ui/src/data/pipeline-config-samples/dbt.js
- config-ui/src/data/pipeline-config-samples/starrocks.js
- plugins/dbt/api/swagger.go
- plugins/dbt/dbt.go
- plugins/dbt/tasks/convertor.go
- plugins/dbt/tasks/git.go
- plugins/dbt/tasks/task_data.go
- plugins/starrocks/starrocks.go
- plugins/starrocks/task_data.go
- plugins/starrocks/tasks.go
> feat: cherrypick dbt and starrocks plugin improvement

- plugins/starrocks/tasks.go
> Fix StarRocks plugin will not sync table struct if source table change struct 

- plugins/starrocks/tasks.go
> fix: StarRocks plugin will not sync table struct if source table change struct

- plugins/gitee/api/blueprint.go
- plugins/gitee/api/blueprint_test.go
- plugins/gitee/impl/impl.go
- plugins/gitee/models/connection.go
- plugins/gitee/tasks/task_data.go
add blueprint support for gitee
relate to #3320
> fix(gitee): add blueprint support

- impl/dalgorm/dalgorm.go
- plugins/core/dal/dal.go
- plugins/starrocks/tasks.go
> fix: starrocks plugin sync data order keyword

- plugins/tapd/tasks/account_converter.go
fix: tapd user_name and full_name
Closes #3540 
> fix: tapd user_name and full_name

- plugins/jira/e2e/snapshot_tables/board_sprints.csv
> fix: jira e2e board-sprints error

- plugins/starrocks/tasks.go
> feat: check count after starrocks sync

- plugins/gitee/api/blueprint.go
- plugins/gitee/api/blueprint_test.go
fix piplineTask's plugin name
relate to #3320 
> fix(gitee): change plugin name for pipeline task

- plugins/gitextractor/gitextractor.go
- plugins/icla/models/migrationscripts/20221021_add_icla_committer.go
- plugins/icla/models/migrationscripts/archived/committer.go
- plugins/icla/models/migrationscripts/register.go
- plugins/icla/plugin_main.go
As a part of a whole refactoring plan, we deal with the migration scripts of the ICLA and GitExtractor in this pull request
Closes #3556
> refactor: migration scripts of ICLA and Gitextractor

- plugins/bitbucket/impl/impl.go
add GetTablesInfo and CloseablePluginTask for bitbucket plugin
> feat: add `GetTablesInfo` and `CloseablePluginTask` for `bitbucket` plugin

- plugins/github/impl/impl.go
- plugins/github/models/migrationscripts/20220715_add_init_tables.go
- plugins/github/models/migrationscripts/20220728_add_runs_table.go
- plugins/github/models/migrationscripts/20220729_add_jobs_table.go
- plugins/github/models/migrationscripts/20220802_add_pipeline_table.go
- plugins/github/models/migrationscripts/20220908_delete_pipeline_table.go
- plugins/github/models/migrationscripts/20220919_add_headrepoId_field_in_githubPr.go
- plugins/github/models/migrationscripts/archived/job.go
- plugins/github/models/migrationscripts/archived/pipeline.go
- plugins/github/models/migrationscripts/archived/run.go
- plugins/github/models/migrationscripts/register.go
refactor migrationscripts for github:
closes #3558
> refactor(github): refactor migrationscripts

- .github/workflows/yaml-lint.yml
Fix yaml lint not running in CI due to the action's name not matching the required pattern.
Closes #3560 
N/A
> fix(ci): fix yaml lint not run

- scripts/jira-api-benchmark.sh
Enhance jira api benchmarking script to cover orderby/since parameters
> feat: cover orderby/since parameter for jira-api-benchmark

- helpers/migrationhelper/migrationhelper.go
- impl/dalgorm/dalgorm.go
- models/migrationscripts/20220903_encrypt_blueprint.go
- models/migrationscripts/20220904_encrypt_pipeline.go
- models/migrationscripts/20220905_modfiy_cicd_pipeline.go
- models/migrationscripts/20220908_modfiy_cicd_tasks.go
- models/migrationscripts/20220913_add_origin_value_for_pr.go
- models/migrationscripts/20220915_rename_pipeline_commits.go
- models/migrationscripts/20220929_change_leadtimeminutes_to_int64.go
- plugins/azure/api/blueprint.go
- plugins/core/dal/dal.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/models/migrationscripts/20220714_add_init_tables.go
- plugins/gitlab/models/migrationscripts/20220729_add_gitlab_ci.go
- plugins/gitlab/models/migrationscripts/20220729_modify_gilab_ci.go
- plugins/gitlab/models/migrationscripts/20220804_add_pipeline_id.go
- plugins/gitlab/models/migrationscripts/20220906_fix_duration_to_float8.go
- plugins/gitlab/models/migrationscripts/20220907_add_pipeline_projects_tables.go
- plugins/gitlab/models/migrationscripts/register.go
- plugins/jira/tasks/epic_collector.go
- plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
- plugins/starrocks/tasks.go
refactor migrationscripts for gitlab
refactor migrationscripts for framework
Add AddTablerColumn and DropTablerColumn for dal
Refactor dal
Fix the lint error for azure.
Closes #3472 
Closes #3573 
> refactor: refactor migrationscripts

- plugins/starrocks/tasks.go
- plugins/starrocks/utils.go
> fix: starrocks sync data type

- plugins/gitlab/tasks/pipeline_collector.go
Add Incremental Sync for Gitlab pipeline
gitlab pipeline  collector query set `updated_after`
Closes #3584  
> feat: Add Incremental Sync for Gitlab `Pipeline`.

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature-request.yml
fix: update the wording for issue templates
Closes #3590
> fix: update the wording for issue templates

- README.md
1. fix live demo links
2. add config-ui availability to the supported data source section
Closes #3605
> docs: fix demo link and add config-ui availability

- api/blueprints/blueprints.go
- services/pipeline.go
update ShouldBindUri to c.Param("blueprintId")
releated to #3594 
> feat: the GetBlueprintPipelines interface support page... params

- plugins/zentao/impl/impl.go
- plugins/zentao/models/archived/story.go
- plugins/zentao/models/archived/task.go
- plugins/zentao/models/migrationscripts/20220906_add_init_tables.go
- plugins/zentao/models/story.go
- plugins/zentao/models/task.go
- plugins/zentao/tasks/story_collector.go
- plugins/zentao/tasks/story_convertor.go
- plugins/zentao/tasks/story_extractor.go
- plugins/zentao/tasks/task_collector.go
- plugins/zentao/tasks/task_convertor.go
- plugins/zentao/tasks/task_extractor.go
feat:add zentao task & fix:update stories -> story
Closes xx
> feat:add zentao task & fix:update stories -> story

- plugins/dbt/tasks/convertor.go
Cherry-pick the change in https://github.com/apache/incubator-devlake/pull/3575 into `release-v0.14`
Closes https://github.com/apache/incubator-devlake/issues/3574
> fix: pass the value of projectPath to dbt project-dir argument (#3575)

- api/blueprints/blueprints.go
- services/pipeline_helper.go
fix: the GetBlueprintPipelines pending add status filter
related to #3594
> fix: the GetBlueprintPipelines pending add status filter

- plugins/tapd/tasks/bug_commit_collector.go
- plugins/tapd/tasks/story_bug_collector.go
- plugins/tapd/tasks/story_commit_collector.go
- plugins/tapd/tasks/task_commit_collector.go
1. add incremental for story_bug_collector
2. delete test code
closes #3631
> fix(tapd): add incremental support

- go.mod
- go.sum
- plugins/github/e2e/account_test.go
- plugins/github/e2e/snapshot_tables/_tool_github_repo_accounts.csv
- plugins/github/e2e/snapshot_tables/account.csv
- plugins/github/tasks/account_convertor.go
- plugins/github_graphql/plugin_main.go
- plugins/github_graphql/tasks/account_collector.go
- plugins/github_graphql/tasks/issue_collector.go
- plugins/helper/graphql_async_client.go
- plugins/helper/graphql_collector.go
- scripts/compile-plugins.sh
cherry-pick some github & graphql fix https://github.com/apache/incubator-devlake/pull/3601 & https://github.com/apache/incubator-devlake/pull/3627 to 0.14
Collect devlake success
> cherry-pick some github & graphql fix to 0.14

- plugins/dbt/tasks/convertor.go
> feat: redirect dbt error log to pipeline error

- plugins/starrocks/api/connection.go
> feat: add missing be_host and order_by to api docs

- config-ui/src/data/pipeline-config-samples/dbt.js
- plugins/dbt/api/swagger.go
- plugins/dbt/dbt.go
- plugins/dbt/tasks/convertor.go
- plugins/dbt/tasks/task_data.go
> feat: export all dbt args explicit

- plugins/core/dal/dal.go
- plugins/github_graphql/plugin_main.go
- plugins/github_graphql/tasks/issue_collector.go
- plugins/github_graphql/tasks/pr_collector.go
- plugins/helper/graphql_collector.go
1. replace the number with databaseId in issue.id
2. deal 30/page for pr in github graphql
3. fix a wrong err check
4. fix some typo in dal
Closes #3636 
Closes #3635
> [github_graphql] replace the number with databaseId in issue.id

- plugins/dbt/tasks/convertor.go
Cherry-pick the change in https://github.com/apache/incubator-devlake/pull/3638 into `release-v0.14`
Closes https://github.com/apache/incubator-devlake/issues/3637
> fix: handle the situation when slice is empty (#3638)

- plugins/core/dal/dal.go
- plugins/github_graphql/plugin_main.go
- plugins/github_graphql/tasks/issue_collector.go
- plugins/github_graphql/tasks/pr_collector.go
- plugins/helper/graphql_collector.go
cherry-pick [#3664](https://github.com/apache/incubator-devlake/pull/3664) to 0.14
> cherry-pick #3664 to 0.14

- plugins/starrocks/tasks.go
> fix: close db connections after starrocks sync finish

- models/domainlayer/devops/cicd_scope.go
- models/migrationscripts/20221107_add_cicd_scope.go
- models/migrationscripts/archived/cicd_scope.go
- models/migrationscripts/register.go
add table.cicd_scope and related migration script
add field.cicd_scope_id to cicd_tasks/pipelines and related migration script
Closes xx
> feat(cicd): add cicd scope

- services/task.go
cherry-pick #3657 to 0.14
Closes xx
> fix(framework): cherry-pick #3657 to 0.14

- config-ui/src/App.js
- config-ui/src/components/miller-columns/components/checkbox/checkbox.tsx
- config-ui/src/components/miller-columns/components/checkbox/index.ts
- config-ui/src/components/miller-columns/components/checkbox/styled.ts
- config-ui/src/components/miller-columns/components/checkbox/types.ts
- config-ui/src/components/miller-columns/components/index.ts
- config-ui/src/components/miller-columns/components/item/index.ts
- config-ui/src/components/miller-columns/components/item/item-all.tsx
- config-ui/src/components/miller-columns/components/item/item.tsx
- config-ui/src/components/miller-columns/components/item/styled.ts
- config-ui/src/components/miller-columns/hooks/index.ts
- config-ui/src/components/miller-columns/hooks/use-columns.ts
- config-ui/src/components/miller-columns/hooks/use-item-map.ts
- config-ui/src/components/miller-columns/hooks/use-miller-columns.ts
- config-ui/src/components/miller-columns/hooks/use-test.ts
- config-ui/src/components/miller-columns/index.ts
- config-ui/src/components/miller-columns/miller-columns.tsx
- config-ui/src/components/miller-columns/styled.ts
- config-ui/src/components/miller-columns/types.ts
added component miller-columns.
Prepare for #3670.
Nothing.
> feat(config-ui): added component miller-columns

- plugins/github_graphql/plugin_main.go
- plugins/github_graphql/tasks/check_run_collector.go
CheckSuite.CheckRuns have some columns which are similar to WorkflowJobs.
So collect `CheckRuns` on each CheckSuite to replace WorkflowJobCollector.
Now query 30 CheckSuite in one graphql request. This new collector costs about 40min to collect Devlake's runs & jobs on my computer, and its speed is about 1000/min (CheckSuite) or 2 requests per second.
Closes #3704
The result in `_tool_github_jobs`:
| created\_at | updated\_at | \_raw\_data\_params | \_raw\_data\_table | \_raw\_data\_id | \_raw\_data\_remark | connection\_id | repo\_id | id | run\_id | run\_url | node\_id | head\_sha | url | html\_url | status | conclusion | started\_at | completed\_at | name | steps | check\_run\_url | labels | runner\_id | runner\_name | runner\_group\_id | type |
| :--- | :--- | :--- | :--- | :--- | …
> feat: add check_run collector in github graphql

- models/migrationscripts/20220903_encrypt_blueprint.go
- models/migrationscripts/20220904_encrypt_pipeline.go
- plugins/jenkins/models/migrationscripts/20220916_modify_jenkins_build.go
There are two problems caused migration failed from v0.12 to 0.14
1. _devlake_tasks.id is not in accordance with pipeline.id
- previously, we migrate the whole table instead of changing columns, in this pr, we fixed it
2. reported `_tool_jenkins_builds does not exist` 
- when we are migrating jenkins build, we used cursor, and changed the table name of the cursor before we releasing it. Now we fixed this by not changing this table name before we release it
Closes #3537 
How to verify:
1. use dcoker to deploy v0.12
2. add some data to _devlake_blueprints/pipelines/tasks and _tool_jenkins_builds
3. shut down v0.12, deploy v0.14
4. check data
> fix(migrationscript): resolve bugs when migrating

- grafana/dashboards/WeeklyBugRetro.json
feat: add a 'Bugs to be Triaged' panel to the 'Weekly Bug Retro' dashboard
Closes #3737
> feat: add a 'Bugs to be Triaged' panel

- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/pull_request_template.md
1. change the field order of a feature-request issue
2. update the wording of the feature-request template to help users write a feature request easier
3. update the format of the PR template
N/A
> fix: update the template for feature-request and PR

- plugins/github/api/proxy.go
- plugins/github/impl/impl.go
> feat: add proxy api for github

- config-ui/src/components/blueprints/StandardStackedList.jsx
- config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
- config-ui/src/components/github/miller-columns/index.tsx
- config-ui/src/components/gitlab/miller-columns/index.tsx
- config-ui/src/components/jenkins/config.ts
- config-ui/src/components/jenkins/index.ts
- config-ui/src/components/jenkins/miller-columns/index.tsx
- config-ui/src/components/jenkins/miller-columns/use-jenkins-miller-columns.ts
- config-ui/src/components/jira/miller-columns/index.tsx
- config-ui/src/models/JenkinsJob.js
1. **Jenkins** select job to support **miller-columns** component.
2. Fix custom **miller-columns** will exceed the container.
#3670
Nothing.
> feat(config-ui): jenkins select job to support miller-columns component

- api/blueprints/blueprints.go
- models/blueprint.go
- models/migrationscripts/20221117_add_project_to_blueprint.go
- models/migrationscripts/register.go
- services/blueprint.go
To associate blueprint with project.
We need add project_name to blueprints table, and update API/Service accordingly.
Add migration script about blueprint.
***bp_get.sh***
```bash
#!/bin/sh
curl --location --request GET 'devlake:8080/blueprints/1' \
--data-raw '{
}'
echo "\r\n"
```
***bp_patch.sh***
```bash
#!/bin/sh
curl --location --request PATCH 'devlake:8080/blueprints/1' \
--data-raw '
{
"name":"Test BluePrint",
"projectName":"TestProject",
"cronConfig":"0 0 * * *",
"plan":{},
"settings":
{
"version":"1.0.0",
"connections":
[
{
"plugin":"gitlab",
"connectionId":1,
"scope":[
{
"transformation": {"productionPattern":""},
"options":{"projectId":37,"title":"思码逸 / Lake"}, …
```
> feat: add project to blueprint

- plugins/starrocks/tasks/tasks.go
> refactor: make some log level to debug to reduce

- plugins/dora/tasks/change_lead_time_calculator.go
According to pr #3742 , we have a naming problem, this pr fixed that problem as:
deploymentPairList -> deploymentDiffPairs
pipelineIdClauses -> deploymentClause
> fix(dora): modify naming

- plugins/zentao/models/archived/execution.go
- plugins/zentao/models/archived/project.go
- plugins/zentao/models/execution.go
- plugins/zentao/models/project.go
Modified tables.Began or RealBegan type to time
Closes xx
> fix(zentao): update Began and RealBegan field to time

- plugins/helper/api_client.go
cherry pick #3781 to release-v0.14
> [Cherrypick] fix: proxy connectivity checking

- plugins/helper/api_client.go
The `NewApiClient` function checked API Server connectivity without taking the `proxy` into consideration, which leads to a usability issue, PR #3761 tried to fix the problem by checking the Proxy Server connectivity instead, this PR solve the problem with a different approach:
1. When `proxy` was given, we check the connectivity by sending out a request to the API Server because it is not possible to distinguish DNS Resolution / Port Connectivity while `proxy` is in play. (yes, I learned it the hard way)
2. When `proxy` was not given, we fallback to the good old Checking Mechanism because it helps when our system was deployed to an internal K8s cluster, it is more likely for a k8s cluster to run into a DNS Resolution / Port Connectivity situations
Closes #3761
> fix: proxy connectivity checking

- plugins/starrocks/tasks.go
make some log level to debug to reduce
Closes https://github.com/apache/incubator-devlake/issues/3774
> refactor: make some log level to debug to reduce (#3775)

- plugins/zentao/e2e/snapshot_tables/board_issues_task.csv
- plugins/zentao/tasks/task_convertor.go
* fix(zentao): use zentaoExecution as boardIdGen
* fix(zentao): update e2e
Co-authored-by: Warren Chen <yingchu.chen@merico.dev>
Cherripick #3788  to v0.14
Closes #3789 
> fix(zentao): use zentaoExecution as boardIdGen (#3788)

- plugins/zentao/e2e/snapshot_tables/board_issues_task.csv
- plugins/zentao/tasks/task_convertor.go
> fix(zentao): update for board issues

- plugins/zentao/tasks/api_client.go
- plugins/zentao/tasks/execution_collector.go
- plugins/zentao/tasks/product_collector.go
- plugins/zentao/tasks/project_collector.go
- plugins/zentao/tasks/shared.go
- plugins/zentao/tasks/task_collector.go
cherrypick #3798 to 0.14
Closes xx
> fix(zentao): fix GetTotalPages

- plugins/jira/api/scope.go
- plugins/jira/api/transformation_rule.go
- plugins/jira/impl/impl.go
- plugins/jira/models/board.go
- plugins/jira/models/migrationscripts/20221116_add_trasformation_rule_table.go
In addition to fixing some omissions in #3753, this PR contains the following modification:
1. add `transformation_rule_id` to `_tool_jira_boards`
2. provide `PATCH` API for Jira scope
No, but partially fulfilled issue #3468
the scope API
> refactor: add transformation_rule_id to _tool_jira_boards

- models/domainlayer/code/commits_diff.go
- models/domainlayer/domaininfo/domaininfo.go
- models/migrationscripts/20221109_modfiy_commits_diffs.go
- plugins/refdiff/e2e/project_deployment_commit_diff_test.go
- plugins/refdiff/tasks/commit_diff_calculator.go
- plugins/refdiff/tasks/project_deployment_commit_diff_calculator.go
1. add new table ref_commits for the refdiff plugin.
2. update some struct name
related to #3685 
> feat: add new table ref_commits for the refdiff plugin

- plugins/github/tasks/pr_review_comment_collector.go
- plugins/github/tasks/pr_review_comment_extractor.go
Cherry-pick pr #3812 to release-v0.14
Closes #3720
> Cherry pick pr#3812 to release-v0.14

- plugins/core/plugin_blueprint.go
- plugins/github/api/blueprint.go
- plugins/github/api/blueprint_V200_test.go
- plugins/github/api/blueprint_test.go
- plugins/github/api/blueprint_v200.go
- plugins/github/impl/impl.go
- plugins/github/models/repo.go
- plugins/github/models/transformation_rule.go
This pr implement BlueprintV200 for github according to #3468 
Relate to #3468 
> Feat GitHub blueprint v200

- grafana/dashboards/Jenkins.json
- grafana/dashboards/WeeklyBugRetro.json
fix: update Jenkins and weekly bug retro dashboards
Closes https://github.com/apache/incubator-devlake/issues/3808
Closes https://github.com/apache/incubator-devlake/issues/3809
> fix: update jenkins and weekly bug retro dashboard

- plugins/jenkins/api/blueprint_v100.go
- plugins/jenkins/api/blueprint_v100_test.go
- plugins/jenkins/api/blueprint_v200.go
- plugins/jenkins/api/blueprint_v200_test.go
- plugins/jenkins/api/scope.go
- plugins/jenkins/impl/impl.go
- plugins/jenkins/models/job.go
- plugins/jenkins/models/transformation_rule.go
1. This is the implementation of Jenkins for data source plugins to support the PluginBlueprintV200 interface.
You can know more detail about the PluginBlueprintV200 interface on issue https://github.com/apache/incubator-devlake/pull/3613
2. fix some bug when put & patch scope
Related to #3613
> feat: support bp v200 for jenkins

- models/migrationscripts/20221201_add_project_pr_metric.go
- models/migrationscripts/archived/project_pr_metric.go
- models/migrationscripts/register.go
- plugins/dora/e2e/snapshot_tables/project_pr_metrics.csv
- plugins/dora/tasks/change_lead_time_calculator.go
Rename field name in project_pr_metrics and project_issue_matrics according to issue #3806
Relate to  #3806 
> refactor(domain): rename fields in project pr metrics

- plugins/refdiff/tasks/commit_diff_calculator.go
optimize refdiff performance.
time spent: n*n space: m ==>  time n*n 
related to https://github.com/apache/incubator-devlake/issues/3685
> feat: optimize refdiff performance

- config-ui/package-lock.json
- config-ui/package.json
- config-ui/src/components/index.ts
- config-ui/src/components/loading/index.tsx
- config-ui/src/components/loading/styled.ts
Add new component **Loading**.
> feat(config-ui): add new component loading

- config-ui/src/components/divider/index.tsx
Add new component **Divider**.
> feat(config-ui): add new component divider

- config-ui/src/components/page-header/index.tsx
- config-ui/src/components/page-header/styled.ts
Add new component **PageHeader**.
> feat(config-ui): add new component page-header

- config-ui/src/components/selector/index.ts
- config-ui/src/components/selector/multi-selector/index.tsx
- config-ui/src/components/selector/selector/index.tsx
1. Add new component **Selector**.
2. Add new component **MultiSelector**.
> feat(config-ui): add new component selector

- config-ui/src/components/dialog/index.tsx
- config-ui/src/components/dialog/styled.ts
> feat(config-ui): add new component dialog

- plugins/github/api/blueprint_v200.go
- plugins/github/api/scope.go
- plugins/github/impl/impl.go
- plugins/github/models/repo.go
- plugins/github/tasks/task_data.go
- plugins/gitlab/api/scope.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/models/migrationscripts/archived/project.go
- plugins/gitlab/models/project.go
- plugins/jenkins/api/scope.go
- plugins/jenkins/impl/impl.go
- plugins/jira/api/scope.go
- plugins/jira/impl/impl.go
- plugins/jira/models/board.go
1. support batch save scope
2. change the JSON key to camelCase
No
related to #3468
> feat: suppport batch save scope

- config-ui/src/components/table/index.ts
- config-ui/src/components/table/styled.ts
- config-ui/src/components/table/table.tsx
- config-ui/src/components/table/types.ts
> feat(config-ui): add new component table

- plugins/jira/api/blueprint_v100.go
- plugins/jira/api/blueprint_v200.go
- plugins/jira/api/blueprint_v200_test.go
- plugins/jira/impl/impl.go
- plugins/jira/models/board.go
- plugins/jira/models/transformation_rules.go
This is the implementation of Jenkins for data source plugins to support the PluginBlueprintV200 interface.
You can know more detail about the PluginBlueprintV200 interface on issue https://github.com/apache/incubator-devlake/pull/3613
Related to https://github.com/apache/incubator-devlake/pull/3613
> feat: add bp v200 for jira

- config-ui/src/layouts/base/use-menu.ts
misspell for menu.
Closes #3814
> fix(config-ui): misspell for menu

- config-ui/src/components/gitlab/project-selector/index.tsx
- config-ui/src/components/gitlab/project-selector/use-gitlab-project-selector.ts
use **multi-selector** to replace the original。
Like the original.
> refactor(config-ui): use multi-selector to replace the original

- config-ui/src/hooks/useIntegrations.jsx
- config-ui/src/layouts/base/styled.ts
- config-ui/src/layouts/base/use-menu.ts
- config-ui/src/pages/connections/incoming-webhook/index.jsx
- config-ui/src/styles/common.scss
1. adjust the style for **base-layout**.
2. rename **Data Connections** to **Connections** for menu.
3. remove **styles** that affect structure.
4. remove **console.log** from **useIntegrations**.
> refactor(config-ui): adjust the base layout

- logger/init.go
- runner/run_task.go
> [fix-3845]: Log subtask errors

- scripts/pm/github/create-blueprint-v200.sh
- scripts/pm/github/create-transformationrules.sh
- scripts/pm/github/put-repo.sh
- services/blueprint.go
Enable blueprint v200 on framework level
Related to #3468
> feat: enable blueprint v200 on framework level

- plugins/github/api/blueprint_V200_test.go
- plugins/github/api/blueprint_v200.go
1. divide making scopes and making plans to two funcs
2. refactor makePlan to contain for iteration, and modify unit test
relate to #3486 
> refactor(github): divide making scopes and making plans

- plugins/jenkins/api/blueprint_v200.go
- plugins/jenkins/api/blueprint_v200_test.go
- plugins/jenkins/api/connection.go
- plugins/jenkins/api/init.go
- plugins/jenkins/api/proxy.go
- plugins/jenkins/api/scope.go
- plugins/jenkins/api/transformation_rule.go
- plugins/jenkins/models/job.go
divide making scopes and making plans to two funcs
refactor makePlan to contain for iteration, and modify unit test
bp.settings of response
> Refactor(jenkins): bp v200

- plugins/jira/api/blueprint_v200.go
- plugins/jira/api/blueprint_v200_test.go
divide making scopes and making plans to two funcs
refactor makePlan to contain for iteration, and modify unit test
> Refactor jira bp v200

- models/migrationscripts/20221207_add_cicd_scope_drop_builds_jobs.go
- models/migrationscripts/register.go
- plugins/webhook/api/blueprint_v200.go
fix bug in MakeDataSourcePipelinePlanV200
delete table.builds and table.jobs if they exist
> fix(webhook): MakeDataSourcePipelinePlanV200

- grafana/dashboards/EngineeringOverview.json
some engineering-overview panels can not show well， we need to update some panel's logic and take data.
Closes #3871
> fix: some engineering-overview panels can not show well

- models/task.go
- services/pipeline_helper.go
cherry-picked from https://github.com/apache/incubator-devlake/pull/3894
> fix: pending task status

- config-ui/src/components/logo/index.tsx
- config-ui/src/components/logo/styled.ts
- config-ui/src/layouts/base/base.tsx
- config-ui/src/layouts/base/styled.ts
Add new component **logo**.
Because this is just a pre-work, I found that the same picture and style were referenced when I refactored the **error handling** and **offline**, so I encapsulated the content of this part first so that I could refactor the **error handling** and **offline** later.
> refactor(config-ui): add new component logo

- plugins/github/api/blueprint_V200_test.go
- plugins/github/api/blueprint_v200.go
- plugins/jira/api/blueprint_v200.go
- plugins/jira/api/blueprint_v200_test.go
- plugins/jira/impl/impl.go
Change the process of jira bp v200
Relate to #3468 
Post BP input:
Post BP output:
Trigger Bp output:
> feat(jira): refactor jira bp v200

- plugins/github/tasks/pr_collector.go
- plugins/github/tasks/pr_commit_collector.go
- plugins/github/tasks/pr_commit_convertor.go
- plugins/github/tasks/pr_commit_extractor.go
- plugins/github/tasks/pr_convertor.go
- plugins/github/tasks/pr_extractor.go
- plugins/github/tasks/pr_review_comment_collector.go
- plugins/github/tasks/pr_review_comment_extractor.go
- plugins/github/tasks/pr_review_convertor.go
- Code refactoring based on the proposal https://github.com/apache/incubator-devlake/issues/3867 
Closes #3867
> refactor: change domain types for github

- plugins/gitlab/gitlab.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/tasks/issue_collector.go
- plugins/gitlab/tasks/mr_collector.go
- plugins/gitlab/tasks/mr_commit_collector.go
- plugins/gitlab/tasks/mr_note_collector.go
- plugins/gitlab/tasks/pipeline_collector.go
- plugins/gitlab/tasks/shared.go
- plugins/gitlab/tasks/task_data.go
- plugins/jenkins/tasks/task_data.go
add options CreatedDateAfter for gitlab
1. update issue/pipeline's incremental collector
2. add incremental for mr's incremental collector
3. let issue/mr/mr_commit/mr_note/ only request data created after CreatedDateAfter
Similar like https://github.com/apache/incubator-devlake/issues/3688
> feat: add time filter for gitlab

- config-ui/src/pages/blueprint/create/hooks/use-blueprint-value.ts
- config-ui/src/pages/blueprint/create/styled.ts
- config-ui/src/plugins/common/transformation/styled.ts
- config-ui/src/plugins/github/styled.ts
- config-ui/src/plugins/webook/components/create-dialog/styled.ts
- config-ui/src/plugins/webook/components/view-or-edit-dialog/styled.ts
- config-ui/src/store/connections/use-connections.ts
1. Fixed one connection link failed will make all failed.
2. Fixed miss depends step on create-bp **error**.
3. Adjust the **payload** on create-bp.
4. Adjust the **style** for plugin and create-bp.
> fix(config-ui): create blueprint

- config-ui/src/App.js
- config-ui/src/hooks/useDataScopesManager.jsx
- config-ui/src/pages/blueprint/detail/api.ts
- config-ui/src/pages/blueprint/detail/blueprint-detail-page.tsx
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/index.ts
- config-ui/src/pages/blueprint/detail/types.ts
- config-ui/src/pages/blueprint/detail/use-detail.ts
- config-ui/src/pages/blueprints/blueprint-detail.jsx
- config-ui/src/pages/blueprints/blueprint-settings.jsx
- config-ui/src/pages/blueprints/index.jsx
- config-ui/src/pages/project/detail/panel/blueprint.tsx
1. improve the **project detail** page
2. fixed the interface return value to change.
> feat(config-ui): improve the project detail page

- config-ui/src/config/cron.ts
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/components/index.ts
- config-ui/src/pages/blueprint/detail/components/update-name-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/components/update-policy-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/components/update-scope-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/components/update-transformation-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/blueprint/detail/panel/status.tsx
- config-ui/src/pages/blueprint/detail/styled.ts
- config-ui/src/pages/blueprint/detail/use-detail.ts
refactor the **blueprint setting page**.
> refactor(config-ui): the blueprint setting page

- config-ui/src/index.js
- config-ui/src/pages/blueprint/create/bp-context.tsx
- config-ui/src/pages/blueprint/create/index.tsx
- config-ui/src/pages/blueprint/create/step-one/index.tsx
- config-ui/src/pages/blueprint/create/step-three/index.tsx
- config-ui/src/pages/blueprint/create/step-two/index.tsx
- config-ui/src/store/connections/context.tsx
- config-ui/src/store/connections/index.ts
- config-ui/src/store/connections/use-context-value.ts
- config-ui/src/store/index.ts
1. refactor the global **connection** store.
2. remove **connection** store from **app**.
3. adjust the **connection** store on the **create-blueprint**.
> refactor(config-ui): the connection store

- config-ui/Dockerfile
- config-ui/webpack.production.config.js
1. adjust **Node** version that docker depends on
2. adjust **css-loader** parameter.
> fix(config-ui): build image failed

- config-ui/src/pages/blueprint/create/bp-context.tsx
- config-ui/src/pages/blueprint/detail/components/update-policy-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/blueprint/detail/types.ts
adjust the parameter **createdDateAfter** position on the **create bp**.
Closes #3946
Closes #3947
> fix(config-ui): adjust createdDateAfter position on the create bp

- plugins/jenkins/api/blueprint_v100.go
- plugins/jenkins/api/blueprint_v100_test.go
- plugins/jenkins/api/jobs.go
- plugins/jenkins/api/jobs_test.go
- plugins/jenkins/models/response.go
Since we need compatibility with makePipelinePlanV100
So we need Jenkins to get all the jobs when makePipelinePlanV100
So we need a method to get all Jobs
Now create the method GetAllJobs and the corresponding unit test.
Closes xx
> Jenkins add GetAllJobs

- plugins/gitlab/api/blueprint_v200.go
- plugins/gitlab/impl/impl.go
- plugins/gitlab/models/migrationscripts/20221125_add_html_url_to_project.go
- plugins/gitlab/tasks/project_extractor.go
- plugins/jira/api/scope.go
- plugins/jira/impl/impl.go
support run bp v100 for jira & gitlab.
bp V200 assumed scopes have been saved in db. but bp V100 and advance mode not, so request and save them when calling PrepareTaskData.
I test them by run in cli.
> feat: support run bp v100 for jira & gitlab

- plugins/github/api/connection.go
add res.StatusCode != http.StatusOK 
Closes #3941 
> fix: wrong endpoint but test passed

- config-ui/src/hooks/useConnectionManager.jsx
- config-ui/src/index.css
- config-ui/src/pages/blueprint/create/bp-context.tsx
- config-ui/src/pages/blueprint/create/step-one/index.tsx
- config-ui/src/pages/blueprint/create/styled.ts
- config-ui/src/pages/blueprint/detail/styled.ts
- config-ui/src/plugins/common/data-scope-list/use-data-scope-list.ts
- config-ui/src/plugins/common/data-scope/api.ts
- config-ui/src/plugins/common/data-scope/use-data-scope.ts
- config-ui/src/plugins/common/transformation/use-transformation.ts
- config-ui/src/plugins/github/components/miller-columns/index.tsx
- config-ui/src/plugins/github/components/miller-columns/use-miller-columns.ts
- config-ui/src/plugins/github/components/repo-selector/use-repo-selector.ts
- config-ui/src/plugins/github/types.ts
- config-ui/src/plugins/gitlab/components/miller-columns/index.tsx
- config-ui/src/plugins/gitlab/components/miller-columns/use-miller-columns.ts
- config-ui/src/plugins/gitlab/components/project-selector/use-project-selector.ts
- config-ui/src/plugins/gitlab/types.ts
- config-ui/src/plugins/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/jenkins/types.ts
- config-ui/src/plugins/jira/types.ts
- config-ui/src/store/connections/use-context-value.ts
1. fix the **advanced** mode in bp cannot use.
2. fix the **connection** store type error.
3. adjust some style.
4. fix **transformationId** lost when the scope is selected.
5. fix the redirect link error.
6. improve the **put scopes** fields.
Closes #3950
> fix(config-ui): something error.

- runner/run_pipeline.go
- runner/run_task.go
> fix: display error messages of failed task

- README.md
> Added the Twitter badge ✅

- services/blueprint_makeplan_v200.go
Previously, we only delete project mapping when generating bp plan v200. In this pr, we delete project mapping with the same project name. Then we add project mapping according to project name and scopes generated by `func.genPlanJsonV200`
> fix(framework): update project mapping

- plugins/dbt/tasks/convertor.go
the dbt plugin shouldn't change the working directory
related to #3800 
> fix: the dbt plugin change the working directory

- runner/run_task.go
- services/pipeline_runner.go
- services/task.go
Cherry-pick PR #3985 to `release-v0.14`
> refactor: improve the error message for pipeline and task (#3985)

- config-ui/src/plugins/common/data-scope/use-data-scope.ts
data entities selection is not working
Closes #3894
> fix(config-ui): data entities selection is not working

- config-ui/src/components/page-header/styled.ts
- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
- config-ui/src/layouts/base/styled.ts
- config-ui/src/pages/blueprint/create/components/action/styled.ts
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/project/detail/styled.ts
- config-ui/src/pages/project/home/styled.ts
- config-ui/src/plugins/common/sync-policy/styled.ts
- config-ui/src/styles/pipelines.scss
1. the style for bp **tasks**.
2. bnp upgrade to check **scope transformation.**
3. adjust the default tab to **status**.
> fix(config-ui): the style for bp tasks

- config-ui/src/pages/blueprint/create/step-one/index.tsx
- config-ui/src/store/connections/context.tsx
- config-ui/src/store/connections/types.ts
- config-ui/src/store/connections/use-context-value.ts
add retry test connection on **bp create**.
Closes #3979
> fix(config-ui): add retry test connection on bp create

- plugins/jira/e2e/snapshot_tables/_tool_jira_statuses_for_changelog.csv
- plugins/jira/e2e/snapshot_tables/issue_changelogs.csv
- plugins/jira/tasks/issue_changelog_convertor.go
#3991
Closes #3991
covered by e2e test
> feat: translate issue changelogs original value

- plugins/gitlab/models/migrationscripts/archived/transformation_rules.go
- plugins/gitlab/models/transformation_rule.go
Add refdiff and productionPattern to transformation rules 
Closes #3999 
> fix(gitlab): add fields to transformation rule

- models/migrationscripts/20221221_add_error_name.go
- models/migrationscripts/register.go
- models/pipeline.go
- models/task.go
- runner/run_task.go
- services/pipeline_helper.go
- services/pipeline_runner.go
Add `error_name` to `_devlake_pipelines` and `_devlake_tasks`
Store shorter error message in the column `error_name`
Closes #3974
> refactor: add error_name to _devlake_pipelines and _devlake_tasks

- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/components/update-transformation-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/blueprint/detail/use-detail.ts
updated bp transformation not refresh
Closes #3951
> fix(config-ui): updated bp transformation not refresh

- config-ui/src/hooks/usePipelineManager.jsx
- config-ui/src/pages/blueprint/create/index.tsx
- config-ui/src/pages/blueprint/create/step-one/index.tsx
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/blueprint/detail/use-detail.ts
- config-ui/src/pages/blueprints/blueprint-detail.jsx
- config-ui/src/pages/configure/connections/AddConnection.jsx
- config-ui/src/pages/configure/connections/ConfigureConnection.jsx
- config-ui/src/pages/configure/connections/ConnectionForm.jsx
- config-ui/src/pages/configure/integration/index.jsx
- config-ui/src/pages/configure/settings/tapd.jsx
- config-ui/src/pages/configure/settings/zentao.jsx
- config-ui/src/pages/project/detail/styled.ts
1. fix cannot use advanced mode in project.
2. adjust the style for bp.
3. fix the push link error.
4. fix the token not check if one input skip.
5. fix cannot display correctly when bp has webhook.
6.  fix cannot display correctly when bp is advanced mode.
7. adjust the style for project detail.
> fix(config-ui): some bugs

- config-ui/src/plugins/common/data-scope-list/use-data-scope-list.ts
- config-ui/src/plugins/jenkins/components/miller-columns/index.tsx
> fix(config-ui): put jenkins scope failed

- plugins/jenkins/api/scope.go
- plugins/jenkins/impl/impl.go
fix the jenkins returns 404 if the `fullName` contains the slash symbol `/`
Closes xx
> fix: fix the jenkins 404 error

- api/plugininfo/plugininifo.go
- helpers/migrationhelper/migrationhelper_test.go
- helpers/pluginhelper/tap/models.go
- plugins/ae/impl/impl.go
- plugins/azure/impl/impl.go
- plugins/bitbucket/impl/impl.go
- plugins/core/plugin_model.go
- plugins/customize/impl/impl.go
- plugins/dbt/impl/impl.go
- plugins/dora/impl/impl.go
- plugins/feishu/impl/impl.go
- plugins/gitee/impl/impl.go
- plugins/gitextractor/impl/impl.go
- plugins/github/impl/impl.go
- plugins/github_graphql/impl/impl.go
- plugins/gitlab/impl/impl.go
- plugins/icla/impl/impl.go
- plugins/jenkins/impl/impl.go
- plugins/jira/impl/impl.go
- plugins/org/impl/impl.go
- plugins/refdiff/impl/impl.go
- plugins/starrocks/impl/impl.go
- plugins/tapd/impl/impl.go
- plugins/webhook/impl/impl.go
Completely replace core.Tabler with dal.Tabler
Closes #4002
> refactor: merge core.Table and dal.Tabler

- config-ui/src/pages/blueprint/create/bp-context.tsx
redirect bp id is not right
Closes #4021
> fix(config-ui): redirect bp id is not right

- config-ui/src/plugins/jenkins/components/miller-columns/index.tsx
- plugins/jenkins/models/job.go
fix jenkins plugin not save scope name
> fix: fix jenkins plugin not save scope name

- plugins/github/tasks/cicd_run_collector.go
Add incremental collection for github cicd run
> fix(github): add incremental support for cicd run

- plugins/github/tasks/cicd_run_collector.go
- plugins/github/tasks/comment_collector.go
- plugins/github/tasks/pr_review_comment_collector.go
Update incremental support for:
pr_review_comment_collector.go
cicd_run_collector.go
comment_collector.go
relate to #3886 
> fix(github): update incremental

- plugins/gitlab/models/transformation_rule.go
fix a camel case in gitlab transformation
> fix: fix a camel case in gitlab transformation

- config-ui/src/App.js
- config-ui/src/pages/blueprint/home/api.ts
- config-ui/src/pages/blueprint/home/index.tsx
- config-ui/src/pages/blueprint/home/styled.ts
- config-ui/src/pages/blueprint/home/use-home.ts
refactor the blueprints list page
> refactor(config-ui): the blueprints list page

- config-ui/src/App.js
- config-ui/src/layouts/base/use-menu.ts
- config-ui/src/pages/transformation/detail/api.ts
- config-ui/src/pages/transformation/detail/index.tsx
- config-ui/src/pages/transformation/detail/styled.ts
- config-ui/src/pages/transformation/detail/use-detail.ts
- config-ui/src/pages/transformation/home/index.tsx
- config-ui/src/pages/transformation/home/styled.ts
- config-ui/src/pages/transformation/index.ts
- config-ui/src/plugins/github/styled.ts
- config-ui/src/plugins/github/transformation.tsx
- config-ui/src/plugins/gitlab/styled.ts
- config-ui/src/plugins/gitlab/transformation.tsx
- config-ui/src/plugins/jenkins/styled.ts
- config-ui/src/plugins/jenkins/transformation.tsx
- config-ui/src/plugins/jira/styled.ts
- config-ui/src/store/transformations/api.ts
- config-ui/src/store/transformations/context.tsx
- config-ui/src/store/transformations/index.ts
- config-ui/src/store/transformations/types.ts
- config-ui/src/store/transformations/use-context-value.ts
1. adjust the style for **plugin** **transformation**.
2. add global **transformation** **store**.
3. add new page **transformation** **list**.
4. add new page **transformation** **detail**.
5. add **menu** and **routes** for **transformation**.
> feat(config-ui): add new pages about transformation

- docker-compose.yml
- plugins/dora/dora.go
- plugins/dora/e2e/snapshot_tables/project_pr_metrics.csv
- plugins/dora/tasks/change_lead_time_calculator.go
- plugins/dora/tasks/change_lead_time_calculator_old.go
- plugins/github/api/blueprint_V200_test.go
- plugins/github/api/blueprint_v200.go
- plugins/github/tasks/cicd_run_collector.go
- plugins/github_graphql/tasks/check_run_collector.go
- plugins/helper/api_collector.go
- plugins/helper/api_collector_with_state.go
- plugins/helper/graphql_collector.go
1. fix refdiff in bp v200
2. add incremental support for github graphql check run
3. because of github bug, we have to comment the code which added in pr #4041
4. fix a minor bug in dora change lead time calculator
relate to #3688 
> fix(github): update incremental support for check run

- plugins/gitextractor/main.go
- plugins/gitextractor/store/csv.go
Fix gitex csv which does not save snapshot
Fix logic of using csv or db in gitex.main
Closes #3928 
> fix(gitex): fix bugs

- config-ui/src/pages/pipeline/detail/components/task/index.tsx
- config-ui/src/pages/pipeline/detail/pipeline-detail.tsx
- config-ui/src/pages/pipeline/detail/styled.ts
- config-ui/src/pages/pipeline/types.ts
1. the pipeline tasks permutation error.
2. miss task progress detail.
> fix(config-ui): the pipeline tasks error

- config-ui/src/layouts/base/styled.ts
- config-ui/src/pages/blueprint/detail/blueprint-detail-page.tsx
- config-ui/src/pages/blueprint/detail/styled.ts
add jenkins no scope tips.
Closes #3457
> feat(config-ui): add jenkins no scope tips

- plugins/jenkins/api/jobs.go
- plugins/jenkins/impl/impl.go
fix: jenkins multi-dirs can not collect
mutil path need add **job/** into the api.
Closes #4074
> fix: jenkins multi-dirs can not collect

- services/project.go
rename the project before updating it to fix the project created by rename.
Closes #4079
> fix: fix rename create the new project

- plugins/tapd/models/bug.go
- plugins/tapd/models/bug_custom_field.go
- plugins/tapd/models/migrationscripts/20230103_increase_field_length.go
- plugins/tapd/models/migrationscripts/archived/bug.go
- plugins/tapd/models/migrationscripts/archived/bug_custom_field.go
- plugins/tapd/models/migrationscripts/archived/story.go
- plugins/tapd/models/migrationscripts/archived/story_custom_field.go
- plugins/tapd/models/migrationscripts/archived/task.go
- plugins/tapd/models/migrationscripts/archived/task_custom_field.go
- plugins/tapd/models/story.go
- plugins/tapd/models/story_custom_field.go
- plugins/tapd/models/task.go
- plugins/tapd/models/task_custom_field.go
Increased filed length to meet most situations
Closes #4081 
> fix(tapd): increase fields leangth

- api/project/project.go
- api/router.go
Fixes Backend part of #4086 
Part of #4086
> fix: accept project with name containing slash

- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
- config-ui/src/utils/operator.ts
fix the bugs in upgrade:
1. a typo when reading name
2. scope -> scopes
3. pass correct scopeId
> fix: fix the bug in upgrade

- runner/run_pipeline.go
- runner/run_task.go
Update `pipeline.finished_tasks` in time
Closes #4096
> fix: update `pipeline.finished_tasks`  in time

- plugins/dbt/tasks/convertor.go
i can not recurrent this bug, but it occur in production env.
same to https://github.com/go-gitea/git/blob/master/commit_info.go#L237.
related to #3921
> fix: maybe can fix dbt zombie processes

- config-ui/src/components/delete-button/index.tsx
- config-ui/src/components/dialog/index.tsx
- config-ui/src/components/index.ts
- config-ui/src/pages/blueprint/create/step-three/use-columns.tsx
- config-ui/src/pages/blueprint/create/step-two/index.tsx
- config-ui/src/pages/blueprint/create/step-two/use-columns.tsx
- config-ui/src/pages/blueprint/detail/components/add-scope-dialog/index.tsx
- config-ui/src/pages/blueprint/detail/components/index.ts
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/blueprint/detail/types.ts
- config-ui/src/plugins/common/data-scope-list/index.tsx
- config-ui/src/plugins/common/data-scope-list/styled.ts
- config-ui/src/plugins/common/data-scope-list/use-data-scope-list.ts
- config-ui/src/plugins/common/data-scope/index.tsx
- config-ui/src/plugins/common/data-scope/use-data-scope.ts
- config-ui/src/plugins/github/components/miller-columns/index.tsx
- config-ui/src/plugins/github/components/repo-selector/index.tsx
- config-ui/src/plugins/github/components/repo-selector/use-repo-selector.ts
- config-ui/src/plugins/github/data-scope.tsx
- config-ui/src/plugins/github/types.ts
- config-ui/src/plugins/gitlab/components/miller-columns/index.tsx
- config-ui/src/plugins/gitlab/components/project-selector/index.tsx
- config-ui/src/plugins/gitlab/components/project-selector/use-project-selector.ts
- config-ui/src/plugins/gitlab/data-scope.tsx
- config-ui/src/plugins/gitlab/types.ts
- config-ui/src/plugins/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/jenkins/data-scope.tsx
- config-ui/src/plugins/jira/components/miller-columns/index.tsx
- config-ui/src/plugins/jira/data-scope.tsx
1. adjust the plugin data scope.
2. add new component **delete-button**.
3. adjust the component **dialog** parameter **children**.
4. adjust the create blueprint data scope.
5. adjust the blueprint detail data scope.
> fix(config-ui): the data scope select error

- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- services/blueprint_makeplan_v200.go
Jenkins v100 needn't scope. So I create a V100 bp with jenkins try to upgrade it and fix some some bugs.
> fix: support jenkins v100 upgrade

- config-ui/src/plugins/gitlab/components/miller-columns/index.tsx
- config-ui/src/plugins/jira/data-scope.tsx
data scope cannot select on gitlab and jira
> fix(config-ui): data scope cannot select on gitlab and jira

- config-ui/src/pages/connection/form/components/rate-limit/index.tsx
- config-ui/src/pages/connection/form/components/rate-limit/styled.ts
- config-ui/src/pages/connection/form/index.tsx
- config-ui/src/pages/connection/form/use-form.ts
- config-ui/src/plugins/github/config.ts
- config-ui/src/plugins/gitlab/config.ts
- config-ui/src/plugins/jenkins/config.ts
- config-ui/src/plugins/jira/config.ts
- config-ui/src/plugins/types.ts
adjust the **rateLimitPerHour** default value.
Closes #4068
> fix(config-ui): adjust the rateLimitPerHour default value

- config-ui/src/layouts/base/base.tsx
- config-ui/src/layouts/base/styled.ts
fix the style of version
closes https://github.com/apache/incubator-devlake/issues/3607
> fix: fix the style of version

- plugins/dbt/tasks/convertor.go
i can not recurrent this bug, but it occur in production env.
related to #3921
> fix: maybe can fix-2 dbt zombie processes

- config-ui/src/pages/connection/form/index.tsx
- config-ui/src/pages/connection/home/index.tsx
- config-ui/src/pages/connection/home/styled.ts
- config-ui/src/plugins/bitbucket/config.ts
- config-ui/src/plugins/config.ts
- config-ui/src/plugins/github/config.ts
- config-ui/src/plugins/tapd/config.ts
- config-ui/src/plugins/types.ts
- config-ui/src/plugins/zentao/config.ts
1. add tag **beta** for connection.
2. rename **github-token** to **githubToken**.
3. update plugin the **bitbucket** config.
4. adjust the config for **tapd** and **zentao**.
5. adjust the **position** for plugin.
> feat(config-ui): support connection bitbucket

- .github/ISSUE_TEMPLATE/bug-report.yml
- releases/lake-v0.15.0/docker-compose.yml
- releases/lake-v0.15.0/env.example
prepare for releasing v0.15.0
- create folder `releases/lake-v0.15.0` which should include two files `docker-compose.yml` and `env.example`
- update the bug report template to include the version v0.15.0
Closes #4127 
> docs: prepare for releasing v0.15.0

- config-ui/src/pages/blueprint/components/advanced-editor/index.tsx
- config-ui/src/pages/connection/form/index.tsx
- config-ui/src/pages/project/home/index.tsx
- config-ui/src/plugins/gitlab/config.ts
- config-ui/src/plugins/types.ts
1. add **DORA metrics**  doc link.
2. add **gitlab** on how to create a token.
3. add **advanced** mode examples link.
Closes #4143
> feat(config-ui): add some documentation links

- config-ui/src/pages/pipeline/components/historical/index.tsx
- config-ui/src/pages/transformation/home/index.tsx
1. rename **Download Log** to **Download Logs**
2. fixed copywriting.
Closes #4147
> fix(config-ui): copywriting error

- plugins/bitbucket/api/blueprint.go
- plugins/bitbucket/api/blueprint_test.go
Backwards port of #4138 in to the 0.14 release.
Relates to #4138
> Bitbucket cloning error fix for v0.14.8

- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/blueprint/detail/panel/status.tsx
- config-ui/src/pages/blueprint/detail/use-detail.ts
1. adjust the blueprint status and configuration panel.
2. change the status daily to the next run date.
3. adjust the style for configuration.
Closes #4145
> refactor(config-ui): adjust the blueprint status and configuration panel

- config-ui/src/layouts/base/use-menu.ts
- grafana/dashboards/Homepage.json
- grafana/dashboards/Zentao.json
- fix: dashboard link on the config-ui
- fix: add the missing zentao dashboard
N/A
> fix: home dashboard link and zentao dashboard

- deployment/k8s/k8s-deploy.yaml
- releases/lake-v0.15.0/docker-compose.yml
change grafana theme in docker-compose.yml in 0.15
> feat(releases): change grafana theme in 0.15

- config-ui/src/components/inspector/index.tsx
- config-ui/src/components/inspector/styled.ts
- config-ui/src/pages/blueprint/components/advanced-editor/example/general.ts
- config-ui/src/pages/blueprint/components/advanced-editor/example/github.ts
- config-ui/src/pages/connection/form/use-form.ts
- config-ui/src/plugins/github/components/code-review/index.tsx
- config-ui/src/plugins/github/components/code-review/styled.ts
- config-ui/src/store/transformations/use-context-value.ts
1. Add some description for **inspector**.
2. Adjust the advanced **github** example.
3. **Tips** for optimizing connection test failure.
4. Adjust the **style** for github transformation
5. Hide the **beta connection** for transformation page.
Closes #4149
1. ![image](https://user-images.githubusercontent.com/37237996/211238661-2fb31b81-6382-4108-9c58-1f01339666af.png)
2. ![image](https://user-images.githubusercontent.com/37237996/211238705-5041349c-cea7-4c33-98e7-51cb0dd50576.png)
3. ![image](https://user-images.githubusercontent.com/37237996/211238734-b030aa13-b44e-4bd1-9272-f5c8c9489b5c.png)
4. ![image](https://user-images.githubusercontent.com/37237996/211238754-80dfa697-7159-4da6-9c40-bd32be841cda.png)
5. ![image](https://user-images.githubusercontent.com/37237996/211238768-8e7e62a3- …
> refactor(config-ui): optimize some content

- config-ui/src/plugins/gitlab/api.ts
- config-ui/src/plugins/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/jenkins/components/miller-columns/use-miller-columns.ts
1. filter shared projects in **gitlab**.
2. adjust the rules for **jenkins** miller columns id
Closes #4154
> fix(config-ui): duplicatd ID in items

- config-ui/src/data/pipeline-config-samples/starrocks.js
- plugins/starrocks/api/connection.go
- plugins/starrocks/starrocks.go
- plugins/starrocks/task_data.go
- plugins/starrocks/tasks.go
> feat: skip sync data when table not changed

- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
Optimize the operation in blueprint detail.
Closes #4167
> refactor(config-ui): optimize the operation in blueprint detail

- config-ui/src/pages/pipeline/components/duration/index.tsx
- config-ui/src/pages/pipeline/components/historical/index.tsx
- config-ui/src/pages/pipeline/detail/components/task/index.tsx
- config-ui/src/pages/pipeline/detail/pipeline-detail.tsx
- config-ui/src/pages/pipeline/types.ts
- config-ui/src/utils/time.ts
Pipeline and task duration calculation errors.
Closes #4166
> fix(config-ui): pipeline and task duration calculation errors

- services/blueprint_helper.go
- services/init.go
> fix: blueprint api would panic if len(settings) is zero

- config-ui/src/layouts/base/use-menu.ts
- grafana/dashboards/EngineeringThroughputAndCycleTime.json
- grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
- Update Engineering Throughput and Cycle Time Dashboard
- Update Engineering Throughput and Cycle Time - Team View Dashboard
> Update Engineering Throughput and Cycle Time Dashboard

- services/pipeline_runner.go
- test/services/pipeline_runner_e2e_test.go
> fix: unable to cancel pipeline with skip-on-fail

- plugins/tapd/tasks/iteration_converter.go
> fix(tapd): cherrypick #4193 to v0.14

- .github/workflows/NOTICE-year-check.yml
- NOTICE
- updated the year in the NOTICE file to 2023
- created a GitHub action to check the NOTICE file automatically.
Close #4200
> fix: update NOTICE file

- Makefile
- backend/Makefile
This pr enable us to use main dir's makefile to execute sub dir's makefile 
Closes #4202 
> Fix makefile

- backend/Dockerfile
- backend/plugins/dbt/dbt.go
- backend/plugins/dbt/tasks/convertor.go
add docker init, solve zombie process and add dbt err message.
related to #3919 
> fix: add docker init, solve zombie process

- config-ui/src/pages/connection/form/index.tsx
Connection initial values not work.
> fix(config-ui): connection initial values not work

- config-ui/src/pages/connection/form/index.tsx
The priority of the initial value and get value is wrong
> fix(config-ui): the priority of the initial value and get value is wrong

- config-ui/src/pages/pipeline/components/task/index.tsx
Refactoring missed modifications
Closes #4226
> fix(config-ui): refactoring missed modifications

- plugins/dbt/tasks/convertor.go
> fix: dbt error not return

- plugins/starrocks/tasks.go
> fix: close starrocks conn

- backend/helpers/pluginhelper/api/api_extractor.go
- backend/plugins/jira/tasks/issue_changelog_collector.go
- backend/plugins/jira/tasks/remotelink_collector.go
- backend/plugins/jira/tasks/worklog_collector.go
Modify incremental collection to make collector work efficient.
Closes #4239 
> fix(jira): optimize collector for remotelink worklog changelog

- backend/helpers/pluginhelper/api/api_async_client.go
Some logging corrections.
Closes #4254
> [fix-4254]: Correct logging of http async error

- plugins/helper/api_async_client.go
cherry pick the #4255 to release-v0.15
relate to #4254
> cherrypick #4255 to release-v0.15

- plugins/jira/tasks/issue_changelog_collector.go
- plugins/jira/tasks/remotelink_collector.go
- plugins/jira/tasks/worklog_collector.go
cherrypick #4245 to v0.15
relate to #4239
> fix(jira): cherrypick #4245 to v0.15

- plugins/starrocks/tasks/tasks.go
> fix: close starrocks conn (#4244)

- NOTICE
remove some redundant processing from NOTICE
Closes xx
> Fix release v0.15 notice

- plugins/starrocks/tasks.go
> fix: close pg conn

- backend/generator/cmd/create_plugin.go
- backend/generator/template/plugin/api/blueprint.go-template
- backend/generator/template/plugin/api/connection.go-template
- backend/generator/template/plugin/impl/impl_complete_plugin.go-template
- backend/generator/template/plugin/models/connection.go-template
- backend/generator/template/plugin/tasks/api_client.go-template
- backend/generator/template/plugin/tasks/api_collector.go-template
- backend/generator/template/plugin/tasks/extractor.go-template
- backend/generator/template/plugin/tasks/shared.go-template
- backend/generator/template/plugin/tasks/task_data.go-template
- backend/generator/template/plugin/tasks/task_data_complete_plugin.go-template
- backend/plugins/icla/tasks/task_data.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/connection.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_project.go
- backend/plugins/sonarqube/models/sonarqube_project.go
- backend/plugins/sonarqube/sonarqube.go
- backend/plugins/sonarqube/tasks/api_client.go
- backend/plugins/sonarqube/tasks/projects_collector.go
- backend/plugins/sonarqube/tasks/projects_extractor.go
- backend/plugins/sonarqube/tasks/shared.go
- backend/plugins/sonarqube/tasks/task_data.go
- backend/plugins/zentao/tasks/task_data.go
This pr add sonarqube project collector&extractor
Relate to #2305 
> Feat(sonarqube): projects

- config-ui/package-lock.json
- config-ui/package.json
miller columns repeated selection item.
Closes #4240
> fix(config-ui): miller columns repeated selection item

- plugins/starrocks/tasks/tasks.go
> fix: close pg conn after rows

- config-ui/src/pages/connection/form/components/index.ts
- config-ui/src/pages/connection/form/components/jira-auth/index.tsx
- config-ui/src/pages/connection/form/index.tsx
- config-ui/src/plugins/register/base/connection-fields.ts
- config-ui/src/plugins/register/jira/config.ts
- config-ui/src/plugins/types.ts
Support bearer authentication for **JIRA**.
Closes #4211
> feat(config-ui): support bearer authentication for jira

- backend/helpers/pluginhelper/api/api_client.go
- backend/helpers/pluginhelper/api/apihelperabstract/api_client_abstract.go
- backend/helpers/pluginhelper/api/apihelperabstract/connection_abstract.go
- backend/plugins/ae/impl/impl.go
- backend/plugins/ae/models/connection.go
- backend/plugins/github/api/blueprint_V200_test.go
- backend/plugins/github/api/blueprint_test.go
- backend/plugins/github/api/connection.go
- backend/plugins/github/models/connection.go
- backend/plugins/github/tasks/api_client.go
- backend/plugins/gitlab/models/connection.go
Part of #4298 
Part of #4298 
This PR have been tested
> Refactor: simplify Github ApiClient creation logic - 4298

- config-ui/src/plugins/gitlab/api.ts
- config-ui/src/plugins/gitlab/components/miller-columns/use-miller-columns.ts
Fixed gitlab scope id duplicate.
Closes #4296
> fix(config-ui): gitlab scope id duplicate

- backend/plugins/azure/api/connection.go
- backend/plugins/azure/models/connection.go
- backend/plugins/azure/tasks/api_client.go
1. add swagger doc
2. fix test connection
3. simplify azure api client creation
Part of #4298 
pipeline
> refactor: simplify azure api client creation

- config-ui/src/plugins/gitlab/components/miller-columns/index.tsx
Fixed gitlab scope put error. 
Closes #4296
> fix(config-ui): gitlab scope put error

- backend/plugins/gitee/api/blueprint_test.go
- backend/plugins/gitee/api/connection.go
- backend/plugins/gitee/impl/impl.go
- backend/plugins/gitee/models/connection.go
- backend/plugins/gitee/tasks/api_client.go
[What does this PR do?](refactor: simplify gitee apiclient creation)
Part of #4298 
pipeline
> refactor: simplify gitee apiclient creation

- backend/plugins/gitlab/api/connection.go
- backend/plugins/gitlab/tasks/api_client.go
- backend/plugins/jenkins/api/blueprint_v100_test.go
- backend/plugins/jenkins/api/connection.go
- backend/plugins/jenkins/impl/impl.go
- backend/plugins/jenkins/models/connection.go
- backend/plugins/jenkins/tasks/api_client.go
1. fix gitlab testconnection
2. simplify jenkins apiclient creation
Part of #4298 
gitlab test conn
jenkins-testconn
jenkins-createconn
jenkins-pipeline
> refactor: simplify jenkins apiclient creation

- backend/plugins/customize/tasks/task_data.go
Bug fix, for detail, to #4315 
Closes #4315
No
> fix: task data decode failed

- backend/plugins/jira/api/connection.go
- backend/plugins/jira/models/connection.go
- backend/plugins/jira/tasks/api_client.go
simplify jira apiclient creation
Part of #4298 
test connection for basic auth
test connection for pat
pipeline
> refactor: simplify jira apiclient creation

- backend/generator/template/plugin/api/blueprint.go-template
- backend/generator/template/plugin/api/connection.go-template
- backend/generator/template/plugin/api/init.go-template
- backend/generator/template/plugin/plugin_main.go-template
- backend/generator/template/plugin/tasks/api_client.go-template
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_project.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_project.go
- backend/plugins/sonarqube/sonarqube.go
- backend/plugins/sonarqube/tasks/hotspots_collector.go
- backend/plugins/sonarqube/tasks/hotspots_extractor.go
- backend/plugins/sonarqube/tasks/shared.go
- backend/plugins/sonarqube/tasks/task_data.go
Add hotspots collector&extractor
Part of #2305 
> feat(sonarqube): add hotspots collector&extractor

- backend/plugins/jira/tasks/issue_convertor.go
- backend/plugins/jira/tasks/issue_convertor_test.go
- Fix the bug reported in #4326 
- Supply two more test cases to verify the fix
Closes #4326
> fix: fix jira issue url

- plugins/jira/tasks/issue_convertor.go
- plugins/jira/tasks/issue_convertor_test.go
Cherry-pick PR#4328
Closes #4326
> Cherry-pick PR#4328

- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
sonarqube issue collector and extractor
part of #2305 
> feat: sonarqube issue collector and extractor

- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue_code_block.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_issue_code_block.go
- backend/plugins/sonarqube/tasks/hotspots_extractor.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
Extract code blocks from issues
part of https://github.com/apache/incubator-devlake/issues/2305
_tool_sonarqube_issue_code_blocks
> feat(sonarqube): extract code blocks

- backend/plugins/tapd/api/connection.go
- backend/plugins/tapd/impl/impl.go
- backend/plugins/tapd/models/connection.go
- backend/plugins/tapd/tasks/api_client.go
- backend/plugins/tapd/tasks/task_data.go
- backend/plugins/zentao/api/connection.go
- backend/plugins/zentao/models/connection.go
- backend/plugins/zentao/tasks/api_client.go
1. simplify tapd/zentao apiclient createion
Part of #4298
Tapd create connection
Tapd run pipeline
Tapd test connection
Zentao create connection
Zentao run pipeline
Zentao test connection
> refactor: simplify apiclient tapd/zentao zentao

- backend/generator/template/plugin/tasks/extractor.go-template
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/sonarqube_file_metrics.go
- backend/plugins/sonarqube/tasks/filemetrics_collector.go
- backend/plugins/sonarqube/tasks/filemetrics_extractor.go
- backend/plugins/sonarqube/tasks/hotspots_extractor.go
Add file metrics collector and extractor
part of #2305 
> feat(sonarqube): add file metrics

- backend/helpers/pluginhelper/api/api_client.go
- backend/plugins/bitbucket/api/blueprint.go
- backend/plugins/bitbucket/api/blueprint_test.go
- backend/plugins/bitbucket/tasks/task_data.go
- backend/plugins/gitee/api/blueprint.go
- backend/plugins/gitee/api/blueprint_test.go
- backend/plugins/github/api/blueprint.go
- backend/plugins/github/api/blueprint_test.go
- backend/plugins/github/api/connection.go
- backend/plugins/github/api/proxy.go
- backend/plugins/gitlab/api/blueprint.go
- backend/plugins/gitlab/api/blueprint_test.go
- backend/plugins/gitlab/api/blueprint_v200.go
- backend/plugins/gitlab/api/proxy.go
- backend/plugins/jenkins/api/blueprint_v100.go
- backend/plugins/jenkins/api/blueprint_v100_test.go
- backend/plugins/jenkins/api/jobs.go
- backend/plugins/jenkins/api/jobs_test.go
- backend/plugins/jira/api/proxy.go
- backend/plugins/jira/api/scope.go
unify all apiclient creation for all plugins
Closes #4298
bitbucket-blueprint-normalmode
gitee-blueprint-normalmode
github-blueprint-normalmode
github-proxy
gitlab-blueprint-normalmode
gitlab-blueprint-normalmode-v2
gitlab-proxy
jenkins-blueprint-normalmode
jira-proxy
make-test
> refactor: unify all apiclient creation for all plugins

- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
Reorder columns according to design
part of #2305 
> fix(sonarqube): Reorder columns according to design

- backend/plugins/github_graphql/impl/impl.go
> [fix-4351]: Github Graphql endpoint resolution fix

- config-ui/package-lock.json
- config-ui/package.json
- config-ui/src/plugins/register/github/components/miller-columns/index.tsx
- config-ui/src/plugins/register/github/components/miller-columns/use-miller-columns.ts
- config-ui/src/plugins/register/github/components/repo-selector/index.tsx
- config-ui/src/plugins/register/github/data-scope.tsx
- config-ui/src/plugins/register/gitlab/components/miller-columns/index.tsx
- config-ui/src/plugins/register/gitlab/components/miller-columns/use-miller-columns.ts
- config-ui/src/plugins/register/gitlab/data-scope.tsx
- config-ui/src/plugins/register/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jenkins/components/miller-columns/use-miller-columns.ts
- config-ui/src/plugins/register/jira/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jira/components/miller-columns/use-miller-columns.ts
Simplify **miller-columns** for each plugin.
#4305
> refactor(config-ui): simplify miller-columns for each plugin

- backend/core/models/domainlayer/securitytesting/st_projects.go
- backend/core/models/migrationscripts/20230208_add_security_testing.go
- backend/core/models/migrationscripts/archived/st_projects.go
- backend/core/models/migrationscripts/register.go
- backend/core/plugin/plugin_task.go
- backend/plugins/dora/tasks/task_data.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/sonarqube.go
- backend/plugins/sonarqube/tasks/project_convertor.go
Add project convertor
part of #2305 
> feat(sonarqube): add project convertor

- backend/core/models/domainlayer/securitytesting/st_file_metrics.go
- backend/core/models/domainlayer/securitytesting/st_issues.go
- backend/core/models/domainlayer/securitytesting/st_projects.go
- backend/core/models/migrationscripts/20230208_add_security_testing.go
- backend/core/models/migrationscripts/archived/st_file_metrics.go
- backend/core/models/migrationscripts/archived/st_issues.go
- backend/core/models/migrationscripts/archived/st_projects.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_file_metrics.go
- backend/plugins/sonarqube/tasks/filemetrics_convertor.go
- backend/plugins/sonarqube/tasks/filemetrics_extractor.go
- backend/plugins/sonarqube/tasks/hotspots_convertor.go
- backend/plugins/sonarqube/tasks/issues_convertor.go
- backend/plugins/sonarqube/tasks/projects_convertor.go
add file metrics convertor
part of #2305 
> feat(sonarqube): add file metrics convertor

- backend/core/models/domainlayer/securitytesting/st_issue_code_blocks.go
- backend/core/models/domainlayer/securitytesting/st_issues.go
- backend/core/models/domainlayer/securitytesting/st_projects.go
- backend/core/models/migrationscripts/archived/st_issue_code_blocks.go
- backend/core/models/migrationscripts/archived/st_issues.go
- backend/core/models/migrationscripts/archived/st_projects.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue_code_block.go
- backend/plugins/sonarqube/models/sonarqube_issue_code_block.go
- backend/plugins/sonarqube/tasks/hotspots_convertor.go
- backend/plugins/sonarqube/tasks/issue_code_blocks_convertor.go
- backend/plugins/sonarqube/tasks/issues_convertor.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
- backend/plugins/sonarqube/tasks/projects_convertor.go
sonarqube issue project update
part of #2305 
> feat: sonarqube issue project update

- config-ui/src/pages/connection/form/index.tsx
- config-ui/src/store/connections/api.ts
- config-ui/src/store/connections/types.ts
- config-ui/src/store/connections/use-context-value.ts
Test fails after introducing jira bearer authentication
#4287
> fix(config-ui): test fails after introducing jira bearer authentication

- backend/generator/template/plugin/tasks/api_collector.go-template
- backend/generator/template/plugin/tasks/extractor.go-template
- backend/plugins/customize/api/swagger.go
- backend/plugins/github/api/swagger.go
- backend/plugins/gitlab/api/swagger.go
- backend/plugins/jenkins/api/connection.go
- backend/plugins/jira/api/swagger.go
- backend/plugins/jira/impl/impl.go
- backend/plugins/sonarqube/api/blueprint_v200.go
- backend/plugins/sonarqube/api/blueprint_v200_test.go
- backend/plugins/sonarqube/api/swagger.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/tasks/accounts_collector.go
- backend/plugins/sonarqube/tasks/accounts_extractor.go
- backend/plugins/sonarqube/tasks/filemetrics_collector.go
- backend/plugins/sonarqube/tasks/filemetrics_extractor.go
- backend/plugins/sonarqube/tasks/hotspots_collector.go
- backend/plugins/sonarqube/tasks/hotspots_extractor.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
- backend/plugins/sonarqube/tasks/projects_collector.go
- backend/plugins/sonarqube/tasks/projects_extractor.go
- backend/plugins/tapd/api/swagger.go
- backend/plugins/zentao/api/connection.go
Add blueprint200
Modify collector and extractor templates in generator
part of #2305 
create blueprint:
trigger blueprint
swagger:
> feat(sonarqube): add blueprint200

- plugins/dbt/tasks/convertor.go
Closes https://github.com/apache/incubator-devlake/issues/4233
> fix: dbt error not return (#4237)

- backend/core/models/domainlayer/securitytesting/st_file_metrics.go
- backend/core/models/domainlayer/securitytesting/st_issues.go
- backend/core/models/domainlayer/securitytesting/st_projects.go
- backend/core/models/migrationscripts/20230208_add_security_testing.go
- backend/core/models/migrationscripts/archived/st_file_metrics.go
- backend/core/models/migrationscripts/archived/st_issues.go
- backend/core/models/migrationscripts/archived/st_projects.go
- backend/plugins/sonarqube/api/blueprint_v200.go
- backend/plugins/sonarqube/api/blueprint_v200_test.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/sonarqube/models/migrationscripts/20230111_add_init_tables.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_project.go
- backend/plugins/sonarqube/models/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_project.go
- backend/plugins/sonarqube/tasks/filemetrics_convertor.go
- backend/plugins/sonarqube/tasks/filemetrics_extractor.go
- backend/plugins/sonarqube/tasks/hotspots_convertor.go
- backend/plugins/sonarqube/tasks/issue_code_blocks_convertor.go
- backend/plugins/sonarqube/tasks/issues_convertor.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
- backend/plugins/sonarqube/tasks/projects_convertor.go
Tool Layer: key -> issue/project/hotspot_key
Domain Layer： revision -> commit_sha
part of #2305 
> fix(sonarqube): fix issues from first review

- backend/core/models/domainlayer/securitytesting/st_file_metrics.go
- backend/core/models/domainlayer/securitytesting/st_issues.go
- backend/core/models/migrationscripts/archived/st_file_metrics.go
- backend/core/models/migrationscripts/archived/st_issues.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_account.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/migrationscripts/archived/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_account.go
- backend/plugins/sonarqube/models/sonarqube_file_metrics.go
- backend/plugins/sonarqube/models/sonarqube_hotspot.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
- backend/plugins/sonarqube/tasks/filemetrics_convertor.go
- backend/plugins/sonarqube/tasks/filemetrics_extractor.go
- backend/plugins/sonarqube/tasks/hotspots_convertor.go
- backend/plugins/sonarqube/tasks/hotspots_extractor.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/issues_convertor.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
- backend/plugins/sonarqube/tasks/projects_extractor.go
- backend/plugins/sonarqube/tasks/task_data.go
> fix:(sonarqube) fix issues from second review

- backend/helpers/pluginhelper/api/api_client.go
- backend/plugins/github/api/connection.go
fix: github test connection not working
Closes #4375 
when passing the `connection` to `NewApiClientFromConnection`
> fix: github test connection not working

- backend/plugins/tapd/tasks/story_changelog_extractor.go
Just fix code on branch fix-tapd-convert-unicode
> fix(tapd): convert unicode to string

- plugins/tapd/tasks/story_changelog_extractor.go
Copy code from #4398 to hexun-tap
Part of #4394 
> fix(tapd): cherrypick from #4399 to hexun-tapd

- plugins/tapd/tasks/bug_changelog_collector.go
- plugins/tapd/tasks/story_changelog_extractor.go
cherrypick #4399 #4395 to 0.15
part of #4394 
> fix(tapd): cherrypick #4399#4395 to 0.15

- backend/plugins/gitlab/impl/impl.go
Competion gitlab subtasks
Closes #4404
> fix(gitlab): completion subtasks

- backend/plugins/sonarqube/api/remote.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/tasks/projects_extractor.go
add remote api
same feature as #4396 for sonarqube
```shell
curl --request GET \
--url 'http://127.0.0.1:8080/plugins/sonarqube/connections/1/search-remote-scopes?search=aerosolve' \
--header 'content-type: multipart/form-data'
```
Response:
```json
[
{
"ConnectionId": 0,
"projectKey": "f5a50c63-2e8f-4107-9014-853f6f467757",
"name": "aerosolve",
"qualifier": "TRK",
"visibility": "public",
"lastAnalysisDate": "2023-01-02T06:58:08+0000",
"revision": "442e76ebb7cbc7f60b04fbfac30dbf862aaffc67"
}
]
```
```shell
curl --request GET \
--url http://127.0.0.1:8080/plugins/sonarqube/connections/1/remote-scopes \
--header 'content-type: multipart/form-data'
```
Response:
```json
{
"children": [
...,
{
"type": "scope",
"parentId": null,
"id": "e2c6d5e9-a321-4e8c-b322-03d9599ef962",
"data": { …
```
> feat(sonarqube): add remote api

- backend/core/models/domainlayer/codequality/cq_file_metrics.go
- backend/core/models/domainlayer/codequality/cq_issue_code_blocks.go
- backend/core/models/domainlayer/codequality/cq_issues.go
- backend/core/models/domainlayer/codequality/cq_projects.go
- backend/core/models/migrationscripts/20230208_add_code_quality.go
- backend/core/models/migrationscripts/archived/cq_file_metrics.go
- backend/core/models/migrationscripts/archived/cq_issue_code_blocks.go
- backend/core/models/migrationscripts/archived/cq_issues.go
- backend/core/models/migrationscripts/archived/cq_projects.go
- backend/core/models/migrationscripts/register.go
- backend/core/plugin/plugin_task.go
- backend/plugins/sonarqube/api/blueprint_v200.go
- backend/plugins/sonarqube/api/blueprint_v200_test.go
- backend/plugins/sonarqube/e2e/filemetrics_test.go
- backend/plugins/sonarqube/e2e/hotspot_test.go
- backend/plugins/sonarqube/e2e/issue_test.go
- backend/plugins/sonarqube/e2e/project_test.go
- backend/plugins/sonarqube/tasks/filemetrics_collector.go
- backend/plugins/sonarqube/tasks/filemetrics_convertor.go
- backend/plugins/sonarqube/tasks/filemetrics_extractor.go
- backend/plugins/sonarqube/tasks/hotspots_collector.go
- backend/plugins/sonarqube/tasks/hotspots_convertor.go
- backend/plugins/sonarqube/tasks/hotspots_extractor.go
- backend/plugins/sonarqube/tasks/issue_code_blocks_convertor.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/issues_convertor.go
- backend/plugins/sonarqube/tasks/issues_extractor.go
- backend/plugins/sonarqube/tasks/projects_collector.go
- backend/plugins/sonarqube/tasks/projects_convertor.go
- backend/plugins/sonarqube/tasks/projects_extractor.go
This pr changed sonarqube domain prefix from st_ to cq_
part of #2305 
make dev
run sonarqube
db
> fix(sonarqube): change domain prefix

- backend/plugins/gitlab/api/remote.go
change Name to PathWithNamespace for search
> fix: fix search name

- backend/helpers/pluginhelper/api/connection_helper.go
There is a unique key constraint imposed on the column `name`. Creating a new connection with an existing name should throw an error instead of overwriting the old one.
Closes #4224
> fix: creating a connection with the same name will overwrite the previous one

- backend/plugins/refdiff/tasks/ref_issue_diff_calculator.go
fix #4225 
For simplicity, the bug is summarised as the following one-line code, the variable `pairList` is a slice of 2d array, the error reported in #4225 was caused by an empty `pairList`.
```SQL
WHERE (new_refs.id, old_refs.id) IN pairList
```
Closes #4225
> fix: fix the SQL error `Error 1241: Operand should contain 2 column(s)`

- backend/core/models/blueprint.go
- backend/core/models/collector_state.go
- backend/core/models/migrationscripts/20230213_add_time_after_to_collector_state.go
- backend/core/models/migrationscripts/20230213_add_updated_date_after_to_collector_state.go
- backend/core/models/migrationscripts/register.go
- backend/core/plugin/plugin_blueprint.go
- backend/helpers/pluginhelper/api/api_collector_with_state.go
- backend/plugins/jira/api/blueprint_v200.go
- backend/plugins/jira/impl/impl.go
- backend/plugins/jira/tasks/issue_changelog_collector.go
- backend/plugins/jira/tasks/issue_collector.go
- backend/plugins/jira/tasks/remotelink_collector.go
- backend/plugins/jira/tasks/task_data.go
- backend/plugins/jira/tasks/worklog_collector.go
- backend/server/services/blueprint.go
- backend/test/helper/api.go
This  PR is **Step 1** of https://github.com/apache/incubator-devlake/issues/4403#issuecomment-1430958391
1. Framework side: add `TimeAfter` alongside `CreatedDateAfter`
2. Plugin side: jira switch to `TimeAfter` and all `CreatedDateAfter` related code is deleted
3. Next step: update other plugins
Part of #4403
> Jira switch to timeAfter option

- backend/plugins/sonarqube/api/connection.go
1. add sonarqube connection swagger
2. fix connection nil pointer error when testing connection
part of #2305 
> fix(sonarqube): add connection swagger

- backend/plugins/tapd/tasks/bug_changelog_collector.go
Fix bug changelogs' order value
Closes #4394
> fix(tapd): fix bug changelog order

- config-ui/src/pages/blueprint/create/step-three/use-columns.tsx
- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
- config-ui/src/pages/pipeline/components/task/index.tsx
- config-ui/src/plugins/components/connection-form/fields/endpoint.tsx
- config-ui/src/plugins/components/connection-form/fields/token.tsx
- config-ui/src/plugins/components/data-scope-miller-columns/index.tsx
- config-ui/src/plugins/components/data-scope-search/index.tsx
- config-ui/src/plugins/components/data-scope/index.tsx
- config-ui/src/plugins/components/data-scope/use-data-scope.ts
- config-ui/src/plugins/config.ts
- config-ui/src/plugins/register/gitlab/data-scope.tsx
- config-ui/src/plugins/register/sonarqube/assets/icon.svg
- config-ui/src/plugins/register/sonarqube/config.ts
- config-ui/src/plugins/register/sonarqube/data-scope.tsx
- config-ui/src/plugins/register/sonarqube/index.ts
- config-ui/src/plugins/register/sonarqube/types.ts
1. fixed unable to enter endpoint.
2. fixed input type and initial value error on token.
3. fixed the type for data scope miller columns and search.
4. support plugin sonarqube.
Closes #2305
> feat(config-ui): support plugin sonarqube

- backend/helpers/e2ehelper/data_flow_tester.go
- backend/helpers/pluginhelper/api/apihelperabstract/connection_abstract.go
- backend/helpers/pluginhelper/api/connection_auths.go
- backend/plugins/bamboo/bamboo.go
- backend/plugins/bamboo/impl/impl.go
- backend/plugins/bamboo/models/migrationscripts/archived/project.go
- backend/plugins/bamboo/models/project.go
- backend/plugins/bamboo/tasks/project_collector.go
- backend/plugins/bamboo/tasks/project_extractor.go
- backend/plugins/bamboo/tasks/projects_convertor.go
- backend/plugins/bamboo/tasks/shared.go
- backend/plugins/bamboo/tasks/task_data.go
- backend/plugins/bitbucket/tasks/deployment_extractor.go
- backend/plugins/sonarqube/api/scope.go
- backend/plugins/sonarqube/tasks/projects_extractor.go
Add bamboo project collector/extractor/convertor
part of #3322 
raw:
tool
domain
> feat(bamboo): add project

- backend/helpers/e2ehelper/data_flow_tester.go
- backend/helpers/pluginhelper/api/apihelperabstract/connection_abstract.go
- backend/helpers/pluginhelper/api/connection_auths.go
- backend/plugins/bitbucket/tasks/deployment_extractor.go
- backend/plugins/sonarqube/api/scope.go
In pr #4444 , I changed some `Key` to `ProjectKey` by mistaken. This pr will fix this issue.
The changes will not affect any function of devlake
> fix: revert some ProjectKey to Key

- backend/plugins/bamboo/api/blueprint_V200_test.go
- backend/plugins/bamboo/api/blueprint_v200.go
- backend/plugins/bamboo/impl/impl.go
- backend/plugins/bamboo/models/project.go
- backend/plugins/bamboo/models/share.go
- backend/plugins/bamboo/models/transformation_rule.go
- backend/plugins/bamboo/tasks/project_extractor.go
- backend/plugins/bamboo/tasks/projects_convertor.go
- backend/plugins/bamboo/tasks/shared.go
- backend/plugins/bamboo/tasks/task_data.go
Blueprint v200 for bamboo
related #3322
> Bamboo blueprint

- config-ui/src/plugins/register/github/api.ts
- config-ui/src/plugins/register/github/components/miller-columns/use-miller-columns.ts
GitHub does not list private repositories.
Closes #4448
> fix(config-ui): github does not list private repositories

- backend/plugins/bamboo/impl/impl.go
- backend/plugins/bamboo/models/job.go
- backend/plugins/bamboo/models/migrationscripts/archived/job.go
- backend/plugins/bamboo/models/plan.go
- backend/plugins/bamboo/tasks/job_collector.go
- backend/plugins/bamboo/tasks/job_extractor.go
add job collector and extractor
part of #3322 
> feat(bamboo): add job collector and extractor

- config-ui/src/plugins/github/api.ts
- config-ui/src/plugins/github/components/miller-columns/use-miller-columns.ts
cherry-pick and fixed #4439 and #4448.
Closes #4439 and #4448.
> fix(config-ui): cherry-pick and fixed #4439 and #4448

- config-ui/src/layouts/base/base.tsx
- config-ui/src/layouts/base/use-menu.ts
Remove blueprint from the main menu
Closes #4458
> feat(config-ui): remove blueprint from the main menu

- config-ui/src/plugins/components/connection-form/fields/endpoint.tsx
- config-ui/src/plugins/components/connection-form/fields/index.tsx
- config-ui/src/plugins/components/connection-form/fields/name.tsx
- config-ui/src/plugins/components/connection-form/fields/password.tsx
- config-ui/src/plugins/components/connection-form/fields/proxy.tsx
- config-ui/src/plugins/components/connection-form/fields/rate-limit.tsx
- config-ui/src/plugins/components/connection-form/fields/token.tsx
- config-ui/src/plugins/components/connection-form/fields/username.tsx
- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/tapd/config.ts
- config-ui/src/plugins/register/zentao/config.ts
1. fixed bitbucket missed initial endpoint.
2. adjust the sort for tapd and zentao.
3. standardize connection props.
4. adjust the password input type
> fix(config-ui): some bugs for connection

- config-ui/src/plugins/components/connection-form/fields/password.tsx
- config-ui/src/plugins/components/connection-form/fields/username.tsx
- config-ui/src/plugins/register/tapd/config.tsx
Adjust the plugin config for tapd.
Closes #4473
> fix(config-ui): adjust the plugin config for tapd

- backend/plugins/github/tasks/cicd_job_collector.go
github jobs collector supports diffsync.
The github jobs belong to `run`, we have to collect them by `runs` one by one,
so it does not need to do anything as long as `runs collector` supports `timeFilter`.
For `diffSync`,  it is simple as collecting newly updated `runs` since the last `jobs`  collection
Part of #4403
I've done the following self-testing:
1. collected `runs` with `timeFilter` while some of them have `in-progress`  as their statuses, the `runs` were collected and extracted correctly.
2. collected `jobs`, and data were collected correctly.
3. after all `runs` were completed, I recollected/re-extracted `runs` and `jobs`. a couple of new records appeared in `raw_tables` as expected.
> feat: github jobs collector supports diffsync

- backend/python/pydevlake/pydevlake/__init__.py
- backend/python/pydevlake/pydevlake/api.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/message.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/server/services/remote/plugin/connection_api.go
- backend/server/services/remote/plugin/default_api.go
- backend/server/services/remote/plugin/plugin_extensions.go
- backend/server/services/remote/plugin/remote_scope_api.go
- backend/server/services/remote/plugin/scope_api.go
- backend/server/services/remote/plugin/transformation_rule_api.go
- backend/test/remote/fakeplugin/fakeplugin/main.py
> Blueprint v200 python plugins

- backend/plugins/bitbucket/bitbucket.go
- config-ui/src/plugins/register/bitbucket/transformation.tsx
update cicd tips for bitbucket
Closes #3319
> [config-ui] feat: update cicd tips for bitbucket

- config-ui/src/components/table/styled.ts
- config-ui/src/components/table/table.tsx
- config-ui/src/pages/blueprint/home/index.tsx
- config-ui/src/pages/connection/list/connection.tsx
- config-ui/src/pages/project/home/index.tsx
- config-ui/src/pages/transformation/home/index.tsx
- config-ui/src/plugins/register/webook/connection/index.tsx
Add no-data status for some pages.
Closes #4481
> feat(config-ui): add no-data status for some pages

- backend/core/models/domainlayer/code/commit.go
- backend/core/models/domainlayer/code/repo_commit.go
- backend/core/models/migrationscripts/20230222_add_commit_sha_index.go
- backend/core/models/migrationscripts/register.go
- grafana/dashboards/ComponentAndFileLevelMetrics.json
fix: largest files with lowest number of authors dashboard can not show
Closes #4406 
> fix: largest files with lowest number of authors dashboard can not show

- backend/plugins/jenkins/api/blueprint_v200.go
- backend/plugins/jenkins/impl/impl.go
- backend/plugins/jenkins/jenkins.go
- backend/plugins/jenkins/tasks/stage_collector.go
- backend/plugins/jenkins/tasks/task_data.go
1. renamed `createdDateAfter` to `timeAfter`
2. fixed stage collector query bug
Part of #4403
> refactor: jenkins adopts timeAfter

- backend/plugins/bamboo/impl/impl.go
- backend/plugins/bamboo/tasks/job_build_extractor.go
- backend/plugins/bamboo/tasks/plan_build_convertor.go
- backend/plugins/bamboo/tasks/plan_commit_convertor.go
- backend/plugins/bamboo/tasks/shared.go
- backend/plugins/bamboo/tasks/shared_test.go
This pr mainly add plan_build_convertor and plan_commit_convertor
part of #3322 
> feat(bamboo): add plan build convertor

- backend/plugins/tapd/impl/impl.go
- backend/plugins/tapd/tapd.go
- backend/plugins/tapd/tasks/bug_changelog_collector.go
- backend/plugins/tapd/tasks/bug_collector.go
- backend/plugins/tapd/tasks/bug_commit_collector.go
- backend/plugins/tapd/tasks/iteration_collector.go
- backend/plugins/tapd/tasks/story_bug_collector.go
- backend/plugins/tapd/tasks/story_changelog_collector.go
- backend/plugins/tapd/tasks/story_collector.go
- backend/plugins/tapd/tasks/story_commit_collector.go
- backend/plugins/tapd/tasks/task_changelog_collector.go
- backend/plugins/tapd/tasks/task_collector.go
- backend/plugins/tapd/tasks/task_commit_collector.go
- backend/plugins/tapd/tasks/task_data.go
- backend/plugins/tapd/tasks/worklog_collector.go
Adopts timeAfter
Part of https://github.com/apache/incubator-devlake/issues/4403
> refactor(tapd): adopts timeAfter

- .github/workflows/build.yml
fix: can not build and push devlake image
Closes #4514 
> fix: can not build and push devlake image

- .github/workflows/build.yml
- backend/Dockerfile
fix: can not copy some file due to the file path
and 
fix tini
Closes #4514 
> fix: can not copy some file due to the file path

- backend/test/helper/api.go
- backend/test/helper/client.go
- backend/test/helper/models.go
Remote-Scopes API added to Go IT client.
n/a
> Remote-scope APIs for Go Integration testing client

- config-ui/src/pages/blueprint/create/bp-context.tsx
no decode project name.
Closes #4506
> fix(config-ui): no decode project name

- config-ui/src/plugins/register/github/api.ts
Add params **sort** for github miller-columns.
Closes #4527
> feat(config-ui): add params sort for github miller-columns

- config-ui/package-lock.json
- config-ui/package.json
Upgrade miller-columns-select.
Expand the click area.
> feat(config-ui): upgrade miller-columns-select

- .env.example
- backend/core/config/config_viper.go
- backend/server/api/api.go
Fix the problem that HOST information needs to be included in PORT.
Closes #4496
> fix: fix port

- grafana/dashboards/Sonarqube.json
Add dashboard for sonarqube
Closes #4464 
> fix(sonarqube): add dashboard

- config-ui/src/error/components/bp-upgrade/api.ts
- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
- config-ui/src/pages/blueprint/components/advanced-editor/example/index.ts
- config-ui/src/plugins/components/connection-form/fields/endpoint.tsx
- config-ui/src/plugins/components/data-scope/index.tsx
- config-ui/src/plugins/components/transformation/index.tsx
- config-ui/src/plugins/components/transformation/misc.ts
- config-ui/src/plugins/config.ts
- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/github/config.tsx
- config-ui/src/plugins/register/github/connection-fields/token.tsx
- config-ui/src/plugins/register/gitlab/config.tsx
- config-ui/src/plugins/register/jira/config.tsx
- config-ui/src/plugins/register/jira/connection-fields/auth.tsx
- config-ui/src/plugins/register/jira/data-scope.tsx
- config-ui/src/plugins/register/jira/transformation.tsx
- config-ui/src/plugins/register/sonarqube/config.ts
- config-ui/src/plugins/register/tapd/config.tsx
- config-ui/src/plugins/register/zentao/config.ts
Adjust the text and link for connection.
> fix(config-ui): adjust the text and link for connection

- config-ui/src/pages/project/detail/panel/settings.tsx
- config-ui/src/pages/project/detail/use-project.ts
- config-ui/src/pages/project/home/use-project.ts
Limit the type of project name
> fix(config-ui): limit the type of project name

- config-ui/src/plugins/register/bitbucket/data-scope.tsx
- config-ui/src/plugins/register/gitlab/data-scope.tsx
Missed name in gitlab data scope search.
> fix(config-ui): missed name in gitlab data scope search

- config-ui/src/plugins/components/transformation/index.tsx
- config-ui/src/plugins/components/transformation/use-transformation.ts
- config-ui/src/plugins/register/jira/transformation.tsx
1. missed spaces between text.
2. display the error information returned by the api.
3. issue type cannot be selected in jira.
1. 
2. 
3.
> fix(config-ui): some bugs for transformation

- backend/plugins/gitlab/tasks/mr_enricher.go
- backend/plugins/gitlab/tasks/mr_enricher_test.go
add two unit tests for gitlab mr_enricher
Closes #4561 
> test(gitlab): add two unit tests

- config-ui/src/pages/blueprint/create/components/action/index.tsx
Abnormal loss of focus.
Closes #4258
> fix(config-ui): abnormal loss of focus

- backend/plugins/dora/e2e/snapshot_tables/project_pr_metrics.csv
- backend/plugins/dora/tasks/change_lead_time_calculator.go
combined PrPickupTime + PrReviewTime when cal PrCycleTime
Closes #4382 
Now new cal PrCycleTime = PrPickupTime + PrReviewTime + 1. Just a second diff and I think it's right.
> fix: combined PrPickupTime + PrReviewTime when cal PrCycleTime

- backend/plugins/customize/service/service.go
Set the two columns `created_at` and `updated_at` while importing data from CSV file
Closes #4581
> fix: set created_at and updated_at while importing data from CSV files

- grafana/dashboards/Sonarqube.json
Change creation_date to be created_date
Add Default value for rows.
> fix: sonaqube dashboard fix

- backend/plugins/customize/api/field.go
- backend/plugins/customize/service/service.go
- Remove `isCustomizedField` from the request parameters to create a new field
- Add line numbers to the error message generated when importing the CSV files
Closes #4588
> docs: improve swagger doc and error message

- backend/server/api/blueprints/blueprints.go
- backend/server/services/blueprint.go
> fix: rename is_manual to isManual; page_size to pageSize

- config-ui/src/pages/blueprint/home/index.tsx
Add column status for bp list.
> feat(config-ui): add column status for bp list

- config-ui/src/pages/blueprint/components/sync-policy/index.tsx
Adjust the text for time filter.
> refactor(config-ui): adjust the text for time filter

- config-ui/src/plugins/register/zentao/config.ts
Adjust the text for zentao connection.
> refactor(config-ui): adjust the text for zentao connection

- backend/plugins/tapd/tapd.go
- backend/plugins/tapd/tasks/bug_collector.go
- config-ui/src/pages/blueprint/components/advanced-editor/example/tapd.ts
add pageSize to tapd template
Relate to #4557 
> fix(tapd): add page size to frontend example

- grafana/dashboards/Jenkins.json
jenkins dashboard update fullname to jobname
related to #3838 
previous：
now:
> fix: jenkins dashboard update fullname to jobname

- NOTICE
fix: NOTICE year
related to #4200 
> fix: NOTICE year

- config-ui/src/layouts/base/use-menu.ts
- grafana/dashboards/BitBucket.json
- grafana/dashboards/ContributorExperience.json
- grafana/dashboards/DemoAverageRequirementLeadTimeByAssignee.json
- grafana/dashboards/DemoCommitCountByAuthor.json
- grafana/dashboards/DemoDetailedBugInfo.json
- grafana/dashboards/DemoHowFastDoWeRespondToCustomerRequirements.json
- grafana/dashboards/DemoIsThisMonthMoreProductiveThanLast.json
- grafana/dashboards/DemoWasOurQualityImprovedOrNot.json
- grafana/dashboards/EngineeringOverview.json
- grafana/dashboards/EngineeringThroughputAndCycleTime.json
- grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
- grafana/dashboards/GitHub.json
- grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
- grafana/dashboards/Homepage.json
- grafana/dashboards/Jenkins.json
- grafana/dashboards/Jira.json
- grafana/dashboards/Sonarqube.json
- grafana/dashboards/TAPD.json
- grafana/dashboards/WeeklyBugRetro.json
- grafana/dashboards/WeeklyCommunityRetro.json
- grafana/dashboards/Zentao.json
1. add BitBucket dashboard 
2. add SonarQube dashboard to the homepage
3. update the Grafana manual links in all dashboards
N/A
> feat: add BitBucket dashboard and update other dashboards

- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/bitbucket/transformation.tsx
- config-ui/src/plugins/register/github/config.tsx
- config-ui/src/plugins/register/github/transformation.tsx
The default value of refdiff in transformation error.
> fix(config-ui): the default value of refdiff in transformation error

- devops/releases/lake-v0.16.0/docker-compose.yml
- devops/releases/lake-v0.16.0/env.example
add devops releases lake-v0.16.0
NA
> refactor: add devops releases lake-v0.16.0

- README.md
updated or removed inaccessible links in README
Closes #4605
> docs: update links in readme

- backend/plugins/jira/tasks/task_data.go
- backend/plugins/jira/tasks/task_data_test.go
cherry-pick #4639 
Closes #4637
> cherry-pick#4639

- config-ui/src/plugins/register/jira/config.tsx
Jira transformation field error.
> fix(config-ui): jira transformation field error

- config-ui/package-lock.json
- config-ui/package.json
Child loaded detection is wrong.
> fix(config-ui): child loaded detection is wrong

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/scope_helper_test.go
- backend/plugins/github/api/init.go
- backend/plugins/github/api/scope.go
- backend/plugins/github/impl/impl.go
- backend/plugins/gitlab/api/init.go
- backend/plugins/gitlab/api/scope.go
This pr mainly work on refactor github scope api, and extract a scopeHelper which can be used in other plugins
Part of #4653
> refactor(framework): add scopeHelper

- backend/plugins/gitlab/tasks/account_collector.go
- backend/plugins/gitlab/tasks/commit_collector.go
- backend/plugins/gitlab/tasks/issue_collector.go
- backend/plugins/gitlab/tasks/job_collector.go
- backend/plugins/gitlab/tasks/mr_collector.go
- backend/plugins/gitlab/tasks/mr_commit_collector.go
- backend/plugins/gitlab/tasks/mr_detail_collector.go
- backend/plugins/gitlab/tasks/mr_note_collector.go
- backend/plugins/gitlab/tasks/pipeline_collector.go
- backend/plugins/gitlab/tasks/pipeline_detail_collector.go
- backend/plugins/gitlab/tasks/tag_collector.go
enhance the timeFilter/diffSync support for the gitlab plugin
part of #4535 
> feat: enhance the timeFilter/diffSync support for the gitlab plugin

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/scope_helper_test.go
- backend/plugins/github/api/init.go
- backend/plugins/github/api/scope.go
- backend/plugins/github/models/repo.go
- backend/plugins/gitlab/api/init.go
- backend/plugins/gitlab/api/scope.go
In pr #4632 , we used reflect to refactor, this pr add generic to simplify 
part of #4632 
PUT:
get Github repos
get Github single repo
patch Github repo
> refactor(framework): use generic to optimize

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/scope_helper_test.go
- backend/plugins/github/api/scope.go
- backend/plugins/github/models/repo.go
- backend/plugins/gitlab/api/remote.go
- backend/plugins/gitlab/api/scope.go
- backend/plugins/gitlab/models/project.go
Fix return value which should be one layer struct as below:
But it was :
part of #4653
> refactor(framework): modify scope helper

- config-ui/package-lock.json
- config-ui/package.json
> fix(config-ui): child loaded detection is wrong (#4646)

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/scope_helper_test.go
- backend/plugins/gitlab/api/blueprint_V200_test.go
- backend/plugins/gitlab/models/project.go
- backend/plugins/gitlab/tasks/project_convertor.go
- backend/plugins/gitlab/tasks/project_extractor.go
Fix type of CreatedDate in gitlab project 
part of #4653 
> fix(gitlab): change type of createdDate to adapt scope helper

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/plugins/jenkins/api/init.go
- backend/plugins/jenkins/api/scope.go
- backend/plugins/jenkins/impl/impl.go
- backend/plugins/jenkins/models/job.go
- backend/plugins/jira/api/init.go
- backend/plugins/jira/api/scope.go
- backend/plugins/jira/impl/impl.go
- backend/plugins/jira/models/board.go
- backend/plugins/sonarqube/api/init.go
- backend/plugins/sonarqube/api/remote.go
- backend/plugins/sonarqube/api/scope.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/sonarqube_project.go
This pr mainly refactored scope api for  jira jenkins and sonarqube
part of #4653 
> fix(plugins): refactor jira jenkins and sonarqube's scope

- backend/plugins/github_graphql/tasks/pr_collector.go
cherry-pick https://github.com/apache/incubator-devlake/pull/4668 to 0.16
> fix: decrease page size for github graphql pr collector (#4668)

- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/azuredevops/streams/commits.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/plugins/azuredevops/azuredevops/streams/pull_request_commits.py
- backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
- backend/python/pydevlake/pydevlake/api.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/model.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/stream.py
- backend/server/services/remote/plugin/connection_api.go
- backend/server/services/remote/plugin/plugin_extensions.go
Fixes validation issue for test-connection command.
> Azuredevops: Fix test-connection command

- backend/helpers/pluginhelper/api/api_client.go
- backend/plugins/bitbucket/api/init.go
- backend/plugins/bitbucket/api/remote.go
- backend/plugins/bitbucket/api/scope.go
- backend/plugins/bitbucket/e2e/repo_test.go
- backend/plugins/bitbucket/impl/impl.go
- backend/plugins/bitbucket/models/connection.go
- backend/plugins/bitbucket/models/repo.go
- backend/plugins/bitbucket/tasks/pr_extractor.go
- backend/plugins/bitbucket/tasks/repo_convertor.go
- backend/plugins/gitlab/api/remote.go
1. refactor remote scopes
2. fix scope issues
part of #4653 
> refactor(bitbucket): refactor remote scopes

- backend/plugins/bamboo/api/init.go
- backend/plugins/bamboo/api/remote.go
- backend/plugins/bamboo/impl/impl.go
- backend/plugins/bamboo/models/connection.go
- backend/plugins/bamboo/models/project.go
Refactor bamboo remote-scopes
part of #4653 
> Refactor(bamboo): refactor remote-scopes

- backend/plugins/github/tasks/pr_collector.go
fix: change pr collector detail input.
Closes #4631
before change:
after change:
> fix: change pr collector detail input

- config-ui/src/pages/blueprint/detail/panel/configuration.tsx
> fix(config-ui): missed timeAfter after change data scope (#4696)

- backend/core/plugin/plugin_connection_abstract.go
- backend/helpers/pluginhelper/api/remote_api_helper.go
- backend/helpers/pluginhelper/api/scope_helper.go
- backend/plugins/bamboo/api/blueprint_v200.go
- backend/plugins/bamboo/api/remote.go
- backend/plugins/bamboo/impl/impl.go
- backend/plugins/bamboo/models/connection.go
- backend/plugins/bamboo/models/project.go
- backend/plugins/bitbucket/api/remote.go
- backend/plugins/bitbucket/models/connection.go
- backend/plugins/gitlab/api/remote.go
- backend/plugins/gitlab/models/connection.go
- backend/plugins/gitlab/models/project.go
This pr refactored searchScopes for bamboo, gitlab, bitbucket and extract searchScopes for all plugins.
part of #4653 
> refactor(framework): refactor search scopes

- backend/plugins/jira/tasks/account_collector.go
- backend/plugins/jira/tasks/epic_collector.go
- backend/plugins/jira/tasks/issue_changelog_collector.go
- backend/plugins/jira/tasks/issue_collector.go
- backend/plugins/jira/tasks/issue_type_collector.go
- backend/plugins/jira/tasks/project_collector.go
- backend/plugins/jira/tasks/remotelink_collector.go
- backend/plugins/jira/tasks/sprint_collector.go
- backend/plugins/jira/tasks/status_collector.go
- backend/plugins/jira/tasks/worklog_collector.go
enhance timeFilter/diffSync support for jira
part of https://github.com/apache/incubator-devlake/issues/4535
> feat: enhance timeFilter/diffSync support for jira

- backend/plugins/jenkins/tasks/build_collector.go
feat: enhance timeFilter/diffSync support for jenkins build
part of https://github.com/apache/incubator-devlake/issues/4535
> feat: enhance timeFilter/diffSync support for jenkins build

- config-ui/nginx.conf
> Fix Nginx conf broken syntax

- backend/plugins/github/api/connection.go
When testing the connection using a classic GitHub token, we will now check its permissions. If the token doesn't have the required permissions, the test will fail.
Part of #4571
> feat: check github token permissions when test connection

- backend/plugins/tapd/tasks/bug_status_extractor.go
- backend/plugins/tapd/tasks/story_status_extractor.go
cherrypick #4693 to release-v0.16
> fix(tapd): return nil if row data is an empty array

- backend/plugins/sonarqube/api/blueprint_v200.go
- backend/plugins/sonarqube/api/init.go
- backend/plugins/sonarqube/api/remote.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/models/sonarqube_project.go
- backend/plugins/sonarqube/tasks/shared.go
Refactor sonarqube search scope to adapt new pattern in #4692 
part of #4653 
> refactor(sonarqube): refactor search scopes 

- Makefile
fixed make file about config-ui
> fix(config-ui): make file about config-ui

- README.md
Update the roadmap description
> docs: update the roadmap description

- backend/plugins/github/api/connection.go
add coarse-grained permission checking
related to #4686 
> feat: add coarse-grained permission checking

- backend/plugins/sonarqube/models/migrationscripts/20230321_expend_project_key.go
- backend/plugins/sonarqube/models/migrationscripts/register.go
- backend/plugins/sonarqube/models/sonarqube_issue.go
- backend/plugins/sonarqube/models/sonarqube_project.go
expand project key to 255
This pr will cherry-pick to 0.16
Closes #4716
> fix: expand project key to 255

- backend/plugins/jira/models/issue_commit.go
- backend/plugins/jira/models/migrationscripts/20230322_expand_remotelink_url.go
- backend/plugins/jira/models/migrationscripts/register.go
- backend/plugins/jira/models/remotelink.go
cherry-pick #4746 to release-v0.16
Closes #4726
> cherry-pick #4746 to release-v0.16

- .github/workflows/test-e2e.yml
- backend/helpers/pluginhelper/api/scope_helper.go
- backend/helpers/pluginhelper/api/transformation_rule_helper.go
add transformation rule name to response
part of #4653 
> fix(pluginhelper): add transformation rule name to response

- backend/Dockerfile
- backend/test/helper/api.go
- backend/test/remote/remote_test.go
Python build config was broken. This PR fixes it.
n/a
> fix: Fix broken Python config in Dockerfile

- backend/helpers/migrationhelper/migrationhelper.go
Fix the ChangeColumnsType error with nowhere.
Closes #4749
> fix: fix nil function error

- backend/plugins/gitlab/api/connection.go
Add token permission check for connection test.
> Gitlab token check

- backend/server/api/blueprints/blueprints.go
- backend/server/services/blueprint.go
- backend/server/services/pipeline_helper.go
Add the log to the blueprint cron.
Add the log if the pipelines padding.
related #4761
> fix: add log for cron

- backend/server/api/blueprints/blueprints.go
- backend/server/services/blueprint.go
- backend/server/services/pipeline_helper.go
Cherry-pick the pr #4766 to v0.16
related #4761
> fix: cherry pick #4766

- backend/Dockerfile
> [fix-4763]: Fixed broken /app reference in Dockerfile

- config-ui/src/global.d.ts
- config-ui/src/pages/blueprint/connection-add/components/step-1.tsx
- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/pages/blueprint/create/components/step-1.tsx
- config-ui/src/plugins/components/transformation/index.tsx
- config-ui/src/store/connections/types.ts
- config-ui/src/store/connections/use-context-value.ts
some plugins do not have transformation
> fix(config-ui): some plugins do not have transformation

- backend/server/services/blueprint.go
Cherry-pick of #4787 
related #4761
> Cron fix v0.16

- config-ui/src/error/components/bp-upgrade/api.ts
- config-ui/src/error/components/bp-upgrade/use-bp-upgrade.ts
- config-ui/src/plugins/components/transformation-form/api.ts
- config-ui/src/plugins/components/transformation-select/api.ts
Add connectionId for transformation api.
#4775
> feat(config-ui): add connectionId for transformation api

- config-ui/src/pages/blueprint/connection-add/components/step-3.tsx
- config-ui/src/pages/blueprint/connection-add/context.tsx
- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/plugins/components/data-scope/index.tsx
1. fixed failed to edit bp connection.
2. fixed failed to edit bp connection data-scope.
3. fixed failed to redirect to bp connection.
> fix(config-ui): some bugs for new transformation

- backend/plugins/gitlab/models/project.go
Delete extra fields for GroupResponse to resolve #4790 
Closes 4790
> fix(gitlab): delete fields for GroupResponse

- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/plugins/components/data-scope/index.tsx
Fixed missed initial value in data scope.
> fix(config-ui): missed initial value in data scope

- config-ui/src/plugins/config.ts
- config-ui/src/plugins/register/org/config.ts
- config-ui/src/plugins/register/org/index.ts
> feat(config-ui): support plugin org

- backend/Dockerfile
Cherrypicked Dockerfile fixes from #4734 and #4781 into release v0.16.0-beta11
> [v0.16.0-beta11] Dockerfile fixes from issues #4734 and #4781

- config-ui/src/plugins/components/data-scope/index.tsx
> fix(config-ui): the entities cannot find

- backend/plugins/pagerduty/api/blueprint_v200.go
- backend/plugins/pagerduty/api/transformation_rules.go
- backend/plugins/pagerduty/impl/impl.go
* Transformation rules endpoints fixed
* Ticket scopes erroring out during Blueprint creation -> fixed
> fix(Pagerduty): Ticket scopes fix in Blueprint creation

- config-ui/src/plugins/components/data-scope-form/index.tsx
- config-ui/src/plugins/config.ts
- config-ui/src/plugins/register/base/config.ts
- config-ui/src/plugins/register/pagerduty/assets/icon.svg
- config-ui/src/plugins/register/pagerduty/config.tsx
- config-ui/src/plugins/register/pagerduty/data-scope.tsx
- config-ui/src/plugins/register/pagerduty/index.ts
- config-ui/src/plugins/register/pagerduty/styled.ts
- config-ui/src/plugins/register/pagerduty/types.ts
- config-ui/src/plugins/register/tapd/config.tsx
- config-ui/src/plugins/register/zentao/config.ts
1. adjust the sort for plugins.
2. support plugin pagerduty.
Closes #4575
> feat(config-ui): support plugin pagerduty

- backend/plugins/tapd/tasks/bug_commit_converter.go
- backend/plugins/tapd/tasks/story_commit_converter.go
- backend/plugins/tapd/tasks/task_commit_converter.go
- config-ui/src/plugins/register/zentao/config.ts
cherry-pick  https://github.com/apache/incubator-devlake/pull/4824
> feat: convert issue_repo_commit for tapd (#4824)

- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
All Github actions should run if Python code changes 
n/a
> test: Have Python changes trigger GitHub actions

- config-ui/src/layouts/base/base.tsx
- config-ui/src/layouts/base/styled.ts
- config-ui/src/pages/connection/home/styled.ts
Layout adjustment.
Closes #4843
> refactor(config-ui): layout adjustment

- grafana/dashboards/DORA DEBUG.json
add dora debug dashboard
Close #4850
Dora dashboard exclusively utilizes these 3 SQL queries. Consequently, once the checkers designed for these 3 SQL queries have passed, any new plugins added will be compatible with Dora dashboard.
> feat: add dora debug dashboard

- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/plugins/azuredevops/tests/streams_test.py
- backend/python/pydevlake/pydevlake/api.py
- backend/python/pydevlake/pydevlake/context.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/message.py
- backend/python/pydevlake/pydevlake/model.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/subtasks.py
- backend/python/pydevlake/pydevlake/testing/testing.py
- backend/python/pydevlake/tests/stream_test.py
- backend/python/test/fakeplugin/fakeplugin/main.py
- backend/server/services/remote/models/dynamic_domain_scopes.go
- backend/server/services/remote/models/models.go
- backend/server/services/remote/plugin/plugin_extensions.go
- backend/test/e2e/remote/helper.go
- backend/test/e2e/remote/python_plugin_test.go
Various fixes and improvements to pydevlake, remote framework and azuredevops plugin.
> Fix Azuredevops UI pipeline run 

- config-ui/src/plugins/register/azure/config.tsx
- config-ui/src/plugins/register/azure/transformation.tsx
- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/bitbucket/transformation.tsx
- config-ui/src/plugins/register/github/config.tsx
- config-ui/src/plugins/register/github/transformation.tsx
Update the parameter `tagsOrder` to `tagsLimit`.
Closes #4846
> fix(config-ui): update the parameter tagsOrder to tagsLimit

- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/bitbucket/transformation.tsx
- config-ui/src/plugins/register/github/config.tsx
- config-ui/src/plugins/register/github/transformation.tsx
> cherrypick(config-ui): update the parameter tagsOrder to tagsLimit

- backend/plugins/jenkins/tasks/build_extractor.go
- config-ui/package.json
- config-ui/src/App.tsx
- config-ui/src/aws-exports.ts
- config-ui/src/layouts/base/base.tsx
- config-ui/src/utils/request.ts
- config-ui/yarn.lock
- docker-compose.yml
This pr mainly integrate cognito with config-ui
> feat(configui): integrate cognito

- docker-compose.yml
Revert docker-compose to old version
> feat(configui): revert docker-compose

- config-ui/README.md
> doc(config-ui): update README.md

- config-ui/index.html
- config-ui/src/App.tsx
- config-ui/src/utils/request.ts
- config-ui/vite.config.ts
- docker-compose.yml
> Feat configui support cognito

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/plugins/pagerduty/api/scope.go
- backend/plugins/pagerduty/impl/impl.go
> [fix-4872]: Fix scopes API path in PagerDuty

- config-ui/src/pages/blueprint/connection-add/components/step-1.tsx
- config-ui/src/pages/blueprint/create/components/step-1.tsx
- config-ui/src/plugins/types.ts
- config-ui/src/store/connections/types.ts
- config-ui/src/store/connections/use-context-value.ts
Transformation type missed in plugin config
> fix(config-ui): transformation type missed in plugin config

- config-ui/src/plugins/components/transformation-form/index.tsx
tapd transformation does not bind correctly.
> fix(config-ui): tapd transformation does not bind correctly

- backend/helpers/pluginhelper/api/scope_helper.go
return transformationRuleName in put scopes for config-ui
Related to #4653
> feat: return transformationRuleName in put scopes for config-ui

- backend/plugins/tapd/impl/impl.go
- backend/plugins/tapd/models/bug_custom_field_value.go
- backend/plugins/tapd/models/migrationscripts/20230412_add_custom_field_value.go
- backend/plugins/tapd/models/migrationscripts/archived/bug_custom_field_value.go
- backend/plugins/tapd/models/migrationscripts/archived/story_custom_field_value.go
- backend/plugins/tapd/models/migrationscripts/archived/task_custom_field_value.go
- backend/plugins/tapd/models/story_custom_field_value.go
- backend/plugins/tapd/models/task_custom_field_value.go
- backend/plugins/tapd/tasks/bug_custom_field_enricher.go
- backend/plugins/tapd/tasks/story_custom_field_enricher.go
- backend/plugins/tapd/tasks/task_custom_field_enricher.go
This pr mainly work on:
1. create _tool_tapd_bug/task/story_custom_field_value in db
2. select bug/story/task custom field value from table._tool_tapd_bug/task/story and insert into table._tool_tapd_bug/task/story_custom_field_value
Closes #4914
> Fix tapd custom field enricher

- backend/plugins/tapd/models/migrationscripts/register.go
remove unsupported db migration scripts
> fix(tapd): fix errors caused by cherrypick

- backend/core/models/migrationscripts/20230411_add_cicd_deployment_commits.go
- backend/plugins/bitbucket/e2e/repo_test.go
- backend/plugins/bitbucket/e2e/snapshot_tables/cicd_scopes.csv
- backend/plugins/bitbucket/tasks/pipeline_convertor.go
- backend/plugins/bitbucket/tasks/repo_convertor.go
- backend/plugins/dora/dora.go
- backend/plugins/dora/impl/impl.go
- backend/plugins/dora/tasks/deployment_commits_generator.go
1. fix: bitbucket repo_convertor missed cicd_scope conversion
2. fix: bitbucket pipeline convertor scoping / missed cicd_scope_id
3. feat: dora generate deployments from cicd pipelines/tasks
Part of #4869
data source: https://bitbucket.org/zhenmianws/helloworldrepo/pipelines/results/page/1
input: _tool_bitbucket_pipelines
```
|connection_id|bitbucket_id                          |status   |result    |ref_name  |web_url                                                                                                                                                                                                           |duration_in_seconds|bitbucket_created_on   |bitbucket_complete_on  |created_at             |updated_at             |_raw_data_params …
```
> Refactor Chage Lead Time - Step 4: generate deployments based on cicd pipelines/tasks

- backend/helpers/pluginhelper/api/api_collector.go
- backend/helpers/pluginhelper/api/graphql_collector.go
- backend/plugins/github_graphql/tasks/account_collector.go
- backend/plugins/github_graphql/tasks/issue_collector.go
- backend/plugins/github_graphql/tasks/job_collector.go
- backend/plugins/github_graphql/tasks/pr_collector.go
move extract existing graphql data to general position
Closes #4491
> fix: move extract existing graphql data to general position

- backend/plugins/jira/impl/impl.go
- backend/plugins/jira/tasks/apiv2models/issue.go
- backend/plugins/jira/tasks/issue_collector.go
- backend/plugins/jira/tasks/issue_extractor.go
- backend/plugins/jira/tasks/task_data.go
- Adding `PageSize` to the JiraOptions` struct
- Taking the `PageSize` into account when sending HTTP requests.
Closes #4923
> feat: provide configuable page size for plugin jira

- backend/server/api/api.go
- backend/server/api/login/login.go
- backend/server/api/router.go
- backend/server/services/auth/cognito.go
- config-ui/src/App.tsx
- config-ui/src/layouts/base/base.tsx
- config-ui/src/pages/login/login.tsx
- config-ui/src/utils/history.ts
- config-ui/src/utils/request.ts
Realize the main process of frontend to support authorization
part of #4929
> Feat fe cognito

- config-ui/src/App.tsx
- config-ui/src/layouts/base/base.tsx
- config-ui/src/pages/login/api.ts
- config-ui/src/pages/login/login.tsx
- config-ui/src/pages/login/styld.ts
- config-ui/src/utils/request.ts
Adjust the config-ui about cognito.
> feat(config-ui): adjust the config-ui about cognito

- backend/plugins/customize/api/blueprint.go
Fix #4935 ([Bug][Customize] The function MakePipeLinePlan of the plugin Customize incorrectly refers to the code of the plugin Jira )
Closes #4935
> fix: Fixed the code in the customize plugin that referenced the Jira plugin.

- backend/plugins/customize/api/blueprint.go
Cherry pick #4936 to release-v0.16
Closes #4935 
> fix: customize refers to the code of jira (#4936)

- config-ui/src/layouts/base/base.tsx
hidden signout when token does not exist.
> feat(config-ui): hidden signout when token does not exist

- backend/Dockerfile
- backend/python/plugins/azuredevops/pyproject.toml
- backend/python/pydevlake/pyproject.toml
- backend/python/requirements.txt
> [fix-4944]: Downgrade Python to 3.9 to support dbt plugin

- backend/server/api/api.go
python will register when loading, we have to exclude this from auth
part of #4929 
> fix(api): exclude python register from auth

- config-ui/src/pages/pipeline/components/tasks/styled.ts
- config-ui/src/plugins/register/github/transformation.tsx
1. adjust the wording for github transformation.
2. adjust the style for pipeline task.
> fix(config-ui): adjust the wording for github transformation

- config-ui/src/pages/blueprint/components/sync-policy/index.tsx
- config-ui/src/pages/blueprint/create/components/step-4.tsx
adjust the style for **create blueprint step 4**.
> fix(config-ui): adjust the style for create blueprint step 4

- backend/python/README.md
Update pydevlake README.md to reflect current state of the framework.
Closes #4951
> doc: Update README.md

- grafana/dashboards/WeeklyBugRetro.json
Show all outstanding bugs
Closes #4964
> fix: outstanding bugs in weekly bug retro

- backend/plugins/dbt/tasks/convertor.go
fix: dbt deps command 
Closes #4944 
> fix: dbt deps command fail

- config-ui/src/plugins/register/jira/config.tsx
- config-ui/src/plugins/register/jira/connection-fields/auth.tsx
- config-ui/src/plugins/register/jira/connection-fields/styled.ts
adjust the jira connection auth.
> fix(config-ui): adjust the jira connection auth

- config-ui/src/plugins/components/data-scope-form/index.tsx
data scope cannot select error in zentao.
> fix(config-ui): data scope cannot select error in zentao

- grafana/dashboards/Gitlab.json
fix: gitlab case inconsistency in dashboard sql
Closes #4987 
> fix: gitlab case inconsistency in dashboard sql

- backend/plugins/tapd/models/migrationscripts/20230330_delete_issue.go
delete tapd unnecessary migrations
Closes #5006 
> fix: delete tapd unnecessary migrations

- backend/core/models/domainlayer/devops/cicd_deployment_commit.go
- backend/core/models/migrationscripts/20230411_add_cicd_deployment_commits.go
- backend/core/models/migrationscripts/archived/cicd_deployment.go
- backend/plugins/bitbucket/tasks/deployment_convertor.go
- backend/plugins/dora/tasks/deployment_commits_generator.go
- backend/plugins/webhook/api/deployments.go
- add a new field FinishedDate to the model CicdDeploymentCommit
- provide a migration script
- assign value to the new field
Closes #5004
> feat: add finished_date to cicd_deployment_commits table

- backend/core/runner/db.go
- backend/core/runner/db_test.go
- backend/plugins/jira/tasks/issue_collector.go
- backend/plugins/jira/tasks/issue_collector_test.go
- If the user's time zone is available,  use it to generate JQL
- Adds loc=Local to the MySQL connection string if it's not already there
Closes #4902
> feat: generate JQL with user's time zone

- config-ui/nginx.conf
- config-ui/nginx.sh
support external grafana by EnvVar
Part of #5009
> feat: support external grafana by EnvVar

- config-ui/src/plugins/components/transformation-select/index.tsx
- config-ui/src/plugins/components/transformation/index.tsx
adjust the wording and icon for associate transformation
> fix(config-ui): adjust the wording and icon for associate transformation

- config-ui/src/utils/request.ts
return to login page only when invalid token to missing auth header
part of #4929 
> fix(configui): 

- backend/Dockerfile
fix python build error in dockerfile.
releated to #4944 
> fix: python build error in dockerfile

- config-ui/src/pages/project/home/index.tsx
> fix(config-ui): dora metrics doc link error

- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/bitbucket/transformation.tsx
fixed cicd configuration error about bitbucket transformation.
> fix(config-ui): cicd configruation error about bitbucket transformation

- backend/helpers/pluginhelper/api/scope_helper.go
- backend/plugins/sonarqube/api/scope.go
- backend/plugins/sonarqube/models/sonarqube_project.go
Previously, the request for scopes failed mainly because SonarQube did not have a transformationId, which caused an error when adding a transformation. This PR primarily fixes this issue and also adds a mapstructure tag to sonarqube_project.
Closes #5046 
now we can start sonarqube successfully:
> fix(sonarqube): fix scopes

- backend/plugins/pagerduty/tasks/incidents_collector.go
> [fix-5031]: Pagerduty created after time fix

- backend/plugins/tapd/e2e/bugs_commit_test.go
- backend/plugins/tapd/e2e/snapshot_tables/issue_repo_commits_bug.csv
- backend/plugins/tapd/e2e/snapshot_tables/issue_repo_commits_story.csv
- backend/plugins/tapd/e2e/snapshot_tables/issue_repo_commits_task.csv
- backend/plugins/tapd/e2e/stories_commit_test.go
- backend/plugins/tapd/e2e/tasks_commit_test.go
This pr mainly did merge v0.16.0-hexun-patch to main and fix some e2e bugs
Closes https://github.com/apache/incubator-devlake/issues/4914
> Fix tapd cp hexun patch

- config-ui/src/plugins/components/transformation-form/fields/additional-settings.tsx
- config-ui/src/plugins/components/transformation-form/fields/index.ts
- config-ui/src/plugins/components/transformation-form/fields/styled.ts
- config-ui/src/plugins/components/transformation-form/index.tsx
- config-ui/src/plugins/register/azure/transformation.tsx
- config-ui/src/plugins/register/bitbucket/styled.ts
- config-ui/src/plugins/register/bitbucket/transformation.tsx
- config-ui/src/plugins/register/github/styled.ts
- config-ui/src/plugins/register/github/transformation.tsx
- config-ui/src/plugins/register/gitlab/transformation.tsx
- config-ui/src/plugins/register/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jenkins/data-scope.tsx
- config-ui/src/plugins/register/jenkins/transformation.tsx
1. adjust the transformation
2. turn on the `showSelectAll` in jenkins miller columns.
> refactor(config-ui): adjust the transformation

- backend/server/services/remote/plugin/connection_api.go
Changed the status of failed connection test for remote plugin from 500 to 400.
@hezyin 
Closes #5059
> Change failed connection test status from 500 to 400

- config-ui/src/plugins/components/transformation-form/misc.ts
update doc link for transformation
> fix(config-ui): update doc link for transformation

- backend/helpers/pluginhelper/api/mapstructure.go
- backend/server/services/remote/plugin/transformation_rule_api.go
- backend/test/e2e/remote/python_plugin_test.go
- backend/test/helper/api.go
Cherry pick #5094 to fix #5082 on release-v0.17
> fix: cherry pick #5094

- config-ui/src/plugins/register/webook/create-dialog/use-create.ts
update the webhook deployment sample.
Closes #5097
> fix(config-ui): update the webhook deployment sample

- config-ui/src/plugins/components/data-scope/index.tsx
missed initial entities in data scope form.
Closes #5096
> fix(config-ui): missed initial entities in data scope form

- config-ui/src/App.tsx
db migrate redirect url error.
> fix(config-ui): db migrate redirect url error

- config-ui/src/pages/project/detail/index.tsx
- config-ui/src/plugins/register/webook/create-dialog/index.tsx
- config-ui/src/plugins/register/webook/create-dialog/use-create.ts
keep tab state in project details.
Closes #5095
> fix(config-ui): keep tab state in project details

- config-ui/src/components/alert/index.tsx
- config-ui/src/pages/project/detail/panel/incoming-webhooks.tsx
1. add new component alert.
2. add tips for project incoming webhook.
Closes #5117
> feat(config-ui): add tips for project incoming webhook

- config-ui/src/plugins/components/transformation/index.tsx
> fix(config-ui): no transformation cannot be set

- backend/plugins/gitlab/tasks/account_collector.go
Cherrypick #5134 to v0.17
Closes #5126
> fix: no pagination is used in the collectionAccounts of gitlab

- backend/core/plugin/plugin_utils.go
- backend/core/plugin/plugin_utils_test.go
- backend/core/utils/strings.go
- backend/core/utils/strings_test.go
- backend/plugins/ae/models/connection.go
- backend/server/services/notification.go
- backend/test/helper/client.go
fix #5129 ([Refactor][Plugin Utils] Consider using a secure package for password and secret key handling instead of math/rand)
Closes #5129
> refactor: using `crypto/rand` for password and secret key handling instead of `math/rand`

- config-ui/src/App.tsx
- config-ui/src/index.css
- config-ui/src/layouts/base/use-menu.ts
- config-ui/src/pages/blueprint/connection-add/components/step-1.tsx
- config-ui/src/pages/blueprint/create/index.tsx
- config-ui/src/pages/connection/home/count.tsx
- config-ui/src/pages/connection/home/index.tsx
- config-ui/src/pages/connection/home/styled.ts
- config-ui/src/plugins/register/webook/config.ts
- config-ui/src/plugins/types.ts
- config-ui/src/store/connections/status.tsx
- config-ui/src/store/connections/use-context-value.ts
adjust the connection home page.
#4760
> feat(config-ui): adjust the connection home page

- backend/plugins/jira/models/migrationscripts/20230510_expand_remotelink_selfurl.go
- backend/plugins/jira/models/migrationscripts/register.go
- backend/plugins/jira/models/remotelink.go
Cherry-pick https://github.com/apache/incubator-devlake/pull/5147 back to release-v0.16
> fix: the overflow error of _tool_jira_remotelinks.self (#5147)

- config-ui/src/layouts/base/base.tsx
- config-ui/src/layouts/base/styled.ts
- config-ui/src/pages/connection/detail/api.ts
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/plugins/components/data-scope-form-2/api.ts
- config-ui/src/plugins/components/data-scope-form-2/index.tsx
- config-ui/src/plugins/components/data-scope-form-2/styled.ts
- config-ui/src/plugins/components/data-scope-miller-columns/index.tsx
- config-ui/src/plugins/components/data-scope-search/index.tsx
- config-ui/src/plugins/components/index.ts
- config-ui/src/plugins/register/azure/data-scope.tsx
- config-ui/src/plugins/register/bitbucket/data-scope.tsx
- config-ui/src/plugins/register/github/components/miller-columns/index.tsx
- config-ui/src/plugins/register/github/components/repo-selector/index.tsx
- config-ui/src/plugins/register/github/data-scope.tsx
- config-ui/src/plugins/register/gitlab/data-scope.tsx
- config-ui/src/plugins/register/jenkins/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jenkins/data-scope.tsx
- config-ui/src/plugins/register/jira/components/miller-columns/index.tsx
- config-ui/src/plugins/register/jira/data-scope.tsx
- config-ui/src/plugins/register/pagerduty/data-scope.tsx
- config-ui/src/plugins/register/sonarqube/data-scope.tsx
- config-ui/src/plugins/register/tapd/data-scope.tsx
- config-ui/src/plugins/register/zentao/data-scope.tsx
- config-ui/src/store/tips/context.tsx
- config-ui/src/store/tips/index.ts
1. add global store tips.
2. improve the connection detail page.
#4760
> feat(config-ui): improve the connection detail page

- backend/Makefile
- backend/python/README.md
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
- backend/python/plugins/azuredevops/tests/__init__.py
- backend/python/pydevlake/pydevlake/context.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/model.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/stream.py
- backend/python/pydevlake/pydevlake/subtasks.py
- backend/python/pydevlake/pydevlake/testing/testing.py
- backend/python/pydevlake/tests/stream_test.py
- backend/server/services/remote/plugin/plugin_impl.go
Implements migration of tool tables.
Fix a non-unique primary key in azuredevops table
Closes #5081
> 5081 fix missing records azuredevops

- backend/plugins/feishu/apimodels/im_result.go
- backend/plugins/feishu/impl/impl.go
- backend/plugins/feishu/models/chat_item.go
- backend/plugins/feishu/models/message.go
- backend/plugins/feishu/models/migrationscripts/20230421_add_init_tables.go
- backend/plugins/feishu/models/migrationscripts/archived/chat_item.go
- backend/plugins/feishu/models/migrationscripts/archived/message.go
- backend/plugins/feishu/tasks/chat_collector.go
- backend/plugins/feishu/tasks/chat_extractor.go
- backend/plugins/feishu/tasks/message_collector.go
- backend/plugins/feishu/tasks/message_extractor.go
- backend/plugins/feishu/tasks/task_data.go
collect feishu chat(group) & message.
close https://github.com/apache/incubator-devlake/issues/5162
> feat: collect feishu chat(group) & message

- backend/helpers/pluginhelper/api/api_collector.go
- backend/plugins/slack/README.md
- backend/plugins/slack/api/connection.go
- backend/plugins/slack/api/init.go
- backend/plugins/slack/api/swagger.go
- backend/plugins/slack/apimodels/access_token.go
- backend/plugins/slack/apimodels/im_result.go
- backend/plugins/slack/impl/impl.go
- backend/plugins/slack/models/channel.go
- backend/plugins/slack/models/channel_message.go
- backend/plugins/slack/models/connection.go
- backend/plugins/slack/models/migrationscripts/20230421_add_init_tables.go
- backend/plugins/slack/models/migrationscripts/archived/channel.go
- backend/plugins/slack/models/migrationscripts/archived/channel_message.go
- backend/plugins/slack/models/migrationscripts/archived/connection.go
- backend/plugins/slack/models/migrationscripts/register.go
- backend/plugins/slack/slack.go
- backend/plugins/slack/tasks/api_client.go
- backend/plugins/slack/tasks/channel_collector.go
- backend/plugins/slack/tasks/channel_extractor.go
- backend/plugins/slack/tasks/channel_message_collector.go
- backend/plugins/slack/tasks/channel_message_extractor.go
- backend/plugins/slack/tasks/task_data.go
- backend/plugins/slack/tasks/thread_collector.go
- backend/plugins/slack/tasks/thread_extractor.go
collect slack channel/message/thread
close https://github.com/apache/incubator-devlake/issues/5161
> feat: collect slack channel/message/thread

- backend/plugins/tapd/impl/impl.go
- backend/plugins/tapd/tasks/workspace_converter.go
Cherry pick #5160 back to release-v0.17
> fix: missing board for tapd (#5160)

- backend/server/services/auth/auth.go
- backend/server/services/auth/cognito.go
Some leftover small fixes from #5127
> fix: typo and unused struct from #5127

- config-ui/src/pages/login/login.tsx
> feat: new password confirmation

- backend/core/models/migrationscripts/20230511_add_calendar_months.go
- backend/core/models/migrationscripts/register.go
migration: provide a calendar_months table
part of #4747 
> feat: provide a calendar_months table

- config-ui/package.json
- config-ui/yarn.lock
upgrade miller-columns-select.
Closes #5058
> fix(config-ui): upgrade miller-columns-select

- backend/server/api/api.go
- backend/server/api/login/login.go
- backend/server/services/auth/auth.go
- backend/server/services/auth/cognito.go
- config-ui/src/pages/login/login.tsx
- config-ui/src/utils/request.ts
> Refresh token

- config-ui/src/pages/blueprint/detail/use-detail.ts
- config-ui/src/pages/project/home/use-project.ts
- config-ui/src/utils/operator.ts
adjust the interface to respond to error prompts.
Closes #5198
> refactor(config-ui): adjust the interface to respond to error prompts

- grafana/dashboards/DORA.json
- grafana/dashboards/DORADebug.json
This does the same as #5220 does. Please see screenshots there.
The DORA and DORA validation dashboards on the main and v0.17 have diverged, that's why I put up this PR for v0.17 instead of cherrypicking.
Closes #5216
> feat: improve the UX of DORA dashboards in v0.17

- backend/plugins/pagerduty/api/remote.go
This PR fixes issue #5212 by correcting the paging behaviour of PagerDuty services.
It fixes #5212 .
I'm unable to provide screenshots to demonstrate this works correctly now.
Nope, just a humble fix.
> fix: Correct paging behaviour during PagerDuty service enumeration

- config-ui/src/pages/connection/home/index.tsx
- config-ui/src/plugins/components/connection-form/index.tsx
- config-ui/src/plugins/components/connection-list/index.tsx
- config-ui/src/plugins/components/index.ts
cannot manage webhook.
Closes #5204
> fix(config-ui): cannot manage webhook

- config-ui/src/plugins/register/jenkins/transformation.tsx
> fix(config-ui): the wording about jenkins transformation (#5236)

- backend/helpers/pluginhelper/api/api_async_client.go
- backend/helpers/pluginhelper/api/api_collector.go
- backend/plugins/github/tasks/api_client.go
- backend/plugins/github/tasks/event_collector.go
collecting 300 page success.
Closes #5222
> fix: finish collect event when http code=422

- backend/plugins/github/api/connection.go
- backend/plugins/github/api/connection_test.go
BE implementation of #4712 
Part of #4712
> feat: add warning to github test connection

- config-ui/src/plugins/register/github/connection-fields/styled.ts
- config-ui/src/plugins/register/github/connection-fields/token.tsx
Add warning message for GitHub test connection.
Closes #4712
> feat(config-ui): add warning message for github test connection

- backend/helpers/pluginhelper/api/remote_api_helper.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/sonarqube/api/proxy.go
- backend/plugins/sonarqube/api/remote.go
- backend/plugins/sonarqube/api/scope.go
Fix a bug in sonarqube api.
Fix sonarqube api swagger document.
Closes #5254
> fix(sonarqube): fix search-remote-scope api error, fix api document

- backend/helpers/pluginhelper/api/remote_api_helper.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/sonarqube/api/proxy.go
- backend/plugins/sonarqube/api/remote.go
- backend/plugins/sonarqube/api/scope.go
- backend/plugins/sonarqube/impl/impl.go
Cherry pick  https://github.com/apache/incubator-devlake/pull/5259  https://github.com/apache/incubator-devlake/pull/5167 to branch release-0.17
> cp(sonarqube): added proxy api, fixed search-remote-scope api

- .github/actions/auto-cherry-pick/action.yml
- .github/actions/auto-cherry-pick/cherry-pick.sh
Improve the auto cherry pick action.
Related to #5238
> feat: improve the auto cherry pick action

- backend/plugins/sonarqube/api/proxy.go
> fix: the swagger error for sonarqube-proxy-endpoint

- .github/workflows/auto-cherry-pick.yml
the action permission not enough.
Related to #5238
> fix: the action permission not enough

- backend/helpers/pluginhelper/api/batch_save.go
- backend/helpers/pluginhelper/api/batch_save_test.go
cherry-pick#5244#5256 to release-v0.16
> chore: cherry-pick#5244#5256 to release-v0.16

- backend/Makefile
- backend/python/README.md
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
- backend/python/plugins/azuredevops/tests/__init__.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/model.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/stream.py
- backend/python/pydevlake/pydevlake/subtasks.py
- backend/python/pydevlake/pydevlake/testing/testing.py
- backend/python/pydevlake/tests/stream_test.py
- backend/server/services/remote/plugin/plugin_impl.go
#5081 is missing from v0.17.0-beta-6 which makes other fixes that depend on it ineffective.
Closes #5275
> Cherry pick #5081

- backend/plugins/pagerduty/api/remote.go
- backend/plugins/pagerduty/models/raw/incidents.go
- backend/plugins/pagerduty/models/raw/services.go
- backend/plugins/pagerduty/tasks/incidents_converter.go
- backend/plugins/pagerduty/tasks/incidents_extractor.go
> cherrypick(v0.17.0-beta7): #5278

- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
Lets Github run test actions for PRs made to the release-* branch (beta releases)
Closes n/a
> ci: Enforce CI test execution for cherrypicked PRs

- backend/python/plugins/azuredevops/azuredevops/models.py
Integrate missing changes due to a bad merge conflict resolution in `azuredevops/models.py` during cherry-pick #5285
> fix: Fix bad merge conflict resolution

- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
Enable CI tests for Cherry-Picks (based on #5288)
Closes n/a
> cherrypick(v0.17.0-beta7): #5288 (Enable CI tests for cherry-pick PRs)

- config-ui/src/components/buttons/index.tsx
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/styled.ts
- config-ui/src/pages/project/detail/api.ts
- config-ui/src/pages/project/detail/settings-panel.tsx
- config-ui/src/pages/project/detail/styled.ts
1. support params align in buttons component.
2. support delete project.
3. support delete blueprint.
Related to #4760 and #4864 
Closes #4388
> feat(config-ui): support delete blueprint and project

- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/pydevlake/pydevlake/subtasks.py
Fix a bug in pydevlake when collecting substreams in presence of multiple scopes.
Closes #5309
> Fix substream.fetch

- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/pydevlake/pydevlake/subtasks.py
> cherry-pick(v0.17.0-beta9): #5309

- backend/python/README.md
- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/pydevlake/pydevlake/api.py
> cherry-pick(v0.17.0-beta9): #5083

- backend/plugins/ae/models/migrationscripts/archived/project.go
- backend/plugins/bitbucket/models/migrationscripts/20230322_add_connection_id_to_transformation_rules.go
- backend/plugins/tapd/models/migrationscripts/archived/bug.go
- backend/plugins/tapd/models/migrationscripts/archived/bug_changelog.go
- backend/plugins/tapd/models/migrationscripts/archived/bug_commit.go
- backend/plugins/tapd/models/migrationscripts/archived/bug_custom_field.go
- backend/plugins/tapd/models/migrationscripts/archived/issue.go
- backend/plugins/tapd/models/migrationscripts/archived/iteration.go
- backend/plugins/tapd/models/migrationscripts/archived/story.go
- backend/plugins/tapd/models/migrationscripts/archived/story_category.go
- backend/plugins/tapd/models/migrationscripts/archived/story_changelog.go
- backend/plugins/tapd/models/migrationscripts/archived/story_commits.go
- backend/plugins/tapd/models/migrationscripts/archived/story_custom_field.go
- backend/plugins/tapd/models/migrationscripts/archived/sub_workspace.go
- backend/plugins/tapd/models/migrationscripts/archived/task.go
- backend/plugins/tapd/models/migrationscripts/archived/task_changelog.go
- backend/plugins/tapd/models/migrationscripts/archived/task_commits.go
- backend/plugins/tapd/models/migrationscripts/archived/task_custom_field.go
- backend/plugins/tapd/models/migrationscripts/archived/workitem_type.go
- backend/plugins/tapd/models/migrationscripts/archived/worklog.go
- backend/plugins/tapd/models/migrationscripts/archived/workspace.go
- backend/plugins/zentao/models/archived/account.go
- backend/plugins/zentao/models/archived/bug.go
- backend/plugins/zentao/models/archived/changelog.go
- backend/plugins/zentao/models/archived/department.go
- backend/plugins/zentao/models/archived/execution.go
- backend/plugins/zentao/models/archived/product.go
- backend/plugins/zentao/models/archived/project.go
- backend/plugins/zentao/models/archived/story.go
- backend/plugins/zentao/models/archived/task.go
> fix: migration id defined error

- backend/python/plugins/azuredevops/azuredevops/models.py
Cherry-pick #5337 
Closes #5336
> cherrypick(v0.17.0-beta9): #5337

- config-ui/src/App.tsx
- config-ui/src/components/action/icon-button/index.tsx
- config-ui/src/components/message/index.tsx
- config-ui/src/config/cron.ts
- config-ui/src/pages/blueprint/connection-detail/api.ts
- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/pages/blueprint/detail/blueprint-detail-page.tsx
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/blueprint/detail/configuration-panel.tsx
- config-ui/src/pages/blueprint/detail/status-panel.tsx
- config-ui/src/pages/blueprint/detail/styled.ts
- config-ui/src/pages/blueprint/types.ts
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/pages/connection/detail/styled.ts
- config-ui/src/pages/connection/home/index.tsx
- config-ui/src/pages/project/detail/api.ts
- config-ui/src/pages/project/detail/index.tsx
- config-ui/src/plugins/components/connection-form/index.tsx
- config-ui/src/plugins/components/connection-list/index.tsx
- config-ui/src/plugins/components/data-scope-select/index.tsx
- config-ui/src/plugins/components/scope-config-form/index.tsx
- config-ui/src/plugins/components/scope-config-select/index.tsx
- config-ui/src/plugins/register/azure/transformation.tsx
- config-ui/src/plugins/register/bitbucket/transformation.tsx
- config-ui/src/plugins/register/github/transformation.tsx
- config-ui/src/plugins/register/gitlab/transformation.tsx
- config-ui/src/plugins/register/jenkins/transformation.tsx
- config-ui/src/plugins/register/jira/transformation-fields/cross-domain.tsx
- config-ui/src/plugins/register/jira/transformation.tsx
- config-ui/src/plugins/register/tapd/transformation.tsx
Improve the content for the new design.
Closes #4760
> feat(config-ui): improve the content for the new design

- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
Fix extraction and conversion of running build and jobs.
Those fixes need to be ported to main.
Closes #5344
> fix: Fix extraction and convertion of running builds

- backend/plugins/jira/api/scope_config.go
- backend/plugins/jira/impl/impl.go
- backend/plugins/jira/tasks/task_data.go
- Provide an API to query dev panel commits URLs
- Related to #5225 
Closes #4304
> feat: provide an API to query dev panel commits URLs

- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/model.py
Add code to create SubtaskRun table that was not created since the new go-side migration PR.
> fix: Create SubtaskRun table

- backend/helpers/pluginhelper/api/scope_db_helper.go
- backend/plugins/zentao/api/blueprint_V200_test.go
- backend/plugins/zentao/api/blueprint_v200.go
- backend/plugins/zentao/api/remote.go
- backend/plugins/zentao/models/migrationscripts/20230601_add_scope_config.go
- backend/plugins/zentao/models/product.go
- backend/plugins/zentao/models/project.go
Sometime the project failed to decode
It because of ClosedBy use typestring but not interface.
Closes #5211
> fix: fix 500 error for project

- backend/plugins/jira/api/init.go
- backend/plugins/jira/api/remote.go
- backend/plugins/jira/impl/impl.go
- backend/plugins/jira/models/board.go
- backend/plugins/jira/tasks/apiv2models/board.go
Add Jira remote API.
Closes #5366
> feat: add jira remote api

- backend/plugins/jenkins/api/init.go
- backend/plugins/jenkins/api/jobs.go
- backend/plugins/jenkins/api/remote.go
- backend/plugins/jenkins/impl/impl.go
- backend/plugins/jenkins/models/job.go
- backend/plugins/jenkins/models/response.go
Add RemoteScopes API for Jenkins.
Add SearchRemoteScopes API for Jenkins.
Closes #5357
> feat: add remote api for jenkins

- backend/server/main.go
fix: add ENCRYPTION_SECRET environment variable
Closes #5235 
> fix: add ENCRYPTION_SECRET environment variable

- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/models.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/plugins/azuredevops/azuredevops/streams/pull_request_commits.py
- backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
- backend/python/pydevlake/pydevlake/plugin.py
Add support for repositories hosted by third-parties in azure devops builds 
Closes #5249
> feat: Support external repositories

- backend/python/plugins/azuredevops/azuredevops/api.py
- backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
- backend/python/pydevlake/pydevlake/subtasks.py
Cherry-pick #5386 
Closes #5383
> cherrypick(v0.17.0-beta11): #5386

- backend/plugins/github/api/init.go
- backend/plugins/github/api/remote.go
- backend/plugins/github/impl/impl.go
provides a universal API for the frontend to fetch remote scope
part of #4871
> feat: github remote API

- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/pages/blueprint/home/index.tsx
- config-ui/src/pages/connection/detail/api.ts
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/plugins/components/data-scope-select/index.tsx
- config-ui/src/plugins/components/scope-config-form/api.ts
- config-ui/src/plugins/components/scope-config-select/api.ts
improve the data scope fields
Related to #4760
> feat(config-ui): improve the data scope fields

- backend/server/api/blueprints/blueprints.go
move skipCollectors params from query to body request.
Closes #4866 
> feat: move skipCollectors params from query to body

- backend/plugins/jenkins/models/response.go
Add FullName on ConvertApiScope.
It fixes the job lost id on config-UI
> fix: fix job loss id on remote

- .github/workflows/test-e2e.yml
- backend/core/config/config_viper.go
- backend/core/runner/db.go
- backend/helpers/e2ehelper/data_flow_tester.go
1. remove no .env file warn
2. add mutil-path for e2e etc..
3. add some tips
Closes #5235 
> fix: env config reload logic

- backend/plugins/gitlab/tasks/mr_commit_collector.go
- backend/plugins/gitlab/tasks/mr_note_collector.go
- backend/plugins/gitlab/tasks/shared.go
Fix Gitlab lost merge request commit.
Fix Gitlab lost merge request note.
Closes #5406 
Before new mr:
After creating a new mr:
> fix: fix gitlab lost mr commit

- backend/plugins/zentao/models/archived/changelog.go
- backend/plugins/zentao/models/migrationscripts/20230608_add_init_changelog_tables.go
- backend/plugins/zentao/models/migrationscripts/register.go
Fix addInitChangelogTables about ZentaoChangelog product type.
Closes #5413
> fix: fix zentao migration script

- backend/plugins/zentao/tasks/bug_commits_collector.go
- backend/plugins/zentao/tasks/story_commits_collector.go
- backend/plugins/zentao/tasks/task_commits_collector.go
fix: zentao issue commit repeat collector
Closes #5417 
> fix: zentao issue commit repeat collector

- backend/python/plugins/azuredevops/azuredevops/models.py
Add migration to make columns `_tool_azuredevops_builds.result` and `_tool_azuredevops_gitpullrequests.merge_commit_sha`.
Closes #5298 and #5336
> fix: Add migration for nullable columns

- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/pydevlake/pydevlake/plugin.py
Fix wrong merge conflicts that went undetected because of CI passing.
> fix: Fix wrong merge conflict resolution

- config-ui/src/plugins/components/data-scope-select-remote/index.tsx
- config-ui/src/plugins/register/tapd/config.tsx
- config-ui/src/plugins/register/tapd/data-scope.tsx
- config-ui/src/plugins/types.ts
Fixed cannot add a new data scope in TAPD.
Closes #5433
> fix(config-ui): cannot add a new data scope in tapd

- config-ui/src/config/cron.ts
- config-ui/src/pages/blueprint/detail/components/sync-policy/index.tsx
Fixed cannot click the custom in frequency.
Closes #5435
> fix(config-ui): cannot click the custom in frequency

- config-ui/src/index.css
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/plugins/register/github/config.tsx
Adjust the wording for github data scope
> fix(config-ui): adjust the wording for github data scope

- config-ui/src/components/buttons/index.tsx
- config-ui/src/pages/blueprint/connection-detail/api.ts
- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/pages/connection/detail/index.tsx
Fixed the tips wording and when to show
> fix(config-ui): the tips wording and when to show

- backend/plugins/zentao/tasks/story_extractor.go
- backend/plugins/zentao/tasks/task_extractor.go
Fix story type mapping.
Fix story status mapping.
Fix task type mapping.
Closes #5425
> fix: fix typemapping

- backend/plugins/jenkins/impl/impl.go
Fix the panic error caused by the type assertion 
Closes #5440 
> fix: the type assertion

- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/plugins/azuredevops/azuredevops/streams/builds.py
- backend/python/pydevlake/pydevlake/testing/testing.py
- backend/server/services/remote/plugin/default_api.go
Fixes bugs encountered by the integration tests in #5085 
- Handling of Scopes with ID containing "/" (seen on external repos)
- Handling of the "Provider" for Non-External repos
Closes n/a
> [fix-5085]: Azure bug fixes related to external repo support

- backend/plugins/github/api/connection.go
Update messages returned by Github testconn
> chore: update github testconn msgs

- grafana/dashboards/DORAByTeam.json
fix: dashboard by team calendar_months and format
Closes #5456 
> fix: dashboard by team calendar_months and format

- config-ui/src/plugins/register/jira/api.ts
- config-ui/src/plugins/register/jira/transformation-fields/cross-domain.tsx
- config-ui/src/plugins/register/jira/transformation-fields/styled.ts
- config-ui/src/plugins/register/jira/transformation.tsx
Support jira dev panel configuration
Related to #4304
> feat(config-ui): support jira dev panel configuration

- config-ui/src/pages/blueprint/connection-detail/index.tsx
Fixed data scope cannot display correctly in project.
Closes #5458
> fix(config-ui): data scope cannot display correctly in project

- config-ui/src/pages/connection/detail/index.tsx
Adjust the style for data scope table.
> fix(config-ui): adjust the style for data scope table

- backend/helpers/pluginhelper/api/reflection_helper.go
- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/server/services/remote/plugin/plugin_impl.go
Remote tool tables were being excluded in scope deletions due to a reflection bug. This fixes that.
Closes n/a
> fix: Tool table discovery fix

- backend/plugins/jira/tasks/epic_collector.go
The jira epic collector would fail when epic doesn't exist. 
This PR fixes the problem by simply ignore the 400 error
Related to #5385
> fix: jira failed on deleted epic

- backend/plugins/jira/tasks/epic_collector.go
cherrypick #5464 (fix: jira server failed on deleted epic) to v0.17
> cherrypick #5464 (fix: jira server failed on deleted epic) to v0.17 (Will be available in beta12)

- backend/plugins/github/api/blueprint_V200_test.go
- backend/plugins/github/api/blueprint_v200.go
- backend/plugins/github/api/init.go
- backend/plugins/github/api/remote.go
- backend/plugins/github/impl/impl.go
Fix #5487, the user‘s name shows in the left select box as well as the organizations
Closes #5487 
> feat: add owner to the scope select box

- config-ui/src/pages/connection/detail/api.ts
- config-ui/src/plugins/components/data-scope-select-remote/index.tsx
- config-ui/src/plugins/register/bitbucket/config.tsx
- config-ui/src/plugins/register/github/config.tsx
- config-ui/src/plugins/register/jira/config.tsx
- config-ui/src/plugins/types.ts
1. fix(config-ui): the querystring not correctly in delete scope
2. chore(config-ui): remove console.log from data scope select remote
3. refactor(config-ui): support columnCount in plugin data scope
Closes #5477
> fix(config-ui): the querystring not correctly in delete scope

- config-ui/src/plugins/components/scope-config-form/index.tsx
Fixed missed transformation title for scope config.
> fix(config-ui): missed transformation title for scope config

- config-ui/src/plugins/register/github/connection-fields/styled.ts
- config-ui/src/plugins/register/github/connection-fields/token.tsx
Adjust the content for github token check.
Related to #4712
> fix(config-ui): adjust the content for github token check

- config-ui/src/pages/blueprint/connection-detail/index.tsx
Adjust the wording for remove connection.
> fix(config-ui): adjust the wording for remove connection

- backend/plugins/customize/service/service.go
- backend/plugins/tapd/api/blueprint_v200.go
- backend/plugins/tapd/api/blueprint_v200_test.go
- backend/plugins/tapd/tasks/workspace_converter.go
cherry pick #5497 to branch release-v0.17
Closes #5157
> cherrypick(v0.17.0): #5497

- config-ui/src/pages/blueprint/detail/configuration-panel.tsx
- config-ui/src/utils/request.ts
Fixed collect data interface paramter error.
Closes #5490
> fix(config-ui): collect data interface paramter error

- backend/python/README.md
- backend/python/plugins/azuredevops/azuredevops/main.py
- backend/python/pydevlake/pydevlake/context.py
- backend/python/pydevlake/pydevlake/ipc.py
- backend/python/pydevlake/pydevlake/model.py
- backend/python/pydevlake/pydevlake/plugin.py
- backend/python/pydevlake/pydevlake/testing/testing.py
- backend/python/pydevlake/tests/stream_test.py
- backend/server/services/remote/models/conversion.go
- backend/server/services/remote/plugin/plugin_impl.go
Make ScopeConfig optional in pydevlake
Closes #5453
> [fix-5453](pydevlake): Make ScopeConfig optional

- backend/core/models/blueprint.go
- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/helpers/pluginhelper/services/blueprint_helper.go
> fix: Get BlueprintsByScope APIs must account for plugin name

- backend/server/services/blueprint_makeplan_v200.go
remove gitextractor where skip collector
Closes #4866 
> fix: remove gitextractor where skip collector

- backend/plugins/jira/models/scope_config.go
- backend/plugins/jira/tasks/task_data.go
Fix #5510 ([Bug][Jira] An error occurred on creating scope config )
Closes #5510 
> fix: error on creating scope config

- config-ui/src/plugins/register/jira/api.ts
- config-ui/src/plugins/register/jira/transformation-fields/cross-domain.tsx
- config-ui/src/plugins/register/jira/transformation-fields/dev-panel.tsx
- config-ui/src/plugins/register/jira/transformation-fields/remote-link.tsx
- config-ui/src/plugins/register/jira/transformation-fields/styled.ts
- config-ui/src/utils/operator.ts
Fixed some bugs for jira dev panel.
> fix(config-ui): some bugs for jira dev panel

- backend/core/models/blueprint.go
fix: unmarshal connections fail
Closes #5518 
> fix: unmarshal connections fail

- config-ui/src/components/message/index.tsx
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/pages/connection/detail/styled.ts
Show conflict list when delete connection or scope.
Closes #5517
> feat(config-ui): show conflict list when delete connection or scope

- config-ui/src/pages/blueprint/connection-detail/index.tsx
- config-ui/src/pages/blueprint/detail/components/add-connection-dialog/index.tsx
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/plugins/components/data-scope-select-remote/index.tsx
- config-ui/src/plugins/components/data-scope-select/index.tsx
- config-ui/src/plugins/register/zentao/config.ts
- config-ui/src/plugins/utils.ts
Fixed cannot add a data scope in zentao.
> fix(config-ui): cannot add a data scope in zentao

- config-ui/src/layouts/base/base.tsx
- config-ui/src/utils/request.ts
Remove redirect offline when api throws an error.
Closes #5545
> fix(config-ui): remove redirect offline when api throws an error

- config-ui/src/layouts/base/base.tsx
- config-ui/src/utils/request.ts
> cherry-pick(v0.17.0-beta11): #5546

- backend/plugins/zentao/api/init.go
Fix project scope using the error field.
It made scope can not be listed.
> fix: fix scope error

- backend/core/utils/table_info_checker.go
Follow-up fix PR for a small oversight in #5555 
Closes xx
> fix: added missing err check to table_info_checker

- backend/helpers/pluginhelper/api/batch_save.go
A race condition causes the error.
A mutex is used to create a critical section to ensure only one goroutine at a time can execute that code section.
Closes #5560
> fix: index out of range error of BatchSave

- backend/plugins/jira/api/blueprint_v200.go
- backend/plugins/zentao/tasks/project_convertor.go
cherry-pick #5559 back to release-v0.17
> cherry-pick(v0.17.0-beta13): #5559

- backend/plugins/dora/impl/impl_test.go
- backend/plugins/sonarqube/e2e/account_test.go
- backend/plugins/sonarqube/e2e/filemetrics_test.go
- backend/plugins/sonarqube/e2e/hotspot_test.go
- backend/plugins/sonarqube/e2e/issue_test.go
- backend/plugins/sonarqube/e2e/project_test.go
- backend/plugins/sonarqube/impl/impl.go
- backend/plugins/sonarqube/tasks/hotspots_collector.go
- backend/plugins/sonarqube/tasks/issues_collector.go
- backend/plugins/sonarqube/tasks/task_data.go
Cherry-pick fix #5548 to release-0.17
Closes #5544 
> Cherry-pick fix #5548 to release-0.17

- backend/plugins/zentao/api/blueprint_v200.go
- backend/plugins/zentao/api/remote.go
> fix: scope id fix

- backend/helpers/pluginhelper/api/batch_save.go
Fix #5569, This bug is due to not being careful enough with the use of Mutex
Closes #5569
> fix: stuck tasks

- backend/plugins/tapd/tasks/bug_status_extractor.go
- backend/plugins/tapd/tasks/shared.go
- backend/plugins/tapd/tasks/shared_test.go
- backend/plugins/tapd/tasks/story_status_extractor.go
Cherry-pick #5574 (fix: tapd status extraction error) back to branch `release-v0.17`
Closes #5573
> cherry-pick(v0.17.0-beta13): #5574

- backend/core/runner/run_task.go
Fix #5585 ([Bug][framework] The cancel function does not work)
Closes #5585 
> fix: cancel doesn't work

- backend/python/pydevlake/pydevlake/plugin.py
- backend/server/services/remote/plugin/plugin_extensions.go
- backend/test/e2e/remote/helper.go
Python now accounts for _raw_data_table for scopes
Closes n/a
Caused by #5584 and #5551
> fix: Python now accounts for _raw_data_table for scopes

- backend/plugins/zentao/tasks/bug_convertor.go
- backend/plugins/zentao/tasks/task_convertor.go
Add sprint issue for Zentao story and bug
Fix parent id to be empty if 0.
> Zentao fix

- config-ui/src/components/table/components/content.tsx
- config-ui/src/components/table/hooks/use-row-selection.ts
- config-ui/src/components/table/types.ts
- config-ui/src/pages/connection/detail/index.tsx
- config-ui/src/plugins/components/data-scope-select/index.tsx
- config-ui/src/plugins/components/scope-config-select/index.tsx
- config-ui/src/plugins/utils.ts
Fixed incorrect scope id type.
Closes #5571
> fix(config-ui): incorrect scope id type

- config-ui/package.json
- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/project/home/index.tsx
- config-ui/yarn.lock
The tab state cannot be maintained when jumping the page.
Closes #5599
> fix(config-ui): The tab state cannot be maintained

- config-ui/src/pages/connection/detail/index.tsx
Fixed distinguish undeletable connection reasons.
> fix(config-ui): distinguish undeletable connection reasons

- .github/workflows/golangci-lint.yml
- devops/docker/lake-builder/Dockerfile
Seems the `mockery` can not functions correctlly
https://github.com/apache/incubator-devlake/actions/runs/5420624011/jobs/9855009434?pr=5609
> fix: upgrade swag/mockery to latest

- backend/plugins/github/models/migrationscripts/20230518_fix_run_name_to_text.go
- backend/plugins/github/models/migrationscripts/register.go
- backend/plugins/github/models/run.go
Cherry-pick #5208 #5255 back to release-v0.17
> cherry-pick(v0.17.0-beta): #5208#5255

- docker-compose-dev.yml
As per discussion in PR #5554
Referencing effort to teliminate the .env file usage
eliminate the mounting of the .env file from the devlake container as referenced in
the docker-compose-dev.yml file
Bug #5474
As per discussion in previous PR #5554, crated one PR for fixing in 0.17
and this PR for fixing in main
> pr-type/bug-fix: [Partial] Removed env file mount from devlake container

- config-ui/src/plugins/register/jira/connection-fields/auth.tsx
> cherry-pick(v0.17.0-beta13): #5618

- config-ui/src/components/error-boundary/index.tsx
Fixed uncleaned error content.
> fix(config-ui): uncleaned error content

- config-ui/src/plugins/register/jira/connection-fields/auth.tsx
Fixed missed initial version field in jira.
Closes #5489
> fix(config-ui): missed initial version field in jira

- backend/helpers/pluginhelper/api/scope_generic_helper.go
This is test code for troubleshooting purposes. Not intended to be merged (to release anyway).
n/a
Sample log message:
n/a
> test: Troublshoot deletion failures

- grafana/dashboards/EngineeringOverview.json
Cherry-pick #5623 fix dashboard typo to v0.17
> Cherry-pick #5623 fix dashboard typo to v0.17 (will be available in beta13)

- backend/helpers/pluginhelper/api/connection_helper.go
- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/plugins/ae/api/connection.go
- backend/plugins/bamboo/api/connection.go
- backend/plugins/bitbucket/api/connection.go
- backend/plugins/feishu/api/connection.go
- backend/plugins/gitee/api/connection.go
- backend/plugins/github/api/connection.go
- backend/plugins/gitlab/api/connection.go
- backend/plugins/jenkins/api/connection.go
- backend/plugins/jira/api/connection.go
- backend/plugins/pagerduty/api/connection.go
- backend/plugins/slack/api/connection.go
- backend/plugins/sonarqube/api/connection.go
- backend/plugins/tapd/api/connection.go
- backend/plugins/teambition/api/connection.go
- backend/plugins/trello/api/connection.go
- backend/plugins/webhook/api/connection.go
- backend/plugins/zentao/api/connection.go
- backend/server/services/remote/plugin/connection_api.go
Returning error message alongside `refs`
Closes #5624
Self Tested on Jenkins, the other plugins should work because they are all using the same underlying code.
> fix: connectionHelper.Delete returns proper error response

- config-ui/src/plugins/register/jira/connection-fields/auth.tsx
Remove console.log from jira auth.
> fix(config-ui): remove console.log from jira auth

- config-ui/src/plugins/register/jira/transformation-fields/dev-panel.tsx
Fixed catch jira dev panel throw error.
Closes #5630
> fix(config-ui): catch jira dev panel throw error

- config-ui/src/pages/blueprint/detail/blueprint-detail.tsx
- config-ui/src/pages/project/home/index.tsx
Adjust the tab in project detail.
#5599
> fix(config-ui): adjust the tab in project detail

- config-ui/src/plugins/utils.ts
Adjust interface return value.
#5602
> fix(config-ui): adjust interface return value

- backend/helpers/pluginhelper/api/scope_generic_helper.go
- backend/scripts/compile-plugins.sh
1. fix: scope list was in random order
2. fix: scripts/compile-plugins.sh: 61: [: Linux: unexpected operator
> fix: scope list was in random order
